### ISSUE TITLE
🐛 [Bug]: [slider] When the Slider component v-model is an array, when you change the value of the array, the range of the slider will not change.

### ISSUE THREAD

**Issue by AcWrong02** [opentiny/tiny-vue#1007]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://opentiny.design/vue-playground?mode=pc&theme=default#3.11|eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgbGFuZz1cInRzeFwiPlxyXG4vLyDlvJXlhaUgQG9wZW50aW55L3Z1ZSDnu4Tku7ZcclxuaW1wb3J0IHsgQnV0dG9uLCBMaW5rIH0gZnJvbSAnQG9wZW50aW55L3Z1ZSdcclxuXHJcbmV4cG9ydCBkZWZhdWx0IHtcclxuICBjb21wb25lbnRzOiB7XHJcbiAgICBUaW55QnV0dG9uOiBCdXR0b24sXHJcbiAgICBUaW55TGluazogTGlua1xyXG4gIH0sXHJcbiAgZGF0YSgpIHtcclxuICAgIHJldHVybiB7XHJcbiAgICAgIG1zZzogJ2hlbGxvIHdvcmxkISdcclxuICAgIH1cclxuICB9XHJcbn1cclxuPC9zY3JpcHQ+XHJcblxyXG48dGVtcGxhdGU+XHJcbiAgPFRpbnlCdXR0b24+56Gu5a6aPC9UaW55QnV0dG9uPlxyXG4gIDxoMT57eyBtc2cgfX08L2gxPlxyXG4gIDxkaXYgY2xhc3M9XCJ0aW55dnVlXCI+XHJcbiAgICA8ZGl2IGNsYXNzPVwidGlueXZ1ZS1wYWdlXCI+XHJcbiAgICAgIHRpbnl2dWVcclxuICAgICAgPHRpbnktbGluayB0eXBlPVwic3VjY2Vzc1wiIGhyZWY9J2h0dHBzOi8vZ2l0aHViLmNvbS9vcGVudGlueS90aW55LXZ1ZSc+XHJcbiAgICAgICAgdGlueXZ1ZVxyXG4gICAgICA8L3RpbnktbGluaz5cclxuICAgIDwvZGl2PlxyXG4gIDwvZGl2PlxyXG48L3RlbXBsYXRlPlxyXG5cclxuPHN0eWxlIGxhbmc9XCJsZXNzXCIgc2NvcGVkPlxyXG4gIGgxe1xyXG4gICAgY29sb3I6IzVlN2NlMDtcclxuICB9XHJcbiAgLnRpbnl2dWV7XHJcbiAgICBmb250LXNpemU6IDE4eHA7XHJcbiAgICAmLXBhZ2V7XHJcbiAgICAgIGNvbG9yOiM1ZTdjZTA7XHJcbiAgICB9XHJcbiAgfVxyXG48L3N0eWxlPlxyXG4iLCIiOiJ7XCJpbXBvcnRzXCI6e1wiQG9wZW50aW55L3Z1ZVwiOlwiaHR0cHM6Ly91bnBrZy5jb20vQG9wZW50aW55L3Z1ZUAzLjExL3J1bnRpbWUvdGlueS12dWUubWpzXCIsXCJAb3BlbnRpbnkvdnVlLWljb25cIjpcImh0dHBzOi8vdW5wa2cuY29tL0BvcGVudGlueS92dWVAMy4xMS9ydW50aW1lL3RpbnktdnVlLWljb24ubWpzXCIsXCJAb3BlbnRpbnkvdnVlLWxvY2FsZVwiOlwiaHR0cHM6Ly91bnBrZy5jb20vQG9wZW50aW55L3Z1ZUAzLjExL3J1bnRpbWUvdGlueS12dWUtbG9jYWxlLm1qc1wiLFwiQG9wZW50aW55L3Z1ZS1jb21tb25cIjpcImh0dHBzOi8vdW5wa2cuY29tL0BvcGVudGlueS92dWVAMy4xMS9ydW50aW1lL3RpbnktdnVlLWNvbW1vbi5tanNcIixcInNvcnRhYmxlanNcIjpcImh0dHBzOi8vdW5wa2cuY29tL3NvcnRhYmxlanNAMS4xNS4wL21vZHVsYXIvc29ydGFibGUuZXNtLmpzXCJ9fSIsInRzY29uZmlnLmpzb24iOiJ7XHJcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xyXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXHJcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcclxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcclxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXHJcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxyXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxyXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlXHJcbiAgfSxcclxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XHJcbiAgICBcInRhcmdldFwiOiAzLjNcclxuICB9XHJcbn1cclxuIiwibWF4LW1pbi52dWUiOiI8dGVtcGxhdGU+XG4gIDx0aW55LXNsaWRlciB2LW1vZGVsPVwidmFsdWUzXCIgc3R5bGU9XCJtYXJnaW46NTBweFwiPjwvdGlueS1zbGlkZXI+XG4gIDxidXR0b24gQGNsaWNrPVwiaGFuZGxlQ2xpY2tcIj5cbiAgICBjbGlja1xuICA8L2J1dHRvbj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cImpzeFwiPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgU2xpZGVyIGFzIFRpbnlTbGlkZXIgfSBmcm9tICdAb3BlbnRpbnkvdnVlJ1xuXG5jb25zdCB2YWx1ZTMgPSByZWYoWzIwLCA0MF0pXG5jb25zdCBoYW5kbGVDbGljayA9ICgpPT57XG4gIHZhbHVlMy52YWx1ZSA9IFszMCw1MF1cbn1cbjwvc2NyaXB0PlxuIiwiX28iOnt9fQ==

### Step to reproduce

1. 打开playground
2. 点击click观察效果

### What is expected

点击完click之后，范围应该要跟着变化才对

### What is actually happening

点击完click之后，范围应该没变，在鼠标悬浮上去之后才会变化

**Comment by yoyo201626** [comment]
playground好像失效了
@AcWrong02 
![1234566](https://github.com/opentiny/tiny-vue/assets/104079404/268ee8e7-6959-4ce6-b0c9-9d5ee646b8a5)

**Comment by AcWrong02** [comment]
> playground好像失效了 @AcWrong02 ![1234566](https://private-user-images.githubusercontent.com/104079404/287569926-268ee8e7-6959-4ce6-b0c9-9d5ee646b8a5.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2NTkxMjUsIm5iZiI6MTcwMTY1ODgyNSwicGF0aCI6Ii8xMDQwNzk0MDQvMjg3NTY5OTI2LTI2OGVlOGU3LTY5NTktNGNlNi1iMGM5LTlkNWVlNjQ2YjhhNS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNFQwMzAwMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNWQwNWUxNjMyMzdkYzk1NjAwMWFmMWU4YjRkZjY0YjdlODdkMzhjMjJlYWU2ZmE4Yjg1YjY3ZWY4Njk5OGZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Cl6rdyYuvUa36vmcUKGzjNNJcV5sXkq13pATEfUFhb0)

https://opentiny.design/vue-playground?mode=pc&theme=default#3.11|eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPHRpbnktc2xpZGVyIHYtbW9kZWw9XCJ2YWx1ZTNcIj48L3Rpbnktc2xpZGVyPlxuICA8YnV0dG9uIEBjbGljaz1cImhhbmRsZUNsaWNrXCI+XG4gICAgY2xpY2tcbiAgPC9idXR0b24+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJqc3hcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFNsaWRlciBhcyBUaW55U2xpZGVyIH0gZnJvbSAnQG9wZW50aW55L3Z1ZSdcblxuY29uc3QgdmFsdWUzID0gcmVmKFsyMCwgNDBdKVxuXG5jb25zdCBoYW5kbGVDbGljayA9ICgpPT57XG4gIHZhbHVlMy52YWx1ZSA9IFsxMCw1MF1cbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xyXG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcclxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxyXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXHJcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXHJcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxyXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcclxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcclxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZVxyXG4gIH0sXHJcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xyXG4gICAgXCJ0YXJnZXRcIjogMy4zXHJcbiAgfVxyXG59XHJcbiIsIl9vIjp7fX0=

**Comment by AcWrong02** [comment]
> playground好像失效了 @AcWrong02 ![1234566](https://private-user-images.githubusercontent.com/104079404/287569926-268ee8e7-6959-4ce6-b0c9-9d5ee646b8a5.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2NTkyNjIsIm5iZiI6MTcwMTY1ODk2MiwicGF0aCI6Ii8xMDQwNzk0MDQvMjg3NTY5OTI2LTI2OGVlOGU3LTY5NTktNGNlNi1iMGM5LTlkNWVlNjQ2YjhhNS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNFQwMzAyNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTkwODVjOWVkOTkxZjlhYTllOWU3NThmOThjOTU3YjY0YWI4NmUzNjdhZDViYWMwZDRmY2M5ODY1ZjMyMmE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mgSzgeFlVPqzM_jwngT993BKU1WE9d38rBvzJt77Eag)

不知道为什么playground链接复制过来有问题，我把代码复制到下面了，还麻烦您复制到playground看一下效果
```
<template>
  <tiny-slider v-model="value3"></tiny-slider>
  <button @click="handleClick">
    click
  </button>
</template>

<script setup lang="jsx">
import { ref } from 'vue'
import { Slider as TinySlider } from '@opentiny/vue'

const value3 = ref([20, 40])

const handleClick = ()=>{
  value3.value = [10,50]
}
</script>

```

**Comment by yoyo201626** [comment]
这个问题我来修复

**Comment by AcWrong02** [comment]
> 这个问题我来修复

让我学习学习，哈哈^v^
