### ISSUE TITLE
🐛 [Bug]: In demo after local startup, clicking the "apply" button does not take effect.

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-vue#101]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

本地启动之后，点击组件 demo 的“应用”按钮，弹出来一个保存文件的系统对话框，而修改后的 demo 却没有生效

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/9566362/228984082-9f06bac2-a299-4094-8c65-7becb4622c4f.png">

### Step to reproduce

本地启动之后，点击组件 demo 的“应用”按钮

### What is expected

应用修改后的 demo 代码

### What is actually happening

弹出来一个保存文件的系统对话框，而修改后的 demo 却没有生效

**Comment by acyza** [comment]
这应用按钮是干啥用的？为啥要弹保存文件对话框？
如果它是用来更新文档预览demo的，直接在页面跑用户提交的代码是否存在安全问题？
vue3可以用https://github.com/vuejs/repl ，它预览部分用`iframe`做了隔离。
vue2重构https://github.com/vuejs/repl 可能涉及依赖解析，代码编译等应该会比较麻烦。

建议去掉应用按钮，或用其他方案替换
另外`showSaveFilePicker`有很多主流浏览器都是不支持的，建议判断一下。

**Comment by zzcr** [comment]
目前本地工程已经去掉了这个功能
