### ISSUE TITLE
🐛 [Bug]: When the Slider component presses the pageUp and pageDown keys, the scroll bar of the page moves up and down.

### ISSUE THREAD

**Issue by AcWrong02** [opentiny/tiny-vue#1024]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://opentiny.design/tiny-vue/zh-CN/os-theme/components/slider#shortcut-operation

### Step to reproduce

官网即可看到效果

### What is expected

Slider组件按下pageUp、pageDown键的时候，只有其大小会跟着变化，页面应该是固定的

### What is actually happening

null

**Comment by yoyo201626** [comment]
有贡献者正在修复中 #1038
