### ISSUE TITLE
🐛 [Bug]: Cascader components do not display selected values after configuring displayOnly=true: props= "{checkStrictly: true, multiple: true, leaf: 'leaf', emitPath: false}"

### ISSUE THREAD

**Issue by falcon-jin** [opentiny/tiny-vue#1036]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

cascader 组件配置displayOnly=true  :props="{ checkStrictly: true, multiple: true, leaf: 'leaf', emitPath: false}"后 不展示选中值

### Step to reproduce

<template>
  <tiny-cascader
     :displayOnly=true
    :options="options"
    :props="{ checkStrictly: true, multiple: true, leaf: 'leaf', emitPath: false }"
    v-model="value"
  ></tiny-cascader>
</template>

<script setup>
import { ref } from 'vue'
import { Cascader as TinyCascader } from '@opentiny/vue'

const value = ref([
  ['zhinan', 'anzhuang'],
  ['zhinan', 'kaifa', 'yinruzujian']
])
const options = ref([
  {
    value: 'zhinan',
    label: '指南',
    children: [
      {
        value: 'anzhuang',
        label: '安装',
        children: [
          {
            value: 'xiangmudengji',
            label: '项目登记'
          },
          {
            value: 'huanjingzhunbei',
            label: '环境准备'
          },
          {
            value: 'anzhuangcli',
            label: '安装 CLI'
          },
          {
            value: 'chuangjianxiangmu',
            label: '创建项目'
          }
        ]
      },
      {
        value: 'kaifa',
        label: '开发',
        children: [
          {
            value: 'yinruzujian',
            label: '引入组件'
          },
          {
            value: 'monishuju',
            label: '模拟数据'
          }
        ]
      }
    ]
  },
  {
    value: 'zujian',
    label: '组件',
    children: [
      {
        value: 'basic',
        label: '框架风格',
        children: [
          {
            value: 'layout',
            label: 'Layout 布局'
          },
          {
            value: 'color',
            label: 'Color 色彩'
          },
          {
            value: 'font',
            label: 'Font 字体'
          },
          {
            value: 'icon',
            label: 'Icon 图标'
          }
        ]
      },
      {
        value: 'form',
        label: '表单组件',
        children: [
          {
            value: 'radio',
            label: 'Radio 单选框'
          },
          {
            value: 'checkbox',
            label: 'Checkbox 多选框'
          },
          {
            value: 'input',
            label: 'Input 输入框'
          },
          {
            value: 'number',
            label: 'Numeric 计数器'
          },
          {
            value: 'select',
            label: 'Select 选择器'
          },
          {
            value: 'cascader',
            label: 'Cascader 级联选择器'
          },
          {
            value: 'switch',
            label: 'Switch 开关'
          },
          {
            value: 'slider',
            label: 'Slider 滑块'
          },
          {
            value: 'time-picker',
            label: 'TimePicker 时间选择器'
          },
          {
            value: 'date-picker',
            label: 'DatePicker 日期选择器'
          },
          {
            value: 'form',
            label: 'Form 表单'
          }
        ]
      },
      {
        value: 'data',
        label: '数据组件',
        children: [
          {
            value: 'tree',
            label: 'Tree 树形控件'
          },
          {
            value: 'pager',
            label: 'Pager 分页'
          }
        ]
      },
      {
        value: 'notice',
        label: '提示组件',
        children: [
          {
            value: 'alert',
            label: 'Alert 警告'
          },
          {
            value: 'loading',
            label: 'Loading 加载'
          }
        ]
      },
      {
        value: 'navigation',
        label: '导航组件',
        children: [
          {
            value: 'menu',
            label: 'NavMenu 导航菜单'
          },
          {
            value: 'tabs',
            label: 'Tabs 标签页'
          },
          {
            value: 'breadcrumb',
            label: 'Breadcrumb 面包屑'
          },
          {
            value: 'steps',
            label: 'Steps 步骤条'
          }
        ]
      },
      {
        value: 'others',
        label: '其他组件',
        children: [
          {
            value: 'rate',
            label: 'Rate 评分'
          },
          {
            value: 'tag',
            label: 'Tag 标签'
          },
          {
            value: 'usercontact',
            label: 'UserContact 联系人'
          },
          {
            value: 'slidebar',
            label: 'SlideBar 滚动块'
          }
        ]
      }
    ]
  }
])
</script>

**Comment by yoyo201626** [comment]
displayOnly 目前不是 cascader 组件公开的属性

**Comment by falcon-jin** [comment]
> displayOnly

form表单里面使用cascader组件 配置form表单的displayOnly 属性会导致这个问题

**Comment by falcon-jin** [comment]
> displayOnly 目前不是 cascader 组件公开的属性

form表单里面使用cascader组件 配置form表单的displayOnly 属性会导致这个问题

**Comment by yoyo201626** [comment]
> > displayOnly 目前不是 cascader 组件公开的属性
> 
> form表单里面使用cascader组件 配置form表单的displayOnly 属性会导致这个问题

我跟踪一下

**Comment by yoyo201626** [comment]
这个问题在OpenTiny Vue@3.12.0没问题

注意 emitPath 设置为 false 时，value 只返回该节点的值

@falcon-jin 
![图片](https://github.com/opentiny/tiny-vue/assets/104079404/84b79dde-7a36-4b34-b151-136de8a845ad)

```ts
<template>
  <tiny-cascader 
     v-model="value"
     :options="options" 
     :display-only="true"
     :props="{ checkStrictly: true, multiple: true, leaf: 'leaf', emitPath: false }">
  </tiny-cascader>
</template>

<script>
import { Cascader } from '@opentiny/vue'

export default {
  components: {
    TinyCascader: Cascader
  },
  data() {
    return {
      value: ['xiangmudengji', 'huanjingzhunbei'],
      options: [
        {
          value: 'zhinan',
          label: '指南',
          children: [
            {
              value: 'anzhuang',
              label: '安装',
              children: [
                {
                  value: 'xiangmudengji',
                  label: '项目登记'
                },
                {
                  value: 'huanjingzhunbei',
                  label: '环境准备'
                },
                {
                  value: 'anzhuangcli',
                  label: '安装 CLI'
                },
                {
                  value: 'chuangjianxiangmu',
                  label: '创建项目'
                }
              ]
            },
            {
              value: 'kaifa',
              label: '开发',
              children: [
                {
                  value: 'yinruzujian',
                  label: '引入组件'
                },
                {
                  value: 'monishuju',
                  label: '模拟数据'
                }
              ]
            }
          ]
        },
        {
          value: 'zujian',
          label: '组件',
          children: [
            {
              value: 'basic',
              label: '框架风格',
              children: [
                {
                  value: 'layout',
                  label: 'Layout 布局'
                },
                {
                  value: 'color',
                  label: 'Color 色彩'
                },
                {
                  value: 'font',
                  label: 'Font 字体'
                },
                {
                  value: 'icon',
                  label: 'Icon 图标'
                }
              ]
            },
            {
              value: 'form',
              label: '表单组件',
              children: [
                {
                  value: 'radio',
                  label: 'Radio 单选框'
                },
                {
                  value: 'checkbox',
                  label: 'Checkbox 多选框'
                },
                {
                  value: 'input',
                  label: 'Input 输入框'
                },
                {
                  value: 'number',
                  label: 'Numeric 计数器'
                },
                {
                  value: 'select',
                  label: 'Select 选择器'
                },
                {
                  value: 'cascader',
                  label: 'Cascader 级联选择器'
                },
                {
                  value: 'switch',
                  label: 'Switch 开关'
                },
                {
                  value: 'slider',
                  label: 'Slider 滑块'
                },
                {
                  value: 'time-picker',
                  label: 'TimePicker 时间选择器'
                },
                {
                  value: 'date-picker',
                  label: 'DatePicker 日期选择器'
                },
                {
                  value: 'form',
                  label: 'Form 表单'
                }
              ]
            },
            {
              value: 'data',
              label: '数据组件',
              children: [
                {
                  value: 'tree',
                  label: 'Tree 树形控件'
                },
                {
                  value: 'pager',
                  label: 'Pager 分页'
                }
              ]
            },
            {
              value: 'notice',
              label: '提示组件',
              children: [
                {
                  value: 'alert',
                  label: 'Alert 警告'
                },
                {
                  value: 'loading',
                  label: 'Loading 加载'
                }
              ]
            },
            {
              value: 'navigation',
              label: '导航组件',
              children: [
                {
                  value: 'menu',
                  label: 'NavMenu 导航菜单'
                },
                {
                  value: 'tabs',
                  label: 'Tabs 标签页'
                },
                {
                  value: 'breadcrumb',
                  label: 'Breadcrumb 面包屑'
                },
                {
                  value: 'steps',
                  label: 'Steps 步骤条'
                }
              ]
            },
            {
              value: 'others',
              label: '其他组件',
              children: [
                {
                  value: 'rate',
                  label: 'Rate 评分'
                },
                {
                  value: 'tag',
                  label: 'Tag 标签'
                },
                {
                  value: 'usercontact',
                  label: 'UserContact 联系人'
                },
                {
                  value: 'slidebar',
                  label: 'SlideBar 滚动块'
                }
              ]
            }
          ]
        }
      ]
    }
  }
}
</script>

```

**Comment by falcon-jin** [comment]
> 这个问题在OpenTiny Vue@3.12.0没问题
> 
> 注意 emitPath 设置为 false 时，value 只返回该节点的值
> 
> @falcon-jin ![图片](https://private-user-images.githubusercontent.com/104079404/288996868-84b79dde-7a36-4b34-b151-136de8a845ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNTc5NDEsIm5iZiI6MTcwMjM1NzY0MSwicGF0aCI6Ii8xMDQwNzk0MDQvMjg4OTk2ODY4LTg0Yjc5ZGRlLTdhMzYtNGIzNC1iMTUxLTEzNmRlOGE4NDVhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQwNTA3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjZkMTY5NWY1Y2E0NGM5ZTVmMjdkZDNjODVkNGM4MDlkMzUxZTkzYmVhZjAzZDZiYzJmYmMyNDRkZjE2ZjU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3RXbso-ZML3t3zu7WwiKS9B2J4uZHmV65_QCM-tvgSw)
> 
> ```ts
> <template>
>   <tiny-cascader 
>      v-model="value"
>      :options="options" 
>      :display-only="true"
>      :props="{ checkStrictly: true, multiple: true, leaf: 'leaf', emitPath: false }">
>   </tiny-cascader>
> </template>
> 
> <script>
> import { Cascader } from '@opentiny/vue'
> 
> export default {
>   components: {
>     TinyCascader: Cascader
>   },
>   data() {
>     return {
>       value: ['xiangmudengji', 'huanjingzhunbei'],
>       options: [
>         {
>           value: 'zhinan',
>           label: '指南',
>           children: [
>             {
>               value: 'anzhuang',
>               label: '安装',
>               children: [
>                 {
>                   value: 'xiangmudengji',
>                   label: '项目登记'
>                 },
>                 {
>                   value: 'huanjingzhunbei',
>                   label: '环境准备'
>                 },
>                 {
>                   value: 'anzhuangcli',
>                   label: '安装 CLI'
>                 },
>                 {
>                   value: 'chuangjianxiangmu',
>                   label: '创建项目'
>                 }
>               ]
>             },
>             {
>               value: 'kaifa',
>               label: '开发',
>               children: [
>                 {
>                   value: 'yinruzujian',
>                   label: '引入组件'
>                 },
>                 {
>                   value: 'monishuju',
>                   label: '模拟数据'
>                 }
>               ]
>             }
>           ]
>         },
>         {
>           value: 'zujian',
>           label: '组件',
>           children: [
>             {
>               value: 'basic',
>               label: '框架风格',
>               children: [
>                 {
>                   value: 'layout',
>                   label: 'Layout 布局'
>                 },
>                 {
>                   value: 'color',
>                   label: 'Color 色彩'
>                 },
>                 {
>                   value: 'font',
>                   label: 'Font 字体'
>                 },
>                 {
>                   value: 'icon',
>                   label: 'Icon 图标'
>                 }
>               ]
>             },
>             {
>               value: 'form',
>               label: '表单组件',
>               children: [
>                 {
>                   value: 'radio',
>                   label: 'Radio 单选框'
>                 },
>                 {
>                   value: 'checkbox',
>                   label: 'Checkbox 多选框'
>                 },
>                 {
>                   value: 'input',
>                   label: 'Input 输入框'
>                 },
>                 {
>                   value: 'number',
>                   label: 'Numeric 计数器'
>                 },
>                 {
>                   value: 'select',
>                   label: 'Select 选择器'
>                 },
>                 {
>                   value: 'cascader',
>                   label: 'Cascader 级联选择器'
>                 },
>                 {
>                   value: 'switch',
>                   label: 'Switch 开关'
>                 },
>                 {
>                   value: 'slider',
>                   label: 'Slider 滑块'
>                 },
>                 {
>                   value: 'time-picker',
>                   label: 'TimePicker 时间选择器'
>                 },
>                 {
>                   value: 'date-picker',
>                   label: 'DatePicker 日期选择器'
>                 },
>                 {
>                   value: 'form',
>                   label: 'Form 表单'
>                 }
>               ]
>             },
>             {
>               value: 'data',
>               label: '数据组件',
>               children: [
>                 {
>                   value: 'tree',
>                   label: 'Tree 树形控件'
>                 },
>                 {
>                   value: 'pager',
>                   label: 'Pager 分页'
>                 }
>               ]
>             },
>             {
>               value: 'notice',
>               label: '提示组件',
>               children: [
>                 {
>                   value: 'alert',
>                   label: 'Alert 警告'
>                 },
>                 {
>                   value: 'loading',
>                   label: 'Loading 加载'
>                 }
>               ]
>             },
>             {
>               value: 'navigation',
>               label: '导航组件',
>               children: [
>                 {
>                   value: 'menu',
>                   label: 'NavMenu 导航菜单'
>                 },
>                 {
>                   value: 'tabs',
>                   label: 'Tabs 标签页'
>                 },
>                 {
>                   value: 'breadcrumb',
>                   label: 'Breadcrumb 面包屑'
>                 },
>                 {
>                   value: 'steps',
>                   label: 'Steps 步骤条'
>                 }
>               ]
>             },
>             {
>               value: 'others',
>               label: '其他组件',
>               children: [
>                 {
>                   value: 'rate',
>                   label: 'Rate 评分'
>                 },
>                 {
>                   value: 'tag',
>                   label: 'Tag 标签'
>                 },
>                 {
>                   value: 'usercontact',
>                   label: 'UserContact 联系人'
>                 },
>                 {
>                   value: 'slidebar',
>                   label: 'SlideBar 滚动块'
>                 }
>               ]
>             }
>           ]
>         }
>       ]
>     }
>   }
> }
> </script>
> ```

感谢 找到问题了 数据问题导致的
