### ISSUE TITLE
🐛 [Bug]: Slide组件change的触发次数好像有错误

### ISSUE THREAD

**Issue by AcWrong02** [opentiny/tiny-vue#1074]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://opentiny.design/tiny-vue/zh-CN/os-theme/components/slider#slider-event

输入框模式下：
```
<template>
  <tiny-slider v-model="value2" @change="change" show-input></tiny-slider>
</template>

<script setup>
import { ref } from 'vue'
import { Slider as TinySlider, Notify } from '@opentiny/vue'

const value2 = ref(40)

function change(val) {
  Notify({
    title: '触发change事件',
    message: `改变值为${val}`,
    offset: 100
  })
}

</script>

```

### Step to reproduce

点击Slider的任一区域一下，会发现触发了两次change事件
![image](https://github.com/opentiny/tiny-vue/assets/147061401/ec7c1e7c-43d3-4378-b80e-b1001eca3021)
输入框模式下，修改输入框的值，会发现触发了三次change事件

### What is expected

应该只触发一次

### What is actually happening

应该只触发一次，在输入框模式下甚至会触发三次！

**Comment by AcWrong02** [comment]
I will fix this bug.

**Comment by gweesin** [comment]
The pr #1056 also fixed this issue too.

**Comment by AcWrong02** [comment]
> The pr #1056 also fixed this issue too.

是的，该issue没有关闭而已

**Comment by liguangqing** [comment]
这个bug在3.25.0版本还是存在的
