### ISSUE TITLE
🐛 [Bug]: Slider组件拖拽结束的时候，鼠标还在按钮上，但tooltip隐藏

### ISSUE THREAD

**Issue by AcWrong02** [opentiny/tiny-vue#1077]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://opentiny.design/tiny-vue/zh-CN/os-theme/components/slider

### Step to reproduce

官网直接拖拽看看即可

### What is expected

Slider组件拖拽结束的时候，鼠标还在按钮上，但tooltip应该显示

### What is actually happening

Slider组件拖拽结束的时候，鼠标还在按钮上，但tooltip隐藏

**Comment by AcWrong02** [comment]
I will fix it.

**Comment by shenjunjian** [comment]
已验证
