### ISSUE TITLE
🐛 [Bug]: button按钮-loading属性

### ISSUE THREAD

**Issue by thestar077** [opentiny/tiny-vue#1092]
### Version

3.12.0

### Vue Version

3.2.47

### Link to minimal reproduction

点击按钮之后，loading=true，但是会有1秒的空白再出现转圈的效果

### Step to reproduce

![企业微信截图_17022781393222](https://github.com/opentiny/tiny-vue/assets/16183489/94241edc-b175-4ec0-987c-3a980467f03b)

**Comment by GaoNeng-wWw** [comment]
I will fix it

**Comment by Youyou-smiles** [comment]
API中有个resetTime的props，是用来防止重复点击按钮的。不控制这个props的时候，这个值默认是1秒。在添加laoding=true的按钮中建议加入reset-time="0"，就可以第一时间加上loading效果。

**Comment by GaoNeng-wWw** [comment]
https://github.com/opentiny/tiny-vue/pull/1124 fixed this promblem
