### ISSUE TITLE
🐛 [Bug]: [Slider] 输入框模式下，设置“min”属性为负值并且“value”为负值，不应该使用“%”符号

### ISSUE THREAD

**Issue by yoyo201626** [opentiny/tiny-vue#1111]
### Version

3.12.0

### Vue Version

3

### Link to minimal reproduction

https://opentiny.design/vue-playground?cmpId=slider&fileName=show-iput.vue&apiMode=Options&mode=pc&theme=default

### Step to reproduce

```ts
<template>
  <tiny-slider v-model="value2" :show-input="true" :min="-100"></tiny-slider>
</template>

<script>
import { Slider } from '@opentiny/vue'

export default {
  components: {
    TinySlider: Slider
  },
  data() {
    return {
      value2: -50
    }
  }
}
</script>

```

### What is expected

 输入框后面不应该显示%符号

### What is actually happening

 输入框后面显示%符号

![图片](https://github.com/opentiny/tiny-vue/assets/104079404/5119125a-2027-482b-85c0-3a18481866a7)

**Comment by yoyo201626** [comment]
建议新增加一个属性能配置输入框后面的符号

**Comment by AcWrong02** [comment]
> 建议新增加一个属性能配置输入框后面的符号

我会慢慢去解决这个组件的bug

**Comment by kongwoo** [comment]
What do I think is no problem? Since you have set -100, it can be displayed.
 You can use a custom slot and control whether to display the percentage sign yourself
