### ISSUE TITLE
🐛 [Bug]: [TimePicker] 滚动选择时间二次点击无法滚动至指定位置

### ISSUE THREAD

**Issue by xz-smile** [opentiny/tiny-vue#1132]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://opentiny.design/tiny-vue/zh-CN/os-theme/components/time-picker

### Step to reproduce

官网示例

### What is expected

点击后滚动至指定位置

**Comment by kagol** [comment]
Fixed by @wNing50 on #1169
