### ISSUE TITLE
🐛 [Bug]: The settings and props in the ToolBar of the TinyModal component and table require a default value.

### ISSUE THREAD

**Issue by kongwoo** [opentiny/tiny-vue#1133]
### Version

3.12.1

### Vue Version

2

### Link to minimal reproduction

![image](https://github.com/opentiny/tiny-vue/assets/149995045/e4a7ee0c-a9e3-411a-9adf-abf40e42efda)

### Step to reproduce

我是使用的是vue2,tiny-vue使用3.12.1

### What is expected

修复默认值，后台不要弹出警告

**Comment by zzcr** [comment]
最新版本已无此问题
