### ISSUE TITLE
🐛 [Bug]:  In the Google browser, when editing the custom component of the form, there will be a problem that the input cannot be backfilled, especially numbers.

### ISSUE THREAD

**Issue by kongwoo** [opentiny/tiny-vue#1134]
### Version

3.12.1

### Vue Version

2

### Link to minimal reproduction

下面的表格编辑，截图是我输入了好多“1”，但是没有回填到文本框里面
![image](https://github.com/opentiny/tiny-vue/assets/149995045/adae1744-af8d-4702-8eda-c7bd00fafc80)
等我失去焦点，只进去一个“1”
![image](https://github.com/opentiny/tiny-vue/assets/149995045/a913cad9-6c01-4d60-81c2-afdb79bc158f)
输入文字，不能回填文本框，但是失去焦点，推出编辑模式，会回显正常

### Step to reproduce

下面的表格编辑，截图是我输入了好多“1”，但是没有回填到文本框里面
![image](https://github.com/opentiny/tiny-vue/assets/149995045/adae1744-af8d-4702-8eda-c7bd00fafc80)
等我失去焦点，只进去一个“1”
![image](https://github.com/opentiny/tiny-vue/assets/149995045/a913cad9-6c01-4d60-81c2-afdb79bc158f)
输入文字，不能回填文本框，但是失去焦点，推出编辑模式，会回显正常
控制台 警告：
![image](https://github.com/opentiny/tiny-vue/assets/149995045/fbc2e06e-3faa-4a82-986e-9ac1be5e423a)

**Comment by gimmyhehe** [comment]
问题已收录~。  另外，能否在演练场提供一个最小可复现demo~

**Comment by gimmyhehe** [comment]
@kongwoo 尝试使用表格中使用textarea，未能复现描述问题，能够提供一个可复现demo~

**Comment by kongwoo** [comment]
我的问题是，我的表格在重复的换数据（包括表头和数据），根据不同的数据自动渲染，后面那个搞成文本域，没有回写，估计是在第一次的时候没有给key,不存在,我在验证验证

**Comment by kongwoo** [comment]
return {
          component: Input,
          attrs: { type: "textarea", resize: "vertical" },
        };
我会动态的给 表格设计编辑，我搞了个测试的，没有复现，没出来

**Comment by gimmyhehe** [comment]
@kongwoo 可能是没有加上key导致的某些异常，如无问题的话，可以联系我们关闭issue。如果加上key后还是有问题的话可以重开issue。

**Comment by kongwoo** [comment]
OK ,可以先关掉，我是用的场景比较奇特，一个表格搞了所有，后续我再研究研究

Issues-translate-bot ***@***.***> 于2024年1月13日周六 11:39写道：
