### ISSUE TITLE
🐛 [Bug]: Execute the pnpm build:ui command to build the error report

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-vue#115]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

执行以下命令构建组件库产物报以下错：
```
"./pc.vue" is imported as an external by "../../packages/vue/src/button-group/src/index.ts", but is already an existing non-external module id.
```

### Step to reproduce

执行以下命令构建组件库产物报以下错：
```
"./pc.vue" is imported as an external by "../../packages/vue/src/button-group/src/index.ts", but is already an existing non-external module id.
```

### What is expected

不报错

### What is actually happening

报错

**Comment by acyza** [comment]
windows环境不报错。https://github.com/acyza/tiny-vue/actions/runs/4642089527/jobs/8215659107
ubuntu环境报错。https://github.com/acyza/tiny-vue/actions/runs/4642064864/jobs/8215614369

**Comment by kagol** [comment]
> windows环境不报错。https://github.com/acyza/tiny-vue/actions/runs/4642089527/jobs/8215659107 ubuntu环境报错。https://github.com/acyza/tiny-vue/actions/runs/4642064864/jobs/8215614369

赞！确实是的，我在 windows 下也是成功的，在 macOS 下不行
