### ISSUE TITLE
✨ [Feature]: 为什么一个简单的页面请求超过27M

### ISSUE THREAD

**Issue by wkddkw** [opentiny/tiny-vue#1157]
### What problem does this feature solve

![image](https://github.com/opentiny/tiny-vue/assets/44052099/4ead5156-5bea-4c4f-b65a-1bde2f778bb2)

### What does the proposed API look like

是有什么配置 可以按需加载的 还是应该怎么做 有时间的话 麻烦告知 谢谢

**Comment by GaoNeng-wWw** [comment]
这是生产环境吗？

**Comment by wkddkw** [comment]
![image](https://github.com/opentiny/tiny-vue/assets/44052099/a2f87d74-b5ae-4ef8-b85e-28dd4a92c3f8)
生产环境的确没那么大了 这个页面加载超过5秒 是页面的问题吗

**Comment by wkddkw** [comment]
这个文件是要怎么才能精简一下 变小一点

**Comment by zzcr** [comment]
你好，可以使用按需加载打包插件@opentiny/vue-vite-import：https://opentiny.design/tiny-vue/zh-CN/os-theme/docs/import-components

**Comment by wkddkw** [comment]
好的 谢谢

**Comment by wkddkw** [comment]
![image](https://github.com/opentiny/tiny-vue/assets/44052099/81b9860e-baa7-446f-88fa-6018e3475513)
您好 这种样式如果要全局修改为padding:5px 要在哪个文件改 有参考吗
