### ISSUE TITLE
DialogBox 启用拖动时，能否设置鼠标的位置为拖动范围的限制

### ISSUE THREAD

**Issue by lanrenbulan** [opentiny/tiny-vue#1164]
启用拖动时，允许将窗口一直拖动到鼠标的位置。

比如向左拖动，目前是当窗口左边达到最左时，就不能继续拖动了。预期的效果是还能继续拖动，直到鼠标的位置。

![image](https://github.com/opentiny/tiny-vue/assets/9604624/b3acb744-a6e3-4e23-a8cf-9002f9bc3888)
![image](https://github.com/opentiny/tiny-vue/assets/9604624/66033b06-ac76-4a96-bc39-083e4b6fa71e)

**Comment by wNing50** [comment]
不难实现，得看是否需要设置

**Comment by kagol** [comment]
@lanrenbulan 想了解下是什么场景下需要将弹窗拖到窗口之外呢？

**Comment by kagol** [comment]
> 不难实现，得看是否需要设置

感谢你的贡献，咱们先了解下用户的使用场景，再做判断。@wNing50

**Comment by lanrenbulan** [comment]
公司好多屏幕都很小，用dialog内做表单，如果不能拖到窗口外，都没有多少的拖动空间

**Comment by lanrenbulan** [comment]
> @lanrenbulan 想了解下是什么场景下需要将弹窗拖到窗口之外呢？

公司电脑屏幕都很小，在用dialog内做表单时，如果不能拖到窗口外，都没有多少的拖动空间

**Comment by James-9696** [comment]
目前最新版版本，可将弹窗拖出浏览器窗口外，已实现
