### ISSUE TITLE
✨ [Feature]: Drop-down table component

### ISSUE THREAD

**Issue by tzwhyqq** [opentiny/tiny-vue#117]
### What problem does this feature solve

erp系统里面很多这种输入框弹出下拉表格，表格可以上下左右回车选中等功能。还能有工具栏。

### What does the proposed API look like

系统能提供改组件

**Comment by qinwencheng** [comment]
有图示参考吗 @tzwhyqq

**Comment by kagol** [comment]
@tzwhyqq 请提供一份该组件的效果图或者特性列表

**Comment by tzwhyqq** [comment]
功能列表 
1、下拉弹出表格。
2、弹出表格支持上下键 ，弹出表格底部支持自定义按钮等。
3、按回车选中光标所在行，并回显给选择弹出得列。
[https://hgdtest.oss-cn-hangzhou.aliyuncs.com/test/video/%E7%A4%BA%E4%BE%8B.mp4](url)  地址在浏览器可以打开。
类似aggird，hansontable 他们有个下拉表格。

**Comment by zzcr** [comment]
我们的select组件时支持下拉表格的：https://opentiny.design/tiny-vue/zh-CN/os-theme/components/select#disable-grid-select-radio
