### ISSUE TITLE
✨ [Feature]: Table editing excel editing mode

### ISSUE THREAD

**Issue by tzwhyqq** [opentiny/tiny-vue#118]
### What problem does this feature solve

表格现在编辑都是点编辑按钮弹出个界面或者 把表格里面显示输入框进行编辑，希望能像excel 那样。可以输入就编辑，还能支持方向箭头移动单元格。回车跳到当前单元格下的下一个行单元格。  tab 到下一个单元格。

### What does the proposed API look like

希望表格组件有该功能

**Comment by zzcr** [comment]
可以使用默认插槽，内部放入input框，然后input框就可以一直长显出来，方向箭头和tab跳转我们后面由计划加上
