### ISSUE TITLE
🐛 [Bug]: TinyTimeLine

### ISSUE THREAD

**Issue by IIITMan** [opentiny/tiny-vue#1197]
### Version

2.12.0

### Vue Version

2.6.14

### Link to minimal reproduction

TinyTimeLine

### Step to reproduce

引入TinyTimeLine组件

### What is actually happening

不管是否使用@click事件  控制台都会出现Invalid handler for event "click": got undefined

**Comment by shenjunjian** [comment]
无法重现，可能在最新版本已经修复
