### ISSUE TITLE
🐛 [Bug]:Grid组件中的Refresh按钮会请求2次

### ISSUE THREAD

**Issue by mjl30601901** [opentiny/tiny-vue#1203]
### Version

3.11.1

### Vue Version

3.3.7

### Link to minimal reproduction

https://opentiny.design/tiny-vue/zh-CN/os-theme/components/grid-toolbar#toolbar-refresh-grid

### Step to reproduce

在使用fetch-data的grid表格中，配置工具栏tiny-grid-toolbar和分页Pager，并在工具栏配置refresh按钮。如果直接点击refresh按钮，则只会请求一次数据，这属于正常。但如果点了一下分页，再点refresh按钮，数据请求会执行2次。官方demo就可以复现这个问题。

### What is expected

点击refresh按钮只请求一次

### What is actually happening

点击refresh按钮，连续请求了2次数据

**Comment by zzcr** [comment]
已修复：https://github.com/opentiny/tiny-vue/pull/1208
