### ISSUE TITLE
✨ [Feature]: Switch组件可以支持自定义图标

### ISSUE THREAD

**Issue by AcWrong02** [opentiny/tiny-vue#1204]
### What problem does this feature solve

可以自定义打开和关闭时的自定义图标
![image](https://github.com/opentiny/tiny-vue/assets/147061401/c1504c93-dea8-4b64-8e23-6300be4be3a3)
![image](https://github.com/opentiny/tiny-vue/assets/147061401/7bc346da-cddf-4ed7-b2f6-4a6cd1b95cae)

### What does the proposed API look like

自定义插槽的方式来替换图标

**Comment by zzcr** [comment]
自定义图标的mr已合入，这个单我关了哈
