### ISSUE TITLE
🐛 [Bug]: 附件上传多节点警告

### ISSUE THREAD

**Issue by mjl30601901** [opentiny/tiny-vue#1217]
### Version

3.11.1

### Vue Version

3.3.7

### Link to minimal reproduction

https://opentiny.design/vue-playground?cmpId=file-upload&fileName=basic-usage.vue&apiMode=Composition&mode=pc&theme=default

### Step to reproduce

使用该组件，会直接弹出各种Vue的透传警告，很影响调试

### What is expected

![Snipaste_2023-12-26_21-04-42](https://github.com/opentiny/tiny-vue/assets/75361555/623a01cc-107d-4bd6-8003-3ee4182193e6)

### What is actually happening

无警告

**Comment by chenxi-20** [comment]
你好，playground的警告需要等重新发runtime才会消失，fileupload的官网demo并没有此类警告；请问真正使用此组件时还会报警告吗，如果报警告的话，opentiny/vue版本号是多少呢 @mjl30601901
