### ISSUE TITLE
🐛 [Bug]: Vite Packaging, warning 'Cannot find module @opentiny/vue-icon/xxx'

### ISSUE THREAD

**Issue by Felix-jk** [opentiny/tiny-vue#1222]
### Version

3.12.1

### Vue Version

3.2.47

### Link to minimal reproduction

![image](https://github.com/opentiny/tiny-vue/assets/33026143/c99bbe29-06dc-4eae-aebd-33680e6ac2a9)

### Step to reproduce

![image](https://github.com/opentiny/tiny-vue/assets/33026143/b9b503a7-d515-4155-86ba-56c23cb7506a)

**Comment by chenxi-20** [comment]
加装一下图标库 npm i @opentiny/vue-icon @Felix-jk 
如若不行，还请给出问题复现步骤

**Comment by chenxi-20** [comment]
这边已排查，请等待下一版本修复

**Comment by shenjunjian** [comment]
上图中的图标名，漏掉了在default中导出来。  已提交修复代码

**Comment by Felix-jk** [comment]
大概什么时间发新版本？

**Comment by zzcr** [comment]
已发布新版本解决
