### ISSUE TITLE
🐛 [Bug]: The Select component displays blank when virtual scrolling and filtering are enabled.

### ISSUE THREAD

**Issue by lanrenbulan** [opentiny/tiny-vue#1238]
### Version

3.12

### Vue Version

3.3.7

### Link to minimal reproduction

https://opentiny.design/vue-playground?cmpId=select&fileName=optimization.vue&apiMode=Composition&mode=pc&theme=default

### Step to reproduce

add `filterable`

### What is expected

There will be no blank

### What is actually happening

There is a blank

### Any additional comments (optional)

![image](https://github.com/opentiny/tiny-vue/assets/9604624/6c2826d7-b83c-48d7-be0c-b8daade42d4d)

**Comment by shenjunjian** [comment]
目前虚拟滚动和filter功能不能适配，待以后会讨论方案

**Comment by zzcr** [comment]
3.20.0新版本已支持虚拟滚动有筛选功能
