### ISSUE TITLE
🐛 [Bug]: DialogBox组件拖拽功能，点击右上方的关闭图标的时候会触发拖拽结束事件

### ISSUE THREAD

**Issue by AcWrong02** [opentiny/tiny-vue#1242]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

see this demo:https://opentiny.design/tiny-vue/zh-CN/os-theme/components/dialog-box#draggable
![image](https://github.com/opentiny/tiny-vue/assets/147061401/cadd9855-5005-433f-9e8f-ff4f30a318ce)

### Step to reproduce

点击关闭图标

### What is expected

是否不应该触发拖拽结束事件？

### What is actually happening

只点击关闭图标，但是触发了拖拽事件

**Comment by James-9696** [comment]
目前最新版本，不拖拽，点击关闭close，没有触发拖拽结束事件。

**Comment by shenjunjian** [comment]
已经修复该问题
