### ISSUE TITLE
  const common = new window.TDCommon(['#footer'], {})   common.renderFooter()请问一下这个TDCommon在哪里定义的呀，如何修改

### ISSUE THREAD

**Issue by 1083314824** [opentiny/tiny-vue#1249]
const common = new window.TDCommon(['#footer'], {})   common.renderFooter()请问一下这个TDCommon在哪里定义的呀，如何修改
<img width="336" alt="企业微信截图_17043377641821" src="https://github.com/opentiny/tiny-vue/assets/58287410/ee8fa491-3268-4eaa-a02a-e5d5785e9208">

**Comment by kagol** [comment]
@1083314824 这个是TinyPro头部暴露出来的方法，你修改这个是希望达到什么效果呢？
