### ISSUE TITLE
🐛 [Bug]: Select组件如果render-type设置为tree，no-match-text和no-data-text属性不生效

### ISSUE THREAD

**Issue by pppploi8** [opentiny/tiny-vue#1252]
### Version

@opentiny/vue@3.12.1

### Vue Version

vue@3.3.12

### Link to minimal reproduction

https://opentiny.design/vue-playground?mode=pc&theme=default#3.12|eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgbGFuZz1cInRzeFwiPlxuLy8g5byV5YWlIEBvcGVudGlueS92dWUg57uE5Lu2XG5pbXBvcnQgeyBCdXR0b24sIExpbmsgfSBmcm9tICdAb3BlbnRpbnkvdnVlJ1xuXG5leHBvcnQgZGVmYXVsdCB7XG4gIGNvbXBvbmVudHM6IHtcbiAgICBUaW55QnV0dG9uOiBCdXR0b24sXG4gICAgVGlueUxpbms6IExpbmtcbiAgfSxcbiAgZGF0YSgpIHtcbiAgICByZXR1cm4ge1xuICAgICAgbXNnOiAnaGVsbG8gd29ybGQhJ1xuICAgIH1cbiAgfVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPFRpbnlCdXR0b24+56Gu5a6aPC9UaW55QnV0dG9uPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGRpdiBjbGFzcz1cInRpbnl2dWVcIj5cbiAgICA8ZGl2IGNsYXNzPVwidGlueXZ1ZS1wYWdlXCI+XG4gICAgICB0aW55dnVlXG4gICAgICA8dGlueS1saW5rIHR5cGU9XCJzdWNjZXNzXCIgaHJlZj0naHR0cHM6Ly9naXRodWIuY29tL29wZW50aW55L3RpbnktdnVlJz5cbiAgICAgICAgdGlueXZ1ZVxuICAgICAgPC90aW55LWxpbms+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlIGxhbmc9XCJsZXNzXCIgc2NvcGVkPlxuICBoMXtcbiAgICBjb2xvcjojNWU3Y2UwO1xuICB9XG4gIC50aW55dnVle1xuICAgIGZvbnQtc2l6ZTogMTh4cDtcbiAgICAmLXBhZ2V7XG4gICAgICBjb2xvcjojNWU3Y2UwO1xuICAgIH1cbiAgfVxuPC9zdHlsZT5cbiIsInNyYy8iOiJ7XCJpbXBvcnRzXCI6e1wiQG9wZW50aW55L3Z1ZVwiOlwiaHR0cHM6Ly9ucG0ub25taWNyb3NvZnQuY24vQG9wZW50aW55L3Z1ZUAzLjEyL3J1bnRpbWUvdGlueS12dWUubWpzXCIsXCJAb3BlbnRpbnkvdnVlLWljb25cIjpcImh0dHBzOi8vbnBtLm9ubWljcm9zb2Z0LmNuL0BvcGVudGlueS92dWVAMy4xMi9ydW50aW1lL3RpbnktdnVlLWljb24ubWpzXCIsXCJAb3BlbnRpbnkvdnVlLWxvY2FsZVwiOlwiaHR0cHM6Ly9ucG0ub25taWNyb3NvZnQuY24vQG9wZW50aW55L3Z1ZUAzLjEyL3J1bnRpbWUvdGlueS12dWUtbG9jYWxlLm1qc1wiLFwiQG9wZW50aW55L3Z1ZS1jb21tb25cIjpcImh0dHBzOi8vbnBtLm9ubWljcm9zb2Z0LmNuL0BvcGVudGlueS92dWVAMy4xMi9ydW50aW1lL3RpbnktdnVlLWNvbW1vbi5tanNcIixcIkBvcGVudGlueS92dWUtdGhlbWUvXCI6XCJodHRwczovL25wbS5vbm1pY3Jvc29mdC5jbi9Ab3BlbnRpbnkvdnVlLXRoZW1lQDMuMTIvXCIsXCJzb3J0YWJsZWpzXCI6XCJodHRwczovL25wbS5vbm1pY3Jvc29mdC5jbi9zb3J0YWJsZWpzQDEuMTUuMC9tb2R1bGFyL3NvcnRhYmxlLmVzbS5qc1wifX0iLCJ0c2NvbmZpZy5qc29uIjoie1xyXG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcclxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxyXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXHJcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXHJcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxyXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcclxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcclxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZVxyXG4gIH0sXHJcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xyXG4gICAgXCJ0YXJnZXRcIjogMy4zXHJcbiAgfVxyXG59XHJcbiIsInNyYy9uZXN0LXRyZWUudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZGVtby1zZWxlY3RcIj5cbiAgICA8cD7kuIvmi4nmoJHkuLrnqbrvvIzkvYbml6Dms5Xoh6rlrprkuYnkuLrnqbrml7bmmL7npLrlhoXlrrk8L3A+XG4gICAgPHRpbnktc2VsZWN0XG4gICAgICB2LW1vZGVsPVwidHJlZVZhbHVlM1wiXG4gICAgICBmaWx0ZXJhYmxlXG4gICAgICA6ZmlsdGVyLW1ldGhvZD1cImZpbHRlclwiXG4gICAgICBjbGVhcmFibGVcbiAgICAgIHZhbHVlLWZpZWxkPVwiaWRcIlxuICAgICAgdGV4dC1maWVsZD1cImxhYmVsXCJcbiAgICAgIHJlbmRlci10eXBlPVwidHJlZVwiXG4gICAgICA6dHJlZS1vcD1cIntkYXRhOiBbXX1cIlxuICAgICAgbm8tZGF0YS10ZXh0PVwiTm8gRGF0YSBUZXh0XCJcbiAgICAgIG5vLW1hdGNoLXRleHQ9XCJObyBNYXRjaFwiXG4gICAgPlxuICAgIFx0PHRlbXBsYXRlICNlbXB0eT5cbiAgICAgIFx0PGRpdj5cbiAgICAgICAgICDoh6rlrprkuYnml6DmlbDmja5cbiAgICAgICAgPC9kaXY+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvdGlueS1zZWxlY3Q+XG4gICAgPHA+5LiL5ouJ5qCR5Y+v5pCc57Si77yM5L2G5peg5rOV6Ieq5a6a5LmJ5pCc57Si5LiN5Yiw57uT5p6c5pe255qE5YaF5a65PC9wPlxuICAgIDx0aW55LXNlbGVjdFxuICAgICAgdi1tb2RlbD1cInRyZWVWYWx1ZTNcIlxuICAgICAgZmlsdGVyYWJsZVxuICAgICAgOmZpbHRlci1tZXRob2Q9XCJmaWx0ZXJcIlxuICAgICAgY2xlYXJhYmxlXG4gICAgICB2YWx1ZS1maWVsZD1cImlkXCJcbiAgICAgIHRleHQtZmllbGQ9XCJsYWJlbFwiXG4gICAgICByZW5kZXItdHlwZT1cInRyZWVcIlxuICAgICAgOnRyZWUtb3A9XCJ0cmVlT3BcIlxuICAgICAgbm8tZGF0YS10ZXh0PVwiTm8gRGF0YSBUZXh0XCJcbiAgICAgIG5vLW1hdGNoLXRleHQ9XCJObyBNYXRjaFwiXG4gICAgPjwvdGlueS1zZWxlY3Q+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFNlbGVjdCBhcyBUaW55U2VsZWN0IH0gZnJvbSAnQG9wZW50aW55L3Z1ZSdcblxuY29uc3QgdHJlZVZhbHVlMyA9IHJlZignJylcblxuY29uc3QgdHJlZU9wID0gcmVmKHtcbiAgZGF0YTogW1xuICAgIHtcbiAgICAgIGlkOiAxLFxuICAgICAgbGFiZWw6ICfkuIDnuqcgMScsXG4gICAgICBjaGlsZHJlbjogW1xuICAgICAgICB7XG4gICAgICAgICAgaWQ6IDQsXG4gICAgICAgICAgbGFiZWw6ICfkuoznuqcgMS0xJyxcbiAgICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgICAge1xuICAgICAgICAgICAgICBpZDogOSxcbiAgICAgICAgICAgICAgbGFiZWw6ICfkuInnuqcgMS0xLTEnXG4gICAgICAgICAgICB9LFxuICAgICAgICAgICAge1xuICAgICAgICAgICAgICBpZDogMTAsXG4gICAgICAgICAgICAgIGxhYmVsOiAn5LiJ57qnIDEtMS0yJ1xuICAgICAgICAgICAgfVxuICAgICAgICAgIF1cbiAgICAgICAgfVxuICAgICAgXVxuICAgIH0sXG4gICAge1xuICAgICAgaWQ6IDIsXG4gICAgICBsYWJlbDogJ+S4gOe6pyAyJyxcbiAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgIHtcbiAgICAgICAgICBpZDogNSxcbiAgICAgICAgICBsYWJlbDogJ+S6jOe6pyAyLTEnXG4gICAgICAgIH0sXG4gICAgICAgIHtcbiAgICAgICAgICBpZDogNixcbiAgICAgICAgICBsYWJlbDogJ+S6jOe6pyAyLTInXG4gICAgICAgIH1cbiAgICAgIF1cbiAgICB9XG4gIF1cbn0pXG5cbmNvbnN0IGZpbHRlciA9ICh2YWx1ZSwgZGF0YSkgPT4ge1xuICBpZiAoIXZhbHVlKSByZXR1cm4gdHJ1ZVxuXG4gIHJldHVybiBkYXRhLmxhYmVsLmluY2x1ZGVzKHZhbHVlKVxufVxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBzY29wZWQ+XG4uZGVtby1zZWxlY3QgLnRpbnktc2VsZWN0IHtcbiAgd2lkdGg6IDI3MHB4O1xufVxuPC9zdHlsZT5cbiIsIiI6IntcImltcG9ydHNcIjp7XCJAb3BlbnRpbnkvdnVlXCI6XCJodHRwczovL25wbS5vbm1pY3Jvc29mdC5jbi9Ab3BlbnRpbnkvdnVlQDMuMTIvcnVudGltZS90aW55LXZ1ZS5tanNcIixcIkBvcGVudGlueS92dWUtaWNvblwiOlwiaHR0cHM6Ly9ucG0ub25taWNyb3NvZnQuY24vQG9wZW50aW55L3Z1ZUAzLjEyL3J1bnRpbWUvdGlueS12dWUtaWNvbi5tanNcIixcIkBvcGVudGlueS92dWUtbG9jYWxlXCI6XCJodHRwczovL25wbS5vbm1pY3Jvc29mdC5jbi9Ab3BlbnRpbnkvdnVlQDMuMTIvcnVudGltZS90aW55LXZ1ZS1sb2NhbGUubWpzXCIsXCJAb3BlbnRpbnkvdnVlLWNvbW1vblwiOlwiaHR0cHM6Ly9ucG0ub25taWNyb3NvZnQuY24vQG9wZW50aW55L3Z1ZUAzLjEyL3J1bnRpbWUvdGlueS12dWUtY29tbW9uLm1qc1wiLFwiQG9wZW50aW55L3Z1ZS10aGVtZS9cIjpcImh0dHBzOi8vbnBtLm9ubWljcm9zb2Z0LmNuL0BvcGVudGlueS92dWUtdGhlbWVAMy4xMi9cIixcInNvcnRhYmxlanNcIjpcImh0dHBzOi8vbnBtLm9ubWljcm9zb2Z0LmNuL3NvcnRhYmxlanNAMS4xNS4wL21vZHVsYXIvc29ydGFibGUuZXNtLmpzXCJ9fSIsIl9vIjp7fX0=

### Step to reproduce

复制上面演练场demo链接打开即可

**Comment by jevin98** [comment]
当render-type设置为tree时，popper是tree组件。应该使用treeop属性。传入tree组件的empty-text属性设置空文本

**Comment by pppploi8** [comment]
> 当render-type设置为tree时，popper是tree组件。应该使用treeop属性。传入tree组件的empty-text属性设置空文本
可以，是我没注意到tree-op的说明，谢谢
