### ISSUE TITLE
🐛 [Bug]: 从Progress组件切换到其他组件控制台会报错

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-vue#1266]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

链接：https://opentiny.design/tiny-vue/zh-CN/os-theme/components/progress

从progress组件切换到tree等其他组件，控制台报错。

<img width="1977" alt="image" src="https://github.com/opentiny/tiny-vue/assets/9566362/450fb879-9a34-4ed6-b045-c91a8610761d">

### Step to reproduce

如上

**Comment by chenxi-20** [comment]
问题已修复，需要等待正式环境发布
