### ISSUE TITLE
✨ [Feature]: The tabs add button wants to be next to the tab tag. On the big screen, if you put it to the right, it will move too far.

### ISSUE THREAD

**Issue by z-ab** [opentiny/tiny-vue#127]
### What problem does this feature solve

tabs 添加按钮希望挨着tab标签，在大屏幕上，如果放到右侧，移动距离太远

### What does the proposed API look like

tabs 添加按钮希望挨着tab标签，在大屏幕上，如果放到右侧，移动距离太远

**Comment by kagol** [comment]
@z-ab 我重构了 tabs 组件添加按钮的位置，现在可以通过以下方式实现你要的功能，让添加按钮挨着 tab 标签。

```
<template>
  <tiny-tabs ... class="my-tabs">
    ...
  </tiny-tabs>
</template>

<style>
.my-tabs .tiny-tabs__header {
  justify-content: flex-start;
}
</style>
```

如果你的样式使用了 `scoped`，则需要使用 `::v-deep` 进行样式穿透。

```
.my-tabs ::v-deep .tiny-tabs__header {
  justify-content: flex-start;
}
```

效果如下：

<img width="533" alt="image" src="https://user-images.githubusercontent.com/9566362/231209589-5736205e-e82d-4df0-a18f-47c91788c412.png">

版本已更新，你只需要删除你项目中的 package-lock.json 文件，执行 `npm i` 命令，重装下 @opentiny/vue 即可体验。
