### ISSUE TITLE
🐛 [Bug]: menutree组件无法过滤，急急急急急

### ISSUE THREAD

**Issue by mjl30601901** [opentiny/tiny-vue#1289]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://opentiny.design/vue-playground?cmpId=tree-menu&fileName=filter-node-method.vue&apiMode=Composition&mode=pc&theme=default

### Step to reproduce

:filter-node-method过滤不起作用，即使直接返回false，也无法控制显示和隐藏

### What is expected

:filter-node-method为false隐藏

### What is actually happening

:filter-node-method为false不隐藏

**Comment by jevin98** [comment]
上面demo试了可以正常过滤

**Comment by kagol** [comment]
@mjl30601901 我试了下也是可以过滤的，你的意思是不是不能模糊匹配，目前的过滤是精确关键字匹配的。
