### ISSUE TITLE
🐛 [Bug]: Table component, when the column is frozen and fixed, the row data will be misplaced.

### ISSUE THREAD

**Issue by Felix-jk** [opentiny/tiny-vue#129]
### Version

3.6.1

### Vue Version

3.2.47

### Link to minimal reproduction

图示为 鼠标指向第一行数据，第一行底色是灰色，但是明显出现 “行错位”

> 
      <tiny-grid :data="tableData" align="center" border>
            <tiny-grid :data="tableData" align="center" border>
            <tiny-grid-column type="index" title="序号" width="200" fixed="left"></tiny-grid-column>
            <tiny-grid-column type="sn" title="设备编号" width="200" fixed="left"></tiny-grid-column>
            <tiny-grid-column type="name" title="设备名称" width="200"></tiny-grid-column>
            <tiny-grid-column type="desc" title="设备描述" width="200"></tiny-grid-column>
            <tiny-grid-column type="level" title="设备层级" width="200"></tiny-grid-column>

            <tiny-grid-column title="操作" width="200" fixed="right">
                  <template v-slot="data">
                        <div class="demo-custom-column">
                              <a>查看</a> | <a>编辑</a> | <a>删除</a>
                        </div>
                  </template>
            </tiny-grid-column>
      </tiny-grid>
      
      tableData: [
            { sn: 001, name: '测试001', desc: '描述内容', level:1 },
            ...
      ]

![image](https://user-images.githubusercontent.com/33026143/231363358-376097f6-941e-4bf2-b1d8-1895bfbbfa92.png)

### Step to reproduce

如上

**Comment by awspi** [comment]
我感觉是因为`headerHeight`的值不正确导致的.我注意到当更改页面大小时,也就是重新执行`recalculate`后就正常了,我试着把其中关于`headerHeight`的赋值的代码放在`updateStyle`中执行.结果上来看是解决了 #140

**Comment by kagol** [comment]
Fixed by @awspi on #140
