### ISSUE TITLE
🐛 [Bug]: 3.13.0版本下，tree组件的其它特性中的功能不能正常使用。

### ISSUE THREAD

**Issue by cyberkingkong** [opentiny/tiny-vue#1300]
### Version

3.13.0

### Vue Version

3.3.7

### Link to minimal reproduction

https://opentiny.design/tiny-vue/zh-CN/os-theme/components/tree#other

### Step to reproduce

https://opentiny.design/tiny-vue/zh-CN/os-theme/components/tree#other 文档中的演示在严格模式下，同时勾选下级功能是可以用的

### What is actually happening

opentiny vue 3.13.0+vue3.3.7 下同时勾选下级功能是不可用

**Comment by shenjunjian** [comment]
当前版本， 勾选下级的功能是正常的。 
3.13一般不再发补丁版，如果使用有问题，请升级最新版本
