### ISSUE TITLE
🐛 [Bug]: [anchor]固定模式的文档的文字写反了

### ISSUE THREAD

**Issue by fanbingbing16** [opentiny/tiny-vue#1303]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://opentiny.design/vue-playground?cmpId=anchor&fileName=is-affix.vue&apiMode=Composition&mode=pc&theme=default

### Step to reproduce

打开官网文档，点到Anchor 锚点组件，到固定模式

### What is expected

打开和关闭文字正确

### What is actually happening

打开和关闭文字写反了

**Comment by chenxi-20** [comment]
这个其实不是反的，这个描述是用来引导动作的。因为打开和关闭是一个动词。而不是说明当前的状态；所以后续可以变更一种说明，如：
“关闭固定模式”改为“非固定模式”，“打开固定模式“改为“固定模式”
