### ISSUE TITLE
🐛 [Bug]: 3.13.0 控制台出现警告

### ISSUE THREAD

**Issue by Kuntey** [opentiny/tiny-vue#1309]
### Version

3.13.0

### Vue Version

3.3.9

### Link to minimal reproduction

https://codesandbox.io/p/devbox/open-tiny-vue-tcw9dm

### Step to reproduce

使用表格组件会出现这个问题

### What is expected

移除控制台警告

### What is actually happening

![screenshot-20240116-134429](https://github.com/opentiny/tiny-vue/assets/70432310/37c069b1-5010-4fa6-8afa-f0f400318448)

**Comment by SongGuorong** [comment]
一样，同版本会出现很多的warn警告

![bug](https://github.com/opentiny/tiny-vue/assets/47802638/24311af8-7c15-4af0-ba78-3276cd39b57f)
