### ISSUE TITLE
✨ [Feature]: 【Pager】, hope to provide more text slots, likes total, jumper

### ISSUE THREAD

**Issue by Felix-jk** [opentiny/tiny-vue#1313]
### What problem does this feature solve

![image](https://github.com/opentiny/tiny-vue/assets/33026143/56ab81ca-f86b-496d-beb1-986ae4922741)

### What does the proposed API look like

![image](https://github.com/opentiny/tiny-vue/assets/33026143/56ab81ca-f86b-496d-beb1-986ae4922741)

**Comment by GaoNeng-wWw** [comment]
It seems like it has already been implemented. https://opentiny.design/tiny-vue/zh-CN/os-theme/components/pager

**Comment by zzcr** [comment]
已提供实现：https://opentiny.design/tiny-vue/zh-CN/os-theme/components/pager#custom-total
