### ISSUE TITLE
🐛 [Bug]: 图表组件报错导致无法显示

### ISSUE THREAD

**Issue by fanbingbing16** [opentiny/tiny-vue#1327]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

运行dev分支最新代码

### Step to reproduce

运行dev分支最新代码，打开图表组件文档，折线图、柱状图等正常显示，但是基本用法、 桑基图、瀑布图、漏斗图等，会报错，然后就无法显示图表
![image](https://github.com/opentiny/tiny-vue/assets/84823288/a2de6bb2-5c59-4a12-ac45-626155ec18f2)

### What is expected

正常显示不报错

### What is actually happening

无法显示

**Comment by kagol** [comment]
@fanbingbing16 请问现在还有这个问题吗？

**Comment by fanbingbing16** [comment]
@kagol 我发现我因为chart-beta中只写了几个组件，没有写完，所以导致没有写的组件都报错
