### ISSUE TITLE
✨ [Feature]: There are some problems with watch and computed properties after changing to the new architecture.

### ISSUE THREAD

**Issue by TC-twwang** [opentiny/tiny-vue#133]
### What problem does this feature solve

改为新架构后，针对对象数组的监听好像失效了

### What does the proposed API look like

 solved the feature

**Comment by kagol** [comment]
移动端组件 multi-select 的 isActive 计算属性未跟随其中的数组变化而生效。

**Comment by TC-twwang** [comment]
isActive: computed(() => state.headerInfo.some(item => item.isUP))
headerInfo值改变后，isActive值未改变，且也watch不到headerInfo的改变

**Comment by shenjunjian** [comment]
该问题已经修复！
