### ISSUE TITLE
🐛 [Bug]: 官网的选项式和组合式代码示例切换时，需要手动刷新一次

### ISSUE THREAD

**Issue by mengqiuleo** [opentiny/tiny-vue#1335]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://opentiny.design/tiny-vue/zh-CN/os-theme/components/carousel

### Step to reproduce

官网的选项式和组合式代码示例切换时，需要手动刷新一次

**Comment by GaoNeng-wWw** [comment]
i will fix it
