### ISSUE TITLE
🐛 [Bug]: Cascader cascade selector, missing length judgment for the field children array of the last layer of data

### ISSUE THREAD

**Issue by Felix-jk** [opentiny/tiny-vue#134]
### Version

3.6.1

### Vue Version

3.2.47

### Link to minimal reproduction

如下

### Step to reproduce

```vue
<template>
  <tiny-cascader v-model="value" :options="options"></tiny-cascader>
</template>

<script>
import { Cascader } from '@opentiny/vue'

export default {
  components: {
    TinyCascader: Cascader
  },
  data() {
    return {
      value: 'anzhuangcli',
      options: [
        {
          value: 'zhinan',
          label: '指南',
          children: [
            {
              value: 'anzhuang',
              label: '安装',
              children: [
                {
                  value: 'xiangmudengji',
                  label: '项目登记',
                  children: []  // focus this Field⏰
                }
              ]
            }
          ]
        }
      ]
    }
  }
}
</script>

``` 

### What is expected

组件选中"项目登记"后，隐藏 选项弹出框，并且把文本"项目登记" 设置到 input里

### What is actually happening

组件选中"项目登记"后，选项弹出框 仍然显示（认为 "项目登记" 还有子级可供选择），也未能把文本"项目登记" 设置到 input里。
![image](https://user-images.githubusercontent.com/33026143/231665625-10177dc2-6a7c-434b-8242-00c4008f8bb6.png)

**Comment by kagol** [comment]
感觉这个还是需要讨论下合理性，这个 `children: []` 为空时，目前是会在子面板显示"暂无数据"的，此时"项目登记"是能选还是不能选？（目前的实现是不能选，用户希望能选）我看 Element Plus 和 Ant Design 组件库是直接忽略空数组，不显示"暂无数据"，可以选择"项目登记"。 @zzcr @shenjunjian

**Comment by kagol** [comment]
> 感觉这个还是需要讨论下合理性，这个 `children: []` 为空时，目前是会在子面板显示"暂无数据"的，此时"项目登记"是能选还是不能选？（目前的实现是不能选，用户希望能选）我看 Element Plus 和 Ant Design 组件库是直接忽略空数组，不显示"暂无数据"，可以选择"项目登记"。 @zzcr @shenjunjian

**Comment by zzcr** [comment]
加个空数组判断吧，如果children为空数组也把本项当做最后一层，并且可以选中回显到输入框中

**Comment by kagol** [comment]
> 加个空数组判断吧，如果children为空数组也把本项当做最后一层，并且可以选中回显到输入框中

可以

**Comment by gamesyofo** [comment]
新增一个属性灵活配置？

**Comment by GaoNeng-wWw** [comment]
#143  修复了这个问题
