### ISSUE TITLE
✨ [Feature]: 增加悬浮按钮组件是否需要

### ISSUE THREAD

**Issue by fanbingbing16** [opentiny/tiny-vue#1346]
### What problem does this feature solve

![image](https://github.com/opentiny/tiny-vue/assets/84823288/92cc2b74-c861-4840-aee7-7c8d87eda4e0)
例如这种可以悬浮在固定位置的按钮

### What does the proposed API look like

移入按钮显示自定义内容（更多的图标、提示信息啥的）可以做成slot
点击事件
icon图标
文字
shap形状

**Comment by kagol** [comment]
这个组件是需要的，欢迎贡献

**Comment by fanbingbing16** [comment]
我接下来了，过年几天再去弄

**Comment by kagol** [comment]
Finished by @fanbingbing16 on #1394
