### ISSUE TITLE
✨ [Feature]: TinyVue  缺少TinyNG 里面的卡片组件 

### ISSUE THREAD

**Issue by LinLiang66** [opentiny/tiny-vue#1358]
### What problem does this feature solve

卡片组件是每个项目中必不可少的组件之一，能轻松应对各种页面的效果展示
![image](https://github.com/opentiny/tiny-vue/assets/93206426/95a8af31-73da-4372-ba51-a882302555bf)

### What does the proposed API look like

卡片组件是每个项目中必不可少的组件之一，能轻松应对各种页面的效果展示

**Comment by shuaidaodehongshaorou** [comment]
![image](https://github.com/opentiny/tiny-vue/assets/93206426/ea628e4e-73a4-4d1f-a704-fdc82f851e9e)

**Comment by kagol** [comment]
该组件已在 v3.14.0 版本中提供
