### ISSUE TITLE
🐛 [Bug]: Incorrect vue link on the official website

### ISSUE THREAD

**Issue by gamesyofo** [opentiny/tiny-vue#137]
### Version

1

### Vue Version

1

### Link to minimal reproduction

1

### Step to reproduce

1

### What is expected

1

### What is actually happening

1

### Any additional comments (optional)

1

**Comment by gamesyofo** [comment]
@kagol 需要改哪些文件

**Comment by kagol** [comment]
> @kagol 需要改哪些文件

具体是哪个链接错误呢？是官网底部的链接吗？

**Comment by gamesyofo** [comment]
> > @kagol 需要改哪些文件
> 
> 具体是哪个链接错误呢？是官网底部的链接吗？

![image](https://user-images.githubusercontent.com/48387797/232534846-023f6206-418f-469f-a2ca-149fa16afd32.png)
对，官网底部的链接，仓库搜了代码没找到对应位置

**Comment by hello-yezi** [comment]
@gamesyofo 您说的是建议把链接换成这个么？ https://cn.vuejs.org/

**Comment by kagol** [comment]
Fixed by @hello-yezi
