### ISSUE TITLE
🐛 [Bug]: 循环引用的风险

### ISSUE THREAD

**Issue by gzhidao1011** [opentiny/tiny-vue#1379]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

![image](https://github.com/opentiny/tiny-vue/assets/136431411/a6f2b287-9402-407c-941e-f945b4989d82)

### Step to reproduce

![image](https://github.com/opentiny/tiny-vue/assets/136431411/a266f0a2-4762-4080-87fd-607bb735b608)

**Comment by GaoNeng-wWw** [comment]
应该去这里开issue https://github.com/opentiny/tiny-engine
