### ISSUE TITLE
🐛 [Bug]: The left sidebar of the official website cannot be opened normally after it is closed.

### ISSUE THREAD

**Issue by mengqiuleo** [opentiny/tiny-vue#138]
### Version

3

### Vue Version

^3.2.47

### Link to minimal reproduction

![Snipaste_2023-04-14_01-04-56](https://user-images.githubusercontent.com/85825776/231833281-cb643b55-39f7-44b3-9d22-540495ceff3a.jpg)

### Step to reproduce

关闭左侧侧边栏后，无法打开侧边栏

**Comment by awspi** [comment]
问题是因为`toggle-button`的父元素未设置`overflow: visible;`,导致按钮显示不出来
<img width="530" alt="image" src="https://user-images.githubusercontent.com/66438036/232200134-62448700-3508-4465-aafd-7e64da1877e1.png">

**Comment by kagol** [comment]
已修复并重新部署网站
