### ISSUE TITLE
🐛 [Bug]: button设置native-type为submit，点击后就不会禁用一下，不知道是bug还是本来就是这样设计的？

### ISSUE THREAD

**Issue by fanbingbing16** [opentiny/tiny-vue#1401]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://www.opentiny.design/tiny-vue/zh-CN/os-theme/components/button

### Step to reproduce

点击其他按钮都有防止多次点击，只有基本用法第一行的主要按钮点击不会禁用1000毫秒
不知道这是bug还是这样设计的

**Comment by Youyou-smiles** [comment]
API中有个叫native-type的属性，这个属性用于控制按钮原生的 type 属性，当属性值是 'submit' | 'reset' 的时候 reset-time 是不生效的。

**Comment by shenjunjian** [comment]
确实如此设计的。 native-type 为 submit 或 reset时，  不触发禁用。


![image](https://github.com/user-attachments/assets/512aa33c-2688-4e1f-9d16-21ef9edadb38)
