### ISSUE TITLE
🐛 [Bug]: tag设置closable可关闭，点击关闭按钮不会关闭

### ISSUE THREAD

**Issue by fanbingbing16** [opentiny/tiny-vue#1406]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://www.opentiny.design/tiny-vue/zh-CN/os-theme/components/tag#tag-event-click

### Step to reproduce

点击关闭按钮并不会关闭

### What is expected

可以关闭

**Comment by chenxi-20** [comment]
你好，这个组件比较特殊，一、删除动作如果是组件自身去操作，涉及到组件自我销毁的问题，这样用户侧就获取不到tag真实存在的数量；二、如果是通过样式去隐藏，也是一样的道理。所以关闭动作需要用户自己去删除；也就是说关闭按钮的作用就是给用户侧去操作的，并不是触发组件自我销毁的动作

**Comment by fanbingbing16** [comment]
> 你好，这个组件比较特殊，一、删除动作如果是组件自身去操作，涉及到组件自我销毁的问题，这样用户侧就获取不到tag真实存在的数量；二、如果是通过样式去隐藏，也是一样的道理。所以关闭动作需要用户自己去删除；也就是说关闭按钮的作用就是给用户侧去操作的，并不是触发组件自我销毁的动作

![image](https://github.com/opentiny/tiny-vue/assets/84823288/3cd9bb04-ad06-4933-a647-1a755a867e76)
h好的，那我觉得文档这个地方要说明一下，不然容易照成误解
