### ISSUE TITLE
🐛 [Bug]: After initializing the project, the official website button and alert components are introduced, and the front-end defined (reading 'tiny_mode') is reported. "

### ISSUE THREAD

**Issue by lipan007** [opentiny/tiny-vue#141]
### Version

`-- @opentiny/vue@2.6.1

### Vue Version

2.6.10

### Link to minimal reproduction

e.runtime.esm.js:4605 [Vue warn]: inject() can only be used inside setup() or functional components.

found in

---> <Anonymous>
       <TinyButton>
         <Home> at src/views/Home.vue
           <App> at src/App.vue
             <Root>
ue warn]: Error in setup: "TypeError: Cannot read properties of undefined (reading 'tiny_mode')"

found in

---> <Anonymous>
       <TinyButton>
         <Home> at src/views/Home.vue
           <App> at src/App.vue
             <Root>
peError: Cannot read properties of undefined (reading 'tiny_mode')
 ue warn]: Error in data(): "TypeError: Cannot read properties of undefined (reading 'length')"

found in

---> <Anonymous>
       <TinyButton>
         <Home> at src/views/Home.vue
           <App> at src/App.vue
             <Root>
e.runtime.esm.js:4605 [Vue warn]: Error in render: "TypeError: Cannot read properties of undefined (reading 'buttonDisabled')"

found in

---> <Anonymous>
       <TinyButton>
         <Home> at src/views/Home.vue
           <App> at src/App.vue
             <Root>
e.runtime.esm.js:4605 [Vue warn]: inject() can only be used inside setup() or functional components.

found in

---> <Anonymous>
       <TinyAlert>
         <Home> at src/views/Home.vue
           <App> at src/App.vue
             <Root>

### Step to reproduce

vuecli 初始化项目
安装 tiny
引入官网例子

**Comment by acyza** [comment]
Mybe duplicate #23

**Comment by kagol** [comment]
@lipan007 先将 vue 版本固定为 `2.6.14` 试试看呢？我们来看下这个问题

**Comment by lipan007** [comment]
我把版本固定到2.6.14之后，button还是报相同的错误，alert弹窗文本确实没有了
![uTools_1681717448133](https://user-images.githubusercontent.com/66591734/232418665-791c79d6-ce44-4c5d-95e1-37f052dfa443.png)

**Comment by acyza** [comment]
> 我把版本固定到2.6.14之后，button还是报相同的错误，alert弹窗文本确实没有了 ![uTools_1681717448133](https://user-images.githubusercontent.com/66591734/232418665-791c79d6-ce44-4c5d-95e1-37f052dfa443.png)

你打开node_modules文件夹看看安装的vue版本是不是2.6，我试了2.6.10和2.6.14都没报错。

**Comment by acyza** [comment]
2.7会报错，好像是因为2.7不支持`composition-api`

**Comment by lipan007** [comment]
好了，我把版本固定之后,没有报错了，谢谢

**Comment by acyza** [comment]
@kagol 我看`vue-common`的adapter文件夹里有个vue2.7的文件夹，是有针对vue2.7单独的版本吗？

**Comment by lipan007** [comment]
tinycli后续会支持vue2么

**Comment by kagol** [comment]
> @kagol 我看`vue-common`的adapter文件夹里有个vue2.7的文件夹，是有针对vue2.7单独的版本吗？

是的哈~不过现在还没有发布 2.7 版本，后续有计划发布 2.7 版本，这样业务如果使用 vue2.7 就可以安装 @opentiny/vue@2.7 啦

**Comment by kagol** [comment]
> tinycli后续会支持vue2么

麻烦在这里提交一个 issue 哈
https://github.com/opentiny/tiny-cli/issues

**Comment by kagol** [comment]
> @kagol 我看`vue-common`的adapter文件夹里有个vue2.7的文件夹，是有针对vue2.7单独的版本吗？

vue2.7已支持，目前已发布 alpha 版本：`@opentiny/vue@2.11.0-alpha.2`
