### ISSUE TITLE
✨ [Feature]: need Collapse leftbar

### ISSUE THREAD

**Issue by youmu2010** [opentiny/tiny-vue#142]
### What problem does this feature solve

tinyVue don't support collapse leftbar/menu feature, this is an important and basic function, please support it as soon as possable! 

### What does the proposed API look like

collapse menu/leftbar

**Comment by awspi** [comment]
try `ToggleMenu`

**Comment by GaoNeng-wWw** [comment]
Would it be better to add a breakpoint event to the container component?

## Description

Breakpoint event can listen to the user's screen size change. Trigger event when the user's screen is less than or equal to a certain breakpoint

## Type define

```typescript
export type BreakPoints = 'sm' | 'md' | 'lg' | 'xl'; // or more breakpoints
export type BreakPointEvent = (breakpoints: BreakPoints)=>void;
```

## How to Use

```vue
<template>
  <div class="demo-container coBox1">
    <tiny-container @break-points="onBreakPoint">
      <template #header>
        <tiny-layout>Header</tiny-layout>
      </template>
      <template #aside>
        <tiny-layout>Aside</tiny-layout>
      </template>
      <tiny-layout>Main</tiny-layout>
    </tiny-container>
  </div>
</template>
<script lang="ts" setup>
const onBreakPoint = (breakPoints)=>{
   console.log(breakPoints); // when the user's screen is 768px will console md
}
</script>
```
