### ISSUE TITLE
🐛 [Bug]: TreeMenu 树型菜单  show-expand 属性设置 无效果

### ISSUE THREAD

**Issue by znakoa** [opentiny/tiny-vue#1442]
### Version

"@opentiny/vue": "3",

### Vue Version

”vue": "^3.4.15

### Link to minimal reproduction

TreeMenu 树型菜单  show-expand 属性设置 无效果

### Step to reproduce

TreeMenu 树型菜单  show-expand 属性设置 无效果

### What is expected

![image](https://github.com/opentiny/tiny-vue/assets/59088116/18755d22-2e27-4f9e-9ee0-da9e2b89a35f)
TreeMenu 树型菜单  show-expand 属性设置 无效果

### What is actually happening

![image](https://github.com/opentiny/tiny-vue/assets/59088116/18755d22-2e27-4f9e-9ee0-da9e2b89a35f)
TreeMenu 树型菜单  show-expand 属性设置 无效果

**Comment by wuyiping0628** [comment]
建议升级最新版本
