### ISSUE TITLE
🐛 [Bug]: 官网文档样式出错

### ISSUE THREAD

**Issue by fanbingbing16** [opentiny/tiny-vue#1448]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

页面变成了这样![image](https://github.com/opentiny/tiny-vue/assets/84823288/802f2f25-d514-4112-808c-5fca6f8a2dc7)
正确的样式是
![image](https://github.com/opentiny/tiny-vue/assets/84823288/43a19f8d-b6fa-454c-b211-f6e8c9e87641)

### Step to reproduce

按照视频操作https://zgvideos.oss-cn-shanghai.aliyuncs.com/videos/1709195483514.mp4

**Comment by kagol** [comment]
@fanbingbing16 
我这看着是正常的，你是怎么复现的呢？
![image](https://github.com/opentiny/tiny-vue/assets/9566362/f2c4d15b-b2e1-447f-876b-ab3c949cc00c)

**Comment by kagol** [comment]
哦，看到视频里有复现步骤，确实有这问题

**Comment by GaoNeng-wWw** [comment]
我来修复它
