### ISSUE TITLE
🐛 [Bug]: Input组件clear事件触发的时候input事件不触发

### ISSUE THREAD

**Issue by AcWrong02** [opentiny/tiny-vue#1484]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

<template>
  <div class="demo-input">
    <tiny-input v-model="clearValue" placeholder="clear" clearable @clear="onClear" @input="onInput" @blur="onBlur"></tiny-input>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { Input as TinyInput, Modal } from '@opentiny/vue'

const clearValue = ref('clear')

function onInput(value) {
  Modal.message({ message: `input 事件触发了,接受参数${value.target.value}`, status: 'info' })
}

function onBlur() {
  Modal.message({ message: 'blur 事件触发了', status: 'info' })
}

function onClear() {
  Modal.message({ message: 'clear 事件触发了', status: 'info' })
}
</script>

<style scoped>
.demo-input .tiny-input {
  width: 250px;
  margin: 5px;
}
</style>

### Step to reproduce

1. 点击clear图标，发现只触发了clear事件

### What is expected

触发clear后，应该触发input事件，因为modelValue的值发生改变了

### What is actually happening

只触发了clear事件

**Comment by AcWrong02** [comment]
I will fix it and add unit test of this component.

**Comment by shenjunjian** [comment]
非bug 问题，无需修改。
根据MDN ， input 事件是指的输入时的事件，处理中英文的输入， 接近于keydown ,但也不一样。  
清除动作本来就不是输入事件， 也不需要触发input。
