### ISSUE TITLE
upload file and scrollbar thumb

### ISSUE THREAD

**Issue by bouyeijiang** [opentiny/tiny-vue#1520]
### Version

3.11

### Vue Version

3

### Link to minimal reproduction

1、滚动条问题：调试的时候左右滚动条满粗的，发布以后就变细了，是opentiny版本低了？
2、文件上传问题：使用属性 list-type="saas" 好像没作用，什么也不显示，是opentiny版本低了？
不知道是不是我哪里样式覆盖了！

### Step to reproduce

1、滚动条问题：调试的时候左右滚动条满粗的，发布以后就变细了，是opentiny版本低了？
2、文件上传问题：使用属性 list-type="saas" 好像没作用，什么也不显示，是opentiny版本低了？
不知道是不是我哪里样式覆盖了！

### What is your project name

pm

**Comment by GaoNeng-wWw** [comment]
请问可以附带一个最小复现仓库吗？

**Comment by bouyeijiang** [comment]
用的是tiny pro，可能是部分样式覆盖了

**Comment by bouyeijiang** [comment]
用的是tiny pro，可能是部分样式覆盖了

**Comment by chenxi-20** [comment]
第二个问题，list-type属性新属性，应该是版本的问题，试试看更新版本

**Comment by bouyeijiang** [comment]
tiny list列出有套件
但是为什么tiny update @@opentiny/tiny-toolkit-pro 提示找不到

**Comment by chenxi-20** [comment]
这个套件属于@opentiny/tiny-cli，建议去这里提交issue
https://github.com/opentiny/tiny-cli/issues
@bouyeijiang
