### ISSUE TITLE
tiny-select组件在Safari浏览器中动画显示是从左上角飞下来的

### ISSUE THREAD

**Issue by Awjl** [opentiny/tiny-vue#1523]
### Version

^3.13.0

### Vue Version

^3.13.0

### Link to minimal reproduction

 <tiny-select v-model="spplier" >
          <tiny-option v-for="item in supplierOptions" :key="item.id" :label="item.name" :value="item.id">
          </tiny-option>
        </tiny-select>

### Step to reproduce

 <tiny-select v-model="spplier" >
          <tiny-option v-for="item in supplierOptions" :key="item.id" :label="item.name" :value="item.id">
          </tiny-option>
        </tiny-select>

### What is your project name

3pa

**Comment by shenjunjian** [comment]
从左上角飞下来的bug 已经修复了过，最新版本在Safari浏览器是正常的了
