### ISSUE TITLE
🐛 [Bug]: playground演练场代码显示类型不对

### ISSUE THREAD

**Issue by AcWrong02** [opentiny/tiny-vue#1532]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

根据官方文档，打开一个链接
https://opentiny.design/tiny-vue/zh-CN/os-theme/components/cascader

### Step to reproduce

![image](https://github.com/opentiny/tiny-vue/assets/147061401/850d97d6-6b7a-4e01-91ba-720b44216e40)
明明选择的是组合式API，进入演练场显示的却是选项式的

### What is expected

选择组合式API，进入演练场应该显示组合式API对应代码
选择选项式API，进入演练场应该显示选项式API对应代码

### What is actually happening

不论选择何种类型，进行演练场显示的都是选项式API代码

### What is your project name

null

**Comment by shenjunjian** [comment]
最近文档改版了，在新网站中验证：
1、点击代码展开， 是显示正确的代码风格。
2、点击进入演练声，只显示 **选项式** 风格， 需要修改。
