### ISSUE TITLE
🐛 [Bug]: Anchor anchor fixed mode demo default attribute is-affix is true, which is not convenient for document reading

### ISSUE THREAD

**Issue by CatsAndMice** [opentiny/tiny-vue#156]
### Version

v2.5.0/v3.5.0

### Vue Version

3.0.0

### Link to minimal reproduction

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/58327088/233084798-53609a2e-5e5b-41f8-a4a5-9d8dd986f136.png">
看文档时，它容易盖住文档信息，体验不佳

### Step to reproduce

Anchor 锚点 固定模式demo默认是开启的不随页面滚动，它容易盖住文档信息；
demo可以添加一个按钮，demo中is-affix设置为false,点击后置为true,这样体验会好点，并且盖住文档信息不会很突然

**Comment by chenxi-20** [comment]
已做优化
