### ISSUE TITLE
🐛 [Bug]: 在tsx文件中使用 TinyLink 标签使用onClick会爆错误说“不存在属性”

### ISSUE THREAD

**Issue by YuPeng6688** [opentiny/tiny-vue#1561]
### Version

最新的

### Vue Version

最新的

### Link to minimal reproduction

![WechatIMG3578](https://github.com/opentiny/tiny-vue/assets/150329130/0e91f366-f293-41a5-aa75-105e2fdafe11)

### Step to reproduce

![WechatIMG3578](https://github.com/opentiny/tiny-vue/assets/150329130/61d16770-3e1c-4a7c-8355-b0c39c465175)

### What is expected

在tsx文件中能使用js的方法

### What is your project name

广州地铁数子化系统

**Comment by shenjunjian** [comment]
组件确实未声明事件， 接下来统一整改一下组件的类型声明 。
