### ISSUE TITLE
🐛 [Bug]: The official website demo clicks the edit button and does not have a real full screen.

### ISSUE THREAD

**Issue by CatsAndMice** [opentiny/tiny-vue#157]
### Version

v2.5.0/v3.5.0

### Vue Version

3.0.0

### Link to minimal reproduction

https://opentiny.design/tiny-vue/zh-CN/os-theme/components/anchor#is-affix

### Step to reproduce

<img width="996" alt="image" src="https://user-images.githubusercontent.com/58327088/233089607-10550a7b-5ce9-47ed-af33-719962bbf8cd.png">
点击编辑按钮后，进入编辑全屏，但全屏并没有真正的全屏
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/58327088/233089511-452284eb-35a4-427c-b08e-f7eba0cb9d0c.png">

**Comment by zzcr** [comment]
目前官网的示例的实时编辑已改为vue的repl
