### ISSUE TITLE
🐛 [Bug]: Run @ opentiny/vue-docs package to report an error

### ISSUE THREAD

**Issue by CatsAndMice** [opentiny/tiny-vue#158]
### Version

3.6.1

### Vue Version

3.2.31

### Link to minimal reproduction

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/58327088/233108981-d7429b46-9f51-44cd-bc88-9cf84ebdb3c7.png">
运行@opentiny/vue-docs包命令 `pnpm run docs:dev` 报错

node.js版本：v18.12.0、16.18.0

### Step to reproduce

切换到@opentiny/vue-docs文件目录，运行命令 `pnpm run docs:dev`

**Comment by zzcr** [comment]
目前没有文档启动命令，已在package.json中删除，直接运行pnpm dev就可以启动文档
