### ISSUE TITLE
🐛 [Bug]: 文档问题

### ISSUE THREAD

**Issue by cqder** [opentiny/tiny-vue#1597]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://opentiny.design/tiny-vue/zh-CN/os-theme/docs/import-components

### Step to reproduce

引入组件 -》自动导入（推荐）-》Vite 中:
plugins: [autoImportPlugin()]
在使用electron-vite创建的项目中于‘electron.vite.config.mjs’文件中按文档步骤执行后，运行项目会报错。
查询autoImportPlugin后，
依据“@opentiny/unplugin-tiny-vue/dist/index.d.ts”如下注释中：
/** TinyVue 自动导入组件的插件，支持Vite,Webpack,Rollup 等常见的构建工具。
 * 目前不支持Tiny Icon的自动导入
 * @example
 * import autoImportPlugin from '@opentiny/unplugin-tiny-vue'
 * plugins: [autoImportPlugin('vite')]
 */

将plugins: [autoImportPlugin()]修改为‘plugins: [autoImportPlugin('vite')]’后，能成功运行项目。
请更新文档内容

### What is your project name

demo

**Comment by kagol** [comment]
@cqder 收到，感谢你的反馈~

**Comment by shenjunjian** [comment]
文档已更新
