### ISSUE TITLE
🐛 [Bug]: vue3.4.26 select组件只能放一个Option，放多个报错

### ISSUE THREAD

**Issue by zhongyii** [opentiny/tiny-vue#1606]
### Version

3.15.0

### Vue Version

3.4.26

### Link to minimal reproduction

<tiny-select v-model="value">
      <tiny-option v-for="item in options" :key="item.value" :label="item.label" :value="item.value" :icon="item.icon">
      </tiny-option>
    </tiny-select>

const options = ref([
  { value: '选项1', label: '黄金糕', icon: iconFile() },
  { value: '选项2', label: '双皮奶', icon: iconFile() },
  { value: '选项3', label: '蚵仔煎', icon: iconFile() },
  { value: '选项4', label: '龙须面', icon: iconFile() },
  { value: '选项5', label: '北京烤鸭', icon: iconFile() }
])
报错runtime-core.esm-bundler.js:3160 Uncaught (in promise) TypeError: Cannot assign to read only property '__v_skip' of object '#<Object>'

### Step to reproduce

报错runtime-core.esm-bundler.js:3160 Uncaught (in promise) TypeError: Cannot assign to read only property '__v_skip' of object '#<Object>'

### What is your project name

test

**Comment by kagol** [comment]
@zhongyii vue新版本有一些破坏性变更，请使用 vue@3.4.23 及以下版本。

**Comment by falcon-jin** [comment]
这个问题预计什么时候能够修复啊

**Comment by shubinla** [comment]
> @zhongyii vue新版本有一些破坏性变更，请使用 vue@3.4.23 及以下版本。

试了下3.4.23及以下还是不行啊

**Comment by smallseapig** [comment]
> @zhongyii vue新版本有一些破坏性变更，请使用 vue@3.4.23 及以下版本。

基于【@opentiny/vue3.12.1】切换了【vue3.4.23】后可以正常运行，谢谢！

**Comment by shenjunjian** [comment]
好像 vue@3.4.24 /25/26  这3个小版本出问题了。 后续的vue版本正常。
请避免依赖它们。

不需要组件库做修改。
