### ISSUE TITLE
✨ [Feature]: tiny-input 边框设成0，无效

### ISSUE THREAD

**Issue by zhouxiaobai518** [opentiny/tiny-vue#1607]
### What problem does this feature solve

<template>
  <div class="demo-input">
    <tiny-input v-model="input" placeholder="Please input"></tiny-input>
  </div>
</template>

<script>
import { Input } from '@opentiny/vue'

export default {
  components: {
    TinyInput: Input
  },
  data() {
    return {
      input: ''
    }
  }
}
</script>

<style>
.demo-input .tiny-input {
  width: 250px;
  border: 0px;
}
</style>

### What does the proposed API look like

<script>
import { Input } from '@opentiny/vue'

export default {
  components: {
    TinyInput: Input
  },
  data() {
    return {
      input: ''
    }
  }
}
</script>

<style>
.demo-input .tiny-input {
  width: 250px;
  border: 0px;
}
</style>

### What is your project name

test

**Comment by shenjunjian** [comment]
原因：
.tiny-input 这一层本来就没有边框。 可见的边框是加在 内部元素上的： 
![image](https://github.com/user-attachments/assets/f5a6bea2-048b-4251-97ba-97f5a06bd1f5)

办法：
可以通过 .demo-input    .tiny-input__inner { ..........  } 来覆盖样式。 

建议：
不建议你覆盖组件样式
