### ISSUE TITLE
🐛 [Bug]: PopEditor built-in pager, paging number option positioning exception

### ISSUE THREAD

**Issue by Felix-jk** [opentiny/tiny-vue#161]
### Version

3.6.7

### Vue Version

3.2.47

### Link to minimal reproduction

如下

### Step to reproduce

```vue
<template>
  <tiny-popeditor v-model="value" :grid-op="gridOp" show-pager :pager-op="gridOp.pagerOp"></tiny-popeditor>
</template>

<script>
import { Popeditor } from '@opentiny/vue'

export default {
  components: {
    TinyPopeditor: Popeditor
  },
  data() {
    return {
      value: '',
      gridOp: {
        columns: [
          { field: 'id', title: 'ID', width: 40 },
          { field: 'name', title: '名称' },
          { field: 'province', title: '省份', width: 80 },
          { field: 'city', title: '城市', width: 80 }
        ],
        data: [
          { id: '1', name: 'GFD科技YX公司', city: '福州', province: '福建' },
          { id: '2', name: 'WWW科技YX公司', city: '深圳', province: '广东' }
        ],
        pagerOp: {
          pageSize: 5,
          pageSizes: [5, 10, 20, 50, 100, 500],
          total: 10,
          layout: 'total, prev, pager, next, jumper, sizes'
        }
      }
    }
  }
}
</script>
```

### What is expected

分组数选项，在选项设置下方显示
![image](https://user-images.githubusercontent.com/33026143/233276997-f62c26bc-f6f1-4b42-bf00-347d67dab063.png)

### What is actually happening

![image](https://user-images.githubusercontent.com/33026143/233276684-db947f41-0325-492b-8f54-21bd901cb334.png)

**Comment by shenjunjian** [comment]
当前的最新版本，验证不出来有上述问题了！  下面是演练场路径
https://opentiny.design/vue-playground?mode=pc&theme=default#3.11|eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgbGFuZz1cInRzeFwiPlxyXG4vLyDlvJXlhaUgQG9wZW50aW55L3Z1ZSDnu4Tku7ZcclxuaW1wb3J0IHsgQnV0dG9uLCBMaW5rIH0gZnJvbSAnQG9wZW50aW55L3Z1ZSdcclxuXHJcbmV4cG9ydCBkZWZhdWx0IHtcclxuICBjb21wb25lbnRzOiB7XHJcbiAgICBUaW55QnV0dG9uOiBCdXR0b24sXHJcbiAgICBUaW55TGluazogTGlua1xyXG4gIH0sXHJcbiAgZGF0YSgpIHtcclxuICAgIHJldHVybiB7XHJcbiAgICAgIG1zZzogJ2hlbGxvIHdvcmxkISdcclxuICAgIH1cclxuICB9XHJcbn1cclxuPC9zY3JpcHQ+XHJcblxyXG48dGVtcGxhdGU+XHJcbiAgPFRpbnlCdXR0b24+56Gu5a6aPC9UaW55QnV0dG9uPlxyXG4gIDxoMT57eyBtc2cgfX08L2gxPlxyXG4gIDxkaXYgY2xhc3M9XCJ0aW55dnVlXCI+XHJcbiAgICA8ZGl2IGNsYXNzPVwidGlueXZ1ZS1wYWdlXCI+XHJcbiAgICAgIHRpbnl2dWVcclxuICAgICAgPHRpbnktbGluayB0eXBlPVwic3VjY2Vzc1wiIGhyZWY9J2h0dHBzOi8vZ2l0aHViLmNvbS9vcGVudGlueS90aW55LXZ1ZSc+XHJcbiAgICAgICAgdGlueXZ1ZVxyXG4gICAgICA8L3RpbnktbGluaz5cclxuICAgIDwvZGl2PlxyXG4gIDwvZGl2PlxyXG48L3RlbXBsYXRlPlxyXG5cclxuPHN0eWxlIGxhbmc9XCJsZXNzXCIgc2NvcGVkPlxyXG4gIGgxe1xyXG4gICAgY29sb3I6IzVlN2NlMDtcclxuICB9XHJcbiAgLnRpbnl2dWV7XHJcbiAgICBmb250LXNpemU6IDE4eHA7XHJcbiAgICAmLXBhZ2V7XHJcbiAgICAgIGNvbG9yOiM1ZTdjZTA7XHJcbiAgICB9XHJcbiAgfVxyXG48L3N0eWxlPlxyXG4iLCIiOiJ7XCJpbXBvcnRzXCI6e1wiQG9wZW50aW55L3Z1ZVwiOlwiaHR0cHM6Ly91bnBrZy5jb20vQG9wZW50aW55L3Z1ZUAzLjExL3J1bnRpbWUvdGlueS12dWUubWpzXCIsXCJAb3BlbnRpbnkvdnVlLWljb25cIjpcImh0dHBzOi8vdW5wa2cuY29tL0BvcGVudGlueS92dWVAMy4xMS9ydW50aW1lL3RpbnktdnVlLWljb24ubWpzXCIsXCJAb3BlbnRpbnkvdnVlLWxvY2FsZVwiOlwiaHR0cHM6Ly91bnBrZy5jb20vQG9wZW50aW55L3Z1ZUAzLjExL3J1bnRpbWUvdGlueS12dWUtbG9jYWxlLm1qc1wiLFwiQG9wZW50aW55L3Z1ZS1jb21tb25cIjpcImh0dHBzOi8vdW5wa2cuY29tL0BvcGVudGlueS92dWVAMy4xMS9ydW50aW1lL3RpbnktdnVlLWNvbW1vbi5tanNcIixcInNvcnRhYmxlanNcIjpcImh0dHBzOi8vdW5wa2cuY29tL3NvcnRhYmxlanNAMS4xNS4wL21vZHVsYXIvc29ydGFibGUuZXNtLmpzXCJ9fSIsInRzY29uZmlnLmpzb24iOiJ7XHJcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xyXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXHJcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcclxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcclxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXHJcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxyXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxyXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlXHJcbiAgfSxcclxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XHJcbiAgICBcInRhcmdldFwiOiAzLjNcclxuICB9XHJcbn1cclxuIiwibWFpbi1jb2xvci52dWUiOiI8dGVtcGxhdGU+XG4gIDx0aW55LXBvcGVkaXRvciB2LW1vZGVsPVwidmFsdWVcIiA6Z3JpZC1vcD1cImdyaWRPcFwiIHNob3ctcGFnZXIgOnBhZ2VyLW9wPVwiZ3JpZE9wLnBhZ2VyT3BcIj48L3RpbnktcG9wZWRpdG9yPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdD5cbmltcG9ydCB7IFBvcGVkaXRvciB9IGZyb20gJ0BvcGVudGlueS92dWUnIFxuXG5leHBvcnQgZGVmYXVsdCB7XG4gIGNvbXBvbmVudHM6IHtcbiAgICBUaW55UG9wZWRpdG9yOiBQb3BlZGl0b3JcbiAgfSxcbiAgZGF0YSgpIHtcbiAgICByZXR1cm4ge1xuICAgICAgdmFsdWU6ICcnLFxuICAgICAgZ3JpZE9wOiB7XG4gICAgICAgIGNvbHVtbnM6IFtcbiAgICAgICAgICB7IGZpZWxkOiAnaWQnLCB0aXRsZTogJ0lEJywgd2lkdGg6IDQwIH0sXG4gICAgICAgICAgeyBmaWVsZDogJ25hbWUnLCB0aXRsZTogJ+WQjeensCcgfSxcbiAgICAgICAgICB7IGZpZWxkOiAncHJvdmluY2UnLCB0aXRsZTogJ+ecgeS7vScsIHdpZHRoOiA4MCB9LFxuICAgICAgICAgIHsgZmllbGQ6ICdjaXR5JywgdGl0bGU6ICfln47luIInLCB3aWR0aDogODAgfSBcbiAgICAgICAgXSxcbiAgICAgICAgZGF0YTogW1xuICAgICAgICAgIHsgaWQ6ICcxJywgbmFtZTogJ0dGROenkeaKgFlY5YWs5Y+4JywgY2l0eTogJ+emj+W3nicsIHByb3ZpbmNlOiAn56aP5bu6JyB9LFxuICAgICAgICAgIHsgaWQ6ICcyJywgbmFtZTogJ1dXV+enkeaKgFlY5YWs5Y+4JywgY2l0eTogJ+a3seWcsycsIHByb3ZpbmNlOiAn5bm/5LicJyB9XG4gICAgICAgIF0sXG4gICAgICAgIHBhZ2VyT3A6IHtcbiAgICAgICAgICBwYWdlU2l6ZTogNSxcbiAgICAgICAgICBwYWdlU2l6ZXM6IFs1LCAxMCwgMjAsIDUwLCAxMDAsIDUwMF0sXG4gICAgICAgICAgdG90YWw6IDEwLFxuICAgICAgICAgIGxheW91dDogJ3RvdGFsLCBwcmV2LCBwYWdlciwgbmV4dCwganVtcGVyLCBzaXplcydcbiAgICAgICAgfVxuICAgICAgfVxuICAgIH1cbiAgfVxufVxuPC9zY3JpcHQ+IiwiX28iOnt9fQ==
