### ISSUE TITLE
🐛 [Bug]: Official document component pop-up box exception

### ISSUE THREAD

**Issue by Zz-ZzzZ** [opentiny/tiny-vue#163]
### Version

Windows 11 Chrome

### Vue Version

latest

### Link to minimal reproduction

https://opentiny.design/

### Step to reproduce

![1682055603384](https://user-images.githubusercontent.com/48228016/233549663-b90ac7d5-b8ea-45c6-8b77-94f47d79dc4a.jpg)
在此处点击选择框或日期选择器滚动鼠标时会导致弹出层错位

### What is expected

应和组件文档内部一样弹出层位置始终跟随组件

**Comment by zzcr** [comment]
新版本已修复此问题
