### ISSUE TITLE
🐛 [Bug]: 单独引入树组件opentiny/vue-tree后打包内存溢出

### ISSUE THREAD

**Issue by Hxlone** [opentiny/tiny-vue#1639]
### Version

3.14.1

### Vue Version

3.3.4

### Link to minimal reproduction

![img_v3_02b4_9218ea60-d17d-4d7e-8d90-40fedb8fdc5g](https://github.com/opentiny/tiny-vue/assets/35062576/a63712bc-bda8-4bd0-aa18-d0fbe1bb8981)
如图

### Step to reproduce

项目中单独引入opentiny/vue-tree后执行npm run build 打包内存溢出

### What is your project name

0

**Comment by GaoNeng-wWw** [comment]
如果使用的是vite, 目前临时解决方案只有增大打包`max_old_space_size`的允许范围
```
export NODE_OPTIONS=--max-old-space-size=32768
```
更多: https://github.com/vitejs/vite/issues/2433
