### ISSUE TITLE
🐛 [Bug]: 调用 Modal.confirm 控制台警告：Failed to resolve component: question

### ISSUE THREAD

**Issue by ezhizao** [opentiny/tiny-vue#1665]
### Version

3.16.0

### Vue Version

3.4.21

### Link to minimal reproduction

新建一个vue3项目
【package.json】文件内容
{
  "name": "vue3-test",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@opentiny/vue": "^3.16.0",
    "vue": "^3.4.21"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.0.4",
    "vite": "^5.2.0"
  }
}
【App.vue】文件内容
<script setup>
import { onMounted } from 'vue'
import HelloWorld from './components/HelloWorld.vue'
import { Modal } from '@opentiny/vue'
import { IconHelpSolid } from '@opentiny/vue-icon'

onMounted(() => {
  Modal.confirm('您确定要删除吗？').then((res) => {
    console.log(res)
  })
})
</script>

<template>
  <div>
    <a href="https://vitejs.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
  </div>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

### Step to reproduce

执行npm run dev，控制台就出现警告：Failed to resolve component: question
![warning](https://github.com/opentiny/tiny-vue/assets/165622076/2404b189-bdbf-4735-ae56-eee0656d8c28)

### What is your project name

练习的项目

**Comment by James-9696** [comment]
此问题已定位

**Comment by James-9696** [comment]
3.17 版本已修改
