### ISSUE TITLE
🐛 [Bug]: WeChat account error of the official assistant in Issue template

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-vue#167]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

应该是：opentiny-official

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/9566362/233767443-8cc15786-b29c-40f6-ad3d-52dbbafe473c.png">

### Step to reproduce

Issue 模板中的小助手微信号错误，应该是：opentiny-official

**Comment by heygsc** [comment]
改动了一下，连同issue #168 ， pr已经提交 #171

**Comment by kagol** [comment]
Fixed by @heygsc on #171
