### ISSUE TITLE
🐛 [Bug]: select多选场景下不设置filterable，点击输入框不会触发focus和blur事件

### ISSUE THREAD

**Issue by wtina** [opentiny/tiny-vue#1675]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

<template>
  <div>
    <div>单选</div>
    <br />
    <h-select
      v-model="value1"
      clearable
      @change="change"
      @blur="blur"
      @focus="focus"
      @visible-change="visibleChange"
      @clear="clear"
      @dropdown-click="dropdownClick"
    >
      <h-option v-for="item in options" :key="item.value" :label="item.label" :value="item.value"> </h-option>
    </h-select>
    <br />
    <br />
    <div>多选</div>
    <br />
    <h-select
      v-model="value2"
      multiple
      clearable
      @change="change"
      @blur="blur"
      @focus="focus"
      @visible-change="visibleChange"
      @on-item-remove="removeTag"
      @dropdown-click="dropdownClick"
    >
      <h-option v-for="item in options" :key="item.value" :label="item.label" :value="item.value"> </h-option>
    </h-select>
  </div>
</template>

<script>
import { Select, Option, Modal } from '@hui3/vue'

export default {
  components: {
    HSelect: Select,
    HOption: Option
  },
  data() {
    return {
      options: [
        { value: '选项1', label: '黄金糕' },
        { value: '选项2', label: '双皮奶' },
        { value: '选项3', label: '蚵仔煎' },
        { value: '选项4', label: '龙须面' },
        { value: '选项5', label: '北京烤鸭' }
      ],
      value1: '',
      value2: []
    }
  },
  methods: {
    change() {
      Modal.message({
        message: '触发 change 事件',
        status: 'info'
      })
    },
    clear() {
      Modal.message({
        message: '触发 clear 事件',
        status: 'info'
      })
    },
    focus() {
      Modal.message({
        message: '触发 focus 事件'
      })
    },
    blur() {
      Modal.message({
        message: '触发 blur 事件',
        status: 'info'
      })
    },
    removeTag() {
      Modal.message({
        message: '触发 on-item-remove 事件',
        status: 'info'
      })
    },
    visibleChange() {
      // Modal.message({
      //   message: '触发 visible-change 事件',
      //   status: 'info'
      // })
    },
    dropdownClick() {
      Modal.message({
        message: '触发 dropdown-click 事件',
        status: 'info'
      })
    }
  }
}
</script>

<style lang="less" scoped>
.tiny-select {
  width: 280px;
}
p {
  font-size: 14px;
  line-height: 1.5;
}
</style>

### Step to reproduce

不开启filterable

### What is expected

希望不开启filterable，也可以触发聚焦失焦事件

### What is actually happening

实际不会触发失焦聚焦事件

### What is your project name

hundsun

### Any additional comments (optional)

无

**Comment by wtina** [comment]
When filterable is not set, if there is no selected item, clicking the input box will trigger. When there is a selected item, the input box will be covered by the tag and will not trigger.

**Comment by wtina** [comment]
> > Bot detected the issue body's language is not English, translate it automatically.
> 
> **Title:** 🐛 [Bug]: Filterable is not set in the select multi-select scenario, and clicking the input box will not trigger the focus and blur events.

When filterable is not set, if there is no selected item, clicking the input box will trigger. When there is a selected item, the input box will be covered by the tag and will not trigger.

**Comment by shenjunjian** [comment]
为什么这个组件从 hui 库中引入呢？提供的源码第一行：
import { Select, Option, Modal } from '**@hui3/vue**'

**Comment by shenjunjian** [comment]
![image](https://github.com/user-attachments/assets/3f716390-7d4e-46cb-806b-0ff36ff2d8d9)

根据文档，它是监听输入框的事件。 而没有filter时，  下拉组件只有下拉/ 选择功能， 没有输入框的。所以没有这blur事件是合理的。
