### ISSUE TITLE
🐛 [Bug]: Incorrect local startup port number in Chinese and English README and contribution guide documents

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-vue#168]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

`pnpm dev` 命令启动的端口号应该是：7130

<img width="469" alt="image" src="https://user-images.githubusercontent.com/9566362/233767581-06e41808-8c67-4d6e-b33c-a2dfcc5d9768.png">

### Step to reproduce

`pnpm dev` 命令启动的端口号应该是：7130

**Comment by heygsc** [comment]
改动了一下，pr已提交  #170

**Comment by heygsc** [comment]
改动了一下，连同issue #167 ， pr已经提交 #171

**Comment by kagol** [comment]
Fixed by @heygsc on #171
