### ISSUE TITLE
🐛 [Bug]: select组件开启属性click-expend,不会生效，选中项被隐藏

### ISSUE THREAD

**Issue by wtina** [opentiny/tiny-vue#1692]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

<template>
  <div>
    <br />
    <div>场景1： collapse-tags折叠</div>
    <br />
    
    <br />
    <br />
    <div>场景2： hover-expand 折叠</div>
    <br />
    
    <br />
    <br />
    <br />
    <div>场景3： click-expand 折叠</div>
    <br />
    <h-select v-model="value3" :max-visible-rows="2" multiple click-expand>
      <h-option v-for="item in options" :key="item.value" :label="item.label" :value="item.value"> </h-option>
    </h-select>
  </div>
</template>

<script>
import { Select, Option } from '@hui3/vue'

export default {
  components: {
    HSelect: Select,
    HOption: Option
  },
  data() {
    return {
      options: [
        { value: '选项1', label: '黄金糕' },
        { value: '选项2', label: '双皮奶' },
        { value: '选项3', label: '蚵仔煎' },
        { value: '选项4', label: '龙须面超长超长超长超长超长超长超长超长超长' },
        { value: '选项5', label: '北京烤鸭' },
        { value: '选项6', label: '肠粉' }
      ],
      value1: ['选项1', '选项2'],
      value2: ['选项1', '选项2', '选项3', '选项4'],
      value3: ['选项1', '选项2', '选项3', '选项4', '选项5']
    }
  }
}
</script>

<style lang="less" scoped>
.tiny-select {
  width: 280px;
}
</style>

### Step to reproduce

开启click-expend，不会折叠，选中项不会展示

### What is your project name

hundsun

**Comment by kagol** [comment]
@wtina API文档错误，应该是`click-expand`，而不是`click-expend`，我们将在下一个版本中修复此问题。
关于`click-expand`的使用可以参考以下demo：
[https://opentiny.design/tiny-vue/zh-CN/smb-theme/components/select#collapse-tags](https://opentiny.design/tiny-vue/zh-CN/smb-theme/components/select#collapse-tags)
![image](https://github.com/opentiny/tiny-vue/assets/9566362/7d2b9c92-75c9-439d-b65a-6702335f6194)
