### ISSUE TITLE
🐛 [Bug]: form表单配置display-only label-position="right"有些组件样式不对

### ISSUE THREAD

**Issue by falcon-jin** [opentiny/tiny-vue#1698]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

![image](https://github.com/opentiny/tiny-vue/assets/48880836/8bf34fe9-d508-4ad6-9bd1-57ba548d5e4f)
https://opentiny.design/vue-playground?cmpId=form&fileName=display-only.vue&apiMode=Options&mode=pc&theme=default

### Step to reproduce

上面演练场 label-position="right"

### What is your project name

https://opentiny.design/vue-playground?cmpId=form&fileName=display-only.vue&apiMode=Options&mode=pc&theme=default

**Comment by gimmyhehe** [comment]
@falcon-jin 问题已收录，修复后将于3.18.0版本发布~
