### ISSUE TITLE
🐛 [Bug]: tiny-grid中单元格右键菜单点击事件无效

### ISSUE THREAD

**Issue by stwflyfox** [opentiny/tiny-vue#1709]
### Version

latest

### Vue Version

vue3

### Link to minimal reproduction

tiny-grid中右键菜单点击事件无效

### Step to reproduce

[在tinyVue官方演练场中测试](https://opentiny.design/vue-playground?cmpId=grid-context-menu&fileName=context-menu/cell-menu.vue&apiMode=Options&mode=pc&theme=default)
使用 chrome (版本126.0.6478.115) 不会触发菜单点击后事件
![image](https://github.com/opentiny/tiny-vue/assets/3983204/cfb17ebf-7683-4dee-8174-5afc413fff24)
在 360 浏览器中会触发，但打开了一个空白页
![image](https://github.com/opentiny/tiny-vue/assets/3983204/f64f22ff-ebe3-4472-9ac6-826826e15a21)

### What is your project name

TinyVue

**Comment by gimmyhehe** [comment]
@stwflyfox 在演练场中确实会有此问题，但是在真实工程中并没有，应该是演练场的bug，我们定位一下~

**Comment by gweesin** [comment]
have been working normally now.
