### ISSUE TITLE
✨ [Feature]: Select 选择器建议添加布尔类型的支持

### ISSUE THREAD

**Issue by YuPeng6688** [opentiny/tiny-vue#1715]
### What problem does this feature solve

多类型多方案场景的一个支持，比如用户业务需求用到此组件就只要布尔值，可以给用户操作多一个选择

### What does the proposed API look like

添加支持布尔类型

### What is your project name

广州地铁数字化管理系统

**Comment by kagol** [comment]
@YuPeng6688 你指的是`v-model`绑定值支持布尔类型吗？
![image](https://github.com/opentiny/tiny-vue/assets/9566362/9feb2e72-a0b8-4739-a55c-577a0bac96a2)

**Comment by YuPeng6688** [comment]
是的

**Comment by zzcr** [comment]
你好，经过内部评审，不需要做，可以用switch组件代替哈
