### ISSUE TITLE
🐛 [Bug]: pnpm lock file shouldn't be ignored by git

### ISSUE THREAD

**Issue by zuixinwang** [opentiny/tiny-vue#172]
### Version

latest

### Vue Version

^3.2.31

### Link to minimal reproduction

It is necessary to lock dependent version

### Step to reproduce

deps installation successful, but postinstall hook runs failed, maybe caused by deps version, I will check it later.I think the deps lock file shouldn't be ignored by git.
<img width="1080" alt="1" src="https://user-images.githubusercontent.com/59717852/233785260-8a87c669-0d2d-4b69-8423-19dd7f65c002.png">

@kagol

**Comment by zuixinwang** [comment]
I switch pnpm to version 7.11.0, it works OK with some warn

**Comment by zuixinwang** [comment]
@kagol 
Hello, is this PR useful? 😺

**Comment by kagol** [comment]
> @kagol Hello, is this PR useful? 😺

I agree.

**Comment by zuixinwang** [comment]
But the lock file is still not in the repo. 🐶 @kagol

**Comment by zuixinwang** [comment]
Can you commit the lock file? @kagol 
Installing dependencies is a poor experience, and different version dependencies can cause unknown issues.

**Comment by zuixinwang** [comment]
Would someone be able to fix this? 🙄

**Comment by zuixinwang** [comment]
@zzcr Can you commit the lock file? 🐶

**Comment by zzcr** [comment]
目前决定不提交lock文件，因为我们内部的lock文件和外部有很大的差异
