### ISSUE TITLE
🐛 [Bug]: 高德地图代码注释错误

### ISSUE THREAD

**Issue by henryTu9972** [opentiny/tiny-vue#1727]
### Version

v2.16.0/v3.16.0

### Vue Version

3.2.13

### Link to minimal reproduction

https://opentiny.design/tiny-vue/zh-CN/os-theme/components/chart-autonavi-map

### Step to reproduce

![微信图片_20240708173327](https://github.com/opentiny/tiny-vue/assets/109933518/4b77bbbd-2b22-43a2-9536-cc8037fab8a5)
![微信图片_20240708173327](https://github.com/opentiny/tiny-vue/assets/109933518/f12c86c7-6d74-4fc3-bcd9-7c5920670d2a)
打开tinyvue官网 定位到 Autonavi Chart 高德地图菜单，显示代码。

### What is expected

暂无

### What is actually happening

暂无

### What is your project name

my-project

### Any additional comments (optional)

个人项目使用组件时

**Comment by kagol** [comment]
@henryTu9972 PR #1691 已修复，即将部署~
