### ISSUE TITLE
🐛 [Bug]: PopEditor hides the content when it is closed

### ISSUE THREAD

**Issue by Zz-ZzzZ** [opentiny/tiny-vue#173]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://opentiny.design/tiny-vue/zh-CN/os-theme/components/pop-editor

### Step to reproduce

![1682213872272](https://user-images.githubusercontent.com/48228016/233814717-f73c4c9d-11f0-41a8-a2a7-6f7401481f01.jpg)
关闭时有一个动画效果，而在弹出框完全关闭前会先隐藏弹出框的内容，正常应该是一起消失

**Comment by zzcr** [comment]
您好，感谢你的意见，我们内部评估下~~

**Comment by yoyo201626** [comment]
在3.12.0版本中不能复现，拟关闭问题
