### ISSUE TITLE
🐛 [Bug]: The accuracy of Slider sliding is incorrect.

### ISSUE THREAD

**Issue by Zz-ZzzZ** [opentiny/tiny-vue#174]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://opentiny.design/tiny-vue/zh-CN/os-theme/components/slider

### Step to reproduce

![1682213872303](https://user-images.githubusercontent.com/48228016/233814767-7251f56b-9049-440c-b085-a9b7e2d4f81d.jpg)
这里应该是js精度问题导致的

**Comment by awspi** [comment]
看了下官网确实存在这个问题,但是仓库的文档启动起来并没有成功复现
看slider的源码, 显示的`tipValue`由`activeValue`决定
在函数`setActiveButtonValue()`中调用`calcCurrentValue()`来设置 `activeValue`

在`calcCurrentValue()`代码如下
```ts
const calcCurrentValue = ({ currentValue, props, state }) => {
  if (currentValue <= props.min) {
    // 最小为min
    currentValue = props.min
  } else if (currentValue >= props.max) {
    // 最大为max
    currentValue = props.max
  } else {
    // 如果在范围内，根据step来决定当前值
    const step = props.step > 0 ? props.step : 1
    // step的精度
    let stepPrecision = 0
    // 如果step为小数，获取step的精度
    if (step - parseInt(step) > 0) {
      stepPrecision = step.toString().split('.')[1].length
    }
    const stepValue = (currentValue - props.min) % step

    if (stepValue) {
      currentValue -= stepValue
      // stepValue大于step的一半时，向上取整，否则向下取整
      currentValue += stepValue * 2 > step ? Number(step) : 0
      // 保持精度
      if (stepPrecision) {
        // step为小数时，currentValue也保持相同的精度
        currentValue = currentValue.toFixed(stepPrecision)
      }
    }
    if (state.isDouble) {
      if (state.activeIndex === 0 && currentValue >= state.rightBtnValue) {
        currentValue = state.rightBtnValue
      } else if (state.activeIndex === 1 && currentValue <= state.leftBtnValue) {
        currentValue = state.leftBtnValue
      }
    }
  }

  return currentValue
}
```

或许可以用`currentValue = currentValue.toFixed(stepPrecision)`来兜底,当`stepPrecision===0`时`toFixed(0)`也没问题

**Comment by shenjunjian** [comment]
首先感谢@awspi 来修复问题。 
这个问题在上月已经修复，只是文档网站未更新，于是给您造成疑惑：为什么代码正确，但显示效果不对呢？

于是你去掉if, “可以**用**currentValue = currentValue.toFixed(stepPrecision)**来兜底**,当stepPrecision===0时toFixed(0)也没问题” 

其实这引来另一个不好的地方，假如step是整数，但起始值为小数时，会被截断， 比如下面这样使用：
` <tiny-slider v-model="value" :min="0.7" :step="1" :max="100.7"></tiny-slider>`

所以这个if，仍然不能去掉的。

整体背景：slider组件设计时，是不建议用户使用小数的，文档上有详细的说明。但总是有用户想用小数的步长。
精度判断只是避免用户使用小数步长有明显问题
