### ISSUE TITLE
🐛 [Bug]: The drop-down form components are written in the 3.6.7 version of Modal modal box, and the drop-down box position will be moved up to the upper left corner of the page.

### ISSUE THREAD

**Issue by xiaobaiming-git** [opentiny/tiny-vue#175]
### Version

 "@opentiny/vue": "^3.6.7",

### Vue Version

"vue": "^3.2.47",

### Link to minimal reproduction

3.6.7版本的Modal模态框内写入有下拉的表单组件，下拉框位置均会上移至页面左上角

### Step to reproduce

3.6.7版本的Modal模态框内写入有下拉的表单组件，下拉框位置均会上移至页面左上角
![image](https://user-images.githubusercontent.com/83394966/233827217-679df98f-e399-4898-96ff-25cf988257fb.png)
![image](https://user-images.githubusercontent.com/83394966/233827514-a2f39d00-ef96-4913-a5b4-dbbd058cd85e.png)

**Comment by Huangyilin19** [comment]
抱歉, 我这边复现不了该问题, 能不能提供下问题的demo呢 @xiaobaiming-git 
![image](https://user-images.githubusercontent.com/48042709/236724500-1be5d8fa-5081-4652-8996-819a85f8f94a.png)

**Comment by xiaobaiming-git** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您发送的邮件我已收到，并会尽快回复，谢谢！

**Comment by xiaobaiming-git** [comment]
好的，我这边给你附件了一个demo，您输入npm i把依赖下载然后npm run dev 即可启动，然后除了下拉选择位移，校验的时候校验提示也是移位的，还有弹出编辑弹窗的分页也是，您可以点击一下看看，谢谢，辛苦了












------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "opentiny/tiny-vue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月8日(星期一) 中午11:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [opentiny/tiny-vue] 🐛 [Bug]: 3.6.7版本的Modal模态框内写入有下拉的表单组件，下拉框位置均会上移至页面左上角 (Issue #175)





 
抱歉, 我这边复现不了该问题, 能不能提供下问题的demo呢 @xiaobaiming-git

**Comment by xiaobaiming-git** [comment]
1、好的，我这边给你附件了一个demo，您输入npm i把依赖下载然后npm run dev 即可启动，然后除了下拉选择位移，校验的时候校验提示也是移位的，还有弹出编辑弹窗的分页也是，您可以点击一下看看，谢谢，辛苦了/
2、想起来了，还有一点就是，之后我把弹窗最外层的Modal模态框组件换成DialogBox对话框，效果也还是这样的，也不知道为什么，你可以试试换DialogBox对话框看看是不是也是这样，谢谢，辛苦了辛苦了














------------------ 原始邮件 ------------------
发件人:                                                                                                                        "opentiny/tiny-vue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月8日(星期一) 中午11:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [opentiny/tiny-vue] 🐛 [Bug]: 3.6.7版本的Modal模态框内写入有下拉的表单组件，下拉框位置均会上移至页面左上角 (Issue #175)





 
抱歉, 我这边复现不了该问题, 能不能提供下问题的demo呢 @xiaobaiming-git

**Comment by Huangyilin19** [comment]
没看到邮件附件demo哦,麻烦确认下是否成功上传

**Comment by xiaobaiming-git** [comment]
上次已经发送成功了，在邮件最下面或者最上面













------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "opentiny/tiny-vue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月9日(星期二) 下午4:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [opentiny/tiny-vue] 🐛 [Bug]: 3.6.7版本的Modal模态框内写入有下拉的表单组件，下拉框位置均会上移至页面左上角 (Issue #175)





 
没看到邮件附件demo哦,麻烦确认下是否成功上传

**Comment by xiaobaiming-git** [comment]
***@***.***你的
这个邮箱才可以看到应该





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "opentiny/tiny-vue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月9日(星期二) 下午5:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [opentiny/tiny-vue] 🐛 [Bug]: 3.6.7版本的Modal模态框内写入有下拉的表单组件，下拉框位置均会上移至页面左上角 (Issue #175)





 
我确认了, 确实是没有附件, 只有上面评论的内容.要不你登录邮箱再发一下

**Comment by Huangyilin19** [comment]
看不到你上条信息内容
![image](https://github.com/opentiny/tiny-vue/assets/48042709/c166d738-83c4-4235-a059-968117e247da)

**Comment by xiaobaiming-git** [comment]
***@***.***才可以看到，你看看要不你给我一个你的其他邮箱，或者微信，我再发给你一次。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "opentiny/tiny-vue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月10日(星期三) 上午10:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [opentiny/tiny-vue] 🐛 [Bug]: 3.6.7版本的Modal模态框内写入有下拉的表单组件，下拉框位置均会上移至页面左上角 (Issue #175)





 
看不到你上条信息内容

**Comment by Huangyilin19** [comment]
grandrenaissance@163.com, 麻烦再发下

**Comment by xiaobaiming-git** [comment]
***@***.***&nbsp;邮箱查收一下，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "opentiny/tiny-vue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月10日(星期三) 中午11:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [opentiny/tiny-vue] 🐛 [Bug]: 3.6.7版本的Modal模态框内写入有下拉的表单组件，下拉框位置均会上移至页面左上角 (Issue #175)





 
***@***.***, 麻烦再发下

**Comment by Huangyilin19** [comment]
收到了

**Comment by Huangyilin19** [comment]
问题已修复. 需要自行更新Opentiny/vue到3.9.0版本.
更新后如果遇到icon无法导入的情况, 要在package.json加上 "@opentiny/vue-icon": "~3.9.0", 然后安装一下.

**Comment by xiaobaiming-git** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您发送的邮件我已收到，并会尽快回复，谢谢！

**Comment by Huangyilin19** [comment]
问题已解决，麻烦更新到最新版本3.11.0
![image](https://github.com/opentiny/tiny-vue/assets/48042709/c17fde03-8e09-4fbe-9762-69cc4f743e9f)

**Comment by xiaobaiming-git** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您发送的邮件我已收到，并会尽快回复，谢谢！
