### ISSUE TITLE
🐛 [Bug]: Grid cannot be found on the official website.

### ISSUE THREAD

**Issue by mengqiuleo** [opentiny/tiny-vue#176]
### Version

1

### Vue Version

3

### Link to minimal reproduction

![Snipaste_2023-04-24_12-01-57](https://user-images.githubusercontent.com/85825776/233897499-6e2a7cb1-573e-47fb-aff3-59d5bf9cbc88.jpg)

### Step to reproduce

官网无法通过搜索框查找到 grid，需要手动查找，能否通过搜索定位到表格组件

**Comment by heygsc** [comment]
个人感觉这个不算bug吧。搜索只是对应的标题，表格部分的标题确实没有“grid”，只是文中提到的。

**Comment by kagol** [comment]
@mengqiuleo 左侧导航的组织方式确实需要优化。

**Comment by zzcr** [comment]
目前已可以搜索到grid组件
