### ISSUE TITLE
🐛 [Bug]: PopEditor pop-up editors support exceptions for v-model instructions

### ISSUE THREAD

**Issue by ljy423897608** [opentiny/tiny-vue#177]
### Version

3.6.1

### Vue Version

3.2.13

### Link to minimal reproduction

// 父组件
<f7-select v-model="value" :option="option" />

// f7-select组件
<template>
  <div>
    <popeditor
      width="800"
      :title="option.title"
      size="small"
      trigger="row"
      show-pager
      :multi="option.selectMode === 'radio' ? false : true"
      :icon="IconPlus()"
      :disabled="option.disabled"
      :grid-op="gridOp"
      :pager-op="gridOp.pagerOp"
      :text-field="option.valueName"
      text-split=","
      :value-field="option.valueID"
      value-split=","
      :conditions="option.conditions"
      :remote-search="remoteSearch"
      @change="changeFunc"
      @close="close" />
  </div>
</template>

### Step to reproduce

运行代码。在弹出框中选中数据，点击确定按钮

### What is expected

把这个组件封装下再调用，即v-model的值由封装的组件的父组件传入，仍可以正常显示

### What is actually happening

目前无法正常显示

**Comment by ljy423897608** [comment]
发现是因为在自定义的组件中，PopEditor外层有个div，导致显示异常

**Comment by yuanningning** [comment]
你好，请问这个问题解决了么？是否可以提供一个示例

**Comment by yuanningning** [comment]
> 发现是因为在自定义的组件中，PopEditor外层有个div，导致显示异常

你好，请问这个问题解决了么？是否可以提供一个示例
