### ISSUE TITLE
🐛 [Bug]: 

### ISSUE THREAD

**Issue by iYathin** [opentiny/tiny-vue#1776]
### Version

3.11.1

### Vue Version

3.3.7

### Link to minimal reproduction

```
 <TinyGridColumn field="action" title="操作" width="90">
    <template #default="data">
      {{ data.row }}
      {{ tableData[data.rowIndex].edit }}
   </template>
</TinyGridColumn>

const tableData = reactive<LicenceItem[]>([])

...

const { data: licenceList } = await opLicenceList({ productId: id })
tableData.splice(0, tableData.length, ...data)
```

### Step to reproduce

tableData 为 表格源数据，在编辑操作之后，重新请求数据覆盖 tableData 后，导致 row.edit 和 tableData[rowIndex].edit 状态不一致，后续通过 row.edit 判断错误

### What is your project name

Yukisoft

**Comment by kagol** [comment]
duplicate #1775
