### ISSUE TITLE
🐛 [Bug]: [TinyVue] select component. When optimization is enabled, searchable is enabled. Search is invalid. If options content is replaced at this time, optimization is invalid, and an error will be reported when scrolling.

### ISSUE THREAD

**Issue by qing-feng-a** [opentiny/tiny-vue#178]
### Version

2.5.0

### Vue Version

2.6.14

### Link to minimal reproduction

【TinyVue】select组件，开启optimization后开启searchable，搜索无效，如果此时替换options内容，optimization失效，此时滚动则报错

### Step to reproduce

【TinyVue】select组件，开启optimization后开启searchable，搜索无效，如果此时替换options内容，optimization失效，此时滚动则报错

**Comment by MomoPoppy** [comment]
目前，使用 optimization 属性不支持搜索。使用 optimization 必须使用 options 属性Currently, search is not supported using the optimization attribute. The options attribute must be used to use optimization.
