### ISSUE TITLE
🐛 [Bug]: The tree table cannot delete new rows, and adding child nodes is not supported.

### ISSUE THREAD

**Issue by mengqiuleo** [opentiny/tiny-vue#179]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

树表无法删除新增行，新增不支持添加子节点
相关链接: [gird-tree-grid](https://opentiny.design/tiny-vue/zh-CN/os-theme/components/grid-tree-grid#tree-table-tree-grid-insert-delete-update)

### Step to reproduce

树表无法删除新增行，新增不支持添加子节点

**Comment by GaoNeng-wWw** [comment]
我来修复这个问题

**Comment by kagol** [comment]
Fixed by @GaoNeng-wWw on #224
