### ISSUE TITLE
✨ [Feature]:  一个select 组件500kb ，是本身体积就这么大？还是要配置什么，太不合理了把

### ISSUE THREAD

**Issue by qian-chen97** [opentiny/tiny-vue#1795]
### What problem does this feature solve

![image](https://github.com/user-attachments/assets/d053154a-2d5d-4036-a029-12acc5a37a85)

### What does the proposed API look like

-

### What is your project name

1

**Comment by kagol** [comment]
@ArtisanQ 由于 select 组件包含下拉树、下拉表格功能，耦合了 tree / grid 两个重型组件，近期我们正在做重构和解耦，欢迎一起讨论~ #1633

**Comment by zzcr** [comment]
目前已提供base-select，打包体积会变小很多
