### ISSUE TITLE
🐛 [Bug]: Packaging failed when used in vitepress

### ISSUE THREAD

**Issue by xingyan95** [opentiny/tiny-vue#180]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://opentiny.design/tiny-vue/zh-CN/os-theme/docs/envpreparation

### Step to reproduce

在vitepress里面使用时，开发环境访问正常，但是打包时会失败，提示window is not defined。组件在使用window或者document的时候需要处理下是否是浏览器环境。
```
build error:
  ReferenceError: window is not defined
undefined
```

### What is expected

在vitepress的ssr环境能正常打包。

**Comment by kagol** [comment]
需要提供SSR支持

**Comment by zzcr** [comment]
v3.9.0版本已支持vitepress打包
