### ISSUE TITLE
✨ [Feature]: I hope a sample of combined API can be added to the official website.

### ISSUE THREAD

**Issue by fenghlin666** [opentiny/tiny-vue#181]
### What problem does this feature solve

希望官网能加上组合式 API的样例

### What does the proposed API look like

类似Vue文档那样，可以切换选项式和组合式API的偏好，当前官网只有选项式API的风格在。
[Vue文档](https://cn.vuejs.org/guide/introduction.html)

**Comment by kagol** [comment]
我们有计划支持

**Comment by kagol** [comment]
Finished by @zzcr
