### ISSUE TITLE
🐛 [Bug]: tiny-tree-menu 单行数据设置disabled后依然可以选中

### ISSUE THREAD

**Issue by cjy-bit** [opentiny/tiny-vue#1847]
### Version

3.17.2

### Vue Version

3.17.2

### Link to minimal reproduction

https://www.opentiny.design/vue-playground?cmpId=tree-menu&fileName=props.vue&apiMode=Options&mode=pc&theme=smb

### Step to reproduce

  { id: 202, name: '后端适配器',disabled:true },
1. 设置禁用后，依然可以选中
2. <tiny-tree-menu :data="treeData" :props="mapField" only-check-children></tiny-tree-menu> 设置only-check-children后就不存在这个问题

### What is your project name

demo

**Comment by wuyiping0628** [comment]
https://github.com/opentiny/tiny-vue/pull/1736  已经解决了
