### ISSUE TITLE
🐛 [Bug]:  Failed to resolve entry for package "@opentiny/vue". and Failed to resolve import "./component.js" from "....\packages\theme\src\theme\smb-theme\index.js". Does the file exist?

### ISSUE THREAD

**Issue by Snnerney** [opentiny/tiny-vue#1871]
### Version

 @opentiny/vue@3.17.0

### Vue Version

vue@3.4.37

### Link to minimal reproduction

 [ERROR] Failed to resolve entry for package "@opentiny/vue". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]

    src/main.ts:5:24:
      5 │ import { Loading } from '@opentiny/vue'

 [vite] Internal server error: Failed to resolve import "./component.js" from "..\..\packages\theme\src\theme\smb-theme\index.js". Does the file exist?
  Plugin: vite:import-analysis
  File: D:/download-browser/tiny-vue-dev1/tiny-vue-dev/packages/theme/src/theme/smb-theme/index.js:454:16
  452|  }
  453|
  454|  export * from './component.js'
     |                 ^
  455|
![屏幕截图 2024-08-09 131434](https://github.com/user-attachments/assets/38b453cf-57c0-4bed-8281-52227aa9a2e6)

### Step to reproduce

从github上拉取dev分支代码进行pnpm i拉取依赖，使用pnpm dev运行出现以上错误

### What is actually happening

 [ERROR] Failed to resolve entry for package "@opentiny/vue". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]

    src/main.ts:5:24:
      5 │ import { Loading } from '@opentiny/vue'

 [vite] Internal server error: Failed to resolve import "./component.js" from "..\..\packages\theme\src\theme\smb-theme\index.js". Does the file exist?
  Plugin: vite:import-analysis
  File: D:/download-browser/tiny-vue-dev1/tiny-vue-dev/packages/theme/src/theme/smb-theme/index.js:454:16
  452|  }
  453|
  454|  export * from './component.js'
     |                 ^
  455|
![屏幕截图 2024-08-09 131434](https://github.com/user-attachments/assets/38b453cf-57c0-4bed-8281-52227aa9a2e6)

### What is your project name

Tinyvue

**Comment by kagol** [comment]
@Noospic `pnpm dev` 命令实际执行了三个命令：
```
"dev": "pnpm build:entry && gulp themeConcat -w & pnpm -C examples/vue3 dev",
```

看你的报错应该是第二个生成主题文件的命令执行报错了，可以尝试单独执行该命令：
```
gulp themeConcat -w
```
