### ISSUE TITLE
不理解button组件这个css为什么这样写..建议取消..

### ISSUE THREAD

**Issue by zhezzma** [opentiny/tiny-vue#1883]
```
.tiny-button+.tiny-button {
  margin-left: 8px;
}
```

大概的意思是两个button如果相邻,则margin-left: 8px;
真的有必要吗?这种默认的形式应该用户来控制...
写组件的时候,要恪守单一原则..只处理自己的事情..
写button组件,只要负责button本身的样式就可以了呀!

比如这个如果我在两个button的外层使用flex,flex-col..竖排显示按钮,然后就会造成第二个按钮,有偏移

![image](https://github.com/user-attachments/assets/d6b53e22-d662-4359-983e-3bffb442780c)

**Comment by shenjunjian** [comment]
.tiny-button+.tiny-button是一个常用技巧，　比如弹窗中的确认了取消按钮，　会自动添加了一个边距
防止２个按钮紧挨在一起。　　

组件库里，到底应该不应该有这种样式，　确实是需要讨论的一个点。　像你的使用场景，　就会带来问题。

**Comment by zhezzma** [comment]
> .tiny-button+.tiny-button是一个常用技巧，　比如弹窗中的确认了取消按钮，　会自动添加了一个边距 防止２个按钮紧挨在一起。　　
> 
> 组件库里，到底应该不应该有这种样式，　确实是需要讨论的一个点。　像你的使用场景，　就会带来问题。

如果是弹窗的话..那就是弹窗下.dialogue  .tiny-button+.tiny-button  而不是全局使用

**Comment by zzxming** [comment]
button 作为行级块元素默认单行排列，所以这样处理是没有问题的，你这种纵向排列的情况才是需要特殊处理的

**Comment by lisonge** [comment]
关键在于，没有提供一个可供用户关闭的选项

很多产品 ui 设计都是自己内部定义的 gap

每次遇到这个都很烦

---

框架要改可以参考
```
.tiny-button+.tiny-button:not(no-gap) { margin-left: 8px; }
```

用户手动改，直接在两个 button 之间插入一个
```
<div v-show='0'/>
```
 破坏相近兄弟关系，这样 CSS 匹配不上就不生效了

**Comment by zhezzma** [comment]
你这是写了一个bug，然后让用户在修改你这个bug？
所以你为什么要这样写呢？
单一原则。每个组件只负责自己的事情不就好了。
那我再问一个实际的问题，需要你这样写的组件到底有几个？？所谓的通用不过是想象中的东西。
你这是写组件写最基本的东西，要避免的就是不要污染，产生莫名其妙的东西。

**Comment by lisonge** [comment]
> 你这是写了一个bug，然后让用户在修改你这个bug？

虽然但是，element-plus 照样有这个 <https://github.com/element-plus/element-plus/blob/0b87b9f033af6d1e7d2f69f04181fdc89648d074/packages/theme-chalk/src/button.scss#L71> 而且不可修改

这玩意就是一套抄一套

**Comment by zzcr** [comment]
现阶段也无法去掉这个样式，去掉了会对其他用户造成影响，倒是可以使用config-provider的design配置去修改全局配置，后面我们加个示例说明下吧
