### ISSUE TITLE
[suggestion] I hope to improve the api document of Grid components to explain the structure of the data transmitted from the scope slot more clearly.

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-vue#193]
以下链接中的GridColumn的api：
[https://opentiny.design/tiny-vue/zh-CN/os-theme/components/grid#api](https://opentiny.design/tiny-vue/zh-CN/os-theme/components/grid#api)

![image](https://user-images.githubusercontent.com/9566362/236450655-77d7bf44-8f8d-48dc-b521-37ac33933530.png)

**Comment by vaebe** [comment]
@kagol 这个网址貌似无法访问

**Comment by kagol** [comment]
> @kagol 这个网址貌似无法访问

已更正，谢谢提醒🤝

**Comment by zzcr** [comment]
你好，7月份迭代，我们已安排完善下表格作用域插槽的文档说明
