### ISSUE TITLE
🐛 [Bug]: The style is incorrect when the button component does not pass a string

### ISSUE THREAD

**Issue by qinwencheng** [opentiny/tiny-vue#194]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

```vue
<template>
      <tiny-button>默认按钮</tiny-button>
      <tiny-button type="primary" native-type="submit"></tiny-button>
</template>

<script lang="jsx">
import { Button } from '@opentiny/vue'

export default {
  components: {
    TinyButton: Button
  },
  data() {
    return {
    }
  }
}
</script>

```

### Step to reproduce

参考element-plus 和 tiny 的对比：
[ep链接](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXG48ZWwtYnV0dG9uPnRlc3QgZW1wdHk8L2VsLWJ1dHRvbj5cbjxlbC1idXR0b24+PC9lbC1idXR0b24+XG48ZWwtYnV0dG9uPnRlc3QgZW1wdHk8L2VsLWJ1dHRvbj5cblxuXG48L3RlbXBsYXRlPlxuXG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

对比：
tiny
![image](https://user-images.githubusercontent.com/24841685/236494456-22fa1096-ecfa-4361-b2d0-16ca764d9976.png)
ep
![image](https://user-images.githubusercontent.com/24841685/236494599-b6cdc789-35bc-449e-adb1-589dd9dae781.png)

### What is expected

期望按钮能正常对齐

### What is actually happening

按钮实际上没对齐（不传入内容的情况下）

**Comment by kagol** [comment]
Fixed by @qinwencheng on #203
