### ISSUE TITLE
🐛 [Bug]: Grid表格组件的Enter功能无效

### ISSUE THREAD

**Issue by justhhl** [opentiny/tiny-vue#1968]
### Version

3.17.10

### Vue Version

3.17.10

### Link to minimal reproduction

https://www.opentiny.design/tiny-vue/zh-CN/aurora-theme/components/grid-mouse-keyboard

### Step to reproduce

Grid表格组件，选中列进行编辑，再按键Enter完成编辑。

### What is expected

取消编辑并移动到当前活动单元格下面的单元格

### What is actually happening

焦点仍然在编辑的表格中，没有取消编辑，没有移动到当前活动单元格下面的单元格

### What is your project name

ERP

**Comment by kagol** [comment]
Duplicate #1969
