### ISSUE TITLE
🐛 [Bug]: Tiny ui reported an error after introducing TinyFileUpload. Do we need to install any installation package? if you need to install, please provide the installation command line.

### ISSUE THREAD

**Issue by thestar077** [opentiny/tiny-vue#197]
### Version

3.6.7

### Vue Version

3.2.47

### Link to minimal reproduction

报错信息：Uncaught (in promise) Error: [TINY Error][FileUpload] This component depends on @opentiny/vue-service
前端组件：
<tiny-file-upload size="small" :data="requestData" ref="upload" :action="action">
          <template #trigger>
            <tiny-button type="primary">点击上传</tiny-button>
          </template>
        </tiny-file-upload>

### Step to reproduce

报错信息：Uncaught (in promise) Error: [TINY Error][FileUpload] This component depends on @opentiny/vue-service
前端组件：
<tiny-file-upload size="small" :data="requestData" ref="upload" :action="action">
          <template #trigger>
            <tiny-button type="primary">点击上传</tiny-button>
          </template>
        </tiny-file-upload>

**Comment by chenxi-20** [comment]
给action属性添加一个值，比如action=‘/’即可
