### ISSUE TITLE
🐛 [Bug]: TinyCLI initialization vue-pro project copywriting error

### ISSUE THREAD

**Issue by zaureus** [opentiny/tiny-vue#202]
### Version

@opentiny/vue@3.6.8

### Vue Version

@vue/cli 5.0.8

### Link to minimal reproduction

![微信图片_20230509152529](https://user-images.githubusercontent.com/18185052/237024676-d13006c1-3f10-47ac-bfc5-9ecec259d5de.png)

### Step to reproduce

tiny init pro
? 请输入项目名称： tiny-pro
? 请输入项目描述： 基于TinyPro套件创建的中后台系统
? 请选择您希望使用的技术栈： vue

**Comment by kagol** [comment]
已修复，重新执行 `tiny init pro` 命令即可，非常感谢你的反馈！
