### ISSUE TITLE
[Bug]: DialogBox 对话框打开跟关闭的时候建议添加淡出淡入

### ISSUE THREAD

**Issue by YuPeng6688** [opentiny/tiny-vue#2045]
### What problem does this feature solve

用户使用体验、体感会更好，不会让弹框的突然打开跟关闭显得很生硬

### What does the proposed API look like

在样式中添加淡入淡出的样式即可

### What is your project name

数字化管理系统

**Comment by GaoNeng-wWw** [comment]
i will fix it

**Comment by GaoNeng-wWw** [comment]
#2324 fixed the issue
