### ISSUE TITLE
✨ [Feature]: Components of tiny-vue may need to add unit tests

### ISSUE THREAD

**Issue by mengqiuleo** [opentiny/tiny-vue#206]
### What problem does this feature solve

增加单元测试，有利提高代码质量，简化代码重构。

建议优先完善高频组件的 TypeScript 类型声明。

[TinyVue 高频组件](https://github.com/opentiny/tiny-vue/wiki/TinyVue-%E9%AB%98%E9%A2%91%E7%BB%84%E4%BB%B6%E5%88%97%E8%A1%A8)

### What does the proposed API look like

增加单元测试。

**Comment by kagol** [comment]
需要的，我们正在规划这块，也欢迎一起参与进来～

**Comment by kagol** [comment]
可以在`packages/vue`目录下搜索`test.todo`关键字，找到待补充的单元测试。
执行全量单元测试：`pnpm test:unit3`
执行单个组件的单元测试：`pnpm test:unit3 button`

**Comment by kagol** [comment]
The unit testing of components needs to be continuously improved.

**Comment by mengqiuleo** [comment]
单测是否可以参考这个 wiki: [TinyVue 高频组件列表](https://github.com/opentiny/tiny-vue/wiki/TinyVue-%E9%AB%98%E9%A2%91%E7%BB%84%E4%BB%B6%E5%88%97%E8%A1%A8)

**Comment by kagol** [comment]
除了单元测试，也可以补充组件的 e2e 测试用例，基于 Playwright，可以模拟用户实际的操作。目前 PR 合入门禁中已经集成了 e2e 测试，当前组件的 e2e 测试必须通过才能合入。

~e2e 测试执行时会打开浏览器（默认值 3101 端口，如果需要修改端口，需要在 examples/docs/vue3/playwright.config.js 中进行修改），所以需要执行 pnpm site 本地启动项目才行。~

更正：pnpm test:e2e 命令会自动执行 pnpm site 启动本地项目

执行全量 e2e 测试用例：
```
pnpm test:e2e3
```


执行单个组件的 e2e 测试用例
```
pnpm test:e2e3 ./date-picker
```
