### ISSUE TITLE
🐛 [Bug]: Click the button in the loading component modifier demo, and the api table style changes

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-vue#208]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

地址：https://opentiny.design/tiny-vue/zh-CN/os-theme/components/loading#body

<img width="1376" alt="image" src="https://github.com/opentiny/tiny-vue/assets/9566362/c5fa4c43-f40f-4512-8d70-3cd238c9eeb4">

### Step to reproduce

复现地址：https://opentiny.design/tiny-vue/zh-CN/os-theme/components/loading#body

**Comment by qinwencheng** [comment]
这个BUG是由于不同组件混用导致的。解决方法是把文档的表格组件统一为tiny自己的表格组件 (呃~)。
------
**详细说明如下：**
当全局loading激活时，body里会添加一个 `.tiny-loading__parent-relative` 类。这个类会影响到表格的td元素，使其出现如下内容：（如图）

![image](https://github.com/opentiny/tiny-vue/assets/24841685/f7d58b2e-a058-4951-9167-2a8a61dfc46f)

原因是因为 `.tiny-loading__parent-relative` 这样以`tiny-`开头的类的出现，导致了 `[class*=tiny-] td` 的出现，它的优先级（0011）和 naive UI 的 `.n-table td` 选择器（0011）相同，所以后者被覆盖了。而 `[class*=tiny-] td` 选择器设置了 `padding: 0` ，最终导致了td元素的样式错乱。
如果使用tiny自己的表格组件，它的td选择器是 `.tiny-grid.tiny-grid-editable .tiny-grid-body__column` ，优先级是0030，高于 `[class*=tiny-] td` ，所以永远不会它被覆盖，也就不会出现BUG。这也是dev版的文档没有出现这个问题的原因。（如图）

![image](https://github.com/opentiny/tiny-vue/assets/24841685/b3fa7ae2-0cce-4447-9347-b1524f47cb09)
