### ISSUE TITLE
✨ [Feature]: [Tree] Does the Tree component need a connector?

### ISSUE THREAD

**Issue by mengqiuleo** [opentiny/tiny-vue#212]
### What problem does this feature solve

连接线：节点之间带连接线的树，常用于文件目录结构展示。
<img width="227" alt="Snipaste_2023-05-12_16-22-26" src="https://github.com/opentiny/tiny-vue/assets/85825776/0de9e342-5de1-48bf-b757-49ad0c8d2316">

Tree 组件是否需要连接线，**如果需要，我可以提一个 pr**

### What does the proposed API look like

新增 showLine 属性，用户使用 showLine 属性开启连接线。

**Comment by kagol** [comment]
@mengqiuleo 需要的，欢迎提交PR～

**Comment by kagol** [comment]
Finished by @Huangyilin19
