### ISSUE TITLE
🐛 [Bug]: The code style of the sample code in the document should be unified.

### ISSUE THREAD

**Issue by gausszhou** [opentiny/tiny-vue#213]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://opentiny.design/tiny-vue/zh-CN/os-theme/docs/import-components

### Step to reproduce

https://opentiny.design/tiny-vue/zh-CN/os-theme/docs/installation

### What is expected

应当统一代码风格为 `{ ...x }` 而不是使用 `Object.assign({}, x)`
```js
define: {
  'process.env': { ...process.env }
}
```

### What is actually happening
https://opentiny.design/tiny-vue/zh-CN/os-theme/docs/import-components
```
define: {
  'process.env': Object.assign({}, process.env)
}
```

**Comment by kagol** [comment]
@gausszhou 是的，应该统一下
