### ISSUE TITLE
🐛 [Bug]: tiny-tooltip内部嵌套tiny-form-item时，item下的元素class错误

### ISSUE THREAD

**Issue by pppploi8** [opentiny/tiny-vue#2138]
### Version

3.18.0

### Vue Version

3.4.38

### Link to minimal reproduction

https://opentiny.design/vue-playground?mode=pc&theme=smb#3.18|eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgbGFuZz1cInRzeFwiPlxuLy8g5byV5YWlIEBvcGVudGlueS92dWUg57uE5Lu2XG5pbXBvcnQgeyBCdXR0b24sIExpbmsgfSBmcm9tICdAb3BlbnRpbnkvdnVlJ1xuXG5leHBvcnQgZGVmYXVsdCB7XG4gIGNvbXBvbmVudHM6IHtcbiAgICBUaW55QnV0dG9uOiBCdXR0b24sXG4gICAgVGlueUxpbms6IExpbmtcbiAgfSxcbiAgZGF0YSgpIHtcbiAgICByZXR1cm4ge1xuICAgICAgbXNnOiAnaGVsbG8gd29ybGQhJ1xuICAgIH1cbiAgfVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPFRpbnlCdXR0b24+56Gu5a6aPC9UaW55QnV0dG9uPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGRpdiBjbGFzcz1cInRpbnl2dWVcIj5cbiAgICA8ZGl2IGNsYXNzPVwidGlueXZ1ZS1wYWdlXCI+XG4gICAgICB0aW55dnVlXG4gICAgICA8dGlueS1saW5rIHR5cGU9XCJzdWNjZXNzXCIgaHJlZj0naHR0cHM6Ly9naXRodWIuY29tL29wZW50aW55L3RpbnktdnVlJz5cbiAgICAgICAgdGlueXZ1ZVxuICAgICAgPC90aW55LWxpbms+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlIGxhbmc9XCJsZXNzXCIgc2NvcGVkPlxuICBoMXtcbiAgICBjb2xvcjojNWU3Y2UwO1xuICB9XG4gIC50aW55dnVle1xuICAgIGZvbnQtc2l6ZTogMTh4cDtcbiAgICAmLXBhZ2V7XG4gICAgICBjb2xvcjojNWU3Y2UwO1xuICAgIH1cbiAgfVxuPC9zdHlsZT5cbiIsInNyYy8iOiJ7XCJpbXBvcnRzXCI6e1widnVlXCI6XCJodHRwczovL3JlZ2lzdHJ5Lm5wbW1pcnJvci5jb20vdnVlLzMuNC4yNy9maWxlcy9kaXN0L3Z1ZS5ydW50aW1lLmVzbS1icm93c2VyLmpzXCIsXCJlY2hhcnRzXCI6XCJodHRwczovL3JlZ2lzdHJ5Lm5wbW1pcnJvci5jb20vZWNoYXJ0cy81LjQuMS9maWxlcy9kaXN0L2VjaGFydHMuZXNtLmpzXCIsXCJAdnVlL2NvbXBpbGVyLXNmY1wiOlwiaHR0cHM6Ly9yZWdpc3RyeS5ucG1taXJyb3IuY29tL0B2dWUvY29tcGlsZXItc2ZjLzMuNC4yNy9maWxlcy9kaXN0L2NvbXBpbGVyLXNmYy5lc20tYnJvd3Nlci5qc1wiLFwiQG9wZW50aW55L3Z1ZVwiOlwiaHR0cHM6Ly9yZWdpc3RyeS5ucG1taXJyb3IuY29tL0BvcGVudGlueS92dWUtcnVudGltZS8zLjE4L2ZpbGVzL2Rpc3QzL3RpbnktdnVlLXBjLm1qc1wiLFwiQG9wZW50aW55L3Z1ZS1pY29uXCI6XCJodHRwczovL3JlZ2lzdHJ5Lm5wbW1pcnJvci5jb20vQG9wZW50aW55L3Z1ZS1ydW50aW1lLzMuMTgvZmlsZXMvZGlzdDMvdGlueS12dWUtaWNvbi5tanNcIixcIkBvcGVudGlueS92dWUtbG9jYWxlXCI6XCJodHRwczovL3JlZ2lzdHJ5Lm5wbW1pcnJvci5jb20vQG9wZW50aW55L3Z1ZS1ydW50aW1lLzMuMTgvZmlsZXMvZGlzdDMvdGlueS12dWUtbG9jYWxlLm1qc1wiLFwiQG9wZW50aW55L3Z1ZS1jb21tb25cIjpcImh0dHBzOi8vcmVnaXN0cnkubnBtbWlycm9yLmNvbS9Ab3BlbnRpbnkvdnVlLXJ1bnRpbWUvMy4xOC9maWxlcy9kaXN0My90aW55LXZ1ZS1jb21tb24ubWpzXCIsXCJAb3BlbnRpbnkvdnVlLWRpcmVjdGl2ZVwiOlwiaHR0cHM6Ly9yZWdpc3RyeS5ucG1taXJyb3IuY29tL0BvcGVudGlueS92dWUtcnVudGltZS8zLjE4L2ZpbGVzL2Rpc3QzL3RpbnktdnVlLWRpcmVjdGl2ZS5tanNcIixcIkBvcGVudGlueS92dWUtdGhlbWUvXCI6XCJodHRwczovL3JlZ2lzdHJ5Lm5wbW1pcnJvci5jb20vQG9wZW50aW55L3Z1ZS10aGVtZS8zLjE4L2ZpbGVzL1wiLFwiQG9wZW50aW55L3Z1ZS10aGVtZS1tb2JpbGUvXCI6XCJodHRwczovL3JlZ2lzdHJ5Lm5wbW1pcnJvci5jb20vQG9wZW50aW55L3Z1ZS10aGVtZS1tb2JpbGUvMy4xOC9maWxlcy9cIixcIkBvcGVudGlueS92dWUtcmVuZGVybGVzcy9cIjpcImh0dHBzOi8vcmVnaXN0cnkubnBtbWlycm9yLmNvbS9Ab3BlbnRpbnkvdnVlLXJlbmRlcmxlc3MvMy4xOC9maWxlcy9cIixcInNvcnRhYmxlanNcIjpcImh0dHBzOi8vcmVnaXN0cnkubnBtbWlycm9yLmNvbS9zb3J0YWJsZWpzLzEuMTUuMC9maWxlcy9tb2R1bGFyL3NvcnRhYmxlLmVzbS5qc1wiLFwiQG9wZW50aW55L3Z1ZS1kZXNpZ24tc21iXCI6XCJodHRwczovL3JlZ2lzdHJ5Lm5wbW1pcnJvci5jb20vQG9wZW50aW55L3Z1ZS1kZXNpZ24tc21iLzMuMTgvZmlsZXMvaW5kZXguanNcIn19IiwidHNjb25maWcuanNvbiI6IntcclxuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XHJcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcclxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxyXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxyXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcclxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXHJcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXHJcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWVcclxuICB9LFxyXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcclxuICAgIFwidGFyZ2V0XCI6IDMuM1xyXG4gIH1cclxufVxyXG4iLCJzcmMvYmFzaWMtdXNhZ2UudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiYm94XCI+XG4gICAgPGRpdiBjbGFzcz1cInRvcFwiPlxuICAgICAgPHRpbnktZm9ybT5cbiAgICAgICAgPHRpbnktdG9vbHRpcCBjbGFzcz1cIml0ZW1cIiBlZmZlY3Q9XCJkYXJrXCIgY29udGVudD1cIlRvcCBMZWZ0IOaPkOekuuaWh+Wtl1wiIHBsYWNlbWVudD1cInRvcC1zdGFydFwiPlxuICAgICAgICAgIDx0aW55LWZvcm0taXRlbSBsYWJlbD1cInRlc3RcIj5cbiAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJ0ZXN0XCI+6L+Z5Liq5YWD57Sg55qEY2xhc3PlupTor6XmmK9cInRpbnktdG9vbHRpcCB0ZXN0XCLvvIzlrp7pmYXmmK9cInRpbnktdG9vbHRpcHRlc3RcIu+8jDMuMTfniYjmnKzmraPluLjvvIwzLjE45byA5aeL5Ye6546wYnVnPC9kaXY+XG4gICAgICAgICAgPC90aW55LWZvcm0taXRlbT5cbiAgICAgICAgPC90aW55LXRvb2x0aXA+XG4gICAgICA8L3RpbnktZm9ybT5cbiAgICA8L2Rpdj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJqc3hcIj5cbmltcG9ydCB7IFRvb2x0aXAgYXMgVGlueVRvb2x0aXAsIEZvcm0gYXMgVGlueUZvcm0sIEZvcm1JdGVtIGFzIFRpbnlGb3JtSXRlbSB9IGZyb20gJ0BvcGVudGlueS92dWUnXG48L3NjcmlwdD5cbiIsIiI6IntcImltcG9ydHNcIjp7XCJ2dWVcIjpcImh0dHBzOi8vcmVnaXN0cnkubnBtbWlycm9yLmNvbS92dWUvMy40LjI3L2ZpbGVzL2Rpc3QvdnVlLnJ1bnRpbWUuZXNtLWJyb3dzZXIuanNcIixcImVjaGFydHNcIjpcImh0dHBzOi8vcmVnaXN0cnkubnBtbWlycm9yLmNvbS9lY2hhcnRzLzUuNC4xL2ZpbGVzL2Rpc3QvZWNoYXJ0cy5lc20uanNcIixcIkB2dWUvY29tcGlsZXItc2ZjXCI6XCJodHRwczovL3JlZ2lzdHJ5Lm5wbW1pcnJvci5jb20vQHZ1ZS9jb21waWxlci1zZmMvMy40LjI3L2ZpbGVzL2Rpc3QvY29tcGlsZXItc2ZjLmVzbS1icm93c2VyLmpzXCIsXCJAb3BlbnRpbnkvdnVlXCI6XCJodHRwczovL3JlZ2lzdHJ5Lm5wbW1pcnJvci5jb20vQG9wZW50aW55L3Z1ZS1ydW50aW1lLzMuMTgvZmlsZXMvZGlzdDMvdGlueS12dWUtcGMubWpzXCIsXCJAb3BlbnRpbnkvdnVlLWljb25cIjpcImh0dHBzOi8vcmVnaXN0cnkubnBtbWlycm9yLmNvbS9Ab3BlbnRpbnkvdnVlLXJ1bnRpbWUvMy4xOC9maWxlcy9kaXN0My90aW55LXZ1ZS1pY29uLm1qc1wiLFwiQG9wZW50aW55L3Z1ZS1sb2NhbGVcIjpcImh0dHBzOi8vcmVnaXN0cnkubnBtbWlycm9yLmNvbS9Ab3BlbnRpbnkvdnVlLXJ1bnRpbWUvMy4xOC9maWxlcy9kaXN0My90aW55LXZ1ZS1sb2NhbGUubWpzXCIsXCJAb3BlbnRpbnkvdnVlLWNvbW1vblwiOlwiaHR0cHM6Ly9yZWdpc3RyeS5ucG1taXJyb3IuY29tL0BvcGVudGlueS92dWUtcnVudGltZS8zLjE4L2ZpbGVzL2Rpc3QzL3RpbnktdnVlLWNvbW1vbi5tanNcIixcIkBvcGVudGlueS92dWUtZGlyZWN0aXZlXCI6XCJodHRwczovL3JlZ2lzdHJ5Lm5wbW1pcnJvci5jb20vQG9wZW50aW55L3Z1ZS1ydW50aW1lLzMuMTgvZmlsZXMvZGlzdDMvdGlueS12dWUtZGlyZWN0aXZlLm1qc1wiLFwiQG9wZW50aW55L3Z1ZS10aGVtZS9cIjpcImh0dHBzOi8vcmVnaXN0cnkubnBtbWlycm9yLmNvbS9Ab3BlbnRpbnkvdnVlLXRoZW1lLzMuMTgvZmlsZXMvXCIsXCJAb3BlbnRpbnkvdnVlLXRoZW1lLW1vYmlsZS9cIjpcImh0dHBzOi8vcmVnaXN0cnkubnBtbWlycm9yLmNvbS9Ab3BlbnRpbnkvdnVlLXRoZW1lLW1vYmlsZS8zLjE4L2ZpbGVzL1wiLFwiQG9wZW50aW55L3Z1ZS1yZW5kZXJsZXNzL1wiOlwiaHR0cHM6Ly9yZWdpc3RyeS5ucG1taXJyb3IuY29tL0BvcGVudGlueS92dWUtcmVuZGVybGVzcy8zLjE4L2ZpbGVzL1wiLFwic29ydGFibGVqc1wiOlwiaHR0cHM6Ly9yZWdpc3RyeS5ucG1taXJyb3IuY29tL3NvcnRhYmxlanMvMS4xNS4wL2ZpbGVzL21vZHVsYXIvc29ydGFibGUuZXNtLmpzXCIsXCJAb3BlbnRpbnkvdnVlLWRlc2lnbi1zbWJcIjpcImh0dHBzOi8vcmVnaXN0cnkubnBtbWlycm9yLmNvbS9Ab3BlbnRpbnkvdnVlLWRlc2lnbi1zbWIvMy4xOC9maWxlcy9pbmRleC5qc1wifX0iLCJfbyI6e319

### Step to reproduce

如果在演练场选择3.17版本，审查元素查看class显示正常，如果是3.18版本，class少了一个空格

### What is your project name

1

**Comment by shenjunjian** [comment]
在最新版本中，已经修复过这个问题了， 3.19.0 已经正常了
