### ISSUE TITLE
✨ [Feature]: BulletinBoard 公告牌,需要增加item点击事件

### ISSUE THREAD

**Issue by happy2091366** [opentiny/tiny-vue#2143]
### What problem does this feature solve

BulletinBoard 公告牌,现在靠传入数据的URL或者Route来跳转，这个跳转如需跳转到详情之类的，那么就非常的麻烦，要在后端数据里拼接URL或者Route，即使这样有时候也不能达到需要的效果，所以如果有个item点击事件获取到当前点击行的数据，那就可以不用后端，前端都可方便的处理了，谢谢！另外，NEW图标(新公告前缀)只显示在第一行上面，不能自定义，这个不太符合常理。

### What does the proposed API look like

暂无

### What is your project name

OA

**Comment by wuyiping0628** [comment]
已添加
