### ISSUE TITLE
🐛 [Bug]: 动作菜单不显示更多按钮时后面有个分隔符

### ISSUE THREAD

**Issue by falcon-jin** [opentiny/tiny-vue#2159]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

动作菜单不显示更多按钮时后面有个分隔符
https://opentiny.design/vue-playground?cmpId=action-menu&fileName=max-show-num.vue&apiMode=Composition&mode=pc&theme=aurora

### Step to reproduce

![image](https://github.com/user-attachments/assets/143360e8-5bbb-4ae2-a571-43d0fe37976e)

### What is your project name

demo

**Comment by betavs** [comment]
fixed by #1967
