### ISSUE TITLE
🐛 [Bug]: Transfer 穿梭框的两个bug

### ISSUE THREAD

**Issue by stwflyfox** [opentiny/tiny-vue#2230]
### Version

latest

### Vue Version

vue3

### Link to minimal reproduction

none

### Step to reproduce

1.使用 modelVaule 时穿梭无效
![trans error1](https://github.com/user-attachments/assets/0c2fd3d9-61c4-4658-8414-bb8488b7ac70)
2.启用过滤搜索，选择值为空时显示布局不正确
![trans error2](https://github.com/user-attachments/assets/b5261967-0cba-4cb8-b49e-7eeeb77d0e07)

### What is your project name

TinyVue

**Comment by shenjunjian** [comment]
问题1： 双向绑定值，必须用 v-model ， 只绑定 :modelValue是单身绑定， 数据不更新是合理的。  非问题
问题2:   过滤时误增加了 display:flex， 已经在之前修复过了。
