### ISSUE TITLE
🐛 [Bug]: Slider component, change the incoming props, the style has an error

### ISSUE THREAD

**Issue by awspi** [opentiny/tiny-vue#225]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://codesandbox.io/s/bitter-shadow-h5ep1v?file=/src/App.vue

### Step to reproduce

```vue
<template>
  <div>
    <el-slider v-model="value" :max="max"  @change="change"/>
      value: {{ value }} max: {{ max }} ischangeEventTriggered: {{ischangeEventTriggered}}
      <button @click="maxChange">
        maxChange
      </button>
      <button @click="valChange">
        valChange
      </button>
    </div>


</template>

<script lang="ts" setup>
  import { ref } from 'vue'
  const value = ref(5)
  const max=ref(10)
  const ischangeEventTriggered=ref(false)

  const maxChange=()=>{
    max.value=20
  }
  const valChange=()=>{
    value.value=8
  }
  const change=(val)=>{
    ischangeEventTriggered.value=true
  }


</script>
<style scoped>
</style>

```

### What is actually happening

1.  修改传入的value的值 滑块位置不会立刻更新

![image](https://github.com/opentiny/tiny-vue/assets/66438036/7b40e885-bd8b-4064-b19c-d4a8e0cce026)

2. 修改传入的max/min  tooltip位置对 但是滑块位置不对 

![image](https://github.com/opentiny/tiny-vue/assets/66438036/cc8de523-8ced-4199-8b05-e9d7572e0a0e)

### Any additional comments (optional)

似乎只是style设置的不对,值是对的
其他组件库如`element-plus`是支持动态修改的

**Comment by yoyo201626** [comment]
新版本已经修复
![图片](https://github.com/opentiny/tiny-vue/assets/104079404/b287441d-a330-4593-8fd4-4064ea7f12b0)
https://codesandbox.io/p/sandbox/objective-rain-t8y3jv
