### ISSUE TITLE
🐛 [Bug]: treeSelect动态加载问题

### ISSUE THREAD

**Issue by 545702838** [opentiny/tiny-vue#2287]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://github.com/opentiny/tiny-vue

### Step to reproduce

页面上使用treeSelect组件
![image](https://github.com/user-attachments/assets/424e1732-28c1-4a31-8df9-93d8865a0352)
在组件tree-op中，绑定数值

在ts中定义数值，如果直接定义数值，则可以直接在页面上显示，如下两幅图所示
![image](https://github.com/user-attachments/assets/2abf1420-cb1b-435d-a2ce-1a418a076ea7)
![image](https://github.com/user-attachments/assets/75895cf8-26f9-4afb-8c3b-c5193f68e0f1)
但是如果定义是赋空，在后续onMounted中，给定义的数值赋值，则组件中无数据，无法动态加载
![image](https://github.com/user-attachments/assets/3fe68055-b6c9-4fa8-bacf-a79b5877b69e)
![image](https://github.com/user-attachments/assets/7a74465b-b448-4af5-a137-d885f0cc9b7b)
![image](https://github.com/user-attachments/assets/c152fad6-eb87-495a-82cd-e85ca4b52730)

### What is expected

显示动态加载的数据在下拉框中

### What is actually happening

仅初次定义的数据可以被加载中树形结构中，后续的动态更新的并不能加载进入下拉列表

### What is your project name

Emp

**Comment by kagol** [comment]
Fixed in #2500
