### ISSUE TITLE
✨ [Feature]: 组件渲染时通过添加 class 选择器而不是直接写入行内样式

### ISSUE THREAD

**Issue by smallseapig** [opentiny/tiny-vue#2293]
### What problem does this feature solve

**优化建议：**
- 建议组件渲染时通过`class`选择器，替代行内样式。
- 较常见的需要调整样式的组件：`grid`, `pager`, `form`

**问题根源：**
- 涉及修改样式时去获取元素`DOM`的属性再去修改明显不可能，写`!important`会被直接叉出去
![image](https://github.com/user-attachments/assets/a188898f-6fe2-4508-b2fb-4258cfc5ec19)

### What does the proposed API look like

不涉及

### What is your project name

MOM

**Comment by zzcr** [comment]
这个是label属性配置的宽度，所以需要使用style行内样式
