### ISSUE TITLE
🐛 [Bug]: When the vue@2.7.14 version uses the button component of tiny-vue, the button component does not render, and the browser console reports an error: Cannot read properties of null (reading 'proxy')

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-vue#23]
### Version

2.5.0

### Vue Version

2.7.14

### Link to minimal reproduction

无

### Step to reproduce

复现步骤如下：
- 创建一个 vue cli 项目：`vue create tiny-vue-demo-vue2`（默认创建的vue cli项目，vue版本为`2.7.14`）
- 安装tiny-vue：`npm i @opentiny/vue@2`
- 使用button组件：`<tiny-button>TinyVue</tiny-button>`
- 启动项目：`npm run serve`

启动之后button组件未渲染，浏览器控制台报以下错误：

```
TypeError: Cannot read properties of null (reading 'proxy')
    at tools (vue2.js?3125:195:1)
    at setup (index.js?1a88:111:1)
    at setup$1 (pc.js?5ce6:68:1)
    at mergedSetupFn (vue-composition-api.esm.js?a6f4:2079:1)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:3017:1)
    at initSetup (vue.runtime.esm.js?2b0e:2440:1)
    at initState (vue.runtime.esm.js?2b0e:5365:1)
    at Vue._init (vue.runtime.esm.js?2b0e:5691:1)
    at new VueComponent (vue.runtime.esm.js?2b0e:5826:1)
    at createComponentInstanceForVnode (vue.runtime.esm.js?2b0e:4544:1)
```

**Comment by kagol** [comment]
将vue版本号降到`2.6.10`可解决该问题，但同时会导致alert组件description无法渲染。

如下方式使用：

```html
<tiny-button>TinyVue</tiny-button>
<tiny-alert description="TinyVue"></tiny-alert>
```

alert中的description未渲染：

<img width="572" alt="image" src="https://user-images.githubusercontent.com/9566362/221398839-1fec65a8-ee90-48b8-90a4-24daa18387ed.png">

**Comment by hoasou** [comment]
你可能需要锁定版本到 vue@2.6.14，在 vue@2.6.13 版本中更新了 slot 插槽为函数，可参考 vue 更新日志：https://github.com/vuejs/vue/releases?page=4
slot 插槽修改点：
https://github.com/vuejs/vue/commit/ce457f9f4d48548d5e8763c47d013e23c2b65c12

**Comment by kagol** [comment]
> 你可能需要锁定版本到 vue@2.6.14，在 vue@2.6.13 版本中更新了 slot 插槽为函数，可参考 vue 更新日志：https://github.com/vuejs/vue/releases?page=4
> slot 插槽修改点：
> https://github.com/vuejs/vue/commit/ce457f9f4d48548d5e8763c47d013e23c2b65c12

感谢解惑，我试试看
