### ISSUE TITLE
✨ [Feature]: Grid components use setup ts to write and report errors, but can run, other components do not have this problem.

### ISSUE THREAD

**Issue by jllb** [opentiny/tiny-vue#232]
### What problem does this feature solve

Grid组件用setup ts写回报错，但是可以运行，其他组件就没有这个问题。
![2ce943d79cacaac5f3ee333e0ceff43](https://github.com/opentiny/tiny-vue/assets/16914548/d7d3d37e-5db3-455c-8c0a-4594eadb09b7)

### What does the proposed API look like

Grid组件用setup ts写回报错，但是可以运行，其他组件就没有这个问题。

**Comment by zzcr** [comment]
我们会在6月底的版本修复这个问题哈3.9.0版本

**Comment by zzcr** [comment]
v3.9.0版本已修复
