### ISSUE TITLE
🐛 [Bug]: TinyPro, Phase plan-- > specify frequency when the selection box is not selected, the prompt style dislocation is required.

### ISSUE THREAD

**Issue by nextniko** [opentiny/tiny-vue#235]
### Version

3

### Vue Version

3

### Link to minimal reproduction

https://github.com/opentiny/tiny-vue

### Step to reproduce

![wOuZnI4nhZ](https://github.com/opentiny/tiny-vue/assets/40553790/54665073-bfe9-413f-b9b9-c0b59cd5f2c5)
路径： https://opentiny.design/vue-pro/pages/form/base
功能：阶段计划 --> 指定频次 当不选选择框时，必填提示 样式错位。

**Comment by kagol** [comment]
@nextniko Please report a bug at [https://github.com/opentiny/tiny-cli/issues](https://github.com/opentiny/tiny-cli/issues), thank you!
