### ISSUE TITLE
🐛 [Bug]: When the grid component operation column is frozen and fixed:left,right is set, the bottom scroll bar displays an error

### ISSUE THREAD

**Issue by DamonCais** [opentiny/tiny-vue#236]
### Version

3.7.0

### Vue Version

3

### Link to minimal reproduction

https://opentiny.design/tiny-vue/zh-CN/os-theme/components/grid-fixed

### Step to reproduce

操作列冻结同时设置fixed：left,right。

### What is expected

底部滚动条在表格上面

### What is actually happening

移动滚动条时，被冻结块遮挡
![image](https://github.com/opentiny/tiny-vue/assets/33564888/e3c6ba70-4f05-477c-9b10-572431261c5a)

**Comment by zzcr** [comment]
v3.9.0版本的grid组件，改变了冻结列的实现方式，应该不会出现这个问题了
