### ISSUE TITLE
✨ [Feature]: The display of attributes in the api table on the official website looks very difficult. I want to add a line under each attribute.

### ISSUE THREAD

**Issue by lhuansheng** [opentiny/tiny-vue#237]
### What problem does this feature solve

![image](https://github.com/opentiny/tiny-vue/assets/62824587/d995c2f0-944e-44dd-bf2f-745fe5d2c354)

### What does the proposed API look like

如题

**Comment by qinwencheng** [comment]
刷新下当前页面试试？

**Comment by zzcr** [comment]
v3.9.0版本的官网已修复此问题
