### ISSUE TITLE
🐛 [Bug]: 本地开发是正常的 打包后部分组件样式丢失

### ISSUE THREAD

**Issue by extra-zhao** [opentiny/tiny-vue#2374]
### Version

@opentiny/vue@3.18.0

### Vue Version

3.4.4

### Link to minimal reproduction

none

### Step to reproduce

本地开发时 样式均正常
![image](https://github.com/user-attachments/assets/0965bffb-7dc5-421d-885d-02f111ee92f9)

打包之后 部分组件样式丢失 例如 tiny-alert、按钮的loading等
![image](https://github.com/user-attachments/assets/2942f867-bdd4-46f7-814d-a0a9c53f22b5)

工程是vite搭建的vue工程  下面是package.json和vite.config
![image](https://github.com/user-attachments/assets/5894c172-9961-49a2-9936-fc03b08fd3f7)

![image](https://github.com/user-attachments/assets/978130a2-3c46-4a12-b320-7f7534911072)

### What is your project name

vite-vue-app

**Comment by mengqiuleo** [comment]
原因：与 按需引入插件无关，与切换主题有关。

svg 上有自定义类名 tiny-svg，切换主题打包后，tiny-svg 的默认样式丢失。

似乎已经被修复。相关 pr : #2395

**Comment by zzcr** [comment]
@opentiny/vue-theme@3.18.4版本已修复此问题哈
