### ISSUE TITLE
✨ [Feature]: Can you provide several vue basic development templates?

### ISSUE THREAD

**Issue by zhanghaifei1997** [opentiny/tiny-vue#239]
### What problem does this feature solve

能否提供几个vue基础开发模板呢，比如多页面后台管理，单页面应用

### What does the proposed API look like

组建的整体风格很喜欢，如果有几个能拿来直接二次开的基础模板就更好了

**Comment by kagol** [comment]
看下这个能不能满足：https://opentiny.design/vue-pro/pages/
