### ISSUE TITLE
✨ [Feature]: 表格的最后一行冻结

### ISSUE THREAD

**Issue by fanbingbing16** [opentiny/tiny-vue#2416]
### What problem does this feature solve

现在有一个需求是表格的最后一行冻结，一个表示数据的表格，最后一行是合计，希望最后一行和表格头都可以冻结，表格头是可以冻结的    现在的处理方法是用了两个表格，然后第一个表格显示数据将分页去掉，第二个表格只显示合计，这样让人看着以为是一个表格然后最后一行冻结，但是这样的效果不好

### What does the proposed API look like

fixed:'bottom'

### What is your project name

grid

**Comment by gimmyhehe** [comment]
@fanbingbing16 你的功能可以通过定位表尾来实现，表尾相对于表格来说，位置是冻结的

**Comment by fanbingbing16** [comment]
> @fanbingbing16 你的功能可以通过定位表尾来实现，表尾相对于表格来说，位置是冻结的

具体是咋样的，没找到文档

**Comment by gimmyhehe** [comment]
@fanbingbing16  https://opentiny.design/tiny-vue/zh-CN/os-theme/components/grid-footer 可以参考一下表格设置表尾相关的demo哈~
