### ISSUE TITLE
🐛 [Bug]: Clicking on the Anchor component in the official website example will cause the style of the whole site to change.

### ISSUE THREAD

**Issue by qinwencheng** [opentiny/tiny-vue#242]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://opentiny.design/tiny-vue/zh-CN/os-theme/components/anchor

### Step to reproduce

先任意打开某个组件，例如 #237 中提到的tree-menu组件，效果如图：
![image](https://github.com/opentiny/tiny-vue/assets/24841685/4c53993e-8a9b-45e4-aa88-d7a39976235a)
显示正常，表格有内边距，滚动条也正常，
此时打开anchor组件，可以看到滚动条发生了变化，表格样式也发生了变化：
![image](https://github.com/opentiny/tiny-vue/assets/24841685/ca6af014-7fd4-4cd5-a713-186aff8978b6)
样式发生变化的原因可以参考issue #208 
现在额外的问题是，当样式发生改变之后，点开其他组件，其他组件的页面将会受到影响，再来到tree-menu组件：
![image](https://github.com/opentiny/tiny-vue/assets/24841685/bcfedbc9-22f4-48b8-9095-adde4a03fc0e)
可以发现， #237 中的问题复现

### What is expected

不应该点开某个组件之后，之后导致其他组件页面的样式跟着变化

### What is actually happening

点开anchor组件的页面后，body会增加上一个 `tiny-anchor-scroll-container` 类，导致出现了和 #208 类似的问题

**Comment by chenxi-20** [comment]
问题已收录，请等待下一版本发布
