### ISSUE TITLE
🐛 [Bug]: DatePicker 日期选择器 禁用状态 点击顶部年份会导致内存泄漏，导致页面直接无响应

### ISSUE THREAD

**Issue by wuvirv** [opentiny/tiny-vue#2474]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

![微信图片_20241030145228](https://github.com/user-attachments/assets/43e3e4e0-5a07-483c-b3b2-119bead37886)

### Step to reproduce

1. 使用禁用状态的日期组件
2. 点击年份 筛选条件
3. 页面卡死

### What is expected

正常禁用年份

### What is actually happening

页面无响应

### What is your project name

lis

**Comment by Youyou-smiles** [comment]
这个已经修复了，得等下个版本上线就好了。
