### ISSUE TITLE
🐛 [Bug]: 体验,每次tiny init pro 都会提示当前目录下已存在文件,其实并没有

### ISSUE THREAD

**Issue by vp1c** [opentiny/tiny-vue#2477]
### Version

all

### Vue Version

all

### Link to minimal reproduction

none

### Step to reproduce

<img width="572" alt="微信图片_20241101155649" src="https://github.com/user-attachments/assets/3e101964-586d-4bc3-9d11-7357331d8d61">

### What is your project name

none

**Comment by GaoNeng-wWw** [comment]
这句话的意思是「当前目录不为空，如果继续创建可能会存在覆盖同名文件的风险」

![2477](https://github.com/user-attachments/assets/cd3deef5-1f5a-4c3a-939e-9cf27baa4925)

**Comment by vp1c** [comment]
=-= 新电脑, 等我重做系统在试试
