### ISSUE TITLE
✨ [Feature]: 官网查看组件文档时，侧边栏经常误触，自动收起

### ISSUE THREAD

**Issue by smallseapig** [opentiny/tiny-vue#2491]
### What problem does this feature solve

**优化建议：**
- 取消空白处的事件触发
**问题根源：**
- 查看组件时，侧边栏会自动展开，再次点击会自动收起，但是由于点击空白处也会自动收起，导致经常性误触
![image](https://github.com/user-attachments/assets/2f2c1e70-c784-4bb0-a369-6e7cccde8ae8)

### What does the proposed API look like

不涉及

### What is your project name

官网

**Comment by kagol** [comment]
@smallseapig 感谢你的反馈，这是一个问题，我们来修复下

**Comment by gimmyhehe** [comment]
已修复，待发布新官网~
