### ISSUE TITLE
🐛 [Bug]: Menu display bug after TinyPro theme switch

### ISSUE THREAD

**Issue by Azir-11** [opentiny/tiny-vue#255]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://github.com/opentiny/tiny-vue

### Step to reproduce

1、打开主题配置，选择蜜糖主题或其他背景色不透明的主题
![image](https://github.com/opentiny/tiny-vue/assets/79054161/7ac55908-cffc-40a0-b067-4c49f3063fef)

2、将鼠标移至已激活的菜单选项中
![image](https://github.com/opentiny/tiny-vue/assets/79054161/e52e87da-329f-4f89-9250-f4655a43dbbb)

### What is expected

正常显示各个部分

### What is actually happening

激活的菜单文字颜色消失，甚至是有选中状态的所有组件在鼠标选中的时候都会发生这个情况，例如表格组件
在使用深邃夜空主题时还出现了更严重的问题：
![image](https://github.com/opentiny/tiny-vue/assets/79054161/79d7ccce-c518-4210-be7d-08bc83cc4124)

### Any additional comments (optional)

这是在“最佳实践”中的TinyPro中发现的问题，我也不知道是否应该提交在这，但是我并没有找到TinyPro的仓库地址，他的示例及文档界面内的github链接均将我链到了这里

**Comment by kagol** [comment]
@HnyLi 感谢你的反馈，TinyPro的问题可以提交在：[https://github.com/opentiny/tiny-cli](https://github.com/opentiny/tiny-cli)

**Comment by jishuai-cool** [comment]
非常感谢您的反馈，我们这边重新设计一下存在视觉效果问题的主题色，待设计开发完成后再进行展示
