### ISSUE TITLE
✨ [Feature]: The Tree component renders big data, and the page stutters when all is expanded or searched.

### ISSUE THREAD

**Issue by githubbylyf** [opentiny/tiny-vue#256]
### What problem does this feature solve

业务需要渲染近9000条左右的数据，点击全部展开或者前端实现搜索时，会出现页面卡顿的情况

### What does the proposed API look like

希望有类似滚动加载和服务端搜索的功能，若有更好的实现方法也可，期待回复。

**Comment by kagol** [comment]
Need to support virtual scrolling feature, we are planning this feature.

**Comment by zzcr** [comment]
可以参考虚拟滚动：https://opentiny.design/tiny-vue/zh-CN/os-theme/components/grid-large-data#tiny-first-menu-virtual-rolling
