### ISSUE TITLE
🐛 [Bug]: After setting the numerical precision of the Numeric counter, the decimal point input exception

### ISSUE THREAD

**Issue by Felix-jk** [opentiny/tiny-vue#261]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://opentiny.design/tiny-vue/zh-CN/os-theme/components/numeric#precision

### Step to reproduce

官方文档提供的示例
1. 输入数字，可以正常显示。输入小数点，没显示出来。再输入数字，数字能正常显示，但小数点还没显示；
2. 组件失焦后，会补全精度0 和小数点；
3. 组件重新聚焦后，输入小数点，可正常显示。

**Comment by Huangyilin19** [comment]
我没太理解第2个问题, 能解释一下吗

**Comment by Huangyilin19** [comment]
已修复， 可以更新TinyVue到3.8.2或更新版本
