### ISSUE TITLE
🐛 [Bug]: tiny-modal与tiny-grid联合使用时候出现BUG

### ISSUE THREAD

**Issue by RZGD** [opentiny/tiny-vue#2611]
### Version

@opentiny/vue@3.19.0

### Vue Version

3.0

### Link to minimal reproduction

<template>
  <span @click="set_data_loaded()"> 加载完成</span>
  <span @click="toshow()"> 弹出</span>
  <div v-if="data_loaded">
    <tiny-grid> <tiny-grid-column type="selection" width="40" /> </tiny-grid>
    
  </div>

  <tiny-modal v-if="show_dialog" v-model="show_dialog" type="confirm"  title="bolist页面">
    <bolist> </bolist>
  </tiny-modal>
  
</template>

<script lang="ts" setup>
import { ref, } from 'vue'
import bolist from './bolist.vue';
import { TinyGrid, TinyGridColumn } from '@opentiny/vue'
const data_loaded = ref(false);
const show_dialog = ref(false);

function set_data_loaded() {
  setTimeout(() => { data_loaded.value = true; }, 200)
}
function toshow() {
  show_dialog.value = true;
}

</script>

### Step to reproduce

建立一个bolist.vue组件。并在tiny-moda组件中弹出bolist.vue组件。
操作步骤先点击【加载完成】，然后点击【弹出】，在弹出框中再点击【加载完成】，然后关闭弹窗则报错。
[代码.txt](https://github.com/user-attachments/files/18016092/default.txt)

https://github.com/user-attachments/assets/d999e71d-fcf3-4249-aecd-93e47a141111

。

https://github.com/user-attachments/assets/6a595b4f-14a3-42a5-b8a4-988a7a3f1611

### What is your project name

aaaa

**Comment by gimmyhehe** [comment]
@RZGD  tiny-modal中 v-if和v-model使用了同一个标志，因此弹窗关闭时，是直接销毁了整个弹窗。表格中逻辑较复杂，同时隐藏与销毁可能会导致问题。建议将v-if标志与v-model标志分开。
示例代码：
```
<template>
  <span @click="set_data_loaded()"> 加载完成</span>
  <span @click="toshow()"> 弹出</span>
  <div v-if="data_loaded">
    <tiny-grid> <tiny-grid-column type="selection" width="40" /> </tiny-grid>
    <!-- <el-table> <el-table-column type="selection" width="40" /> </el-table> -->
  </div>

  <tiny-modal v-if="modalShow" v-model="show_dialog" type="confirm" title="bolist页面">
    <bolist> </bolist>
  </tiny-modal>
</template>

<script lang="ts" setup>
import { ref } from 'vue'
import bolist from './basic-usage.vue'
import { TinyGrid, TinyGridColumn, TinyModal } from '@opentiny/vue'
const data_loaded = ref(false)
const show_dialog = ref(false)
const modalShow = ref(false)

function set_data_loaded() {
  setTimeout(() => {
    data_loaded.value = true
  }, 200)
}
function toshow() {
  show_dialog.value = true
  modalShow.value = true
}
</script>
```
