### ISSUE TITLE
🐛 [Bug]: SSR渲染遇到报错

### ISSUE THREAD

**Issue by weixingqi** [opentiny/tiny-vue#2621]
### Version

3.18.0

### Vue Version

3.3.7

### Link to minimal reproduction

在vitepress中使用tinyvue，执行npm run build遇到报错信息window is not define. 定位发现问题代码在tiny-vue中  
具体代码为`const RAF  =  window.requestAnimationFrame`

### Step to reproduce

在vitepress中使用tinyvue，执行npm run build遇到报错信息window is not define. 定位发现问题代码在tiny-vue中  
具体代码为`const RAF  =  window.requestAnimationFrame`

### What is your project name

unibuy

**Comment by zzcr** [comment]
已修复，在3.21.0版本修复：https://github.com/opentiny/tiny-vue/pull/2635
