### ISSUE TITLE
🐛 [Bug]:  表格组件，双击列 ，列自动缩小，正常应该自适应

### ISSUE THREAD

**Issue by 552847957** [opentiny/tiny-vue#2631]
### Version

@opentiny/vue@3.19.0

### Vue Version

3.0

### Link to minimal reproduction

表格组件中，双击列 ，列自动缩小，正常应该自适应
<img width="768" alt="微信图片_20241210083612" src="https://github.com/user-attachments/assets/c6092c74-98b3-431f-a5fe-55987ce2efdc">

### Step to reproduce

表格组件中，双击列 ，列自动缩小，正常应该自适应

### What is your project name

tiny-vue

**Comment by gimmyhehe** [comment]
@552847957 
表格列宽度是否自适应是由表格列是否设置了宽度决定的。列后面的竖线是用于表格拖拽设置宽度的。正常情况下双击列是将列固定为当前宽度（鼠标按下 --> 拖拽移动量为0 --> 鼠标松开，设置宽度与原宽度一致。）
目前双击列自动缩小的原因是拖拽开始的位置会比实际位置偏左一些，导致鼠标放开时，列宽度缩小了。这个问题我们将会修复并在3.21.0版本发布修复
