### ISSUE TITLE
🐛 [Bug]: 游览器对表格进行缩放或者放大到某个比例会出现滚动条

### ISSUE THREAD

**Issue by xfycoding** [opentiny/tiny-vue#2648]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://opentiny.design/tiny-vue/zh-CN/os-theme/components/grid-size

### Step to reproduce

![微信图片_20241214150723](https://github.com/user-attachments/assets/baaaaa71-eb24-46f6-8d3e-b3e21e122526)

### What is your project name

demo

**Comment by gimmyhehe** [comment]
@xfycoding 出现滚动条的原因是因为浏览器缩放的时候，宽度会出现小数点。但是通过clientWidth获取的值是进过四舍五入的值处理后的。因此表格宽度会比实际多出零点几像数，导致出现滚动条。

![image](https://github.com/user-attachments/assets/fb2703ba-6582-4114-ab68-4dce978caf12)
![image](https://github.com/user-attachments/assets/ec5befb4-2ef2-47a0-8faf-eca11c7d8331)

如果确实需要对缩放进行适配且确认此表格不会出现滚动条的情况下，建议通过设置样式适配：
![image](https://github.com/user-attachments/assets/736a430b-9856-4480-82ce-d10ae75f8d80)
