### ISSUE TITLE
🐛 [Bug]: Internal-cli path processing should distinguish between dev and build, involving template path and other path resolution.

### ISSUE THREAD

**Issue by zuixinwang** [opentiny/tiny-vue#267]
### Version

latest

### Vue Version

无关

### Link to minimal reproduction

`internal-cli` 执行 `create:ui` 脚本命令是有效的，但如果执行 `build` 脚本命令之后，执行 `dist/cjs/commands/create/create-ui.js` 文件会报错。
主要还是内部的 `utils` 的路径解析，很多需要区分 `dev` 和 `build`，尤其是涉及到 `template` 模板目录的处理。

请先查看此 [`pr`](https://github.com/opentiny/tiny-vue/pull/257) ，后续我可以处理这里的路径问题。

### Step to reproduce

`internal-cli` 执行 `create:ui` 脚本命令是有效的，但如果执行 `build` 脚本命令之后，执行 `dist/cjs/commands/create/create-ui.js` 文件会报错。
主要还是内部的 `utils` 的路径解析，很多需要区分 `dev` 和 `build`，尤其是涉及到 `template` 模板目录的处理。

请先查看此 [`pr`](https://github.com/opentiny/tiny-vue/pull/257) ，后续我可以处理这里的路径问题。

**Comment by kagol** [comment]
@zuixinwang 非常感谢你的反馈和贡献，我们正在检视 #257，也欢迎你加入我们的OpenTiny技术交流群：opentiny-official ，可以一起交流~

**Comment by zuixinwang** [comment]
是什么群，有二维码么
