### ISSUE TITLE
🐛 [Bug]: input type="textarea" setting autosize performance does not meet expectations

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-vue#275]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

按照以下方式设置 autosize，在没有输入任何内容时应该显示一行文本才对，实际上显示了两行文本

```html
<tiny-input type="textarea" :autosize="{minRows: 1, maxRows: 6}"  v-model="input" placeholder="cols 为默认"></tiny-input>
```

### Step to reproduce

按以下方式使用 input 组件，设置 autosize 的minRows 为1，不输入任何内容情况下应该只显示一行文本的高度

```html
<tiny-input type="textarea" :autosize="{minRows: 1, maxRows: 6}"  v-model="input" placeholder="cols 为默认"></tiny-input>
```

<img width="711" alt="image" src="https://github.com/opentiny/tiny-vue/assets/9566362/be914d89-843a-47d7-9fc9-a67f11b12315">

**Comment by rayhaoqin** [comment]
已修复该问题，请等待下个版本发布
