### ISSUE TITLE
🐛 [Bug]: The position of the multi-selection drop-down box on the home page

### ISSUE THREAD

**Issue by 314857493** [opentiny/tiny-vue#277]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://opentiny.design/

### Step to reproduce

![ab20a8e2eec12b82c2aecc8d2c17ad4b](https://github.com/opentiny/tiny-vue/assets/34772902/f0a5b717-cf14-4f9c-a22c-ccfead1768f5)
![cbb6f60ae5e546a48267d6192559f3d3](https://github.com/opentiny/tiny-vue/assets/34772902/7c85859d-2ce9-4fe4-8122-ede6e7880e5c)

**Comment by zzcr** [comment]
可以使用如下解决方案：
https://github.com/opentiny/tiny-vue/wiki/%E3%80%90TinyVue%E3%80%91date-pick%E7%BB%84%E4%BB%B6%E6%88%96%E8%80%85select%E9%80%89%E6%8B%A9%E7%9A%84%E4%B8%8B%E6%8B%89%E9%9D%A2%E6%9D%BF%E4%B8%8D%E4%BC%9A%E8%B7%9F%E9%9A%8F%E9%A1%B5%E9%9D%A2%E6%BB%9A%E5%8A%A8%E6%9D%A1%E6%BB%9A%E5%8A%A8%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88
