### ISSUE TITLE
🐛 [Bug]: Local project-use the menu below the guide, the page is not refreshed

### ISSUE THREAD

**Issue by GuYith** [opentiny/tiny-vue#280]
### Version

3.7.12

### Vue Version

lastest

### Link to minimal reproduction

None

### Step to reproduce

运行本地项目，点击“使用指南”下的任意子菜单

### What is expected

页面刷新，展示期望内容

### What is actually happening

页面没有刷新

### Any additional comments (optional)

本地项目在解析目录时，只考虑了组件，没有考虑“使用指南”相关子菜单。
![OpenTiny-Bug-Menu-2](https://github.com/opentiny/tiny-vue/assets/48597370/d267d187-1d09-4889-a533-5c32c3755d9c)
![OpenTiny-Bug-Menu](https://github.com/opentiny/tiny-vue/assets/48597370/7700e4b4-a524-4e05-9bfc-7fa0024a76fa)

**Comment by zzcr** [comment]
新版本官网已修复
