### ISSUE TITLE
🐛 [Bug]: Official website-does not display when the Achor component sets is-addfix to true

### ISSUE THREAD

**Issue by GuYith** [opentiny/tiny-vue#281]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

无

### Step to reproduce

点击官网Achor组件固定模式下的按钮即可复现
(在滚动容器中，为tiny-anchor添加:is-affix=true出现同样情况，Anchor组件消失)
![OpenTiny-Bug-Ancor](https://github.com/opentiny/tiny-vue/assets/48597370/18438500-f66c-46b9-84dc-0dece460dc33)
![OpenTiny-Bug-Ancor-2](https://github.com/opentiny/tiny-vue/assets/48597370/4995c9a3-904c-4ea0-a987-b542ffdfe53e)

**Comment by chenxi-20** [comment]
这个问题已解决
