### ISSUE TITLE
🐛 [Bug]: There is a name error in the TinyVue component exported in CDN mode

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-vue#286]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

importmap方式导入：
```
"@opentiny/vue": "https://unpkg.com/@opentiny/vue@3.8.3/runtime/tiny-vue.mjs",
```

主要存在以下问题：
1. 部分组件没有 name，比如：Loading、GridManager
2. 部分组件名称不正确，比如：YearRange的名称是`TinyMonthRange`，应该是`TinyYearRange`
3. 整体导出的 TinyVue，缺乏 install，导致没法直接通过 use(TinyVue) 全量注册

### Step to reproduce

如上

**Comment by zzcr** [comment]
v3.9.0版本已修复
