### ISSUE TITLE
✨ [Feature]: Tiny-vue-theme theme tool missing type declaration file

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-vue#287]
### What problem does this feature solve

通过以下方式使用，会提示无法找到类型声明文件：

```ts
import ThemeTool from '@opentiny/vue-theme/theme-tool'
import { tinySmbTheme } from '@opentiny/vue-theme/theme'
```

### What does the proposed API look like

希望tiny-vue-theme包产物提供类型声明文件，提升开发者体验。

**Comment by zzcr** [comment]
v3.9.0版本已添加类型声明文件
