### ISSUE TITLE
✨ [Feature]: Hope to add project-related documentation

### ISSUE THREAD

**Issue by GuYith** [opentiny/tiny-vue#288]
### What problem does this feature solve

tiny-vue的文件结构比较复杂，很多目录文件的作用/逻辑直接读代码很难搞清楚
希望完善各个目录文件的README.md，目前只有theme，renderless等部分文件夹下有，且内容不清晰
另：renderless目录下README.md中的链接无法打开 [https://open.codehub.huawei.com/innersource/originjs/tiny/opentiny-vue/home](https://open.codehub.huawei.com/innersource/originjs/tiny/opentiny-vue/home)

### What does the proposed API look like

-

**Comment by kagol** [comment]
@GuYith 这个需要完善下
