### ISSUE TITLE
✨ [Feature]: When tiny-popeditor gets the focus and enters it manually, value1 cannot bind in both directions. How to deal with this problem?

### ISSUE THREAD

**Issue by thestar077** [opentiny/tiny-vue#289]
### What problem does this feature solve

<tiny-popeditor v-model="value1" tabindex="-1" :readonly="false" :grid-op="gridOp" text-field="name" value-field="id"></tiny-popeditor>
{{value1}}
value1的值没有更新

### What does the proposed API look like

<tiny-popeditor v-model="value1" tabindex="-1" :readonly="false" :grid-op="gridOp" text-field="name" value-field="id"></tiny-popeditor>
{{value1}}
value1的值没有更新

**Comment by kagol** [comment]
补充截图：
![image](https://github.com/opentiny/tiny-vue/assets/9566362/823dbc3b-0153-467d-a744-140f06e5b68a)

**Comment by yuanningning** [comment]
配置suggest 开启联想功能，输入框输入后自动触发联想查询；该功能需要联合 remoteSearch 使用。

**Comment by thestar077** [comment]
> 配置suggest 开启联想功能，输入框输入后自动触发联想查询；该功能需要联合 remoteSearch 使用。

抱歉，没理解。
1.tiny-popeditor 对应api里找不到suggest 
2.结合使用remoteSearch 无效，应该是使用方法不对导致无效
能提供demo代码说明具体怎么实现吗，谢谢

**Comment by yuanningning** [comment]
> > 配置suggest 开启联想功能，输入框输入后自动触发联想查询；该功能需要联合 remoteSearch 使用。
> 
> 抱歉，没理解。 1.tiny-popeditor 对应api里找不到suggest 2.结合使用remoteSearch 无效，应该是使用方法不对导致无效 能提供demo代码说明具体怎么实现吗，谢谢

新增加了api文档和demo示例，详细demo代码见https://github.com/yuanningning/tiny-vue/commit/13d51db22aea4153bd3d816253b36cfe35e70260     中的suggest.vue

**Comment by thestar077** [comment]
> 新增加了api文档和demo示例，详细demo代码见[yuanningning@13d51db](https://github.com/yuanningning/tiny-vue/commit/13d51db22aea4153bd3d816253b36cfe35e70260) 中的suggest.vue

感谢提供demo，可是我的需求是只需要手动输入value值响应即可，不需要输入后匹配再勾选value值才响应
