### ISSUE TITLE
🐛 [Bug]: Row-class-name= "rowClass" error when table setting custom row style class name

### ISSUE THREAD

**Issue by zhanghaifei1997** [opentiny/tiny-vue#291]
### Version

"@opentiny/vue": "^3.6.8",

### Vue Version

"vue": "^3.2.31",

### Link to minimal reproduction

![image](https://github.com/opentiny/tiny-vue/assets/57278786/d63a26c3-9f64-4076-acf8-86a10b4bca3e)

### Step to reproduce

![image](https://github.com/opentiny/tiny-vue/assets/57278786/4f85f08d-d523-4cf9-9545-9d952ae1291b)

**Comment by zzcr** [comment]
你好，row-class-name前面是不是少了一个冒号啊~~，没有冒号就被当作一个字符串了
