### ISSUE TITLE
✨ [Feature]: Can you add an alignment to the paging function of the table component align: [left,center,right]

### ISSUE THREAD

**Issue by zhanghaifei1997** [opentiny/tiny-vue#292]
### What problem does this feature solve

![image](https://github.com/opentiny/tiny-vue/assets/57278786/871bc957-b036-4764-a6b6-c0154c220d4d)

### What does the proposed API look like

表格组件的分页功能能不能添加一个对齐方式align：【left，center，right】

**Comment by zhanghaifei1997** [comment]
还有这里的总条数最好支持自定义【totalText：‘共’】

**Comment by zzcr** [comment]
已在这个迭代完成了align：【left，center，right】属性的开发，等待月底版本发布
