### ISSUE TITLE
🐛 [Bug]: The button component has an abnormal icon icon color when both plain and disabled are set.

### ISSUE THREAD

**Issue by zhanghaifei1997** [opentiny/tiny-vue#293]
### Version

"@opentiny/vue": "^3.6.8",

### Vue Version

"vue": "^3.2.31",

### Link to minimal reproduction

![image](https://github.com/opentiny/tiny-vue/assets/57278786/6b628543-b070-427a-83e8-c09bd0337176)

### Step to reproduce

![image](https://github.com/opentiny/tiny-vue/assets/57278786/deebc458-6c89-471e-90e9-57cf9a5e5ff0)

### What is expected

我这里因为使用success和danger状态的按钮所以就改了两个，按理来说你们应该把所有状态的按钮都要改一下这个样式

**Comment by gimmyhehe** [comment]
问题已收录，修改后将在下一版本发布~

**Comment by kagol** [comment]
Fixed by @gimmyhehe by #299
