### ISSUE TITLE
✨ [Feature]: Can the Progress progress bar component add a custom progress bar background color bgcolor?

### ISSUE THREAD

**Issue by zhanghaifei1997** [opentiny/tiny-vue#295]
### What problem does this feature solve

Progress 进度条组件是否可以增加一个自定义进度条背景色bgcolor，现有的color字段只可以自定义进度条的，但是很多情况下整个进度条（条状和圆形的都需要自定义背景色跟进度条颜色），最好内部的字体大小粗细颜色也能自定义，再添加一个标题和副标题的自定义

### What does the proposed API look like

![image](https://github.com/opentiny/tiny-vue/assets/57278786/0bdcac6c-eb8f-48ea-a903-1e612c49b86c)

**Comment by chenxi-20** [comment]
这个现有的api是可以满足的，color可以自定义背景色的，至于自定义内部字体大小可以自己写个样式即可完成修改，标题和副标题的定义一般就不属于进度条组件的工作了，这一部分属于自定义的
