### ISSUE TITLE
🐛 [Bug]: Select will misplace when choosing.

### ISSUE THREAD

**Issue by khy-ocean** [opentiny/tiny-vue#300]
### Version

 @opentiny/vue@3.8.2 

### Vue Version

"vue": "^3.2.47",

### Link to minimal reproduction

![image](https://github.com/opentiny/tiny-vue/assets/55942194/9d16fcb8-ac02-4d5a-871a-1628b34a647d)

### Step to reproduce

框架：无界微前端框架
前提：选择框组件在子应用的弹框中，弹框滚动固定，子应用页面在无界主应用中高度自动撑高可以滚动，overflow:auto设置在主应用中
推测：子应用在主应用中高度自动撑高，所以子应用在主应用中滚动的时候，子应用中选择框组件的弹出选项是挂载在body且使用fixed定位，因此选项框会跟随子应用内容滚动

### What is expected

选择器下拉面板在对应选择器下面
![企业微信截图_16884667646341](https://github.com/opentiny/tiny-vue/assets/55942194/63cce8ad-e477-4031-ab44-f4bbcac72a84)

### What is actually happening

选择器下拉面板错位，不在对应选择器下面

![image](https://github.com/opentiny/tiny-vue/assets/55942194/51fe48c8-3e73-4798-9c3d-61d1aa3cf0f2)

**Comment by kagol** [comment]
@khy-ocean 你试下这个方案

https://github.com/opentiny/tiny-vue/wiki/%E3%80%90TinyVue%E3%80%91date-pick%E7%BB%84%E4%BB%B6%E6%88%96%E8%80%85select%E9%80%89%E6%8B%A9%E7%9A%84%E4%B8%8B%E6%8B%89%E9%9D%A2%E6%9D%BF%E4%B8%8D%E4%BC%9A%E8%B7%9F%E9%9A%8F%E9%A1%B5%E9%9D%A2%E6%BB%9A%E5%8A%A8%E6%9D%A1%E6%BB%9A%E5%8A%A8%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88

**Comment by khy-ocean** [comment]
@kagol 提供的方案和描述的问题不一样，现在的问题是“下拉面板跟随页面滚动”，要求是“下拉面板跟随下拉框，而不要跟随页面滚动而导致下拉面板错位”

**Comment by zzcr** [comment]
大概了解你的问题了，内部也有工业软件云的项目遇到过类似问题，我们初步决定添加几个全局配置：1、始终保持absolute布局配置  2、页面滚动时下拉框面板直接关闭配置

**Comment by zzcr** [comment]
7月份迭代增加这两个配置

**Comment by khy-ocean** [comment]
@zzcr 什么时候迭代的话麻烦通知一下，辛苦了

**Comment by zzcr** [comment]
3.11.0版本已修复此问题
