### ISSUE TITLE
🐛 [Bug]: After inline editing of the Table component, click on the area outside the edit column, and the editing content will not take effect.

### ISSUE THREAD

**Issue by Felix-jk** [opentiny/tiny-vue#301]
### Version

3.6.7

### Vue Version

latest

### Link to minimal reproduction

输入完之后点击编辑列以外的位置刚才输入的修改不生效，并且样式也不会还原；只有点击编辑列的其他编辑框才能生效，并且样式还原

![60f19ff168cbe9f4878a802159f8bd9](https://github.com/opentiny/tiny-vue/assets/33026143/d3cdb48b-6e7c-417d-876f-35c166d5b66b)

### Step to reproduce

同上

**Comment by zzcr** [comment]
可以查看这个例子（ialogBox弹窗中的可编辑表格编辑器无法正常失焦）：https://opentiny.design/tiny-vue/zh-CN/os-theme/components/grid-faq#faq-gridInDialogBox
