### ISSUE TITLE
🐛 [Bug]: The problem of Table component dragging

### ISSUE THREAD

**Issue by Felix-jk** [opentiny/tiny-vue#302]
### Version

3.6.7

### Vue Version

latest

### Link to minimal reproduction

把最后一条数据拖到最上面，拖上去之后，第一条显示的是倒数第二条的数据

![微信图片_20230706174118](https://github.com/opentiny/tiny-vue/assets/33026143/6e8dc737-86f7-4cc2-ae9d-1937d3a611a0)

![2](https://github.com/opentiny/tiny-vue/assets/33026143/955c6b44-10c7-4c41-a42b-7d06d9cffe4d)

### Step to reproduce

同上

**Comment by zzcr** [comment]
你好可否提供个可以复现的例子呢？我在官网试了是正常的：https://opentiny.design/tiny-vue/zh-CN/os-theme/components/grid-drag#drag-row-drag
