### ISSUE TITLE
✨ [Feature]:  Please support unplugin-vue-components 

### ISSUE THREAD

**Issue by transtone** [opentiny/tiny-vue#304]
### What problem does this feature solve

不积极加入vue开发相关生态，谁知道有个什么 opentiny，还要自己写按需加载的解析器，对开发者太不友好了。

### What does the proposed API look like

添加 [unplugin-vue-components](https://github.com/antfu/unplugin-vue-components) 组件

**Comment by kagol** [comment]
很好的建议，自动按需导入组件还是很实用的，可以支持

**Comment by lanrenbulan** [comment]
现在支持了吗

**Comment by mengqiuleo** [comment]
我来实现这个新特性🚀

**Comment by kagol** [comment]
Finished by @mengqiuleo on #1397, released in v3.14.0
