### ISSUE TITLE
✨ [Feature]: The template is expected to adapt to mobile devices.

### ISSUE THREAD

**Issue by mr-yangli** [opentiny/tiny-vue#308]
### What problem does this feature solve

首先声明我是一个后端开发，对样式不是很熟悉，前不久欧然发现这个框架，挺强大的，希望能适配一下移动端

### What does the proposed API look like

希望能适配移动端就完美了

**Comment by zzcr** [comment]
移动端已经有了，但是官网还没出来哈，我们将会在2024年初开放移动端官网
