### ISSUE TITLE
🐛 [Bug]: Guide component, ultra-wide when browsing on the phone.

### ISSUE THREAD

**Issue by digitalboy** [opentiny/tiny-vue#309]
### Version

最新版

### Vue Version

^3.0

### Link to minimal reproduction

https://opentiny.design/tiny-vue/zh-CN/os-theme/components/guide

### Step to reproduce

手机浏览器edge

**Comment by changpw** [comment]
props中width默认值设置为510px，是不是应该根据是否为移动端进行修改默认值？

**Comment by kagol** [comment]
Fixed by @xlearns on #499
