### ISSUE TITLE
✨ [Feature]: Please add the IMG component.

### ISSUE THREAD

**Issue by digitalboy** [opentiny/tiny-vue#310]
### What problem does this feature solve

没有img组件的话，不方便，或者推荐一个。

### What does the proposed API look like

<tiny-img>

**Comment by kagol** [comment]
有图片组件的。
https://opentiny.design/tiny-vue/zh-CN/os-theme/components/image

**Comment by digitalboy** [comment]
好的，看到了。 感谢。 @kagol
