### ISSUE TITLE
✨ [Feature]:  Please add mind map component

### ISSUE THREAD

**Issue by digitalboy** [opentiny/tiny-vue#312]
### What problem does this feature solve

这个需求场景还是比较多的。

### What does the proposed API look like

参考 xmind 中的一些样式就好。

**Comment by zzcr** [comment]
您好，感谢你的意见，我们内部评估下~~

**Comment by GaoNeng-wWw** [comment]
> 您好，感谢你的意见，我们内部评估下~~

Has the component been implemented? I want to give it a try

**Comment by GaoNeng-wWw** [comment]
#1207 已经实现了

**Comment by kagol** [comment]
Finished by @GaoNeng-wWw on #1207, released in v3.14.0
