### ISSUE TITLE
✨ [Feature]: Please add note-marking component

### ISSUE THREAD

**Issue by digitalboy** [opentiny/tiny-vue#313]
### What problem does this feature solve

类似于读书类app，划线笔记可以提高文本的可读性和社交性。

### What does the proposed API look like

类似于读书笔记

**Comment by zzcr** [comment]
您好，感谢你的意见，我们内部评估下~~

**Comment by zzcr** [comment]
您好，我们这边内部评审后决定暂时不做，理由是偏业务，不是通用组件，同时也非常欢迎您参与共建
