### ISSUE TITLE
✨ [Feature]: Can the selection range type of the date selector increase the year range?

### ISSUE THREAD

**Issue by zouzhixiang** [opentiny/tiny-vue#316]
### What problem does this feature solve

日期选择器的选择范围类型能增加年范围吗

### What does the proposed API look like

datePicker  的 type 增加一个 yearrange

**Comment by zzcr** [comment]
你好，已增加年范围的选择了哈（https://opentiny.design/tiny-vue/zh-CN/os-theme/components/date-picker#date-range）
