### ISSUE TITLE
🐛 [Bug]: In TinyVue documents, the description of browser compatibility is not clear

### ISSUE THREAD

**Issue by Tangzhongnan** [opentiny/tiny-vue#318]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://opentiny.design/tiny-vue/zh-CN/os-theme/docs/envpreparation

### Step to reproduce

https://opentiny.design/tiny-vue/zh-CN/os-theme/docs/envpreparation-环境准备

### What is actually happening

WARNING

浏览器兼容性 TinyVue 支持主流浏览器的最新版本：Chrome、Edge、IE、Firefox、Opera、Safari 不支持IE浏览器

这是官方文档中的说明，前面说支持支持主流浏览器的最新版本包括IE，后面又说不支持IE浏览器，所以说TinyVue对浏览器的兼容性到底是怎样的？

**Comment by zzcr** [comment]
已修改官网描述
