### ISSUE TITLE
✨ [Feature]: It is hoped that the table component of Tiny-Vue can add column setting function.

### ISSUE THREAD

**Issue by yehuo2003** [opentiny/tiny-vue#323]
### What problem does this feature solve

就像Tiny-NG一样的列设置功能
![image](https://github.com/opentiny/tiny-vue/assets/44639685/d3da8433-91e1-4848-b007-bd2cddfaaa39)
在TIny-Vue中没有, 希望可以加上

### What does the proposed API look like

就像Tiny-NG一样的列设置功能
![image](https://github.com/opentiny/tiny-vue/assets/44639685/d3da8433-91e1-4848-b007-bd2cddfaaa39)
在TIny-Vue中没有, 希望可以加上

**Comment by zzcr** [comment]
3.11.0版本已添加此功能
