### ISSUE TITLE
✨ [Feature]: In the out-of-the-box front end of TinyPro, how to achieve the TAB multi-page switching effect in the breadcrumb navigation bar?

### ISSUE THREAD

**Issue by joyoes** [opentiny/tiny-vue#325]
### What problem does this feature solve

✨ [Feature]:在TinyPro开箱即用的中后台前端中， 怎么在面包屑导航栏处实现TAB多页面的切换效果啊？

### What does the proposed API look like

✨ [Feature]:在TinyPro开箱即用的中后台前端中， 怎么在面包屑导航栏处实现TAB多页面的切换效果啊？

**Comment by kagol** [comment]
@joyoes 可否截个效果图看下？

**Comment by joyoes** [comment]
@kagol 截图如下
![TAB切换页面](https://github.com/opentiny/tiny-vue/assets/16605854/d9e190cf-403b-4f39-bdcb-6fbd9dbd8b91)

**Comment by joyoes** [comment]
> 

效果图弄给你了，你也不回复我呢

**Comment by horadrim1015** [comment]
我也有这个需求

**Comment by joyoes** [comment]
@kagol 然后点击头部的菜单栏，左侧能显示相应的子菜单。点击左侧的子菜单后，能显示相应的TAB页面。

**Comment by kagol** [comment]
> @kagol 然后点击头部的菜单栏，左侧能显示相应的子菜单。点击左侧的子菜单后，能显示相应的TAB页面。

了解了，我们内部讨论下
