### ISSUE TITLE
✨ [Feature]: How to achieve functions similar to online spreadsheets?

### ISSUE THREAD

**Issue by joyoes** [opentiny/tiny-vue#326]
### What problem does this feature solve

怎么实现类似在线电子表格的功能啊？✨ [Feature]: 

### What does the proposed API look like

怎么实现类似在线电子表格的功能啊？✨ [Feature]:

**Comment by kagol** [comment]
@joyoes 麻烦截个效果图看下

**Comment by transtone** [comment]
@joyoes  是类似 [S2](https://s2.antv.vision/examples)，还是类似 [Luckysheet](https://github.com/dream-num/Luckysheet) ？
