### ISSUE TITLE
🐛 [Bug]: ToggleMenu's get-menu-data-async doesn't work at all.

### ISSUE THREAD

**Issue by Aostas** [opentiny/tiny-vue#328]
### Version

3

### Vue Version

3.2.45

### Link to minimal reproduction

https://opentiny.design/tiny-vue/zh-CN/os-theme/components/toggle-menu#get-menu-data-async

### Step to reproduce

修改实例代码中的数据，甚至把数据以及`:get-menu-data-async="getMenuDataAsync"`全删掉，显示数据无变化，猜测是get-menu-data-async未执行，使用了默认数据。

```vue
<script setup lang="ts">
function getMenuDataAsync() {
  console.log("getMenuDataAsync")
}
</script>

<template>
  <div class="root-container">
    <tiny-container pattern="simple">
      <template #aside>
        <tiny-layout>
          <tiny-tree-menu style="width: auto;" :get-menu-data-async="getMenuDataAsync"></tiny-tree-menu>
        </tiny-layout>
      </template>
      <tiny-layout style="height: 100vh;">
      </tiny-layout>
    </tiny-container>
  </div>
</template>

<style scoped>
</style>

```
在`console.log("getMenuDataAsync")`未打印，打断点也不会触发

### What is expected

执行`getMenuDataAsync`后获得目录数据

### What is actually happening

未执行`getMenuDataAsync`

### Any additional comments (optional)

TreeMenu的异步会有吗，本来想用TreeView的

**Comment by Huangyilin19** [comment]
这确实是个问题，我们内部先评审下解决方案。

**Comment by James-9696** [comment]
修复中

**Comment by James-9696** [comment]
已修复，待发布。
