### ISSUE TITLE
🐛 [Bug]: When the label value of the checkbox component is 0, it does not display

### ISSUE THREAD

**Issue by windhc** [opentiny/tiny-vue#329]
### Version

3.9.1

### Vue Version

3.3.4

### Link to minimal reproduction

![image](https://github.com/opentiny/tiny-vue/assets/13448833/5c57517d-a649-475b-b3f7-744bdf7b4c31)

### Step to reproduce

![image](https://github.com/opentiny/tiny-vue/assets/13448833/49edca97-6fde-434e-95ef-a222bf80220a)

i-1的值为0时，label不显示

**Comment by gimmyhehe** [comment]
问题已收录，修改后将在下一版本发布~

**Comment by kagol** [comment]
Fixed by @gimmyhehe on #331
