### ISSUE TITLE
🐛 [Bug]: Table filtering when inputFilter is turned on, select [include] background without highlight

### ISSUE THREAD

**Issue by qindongliang** [opentiny/tiny-vue#330]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

1，打开官网页面 https://opentiny.design/tiny-vue/zh-CN/os-theme/components/grid-filter#api
2，在第一个例子点击公司名过滤
3，点击包含，无高亮，三个过滤条件的背景颜色都一样，无法区分当前是那种过滤模式在生效的

![image](https://github.com/opentiny/tiny-vue/assets/7587994/cfe2c886-f4ea-40a7-9c5d-115bed1213f7)

### Step to reproduce

1，打开官网页面 https://opentiny.design/tiny-vue/zh-CN/os-theme/components/grid-filter#api
2，在第一个例子点击公司名过滤
3，点击包含，无高亮，三个过滤条件的背景颜色都一样，无法区分当前是那种过滤模式在生效的

### What is expected

能够通过背景颜色高亮区分

**Comment by zzcr** [comment]
新版本已修复此问题
