### ISSUE TITLE
✨ [Feature]: Add a prefix to the exported component

### ISSUE THREAD

**Issue by jzymx50** [opentiny/tiny-vue#336]
### What problem does this feature solve

目前，组件import时需要改名：
`import { Checkbox as TinyCheckbox, Link as TinyLink } from '@opentiny/vue';`
希望可以避免重复的改名工作

### What does the proposed API look like

类似
`import { TinyCheckbox, TinyLink } from '@opentiny/vue';`
具体前缀可以讨论。如为了简洁，可以用"Ti"。
同时考虑向下兼容，原本的导出可以保留。在示例中，可以用带前缀的导出名，鼓励新写法。

**Comment by zzcr** [comment]
您好，感谢你的意见，我们内部评估下~~

**Comment by gimmyhehe** [comment]
@jzymx50 于3.17.0新增Tiny前缀组件导出
```
import { TinyCheckbox, TinyLink } from '@opentiny/vue';
```
目前这种写法已支持
