### ISSUE TITLE
🐛 [Bug]: Using CDN to introduce grid components, some dependencies @opentiny/vue are not exported

### ISSUE THREAD

**Issue by mengqiuleo** [opentiny/tiny-vue#343]
### Version

3.9.1

### Vue Version

3.2.47

### Link to minimal reproduction

[Grid 表格 - 右键菜单](https://opentiny.design/tiny-vue/zh-CN/os-theme/components/grid-context-menu)
playground在线demo复现：[tinyvue-playground](https://opentiny.github.io/tiny-vue-playground/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICA8dGlueS1ncmlkXG4gICAgICA6ZGF0YT1cInRhYmxlRGF0YVwiXG4gICAgICA6Y29udGV4dC1tZW51PVwie1xuICAgICAgICBoZWFkZXI6IHsgb3B0aW9uczogaGVhZGVyTWVudXMgfSxcbiAgICAgICAgdmlzaWJsZU1ldGhvZFxuICAgICAgfVwiXG4gICAgICBAY29udGV4dC1tZW51LWNsaWNrPVwiY29udGV4dE1lbnVDbGlja0V2ZW50XCJcbiAgICA+XG4gICAgICA8dGlueS1ncmlkLWNvbHVtbiB0eXBlPVwiaW5kZXhcIiB3aWR0aD1cIjYwXCI+PC90aW55LWdyaWQtY29sdW1uPlxuICAgICAgPHRpbnktZ3JpZC1jb2x1bW4gZmllbGQ9XCJuYW1lXCIgdGl0bGU9XCLlkI3np7BcIj48L3RpbnktZ3JpZC1jb2x1bW4+XG4gICAgICA8dGlueS1ncmlkLWNvbHVtbiBmaWVsZD1cImFyZWFcIiB0aXRsZT1cIuWMuuWfn1wiPjwvdGlueS1ncmlkLWNvbHVtbj5cbiAgICAgIDx0aW55LWdyaWQtY29sdW1uIGZpZWxkPVwiY3JlYXRlZERhdGVcIiB0aXRsZT1cIuWIm+W7uuaXtumXtFwiPjwvdGlueS1ncmlkLWNvbHVtbj5cbiAgICAgIDx0aW55LWdyaWQtY29sdW1uIGZpZWxkPVwiZW1wbG95ZWVzXCIgdGl0bGU9XCLkurrmlbBcIj48L3RpbnktZ3JpZC1jb2x1bW4+XG4gICAgICA8dGlueS1ncmlkLWNvbHVtbiBmaWVsZD1cImludHJvZHVjdGlvblwiIHRpdGxlPVwi5YWs5Y+4566A5LuLXCI+PC90aW55LWdyaWQtY29sdW1uPlxuICAgIDwvdGlueS1ncmlkPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cImpzeFwiPlxuaW1wb3J0IHsgR3JpZCwgR3JpZENvbHVtbiwgTW9kYWwgfSBmcm9tICdAb3BlbnRpbnkvdnVlJ1xuaW1wb3J0IHsgYWxlcnQgfSBmcm9tICdAb3BlbnRpbnkvdnVlLW1vZGFsJ1xuXG5leHBvcnQgZGVmYXVsdCB7XG4gIGNvbXBvbmVudHM6IHtcbiAgICBUaW55R3JpZDogR3JpZCxcbiAgICBUaW55R3JpZENvbHVtbjogR3JpZENvbHVtblxuICB9LFxuICBkYXRhKCkge1xuICAgIHJldHVybiB7XG4gICAgICBoZWFkZXJNZW51czogW1xuICAgICAgICBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgY29kZTogJ2V4cG9ydEFsbCcsXG4gICAgICAgICAgICBuYW1lOiAn5a+85Ye65omA5pyJLmNzdicsXG4gICAgICAgICAgICB2aXNpYmxlOiB0cnVlLFxuICAgICAgICAgICAgZGlzYWJsZWQ6IGZhbHNlXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICBjb2RlOiAnaW1wb3J0QWxsJyxcbiAgICAgICAgICAgIG5hbWU6ICflr7zlhaXmiYDmnIkuY3N2JyxcbiAgICAgICAgICAgIHZpc2libGU6IHRydWUsXG4gICAgICAgICAgICBkaXNhYmxlZDogZmFsc2VcbiAgICAgICAgICB9XG4gICAgICAgIF1cbiAgICAgIF0sXG5cbiAgICAgIHRhYmxlRGF0YTogW1xuICAgICAgICB7XG4gICAgICAgICAgaWQ6ICcxJyxcbiAgICAgICAgICBuYW1lOiAnR0ZE56eR5oqAWVjlhazlj7gnLFxuICAgICAgICAgIHVzZXJJZDogNDIxMDAwMTAzNjI0MTgzLFxuICAgICAgICAgIGFyZWE6ICfljY7kuJzljLonLFxuICAgICAgICAgIHByb3ZpbmNlOiAn56aP5bu655yBJyxcbiAgICAgICAgICBjaXR5OiAn56aP5beeJyxcbiAgICAgICAgICBjb250YWN0OiAn6K6455SfJyxcbiAgICAgICAgICB0ZWxlcGhvbmU6ICcxMjM0NTY3ODkwJyxcbiAgICAgICAgICBhZGRyZXNzOiAn56aP5beeJyxcbiAgICAgICAgICBpcGFkZHJlc3M6ICcxOTIuMTY4LjExMS4xMTEnLFxuICAgICAgICAgIGludHJvZHVjdGlvbjogJ+WFrOWPuOaKgOacr+WSjOeglOWPkeWunuWKm+mbhOWOmu+8jOaYr+WbveWutjg2M+mhueebrueahOWPguS4juiAhe+8jOW5tuiiq+aUv+W6nOiupOWumuS4uuKAnOmrmOaWsOaKgOacr+S8geS4muKAneOAgicsXG4gICAgICAgICAgZW1wbG95ZWVzOiA4MDAsXG4gICAgICAgICAgY3JlYXRlZERhdGU6ICcyMDE0LTA0LTMwIDAwOjU2OjAwJyxcbiAgICAgICAgICBib29sZTogZmFsc2UsXG4gICAgICAgICAgYXNzZXRzOiAnMTAwMDAwMCcsXG4gICAgICAgICAgcmF0ZTogMC45XG4gICAgICAgIH0sXG4gICAgICAgIHtcbiAgICAgICAgICBpZDogJzInLFxuICAgICAgICAgIG5hbWU6ICdXV1fnp5HmioBZWOWFrOWPuCcsXG4gICAgICAgICAgdXNlcklkOiA0MjEwMDAxMDM2MjQxODMsXG4gICAgICAgICAgYXJlYTogJ+WNjuWNl+WMuicsXG4gICAgICAgICAgcHJvdmluY2U6ICflub/kuJznnIEnLFxuICAgICAgICAgIGNpdHk6ICfmt7HlnLMnLFxuICAgICAgICAgIGNvbnRhY3Q6ICfmnLHnlJ8nLFxuICAgICAgICAgIHRlbGVwaG9uZTogJzEyMzQ1Njc4OTAnLFxuICAgICAgICAgIGFkZHJlc3M6ICfmt7HlnLPnpo/nlLDljLonLFxuICAgICAgICAgIGlwYWRkcmVzczogJzE5Mi4xNjguMTExLjEnLFxuICAgICAgICAgIGludHJvZHVjdGlvbjogJ+WFrOWPuOaKgOacr+WSjOeglOWPkeWunuWKm+mbhOWOmu+8jOaYr+WbveWutjg2M+mhueebrueahOWPguS4juiAhe+8jOW5tuiiq+aUv+W6nOiupOWumuS4uuKAnOmrmOaWsOaKgOacr+S8geS4muKAneOAgicsXG4gICAgICAgICAgZW1wbG95ZWVzOiAzMDAsXG4gICAgICAgICAgY3JlYXRlZERhdGU6ICcyMDE2LTA3LTA4IDEyOjM2OjIyJyxcbiAgICAgICAgICBib29sZTogdHJ1ZSxcbiAgICAgICAgICBhc3NldHM6ICcxNTAwMDAwJyxcbiAgICAgICAgICByYXRlOiAwLjdcbiAgICAgICAgfSxcbiAgICAgICAge1xuICAgICAgICAgIGlkOiAnMycsXG4gICAgICAgICAgbmFtZTogJ1JGVuaciemZkOi0o+S7u+WFrOWPuCcsXG4gICAgICAgICAgdXNlcklkOiA0NDEwNDc5MTMxNjIzOTYsXG4gICAgICAgICAgYXJlYTogJ+WNjuWNl+WMuicsXG4gICAgICAgICAgcHJvdmluY2U6ICflub/kuJznnIEnLFxuICAgICAgICAgIGNpdHk6ICfkuK3lsbEnLFxuICAgICAgICAgIGNvbnRhY3Q6ICfnp6bnlJ8nLFxuICAgICAgICAgIHRlbGVwaG9uZTogJzEyMzQ1Njc4OTAnLFxuICAgICAgICAgIGFkZHJlc3M6ICfkuK3lsbHluIInLFxuICAgICAgICAgIGlwYWRkcmVzczogJzE5Mi4xNjguMTExLjEyMCcsXG4gICAgICAgICAgaW50cm9kdWN0aW9uOiAn5YWs5Y+45oqA5pyv5ZKM56CU5Y+R5a6e5Yqb6ZuE5Y6a77yM5piv5Zu95a62ODYz6aG555uu55qE5Y+C5LiO6ICF77yM5bm26KKr5pS/5bqc6K6k5a6a5Li64oCc6auY5paw5oqA5pyv5LyB5Lia4oCd44CCJyxcbiAgICAgICAgICBlbXBsb3llZXM6IDEzMDAsXG4gICAgICAgICAgY3JlYXRlZERhdGU6ICcyMDE0LTAyLTE0IDE0OjE0OjE0JyxcbiAgICAgICAgICBib29sZTogZmFsc2UsXG4gICAgICAgICAgYXNzZXRzOiAnMTUwMDAwMCcsXG4gICAgICAgICAgcmF0ZTogMC42XG4gICAgICAgIH0sXG4gICAgICAgIHtcbiAgICAgICAgICBpZDogJzQnLFxuICAgICAgICAgIG5hbWU6ICdUR0Lnp5HmioBZWOWFrOWPuCcsXG4gICAgICAgICAgdXNlcklkOiA3MDI5NzM4OTAwNTUwODgsXG4gICAgICAgICAgYXJlYTogJ+WNjuS4nOWMuicsXG4gICAgICAgICAgcHJvdmluY2U6ICfnpo/lu7rnnIEnLFxuICAgICAgICAgIGNpdHk6ICfpvpnlsqknLFxuICAgICAgICAgIGNvbnRhY3Q6ICflkajnlJ8nLFxuICAgICAgICAgIHRlbGVwaG9uZTogJzEyMzQ1Njc4OTAnLFxuICAgICAgICAgIGFkZHJlc3M6ICfpvpnlsqknLFxuICAgICAgICAgIGlwYWRkcmVzczogJzE5Mi4xNjguMTEuMTExJyxcbiAgICAgICAgICBpbnRyb2R1Y3Rpb246ICflhazlj7jmioDmnK/lkoznoJTlj5Hlrp7lipvpm4TljprvvIzmmK/lm73lrrY4NjPpobnnm67nmoTlj4LkuI7ogIXvvIzlubbooqvmlL/lupzorqTlrprkuLrigJzpq5jmlrDmioDmnK/kvIHkuJrigJ3jgIInLFxuICAgICAgICAgIGVtcGxveWVlczogMzYwLFxuICAgICAgICAgIGNyZWF0ZWREYXRlOiAnMjAxMy0wMS0xMyAxMzoxMzoxMycsXG4gICAgICAgICAgYm9vbGU6IHRydWUsXG4gICAgICAgICAgYXNzZXRzOiAnMTIwMDAwMCcsXG4gICAgICAgICAgcmF0ZTogMC41XG4gICAgICAgIH0sXG4gICAgICAgIHtcbiAgICAgICAgICBpZDogJzUnLFxuICAgICAgICAgIG5hbWU6ICdZSE7np5HmioBZWOWFrOWPuCcsXG4gICAgICAgICAgdXNlcklkOiA3MDI5NzM4OTAwNTUwODgsXG4gICAgICAgICAgYXJlYTogJ+WNjuWNl+WMuicsXG4gICAgICAgICAgcHJvdmluY2U6ICflub/kuJznnIEnLFxuICAgICAgICAgIGNpdHk6ICfpn7blhbMnLFxuICAgICAgICAgIGNvbnRhY3Q6ICfpg5HnlJ8nLFxuICAgICAgICAgIHRlbGVwaG9uZTogJzEyMzQ1Njc4OTAnLFxuICAgICAgICAgIGFkZHJlc3M6ICfpn7blhbMnLFxuICAgICAgICAgIGlwYWRkcmVzczogJzE5Mi4xNjguMTAxLjExMScsXG4gICAgICAgICAgaW50cm9kdWN0aW9uOiAn5YWs5Y+45oqA5pyv5ZKM56CU5Y+R5a6e5Yqb6ZuE5Y6a77yM5piv5Zu95a62ODYz6aG555uu55qE5Y+C5LiO6ICF77yM5bm26KKr5pS/5bqc6K6k5a6a5Li64oCc6auY5paw5oqA5pyv5LyB5Lia4oCd44CCJyxcbiAgICAgICAgICBlbXBsb3llZXM6IDgxMCxcbiAgICAgICAgICBjcmVhdGVkRGF0ZTogJzIwMTItMTItMTIgMTI6MTI6MTInLFxuICAgICAgICAgIGJvb2xlOiB0cnVlLFxuICAgICAgICAgIGFzc2V0czogJzE1MDAwMDAnLFxuICAgICAgICAgIHJhdGU6IDAuNlxuICAgICAgICB9XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBtZXRob2RzOiB7XG4gICAgdmlzaWJsZU1ldGhvZCh7IG9wdGlvbnMsIGNvbHVtbiB9KSB7XG4gICAgICBjb25zdCBpc1Zpc2libGUgPSBjb2x1bW4gJiYgKGNvbHVtbi5wcm9wZXJ0eSA9PT0gJ25hbWUnIHx8IGNvbHVtbi5wcm9wZXJ0eSA9PT0gJ2FyZWEnIHx8IGNvbHVtbi5wcm9wZXJ0eSA9PT0gJ3RlbGVwaG9uZScpXG4gICAgICBjb25zdCBpc0Rpc2FibGVkID0gIWNvbHVtbiB8fCBjb2x1bW4ucHJvcGVydHkgIT09ICdhcmVhJ1xuICAgICAgb3B0aW9ucy5mb3JFYWNoKChsaXN0KSA9PiB7XG4gICAgICAgIGxpc3QuZm9yRWFjaCgoaXRlbSkgPT4ge1xuICAgICAgICAgIGlmICh+WydleHBvcnRBbGwnXS5pbmRleE9mKGl0ZW0uY29kZSkpIHtcbiAgICAgICAgICAgIGl0ZW0uZGlzYWJsZWQgPSBpc0Rpc2FibGVkXG4gICAgICAgICAgfVxuICAgICAgICAgIGl0ZW0udmlzaWJsZSA9IGlzVmlzaWJsZVxuICAgICAgICB9KVxuICAgICAgfSlcbiAgICAgIHJldHVybiB0cnVlXG4gICAgfSxcbiAgICBjb250ZXh0TWVudUNsaWNrRXZlbnQoeyBtZW51LCByb3csIGNvbHVtbiB9KSB7XG4gICAgICBzd2l0Y2ggKG1lbnUuY29kZSkge1xuICAgICAgICBjYXNlICdjb3B5JzpcbiAgICAgICAgICBpZiAocm93ICYmIGNvbHVtbikge1xuICAgICAgICAgICAgTW9kYWwubWVzc2FnZSh7IG1lc3NhZ2U6IGAke3Jvd31gLCBzdGF0dXM6ICdpbmZvJyB9KVxuICAgICAgICAgIH1cbiAgICAgICAgICBicmVha1xuICAgICAgICBkZWZhdWx0OlxuICAgICAgICAgIGFsZXJ0KGDngrnlh7vkuoYgJHttZW51Lm5hbWV9IOmAiemhuWApXG4gICAgICB9XG4gICAgfVxuICB9XG59XG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

报错：
```
Failed to resolve module specifier "@opentiny/vue-modal".
Tip: edit the "Import Map" tab to specify import paths for dependencies.
```

[Grid 表格 - 拖拽](https://opentiny.design/tiny-vue/zh-CN/os-theme/components/grid-drag)
[tinyvue-playground](https://opentiny.github.io/tiny-vue-playground/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPHRpbnktZ3JpZFxuICAgIDpkYXRhPVwidGFibGVEYXRhXCJcbiAgICByb3cta2V5XG4gICAgOmRyb3AtY29uZmlnPVwiZHJvcENvbmZpZ1wiXG4gICAgQHJvdy1kcm9wLWVuZD1cInJvd0Ryb3BFbmRcIlxuICAgIEByb3ctZHJvcC1zdGFydD1cInJvd0Ryb3BTdGFydFwiXG4gICAgQHJvdy1kcm9wLW1vdmU9XCJyb3dEcm9wTW92ZVwiXG4gID5cbiAgICA8dGlueS1ncmlkLWNvbHVtbiB0eXBlPVwiaW5kZXhcIiB3aWR0aD1cIjYwXCI+PC90aW55LWdyaWQtY29sdW1uPlxuICAgIDx0aW55LWdyaWQtY29sdW1uIGZpZWxkPVwibmFtZVwiIHRpdGxlPVwi5YWs5Y+45ZCN56ewXCI+PC90aW55LWdyaWQtY29sdW1uPlxuICAgIDx0aW55LWdyaWQtY29sdW1uIGZpZWxkPVwiZW1wbG95ZWVzXCIgdGl0bGU9XCLlkZjlt6XmlbBcIj48L3RpbnktZ3JpZC1jb2x1bW4+XG4gICAgPHRpbnktZ3JpZC1jb2x1bW4gZmllbGQ9XCJjcmVhdGVkRGF0ZVwiIHRpdGxlPVwi5Yib5bu65pel5pyfXCI+PC90aW55LWdyaWQtY29sdW1uPlxuICAgIDx0aW55LWdyaWQtY29sdW1uIGZpZWxkPVwiY2l0eVwiIHRpdGxlPVwi5Z+O5biCXCI+PC90aW55LWdyaWQtY29sdW1uPlxuICA8L3RpbnktZ3JpZD5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cImpzeFwiPlxuaW1wb3J0IHsgR3JpZCwgR3JpZENvbHVtbiwgTW9kYWwgfSBmcm9tICdAb3BlbnRpbnkvdnVlJ1xuaW1wb3J0IFNvcnRhYmxlIGZyb20gJ3NvcnRhYmxlanMnXG5cbmV4cG9ydCBkZWZhdWx0IHtcbiAgY29tcG9uZW50czoge1xuICAgIFRpbnlHcmlkOiBHcmlkLFxuICAgIFRpbnlHcmlkQ29sdW1uOiBHcmlkQ29sdW1uXG4gIH0sXG4gIGRhdGEoKSB7XG4gICAgcmV0dXJuIHtcbiAgICAgIGRyb3BDb25maWc6IHtcbiAgICAgICAgcGx1Z2luOiBTb3J0YWJsZSxcbiAgICAgICAgcm93OiB0cnVlLFxuICAgICAgICBjb2x1bW46IGZhbHNlIC8vIOWPlua2iOWIl+aLluaLvVxuICAgICAgfSxcbiAgICAgIHRhYmxlRGF0YTogW1xuICAgICAgICB7XG4gICAgICAgICAgaWQ6ICcxJyxcbiAgICAgICAgICBuYW1lOiAnR0ZE56eR5oqAWVjlhazlj7gnLFxuICAgICAgICAgIGNpdHk6ICfnpo/lt54nLFxuICAgICAgICAgIGVtcGxveWVlczogODAwLFxuICAgICAgICAgIGNyZWF0ZWREYXRlOiAnMjAxNC0wNC0zMCAwMDo1NjowMCdcbiAgICAgICAgfSxcbiAgICAgICAge1xuICAgICAgICAgIGlkOiAnMicsXG4gICAgICAgICAgbmFtZTogJ1dXV+enkeaKgFlY5YWs5Y+4JyxcbiAgICAgICAgICBjaXR5OiAn5rex5ZyzJyxcbiAgICAgICAgICBlbXBsb3llZXM6IDMwMCxcbiAgICAgICAgICBjcmVhdGVkRGF0ZTogJzIwMTYtMDctMDggMTI6MzY6MjInXG4gICAgICAgIH0sXG4gICAgICAgIHtcbiAgICAgICAgICBpZDogJzMnLFxuICAgICAgICAgIG5hbWU6ICdSRlbmnInpmZDotKPku7vlhazlj7gnLFxuICAgICAgICAgIGNpdHk6ICfkuK3lsbEnLFxuICAgICAgICAgIGVtcGxveWVlczogMTMwMCxcbiAgICAgICAgICBjcmVhdGVkRGF0ZTogJzIwMTQtMDItMTQgMTQ6MTQ6MTQnXG4gICAgICAgIH0sXG4gICAgICAgIHtcbiAgICAgICAgICBpZDogJzQnLFxuICAgICAgICAgIG5hbWU6ICdUR0Lnp5HmioBZWOWFrOWPuCcsXG4gICAgICAgICAgY2l0eTogJ+m+meWyqScsXG4gICAgICAgICAgZW1wbG95ZWVzOiAzNjAsXG4gICAgICAgICAgY3JlYXRlZERhdGU6ICcyMDEzLTAxLTEzIDEzOjEzOjEzJ1xuICAgICAgICB9LFxuICAgICAgICB7XG4gICAgICAgICAgaWQ6ICc1JyxcbiAgICAgICAgICBuYW1lOiAnWUhO56eR5oqAWVjlhazlj7gnLFxuICAgICAgICAgIGNpdHk6ICfpn7blhbMnLFxuICAgICAgICAgIGVtcGxveWVlczogODEwLFxuICAgICAgICAgIGNyZWF0ZWREYXRlOiAnMjAxMi0xMi0xMiAxMjoxMjoxMidcbiAgICAgICAgfSxcbiAgICAgICAge1xuICAgICAgICAgIGlkOiAnNicsXG4gICAgICAgICAgbmFtZTogJ1dTWOenkeaKgFlY5YWs5Y+4JyxcbiAgICAgICAgICBjaXR5OiAn6buE5YaIJyxcbiAgICAgICAgICBlbXBsb3llZXM6IDgwMCxcbiAgICAgICAgICBjcmVhdGVkRGF0ZTogJzIwMTEtMTEtMTEgMTE6MTE6MTEnXG4gICAgICAgIH0sXG4gICAgICAgIHtcbiAgICAgICAgICBpZDogJzcnLFxuICAgICAgICAgIG5hbWU6ICdLQkfniankuJpZWOWFrOWPuCcsXG4gICAgICAgICAgY2l0eTogJ+i1pOWjgScsXG4gICAgICAgICAgZW1wbG95ZWVzOiA0MDAsXG4gICAgICAgICAgY3JlYXRlZERhdGU6ICcyMDE2LTA0LTMwIDIzOjU2OjAwJ1xuICAgICAgICB9LFxuICAgICAgICB7XG4gICAgICAgICAgaWQ6ICc4JyxcbiAgICAgICAgICBuYW1lOiAn5rex5Zyz5biC56aP5b635a6d572R57uc5oqA5pyvWVjlhazlj7gnLFxuICAgICAgICAgIGNpdHk6ICfljqbpl6gnLFxuICAgICAgICAgIGVtcGxveWVlczogNTQwLFxuICAgICAgICAgIGNyZWF0ZWREYXRlOiAnMjAxNi0wNi0wMyAxMzo1MzoyNSdcbiAgICAgICAgfVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgbWV0aG9kczoge1xuICAgIHJvd0Ryb3BTdGFydCgpIHtcbiAgICAgIE1vZGFsLm1lc3NhZ2UoeyBtZXNzYWdlOiAn6KGM5ouW5ou95byA5aeLJywgc3RhdHVzOiAnaW5mbycgfSlcbiAgICB9LFxuICAgIHJvd0Ryb3BFbmQoKSB7XG4gICAgICBNb2RhbC5tZXNzYWdlKHsgbWVzc2FnZTogJ+ihjOaLluaLvee7k+adnycsIHN0YXR1czogJ2luZm8nIH0pXG4gICAgfSxcbiAgICByb3dEcm9wTW92ZSgpIHtcbiAgICAgIE1vZGFsLm1lc3NhZ2UoeyBtZXNzYWdlOiAn6KGM5ouW5ou956e75YqoJywgc3RhdHVzOiAnaW5mbycgfSlcbiAgICB9XG4gIH1cbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)
```
Failed to resolve module specifier "sortablejs".
Tip: edit the "Import Map" tab to specify import paths for dependencies.
```

### Step to reproduce

如上

**Comment by zzcr** [comment]
新版本官网已修复此问题
