### ISSUE TITLE
🐛 [Bug]: Playground uses vue2 components

### ISSUE THREAD

**Issue by mengqiuleo** [opentiny/tiny-vue#345]
### Version

2.9.0-beta.0

### Vue Version

2.7.13

### Link to minimal reproduction

playground 目前是支持 vue2 的，demo: [vue2 demo](https://opentiny.github.io/tiny-vue-playground/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQ+XG5leHBvcnQgZGVmYXVsdCB7XG4gIGRhdGEoKSB7XG4gICAgcmV0dXJuIHtcbiAgICAgIG1zZzogJ2hlbGxvIHdvcmxkISdcbiAgICB9XG4gIH1cbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG48ZGl2PlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGRpdiBjbGFzcz1cInRpbnl2dWVcIj5cbiAgICA8ZGl2IGNsYXNzPVwidGlueXZ1ZS1wYWdlXCI+XG4gICAgICB0aW55dnVlXG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c3R5bGUgbGFuZz1cImxlc3NcIiBzY29wZWQ+XG4gIGgxe1xuICAgIGNvbG9yOiM1ZTdjZTA7XG4gIH1cbiAgLnRpbnl2dWV7XG4gICAgZm9udC1zaXplOiAxOHhwO1xuICAgICYtcGFnZXtcbiAgICAgIGNvbG9yOiM1ZTdjZTA7XG4gICAgfVxuICB9XG48L3N0eWxlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)   使用版本：vue: 2.7.13,  tinyvue: 2.9.0-beta.0

当引入 tinyvue 组件时报错：
demo: [vue2+tinyvue demo](https://opentiny.github.io/tiny-vue-playground/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQ+XG4vLyDlvJXlhaUgQG9wZW50aW55L3Z1ZSDnu4Tku7ZcbmltcG9ydCB7IEJ1dHRvbiwgTGluayB9IGZyb20gJ0BvcGVudGlueS92dWUnXG5cbmV4cG9ydCBkZWZhdWx0IHtcbiAgY29tcG9uZW50czoge1xuICAgIFRpbnlCdXR0b246IEJ1dHRvbixcbiAgICBUaW55TGluazogTGlua1xuICB9LFxuICBkYXRhKCkge1xuICAgIHJldHVybiB7XG4gICAgICBtc2c6ICdoZWxsbyB3b3JsZCEnXG4gICAgfVxuICB9XG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuPGRpdj5cbiAgPFRpbnlCdXR0b24+56Gu5a6aPC9UaW55QnV0dG9uPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGRpdiBjbGFzcz1cInRpbnl2dWVcIj5cbiAgICA8ZGl2IGNsYXNzPVwidGlueXZ1ZS1wYWdlXCI+XG4gICAgICB0aW55dnVlXG4gICAgICA8dGlueS1saW5rIHR5cGU9XCJzdWNjZXNzXCIgaHJlZj0naHR0cHM6Ly9naXRodWIuY29tL29wZW50aW55L3RpbnktdnVlJz5cbiAgICAgICAgdGlueXZ1ZVxuICAgICAgPC90aW55LWxpbms+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c3R5bGUgbGFuZz1cImxlc3NcIiBzY29wZWQ+XG4gIGgxe1xuICAgIGNvbG9yOiM1ZTdjZTA7XG4gIH1cbiAgLnRpbnl2dWV7XG4gICAgZm9udC1zaXplOiAxOHhwO1xuICAgICYtcGFnZXtcbiAgICAgIGNvbG9yOiM1ZTdjZTA7XG4gICAgfVxuICB9XG48L3N0eWxlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)   使用版本：vue: 2.7.13,  tinyvue: 2.9.0-beta.0

报错信息：
```
Cannot read properties of undefined (reading 'tiny_mode')
```

### Step to reproduce

如上

**Comment by kagol** [comment]
@mengqiuleo 你使用 vue@2.6.14 版本试试看行不行，2.7版本目前还不支持

**Comment by mengqiuleo** [comment]
vue@2.6 版本可以使用，[vue2.6.9-demo](https://opentiny.github.io/tiny-vue-playground/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQ+XG4vLyDlvJXlhaUgQG9wZW50aW55L3Z1ZSDnu4Tku7ZcbmltcG9ydCB7IEJ1dHRvbiwgTGluayB9IGZyb20gJ0BvcGVudGlueS92dWUnXG5cbmV4cG9ydCBkZWZhdWx0IHtcbiAgY29tcG9uZW50czoge1xuICAgIFRpbnlCdXR0b246IEJ1dHRvbixcbiAgICBUaW55TGluazogTGlua1xuICB9LFxuICBkYXRhKCkge1xuICAgIHJldHVybiB7XG4gICAgICBtc2c6ICdoZWxsbyB3b3JsZCEnXG4gICAgfVxuICB9XG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuPGRpdj5cbiAgPHRpbnktYnV0dG9uPuehruWumjwvdGlueS1idXR0b24+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZGl2IGNsYXNzPVwidGlueXZ1ZVwiPlxuICAgIDxkaXYgY2xhc3M9XCJ0aW55dnVlLXBhZ2VcIj5cbiAgICAgIHRpbnl2dWVcbiAgICAgIDx0aW55LWxpbmsgdHlwZT1cInN1Y2Nlc3NcIiBocmVmPSdodHRwczovL2dpdGh1Yi5jb20vb3BlbnRpbnkvdGlueS12dWUnPlxuICAgICAgICB0aW55dnVlXG4gICAgICA8L3RpbnktbGluaz5cbiAgICA8L2Rpdj5cbiAgPC9kaXY+XG48L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzdHlsZSBsYW5nPVwibGVzc1wiIHNjb3BlZD5cbiAgaDF7XG4gICAgY29sb3I6IzVlN2NlMDtcbiAgfVxuICAudGlueXZ1ZXtcbiAgICBmb250LXNpemU6IDE4eHA7XG4gICAgJi1wYWdle1xuICAgICAgY29sb3I6IzVlN2NlMDtcbiAgICB9XG4gIH1cbjwvc3R5bGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)   使用版本：vue: 2.6.9, tinyvue: 2.9.0-beta.0
