### ISSUE TITLE
✨ [Feature]: Please provide Divider component

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-vue#354]
### What problem does this feature solve

The divider is a common component. It is expected to provide a divider component similar to the divider component in elementUI.
https://element.eleme.cn/#/en-US/component/divider

### What does the proposed API look like

For details, see the divider component in elementUI.
https://element.eleme.cn/#/zh-CN/component/divider

---

### What problem does this feature solve

分隔线是一个很常用的组件，希望提供一个类似elementUI里的divider组件
https://element.eleme.cn/#/zh-CN/component/divider

### What does the proposed API look like

可以参考elementUI里的divider组件
https://element.eleme.cn/#/zh-CN/component/divider

**Comment by vaebe** [comment]
I can, within two weeks at the latest.

**Comment by kagol** [comment]
> I can, within two weeks at the latest.

Welcome~

**Comment by kagol** [comment]
Finished by @vaebe on #471
