### ISSUE TITLE
✨ [Feature]: Please provide Skeleton component

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-vue#355]
### What problem does this feature solve

The Skeleton component is generally used to notify the user that data is being loaded. Compared with the Loading component, the Skeleton component can describe a general outline of the content to be loaded, and provide a psychological expectation to the user, thereby improving user experience.

### What does the proposed API look like

You can refer to the Skeleton component of the ElementUI.
https://element-plus.gitee.io/en-US/component/skeleton.html

The ability to provide fine-grained splicing. Rounds and squares allow users to splic themselves to improve component flexibility.

---

### What problem does this feature solve

骨架屏组件一般用于提示用户数据正在加载中，相比Loading组件，Skeleton能够描述即将加载的内容的大致轮廓，给用户一个心理预期，从而提升用户体验。

### What does the proposed API look like

可以参考ElementUI的Skeleton组件：
https://element-plus.gitee.io/zh-CN/component/skeleton.html

做好能提供细粒度拼接的能力，圆形、方形可以让使用者自己拼接，提升组件灵活性。

**Comment by kagol** [comment]
已开发

**Comment by mengqiuleo** [comment]
认领 Skeleton 组件~

**Comment by kagol** [comment]
Finished by @mengqiuleo on #1345, and released in v3.14.0
