### ISSUE TITLE
✨ [Feature]: Please provide ColorPicker component

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-vue#356]
### What problem does this feature solve

ColorPicker allows you to quickly select colors.

### What does the proposed API look like

You can refer to the ColorPicker component of ElementUI.

https://element-plus.gitee.io/en-US/component/color-picker.html

It is best to support the use and splicing of the color selection panel alone, providing greater flexibility for the user.

---

### What problem does this feature solve

ColorPicker可用于快捷选择颜色。

### What does the proposed API look like

可以参考ElementUI的ColorPicker组件：
https://element-plus.gitee.io/zh-CN/component/color-picker.html

最好能支持颜色选择面板单独使用和拼接，为用户提供更大的灵活性

**Comment by GaoNeng-wWw** [comment]
I will fulfill this requirement

**Comment by kagol** [comment]
> I will fulfill this requirement

Welcome @GaoNeng-wWw to participate in ColorPicker component contribution👏

**Comment by kagol** [comment]
已开发
