### ISSUE TITLE
🐛 [Bug]: Form overflow

### ISSUE THREAD

**Issue by bruce000526** [opentiny/tiny-vue#359]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

![image](https://github.com/opentiny/tiny-vue/assets/68933019/2b961693-212d-4f59-9bd8-a2040cc690aa)

### Step to reproduce

TinaPro点击左侧表单页，选择分布表单，逐步创建后，表单溢出
![image](https://github.com/opentiny/tiny-vue/assets/68933019/2f523a57-8b2b-4acb-9691-798b94b0bd5d)

### What is expected

不要溢出
![image](https://github.com/opentiny/tiny-vue/assets/68933019/c44391c0-4fa2-4bf8-b7ab-4e16878291da)

**Comment by gimmyhehe** [comment]
已修复，更新到3.11.0即可~

**Comment by gimmyhehe** [comment]
感谢您对组件库的关注和支持，描述的问题看起来是tiny-cli的问题，欢迎到https://github.com/opentiny/tiny-cli/issues 提issue
