### ISSUE TITLE
✨ [Feature]: Please provide bpmn process designer component

### ISSUE THREAD

**Issue by hg-developer** [opentiny/tiny-vue#363]
### What problem does this feature solve

有考虑支持bpmn流程设计器组件么，强烈建议支持一下

### What does the proposed API look like

有考虑支持bpmn流程设计器组件么，强烈建议支持一下

**Comment by kagol** [comment]
@hg-developer 可否提供下效果图呢？谢谢

**Comment by kagol** [comment]
参考：https://bpmn.io/toolkit/bpmn-js/

**Comment by qq1037305420** [comment]
这东西与业务耦合，集成到组件库有什么作用呢？
