### ISSUE TITLE
🐛 [Bug]: Animation of closing `Drawer`

### ISSUE THREAD

**Issue by AuroraTea** [opentiny/tiny-vue#367]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://opentiny.design/tiny-vue/zh-CN/os-theme/components/drawer

The official documentation shows that.

### Step to reproduce

Click '打开抽屉'.
Close via 'x' and mask both will trigger.

### What is actually happening

The mask disappears first, then the drawer.
![OpenTiny Drawer](https://github.com/opentiny/tiny-vue/assets/43649460/334379a9-d5d0-4ddb-8d97-628b970f02f6)

**Comment by kagol** [comment]
@AuroraTea 该问题已修复
