### ISSUE TITLE
🐛 [Bug]: 【badge】Content is displayed repeatedly

### ISSUE THREAD

**Issue by lyx-jay** [opentiny/tiny-vue#381]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://opentiny.design/tiny-vue/zh-CN/os-theme/components/badge

### Step to reproduce

see as below:
<img width="971" alt="image" src="https://github.com/opentiny/tiny-vue/assets/39766860/ddd2de28-1162-434e-be8d-2c18636660e3">

### What is expected

content is displayed once

### What is actually happening

same content is displayed twice

**Comment by kagol** [comment]
Fixed by @lyx-jay on #382
