### ISSUE TITLE
✨ [Feature]: You can consider lengthening the animation of the drawer, and then closing the mask is actually faster than the drawer💨

### ISSUE THREAD

**Issue by bossbaba** [opentiny/tiny-vue#389]
### What problem does this feature solve

可以考虑把drawer的动画加长一丢丢，然后是mask的关闭居然比drawer还快💨

### What does the proposed API look like

可以考虑把drawer的动画加长一丢丢，然后是mask的关闭居然比drawer还快💨

**Comment by kagol** [comment]
@bossbaba 
#mask的关闭居然比drawer还快
这个问题已经解决啦

**Comment by kagol** [comment]
该问题已修复，可以在官网体验：https://opentiny.design/tiny-vue/zh-CN/os-theme/components/drawer
