### ISSUE TITLE
🐛 [Bug]: Click edit in the table and the pop-up modal will do nothing. Then click the upper right corner to close. The value of the field in the table is gone.

### ISSUE THREAD

**Issue by labike** [opentiny/tiny-vue#396]
### Version

"@opentiny/vue": "^3.6.8",

### Vue Version

"vue": "^3.2.31",

### Link to minimal reproduction

https://github.com/opentiny/tiny-vue/assets/15871933/77e9cbbd-4496-4505-a82d-0b822870cd07

### Step to reproduce

1. 通过tiny-form创建表单，生成table数据
2. 点击table中的编辑按钮弹出modal框
3. 将点击的table row数据回填至modal框中，modal框中的form表单和创建时的一样，比如创建时const createRoleForm = reactive({});回填时也是直接赋值给createRoleForm
4. 什么都不操作直接点击modal右上角关闭;
5. 发现table数据中某个字段的值没了

**Comment by zzcr** [comment]
我猜想应该是你对表格行数据row进行了v-model的双向绑定，当弹窗关闭的时候v-model的值变成了空，所以就清空了~~
