### ISSUE TITLE
🐛 [Bug]: There is a problem with the description of process.env in the official website document, causing the project to fail to start.

### ISSUE THREAD

**Issue by Zhang-qiuxian** [opentiny/tiny-vue#423]
### Version

lastest

### Vue Version

lastest

### Link to minimal reproduction

 用大半天的时间来找这个bug无论怎么设置都无法处理这个报错，TINYModal.tiny_mode = process.env.TINY_MODE || tinyMode && tinyMode.value;
我都跟着[官网示例](https://opentiny.design/tiny-vue/zh-CN/os-theme/docs/develop-demo)直接copy一步步来都未能解决这个报错。

### Step to reproduce

重试n次也是如此

**Comment by zzcr** [comment]
不好意思，官网配置有点问题，我们会尽快更新文档，
正确的配置是： 
```
define: {
  'process.env ': { ...process.env }
}
```
