### ISSUE TITLE
✨ [Feature]: It is recommended to add volar.d.ts and component resolvers

### ISSUE THREAD

**Issue by silentmx** [opentiny/tiny-vue#432]
### What problem does this feature solve

1. 在组件使用过程中缺少组件props类型提示,可以通过添加volar.d.ts配合vue3 volar插件使用

![image](https://github.com/opentiny/tiny-vue/assets/19500024/92353a87-a147-476a-ab85-835a617cdee7)

2. 组件按需加载可以添加unplugin-vue-components插件的ComponentResolver使用，而不必再添加@opentiny/vue-vite-import
```
// https://github.com/antfu/unplugin-vue-components
Components({
  // allow auto load markdown components under `./src/components/`
  extensions: ['vue', 'md'],
  // allow auto import and register components used in markdown
  include: [/\.vue$/, /\.vue\?vue/, /\.md$/],
  dts: 'src/components.d.ts',
  resolvers: [
    // OpenTiny component resolve
    {
      type: "component",
      resolve: (name: string) => {
        if (name.match(/^Tiny[A-Z]|tiny-[a-z]/)) {
          return {
            name: name.replace(/[Tt]iny/, ""),
            as: name,
            from: "@opentiny/vue"
          }
        }
      }
    }
  ]
}),
```

### What does the proposed API look like

暴露volar.d.ts和ComponentResolver

**Comment by zzcr** [comment]
您好，感谢你的意见，我们内部评估下~~

**Comment by shenjunjian** [comment]
1、组件的属性事件声明缺少， 我们最近也在找方案，在确定之后会补全声明 
2、我们暴露的插件其实就是对 unplugin-vue-components 的封装，是和你的方法一样的。 
     封装后能减少用户自行配转unplugin-vue-components。
