### ISSUE TITLE
🐛 [Bug]: The time picker placed in the modal will not open the modal under certain circumstances.

### ISSUE THREAD

**Issue by sugers** [opentiny/tiny-vue#443]
### Version

"@opentiny/vue": "^2.10.0",

### Vue Version

"vue": "^2.6.14",

### Link to minimal reproduction

`<div class="strategy_creatuser_content" v-show="jsvalue==2">
                            <tiny-time-picker
                                  size="small"
                                  is-range
                                  v-model="strategyParams.timeslot"
                                  range-separator="至"
                                  start-placeholder="开始时间"
                                  end-placeholder="结束时间"
                                  placeholder="选择时间范围"
                                ></tiny-time-picker>
                        </div>`

### Step to reproduce

**情况一：把上面的代码放在弹窗tiny-modal之后，首先说明：该弹窗一直处于显示状态，没有添加任何条件控制显隐**
1：如果类名strategy_creatuser_content这个盒子添加v-show或者v-if之后，点击按钮，控制台html是添加了这个弹窗，但是页面没有显示出来。
2：如果类名strategy_creatuser_content这个盒子没有添加v-show或者v-if，点击按钮,该弹窗也不会正常显示出来

**情况二：把上面的代码放在弹窗tiny-modal之后，首先说明：该弹窗添加了条件控制显隐**
1：如果类名strategy_creatuser_content这个盒子添加v-show或者v-if之后，点击按钮，控制台html是添加了这个弹窗，但是页面没有显示出来。
2：如果类名strategy_creatuser_content这个盒子没有添加v-show或者v-if，点击按钮,该弹窗正常显示出来,但是在选择时间之后，该弹窗便会自动消失，再点击按钮的时候，弹窗也无反应

**Comment by sugers** [comment]
@kagol @

**Comment by GaoNeng-wWw** [comment]
更新到最新也会是这样吗? 3.10.0 无法复现

<details><summary>Playground</summary>
https://opentiny.design/tiny-vue/playground#3.10.0|eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgbGFuZz1cInRzeFwiPlxyXG4vLyDlvJXlhaUgQG9wZW50aW55L3Z1ZSDnu4Tku7ZcclxuaW1wb3J0IHsgQnV0dG9uLCBMaW5rIH0gZnJvbSAnQG9wZW50aW55L3Z1ZSdcclxuXHJcbmV4cG9ydCBkZWZhdWx0IHtcclxuICBjb21wb25lbnRzOiB7XHJcbiAgICBUaW55QnV0dG9uOiBCdXR0b24sXHJcbiAgICBUaW55TGluazogTGlua1xyXG4gIH0sXHJcbiAgZGF0YSgpIHtcclxuICAgIHJldHVybiB7XHJcbiAgICAgIG1zZzogJ2hlbGxvIHdvcmxkISdcclxuICAgIH1cclxuICB9XHJcbn1cclxuPC9zY3JpcHQ+XHJcblxyXG48dGVtcGxhdGU+XHJcbiAgPFRpbnlCdXR0b24+56Gu5a6aPC9UaW55QnV0dG9uPlxyXG4gIDxoMT57eyBtc2cgfX08L2gxPlxyXG4gIDxkaXYgY2xhc3M9XCJ0aW55dnVlXCI+XHJcbiAgICA8ZGl2IGNsYXNzPVwidGlueXZ1ZS1wYWdlXCI+XHJcbiAgICAgIHRpbnl2dWVcclxuICAgICAgPHRpbnktbGluayB0eXBlPVwic3VjY2Vzc1wiIGhyZWY9J2h0dHBzOi8vZ2l0aHViLmNvbS9vcGVudGlueS90aW55LXZ1ZSc+XHJcbiAgICAgICAgdGlueXZ1ZVxyXG4gICAgICA8L3RpbnktbGluaz5cclxuICAgIDwvZGl2PlxyXG4gIDwvZGl2PlxyXG48L3RlbXBsYXRlPlxyXG5cclxuPHN0eWxlIGxhbmc9XCJsZXNzXCIgc2NvcGVkPlxyXG4gIGgxe1xyXG4gICAgY29sb3I6IzVlN2NlMDtcclxuICB9XHJcbiAgLnRpbnl2dWV7XHJcbiAgICBmb250LXNpemU6IDE4eHA7XHJcbiAgICAmLXBhZ2V7XHJcbiAgICAgIGNvbG9yOiM1ZTdjZTA7XHJcbiAgICB9XHJcbiAgfVxyXG48L3N0eWxlPlxyXG4iLCIiOiJ7XCJpbXBvcnRzXCI6e1wiQG9wZW50aW55L3Z1ZVwiOlwiaHR0cHM6Ly91bnBrZy5jb20vQG9wZW50aW55L3Z1ZUAzLjEwLjAvcnVudGltZS90aW55LXZ1ZS5tanNcIixcIkBvcGVudGlueS92dWUtaWNvblwiOlwiaHR0cHM6Ly91bnBrZy5jb20vQG9wZW50aW55L3Z1ZUAzLjEwLjAvcnVudGltZS90aW55LXZ1ZS1pY29uLm1qc1wiLFwiQG9wZW50aW55L3Z1ZS1sb2NhbGVcIjpcImh0dHBzOi8vdW5wa2cuY29tL0BvcGVudGlueS92dWVAMy4xMC4wL3J1bnRpbWUvdGlueS12dWUtbG9jYWxlLm1qc1wiLFwiQG9wZW50aW55L3Z1ZS1jb21tb25cIjpcImh0dHBzOi8vdW5wa2cuY29tL0BvcGVudGlueS92dWVAMy4xMC4wL3J1bnRpbWUvdGlueS12dWUtY29tbW9uLm1qc1wiLFwic29ydGFibGVqc1wiOlwiaHR0cHM6Ly91bnBrZy5jb20vc29ydGFibGVqc0AxLjE1LjAvbW9kdWxhci9zb3J0YWJsZS5lc20uanNcIn19IiwidHNjb25maWcuanNvbiI6IntcclxuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XHJcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcclxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxyXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxyXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcclxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXHJcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXHJcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWVcclxuICB9LFxyXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcclxuICAgIFwidGFyZ2V0XCI6IDMuM1xyXG4gIH1cclxufVxyXG4iLCJiYXNlLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICA8ZGl2IGNsYXNzPVwic3RyYXRlZ3lfY3JlYXR1c2VyX2NvbnRlbnRcIiB2LWlmPVwidmlzaWJsZVwiPlxuICAgICAgPHRpbnktdGltZS1waWNrZXIgc2l6ZT1cInNtYWxsXCIgaXMtcmFuZ2UgcmFuZ2Utc2VwYXJhdG9yPVwi6IezXCIgc3RhcnQtcGxhY2Vob2xkZXI9XCLlvIDlp4vml7bpl7RcIiBlbmQtcGxhY2Vob2xkZXI9XCLnu5PmnZ/ml7bpl7RcIiBwbGFjZWhvbGRlcj1cIumAieaLqeaXtumXtOiMg+WbtFwiID48L3RpbnktdGltZS1waWNrZXI+XG4gICAgPC9kaXY+XG4gICAgPHRpbnktYnV0dG9uIEBjbGljaz1cInZhbHVlMSA9ICF2YWx1ZTFcIiA6cmVzZXQtdGltZT1cIjBcIj4g6buY6K6k5o+S5qe9IDwvdGlueS1idXR0b24+XG4gICAgPHRpbnktbW9kYWwgdi1tb2RlbD1cInZhbHVlMVwiIDpsb2NrLXNjcm9sbD1cImZhbHNlXCIgc2hvdy1mb290ZXI+XG4gICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ+XG4gICAgICAgIDxwIGNsYXNzPVwiY3VzdG9tLWNvbnRlbnRcIj50ZXN0PC9wPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L3RpbnktbW9kYWw+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IFRpbWVQaWNrZXIgYXMgVGlueVRpbWVQaWNrZXIsIE1vZGFsIGFzIFRpbnlNb2RhbCwgQnV0dG9uIGFzIFRpbnlCdXR0b259IGZyb20gJ0BvcGVudGlueS92dWUnO1xuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJztcbmNvbnN0IHZpc2libGUgPSByZWYodHJ1ZSk7XG5jb25zdCB2YWx1ZTEgPSByZWYoZmFsc2UpO1xuPC9zY3JpcHQ+IiwiX28
</details>

**Comment by kagol** [comment]
@sugers 希望能在 [Playground](https://opentiny.github.io/tiny-vue-playground/) 中提供一个最小可复现 demo。
