### ISSUE TITLE
🐛 [Bug]: Tree table is stuck when all checkboxes are selected

### ISSUE THREAD

**Issue by tkggusraqk** [opentiny/tiny-vue#447]
### Version

3.9.1

### Vue Version

3.2.45

### Link to minimal reproduction

tree table 数据量达到2000多行时，全部展开，然后进行全选，很卡。
![test](https://github.com/opentiny/tiny-vue/assets/5164663/b8d632f7-bd82-416a-8eae-76fe0e576a1e)

### Step to reproduce
 ```
<script type="importmap">
    {
      "imports": {
        "vue": "https://unpkg.com/vue@3.2.45/dist/vue.esm-browser.js",
        "@opentiny/vue": "https://unpkg.com/@opentiny/vue@3.9.1/runtime/tiny-vue.mjs",
        "@opentiny/vue-common": "https://unpkg.com/@opentiny/vue@3.9.1/runtime/tiny-vue-common.mjs",
        "@opentiny/vue-icon": "https://unpkg.com/@opentiny/vue@3.9.1/runtime/tiny-vue-icon.mjs",
        "@opentiny/vue-locale": "https://unpkg.com/@opentiny/vue@3.9.1/runtime/tiny-vue-locale.mjs"
      }
    }
  </script>
<link rel="stylesheet" href="https://unpkg.com/@opentiny/vue-theme/index.css" />
    <script src="data.js"></script>
```  
        <tiny-grid ref="grid" height="800" :tree-config="{ children: 'children' }">
            <tiny-grid-column type="index" width="auto"></tiny-grid-column>
            <tiny-grid-column type="selection" width="40"></tiny-grid-column>
            <tiny-grid-column field="deptName" title="部门名称" tree-node width="300"></tiny-grid-column>
            <tiny-grid-column field="departLeader" title="分管领导"></tiny-grid-column>
            <tiny-grid-column field="contactsCount" title="人数"></tiny-grid-column>
            <tiny-grid-column field="tel1" title="电话1"></tiny-grid-column>
            <tiny-grid-column field="ManagerName" title="部门管理员"></tiny-grid-column>
            <tiny-grid-column field="tel2" title="电话2"></tiny-grid-column>
            <tiny-grid-column field="fax" title="传真"></tiny-grid-column>
            <tiny-grid-column field="email" title="邮箱"></tiny-grid-column>
            <tiny-grid-column field="roomNum" title="房间号"></tiny-grid-column>
            <tiny-grid-column field="isHomePageShow" title="显示下级"></tiny-grid-column>
            <tiny-grid-column field="smsSign" title="OA短信签名"></tiny-grid-column>
            <tiny-grid-column field="typeVisableRangeName" title="上报行政级别限制"></tiny-grid-column>
            <tiny-grid-column field="deptTypeName" title="部门类型"></tiny-grid-column>
            <tiny-grid-column field="fileUrl" title="外部跳转"></tiny-grid-column>
        </tiny-grid>
```
<script type="module">
        import { createApp } from "vue";
        import TinyVue from "@opentiny/vue";

        function aggregateTableData(data) {
            const result = []
            data.forEach((item) => {
                if (item.parentId == 0) {
                    result.push(item)
                } else {
                    const parent = data.find((i) => i.id == item.parentId)
                    if (!parent) return
                    if (!parent.children) {
                        parent.children = []
                    }
                    parent.children.push(item)
                }
                delete item.parentId
            })

            return result
        }

        createApp({
            data() {
                return {
                    tableData: aggregateTableData(window.deptData)
                }
            },
            created() {
            },
            mounted() {
                this.$refs.grid.loadData(this.tableData);
                this.$refs.grid.setAllTreeExpansion(true);
            }
        })
            .use(TinyVue)
            .mount('#app');
    </script>
```

**Comment by gweesin** [comment]
Hi there, I noticed that this issue has been open for a month without any progress. Could you please confirm if this issue is still being addressed? If assistance is needed, I'd be happy to take it over.

**Comment by tkggusraqk** [comment]
当前还没有修复，看来只能考虑vtable了

**Comment by zzcr** [comment]
这种大数据场景建议使用树表的虚拟滚动

**Comment by zzcr** [comment]
可以参考此例子：https://opentiny.design/tiny-vue/zh-CN/os-theme/components/grid-large-data#tiny-first-menu-grid-large-tree-data
