### ISSUE TITLE
🐛 [Bug]: tiny-file-upload Can using the remove deletion event support the removal of images from the current list after a second confirmation?

### ISSUE THREAD

**Issue by thestar077** [opentiny/tiny-vue#449]
tiny-file-upload 使用remove删除事件可支持二次确认后再移除当前列表的图片吗?目前文档的效果是点击删除图标，弹出二次确认弹窗的同时，未点击确认删除，当前列表就删除了当前的图片

### Version

3.10.0

### Vue Version

3.2.47

### Link to minimal reproduction

<template>
  <div class="content">
    <tiny-file-upload
      class="upload-demo picture-demo"
      :action="action"
      list-type="picture-card"
      :file-list="fileList"
      @remove="handleRemove"
      @preview="previewPicture"
    >
      <tiny-icon-plus class="tiny-svg-size" />
    </tiny-file-upload>
    <tiny-dialog-box v-model:visible="dialogVisible1" width="50%">
      <img style="width: 100%" :src="dialogImageUrl1" alt="Preview Image" />
    </tiny-dialog-box>
  </div>
</template>

<script setup lang="jsx">
import { ref } from 'vue'
import { FileUpload as TinyFileUpload, DialogBox as TinyDialogBox,Modal } from '@opentiny/vue'
import { iconPlus } from '@opentiny/vue-icon'

const action = ref('http://localhost:3000/api/upload')
const dialogVisible1 = ref(false)
const dialogImageUrl1 = ref('')
const fileList = ref([
  {
    name: 'fruit',
    url: `https://res.hc-cdn.com/tiny-vue-web-doc/3.10.2.20230822140904/static/images/fruit.jpg`
  }
])

const TinyIconPlus = iconPlus()

function previewPicture(file) {
  dialogImageUrl1.value = file.url
  dialogVisible1.value = true
}

function handleRemove(arg1) {
  Modal.confirm("确定删除该图片？").then(res => {
    if (res == "confirm") {
      handleremovePicFile(arg1);
    }
  });
};

</script>

### Step to reproduce

<template>
  <div class="content">
    <tiny-file-upload
      class="upload-demo picture-demo"
      :action="action"
      list-type="picture-card"
      :file-list="fileList"
      @remove="handleRemove"
      @preview="previewPicture"
    >
      <tiny-icon-plus class="tiny-svg-size" />
    </tiny-file-upload>
    <tiny-dialog-box v-model:visible="dialogVisible1" width="50%">
      <img style="width: 100%" :src="dialogImageUrl1" alt="Preview Image" />
    </tiny-dialog-box>
  </div>
</template>

<script setup lang="jsx">
import { ref } from 'vue'
import { FileUpload as TinyFileUpload, DialogBox as TinyDialogBox,Modal } from '@opentiny/vue'
import { iconPlus } from '@opentiny/vue-icon'

const action = ref('http://localhost:3000/api/upload')
const dialogVisible1 = ref(false)
const dialogImageUrl1 = ref('')
const fileList = ref([
  {
    name: 'fruit',
    url: `https://res.hc-cdn.com/tiny-vue-web-doc/3.10.2.20230822140904/static/images/fruit.jpg`
  }
])

const TinyIconPlus = iconPlus()

function previewPicture(file) {
  dialogImageUrl1.value = file.url
  dialogVisible1.value = true
}

function handleRemove(arg1) {
  Modal.confirm("确定删除该图片？").then(res => {
    if (res == "confirm") {
      handleremovePicFile(arg1);
    }
  });
};

</script>

**Comment by chenxi-20** [comment]
remove是监听事件的钩子，并不是上传组件的方法钩子。这个想法逻辑上是不可行的

**Comment by chenxi-20** [comment]
@thestar077

**Comment by chenxi-20** [comment]
@thestar077

**Comment by chenxi-20** [comment]
@thestar077

**Comment by chenxi-20** [comment]
这个可以用before-remove钩子完成自己想要的操作。具体查看一下阻止删除文件的demo示例@thestar077
