### ISSUE TITLE
🐛 [Bug]: If a popover is placed in the form, the prompt will appear twice when the form validation fails.

### ISSUE THREAD

**Issue by duanleping** [opentiny/tiny-vue#452]
### Version

@opentiny/vue@3.10.0

### Vue Version

@opentiny/vue@3.10.0

### Link to minimal reproduction

https://opentiny.design/tiny-vue/playground#3.10.0|eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgbGFuZz1cInRzeFwiPlxyXG4vLyDlvJXlhaUgQG9wZW50aW55L3Z1ZSDnu4Tku7ZcclxuaW1wb3J0IHsgQnV0dG9uLCBMaW5rIH0gZnJvbSAnQG9wZW50aW55L3Z1ZSdcclxuXHJcbmV4cG9ydCBkZWZhdWx0IHtcclxuICBjb21wb25lbnRzOiB7XHJcbiAgICBUaW55QnV0dG9uOiBCdXR0b24sXHJcbiAgICBUaW55TGluazogTGlua1xyXG4gIH0sXHJcbiAgZGF0YSgpIHtcclxuICAgIHJldHVybiB7XHJcbiAgICAgIG1zZzogJ2hlbGxvIHdvcmxkISdcclxuICAgIH1cclxuICB9XHJcbn1cclxuPC9zY3JpcHQ+XHJcblxyXG48dGVtcGxhdGU+XHJcbiAgPFRpbnlCdXR0b24+56Gu5a6aPC9UaW55QnV0dG9uPlxyXG4gIDxoMT57eyBtc2cgfX08L2gxPlxyXG4gIDxkaXYgY2xhc3M9XCJ0aW55dnVlXCI+XHJcbiAgICA8ZGl2IGNsYXNzPVwidGlueXZ1ZS1wYWdlXCI+XHJcbiAgICAgIHRpbnl2dWVcclxuICAgICAgPHRpbnktbGluayB0eXBlPVwic3VjY2Vzc1wiIGhyZWY9J2h0dHBzOi8vZ2l0aHViLmNvbS9vcGVudGlueS90aW55LXZ1ZSc+XHJcbiAgICAgICAgdGlueXZ1ZVxyXG4gICAgICA8L3RpbnktbGluaz5cclxuICAgIDwvZGl2PlxyXG4gIDwvZGl2PlxyXG48L3RlbXBsYXRlPlxyXG5cclxuPHN0eWxlIGxhbmc9XCJsZXNzXCIgc2NvcGVkPlxyXG4gIGgxe1xyXG4gICAgY29sb3I6IzVlN2NlMDtcclxuICB9XHJcbiAgLnRpbnl2dWV7XHJcbiAgICBmb250LXNpemU6IDE4eHA7XHJcbiAgICAmLXBhZ2V7XHJcbiAgICAgIGNvbG9yOiM1ZTdjZTA7XHJcbiAgICB9XHJcbiAgfVxyXG48L3N0eWxlPlxyXG4iLCJzcmMvIjoie1wiaW1wb3J0c1wiOntcIkBvcGVudGlueS92dWVcIjpcImh0dHBzOi8vdW5wa2cuY29tL0BvcGVudGlueS92dWVAMy4xMC4wL3J1bnRpbWUvdGlueS12dWUubWpzXCIsXCJAb3BlbnRpbnkvdnVlLWljb25cIjpcImh0dHBzOi8vdW5wa2cuY29tL0BvcGVudGlueS92dWVAMy4xMC4wL3J1bnRpbWUvdGlueS12dWUtaWNvbi5tanNcIixcIkBvcGVudGlueS92dWUtbG9jYWxlXCI6XCJodHRwczovL3VucGtnLmNvbS9Ab3BlbnRpbnkvdnVlQDMuMTAuMC9ydW50aW1lL3RpbnktdnVlLWxvY2FsZS5tanNcIixcIkBvcGVudGlueS92dWUtY29tbW9uXCI6XCJodHRwczovL3VucGtnLmNvbS9Ab3BlbnRpbnkvdnVlQDMuMTAuMC9ydW50aW1lL3RpbnktdnVlLWNvbW1vbi5tanNcIixcInNvcnRhYmxlanNcIjpcImh0dHBzOi8vdW5wa2cuY29tL3NvcnRhYmxlanNAMS4xNS4wL21vZHVsYXIvc29ydGFibGUuZXNtLmpzXCJ9fSIsInRzY29uZmlnLmpzb24iOiJ7XHJcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xyXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXHJcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcclxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcclxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXHJcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxyXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxyXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlXHJcbiAgfSxcclxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XHJcbiAgICBcInRhcmdldFwiOiAzLjNcclxuICB9XHJcbn1cclxuIiwic3JjL2N1c3RvbS12YWxpZGF0aW9uLXJ1bGUudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZGVtby1mb3JtXCI+XG4gICAgPHRpbnktZm9ybVxuICAgICAgcmVmPVwicnVsZUZvcm1SZWZcIlxuICAgICAgOm1vZGVsPVwiY3JlYXRlRGF0YVwiXG4gICAgICA6cnVsZXM9XCJydWxlc1wiIFxuICAgICAgbGFiZWwtd2lkdGg9XCIxMDBweFwiXG4gICAgICB2YWxpZGF0ZS10eXBlPVwidGlwXCJcbiAgICAgIDppbmxpbmUtbWVzc2FnZT1cInRydWVcIlxuICAgICAgXG4gICAgPlxuICAgICAgPHRpbnktZm9ybS1pdGVtIGxhYmVsPVwi55So5oi35ZCNXCIgcHJvcD1cInVzZXJuYW1lXCI+XG4gICAgICAgIDx0aW55LWlucHV0IHYtbW9kZWw9XCJjcmVhdGVEYXRhLnVzZXJuYW1lXCI+PC90aW55LWlucHV0PlxuICAgICAgPC90aW55LWZvcm0taXRlbT5cbiAgICAgIDx0aW55LWZvcm0taXRlbSBsYWJlbD1cIuWvhueggVwiIHByb3A9XCJwYXNzd29yZFwiPlxuICAgICAgICA8dGlueS1pbnB1dCB2LW1vZGVsPVwiY3JlYXRlRGF0YS5wYXNzd29yZFwiIHR5cGU9XCJwYXNzd29yZFwiIHNob3ctcGFzc3dvcmQ+PC90aW55LWlucHV0PlxuICAgICAgICA8dGlueS1wb3BvdmVyIHBsYWNlbWVudD1cInRvcC1zdGFydFwiIHRpdGxlPVwi5by55Ye65o+Q56S6XCIgd2lkdGg9XCIzMDBcIiB0cmlnZ2VyPVwiaG92ZXJcIj5cbiAgICAgICAgICAgIDx1bD5cbiAgICAgICAgICAgICAgPGxpPuaPkOekuuWGheWuuTwvbGk+XG4gICAgICAgICAgICA8L3VsPlxuICAgICAgICAgICAgPHRlbXBsYXRlICNyZWZlcmVuY2U+XG4gICAgICAgICAgICAgIDxsYWJlbD7lvLnlh7rmj5DnpLo8L2xhYmVsPlxuICAgICAgICAgICAgICA8c3ZnXG4gICAgICAgICAgICAgICAgeG1sbnM9XCJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2Z1wiXG4gICAgICAgICAgICAgICAgdmlld0JveD1cIjAgMCAyNCAyNFwiXG4gICAgICAgICAgICAgICAgeG1sOnNwYWNlPVwicHJlc2VydmVcIlxuICAgICAgICAgICAgICAgIGNsYXNzPVwic3Zncy1pY29uIHRpbnktc3ZnXCJcbiAgICAgICAgICAgICAgICBzdHlsZT1cImZvbnQtc2l6ZTogMTRweDsgbWFyZ2luOiAtNHB4IDVweCAwcHggMHB4XCI+XG4gICAgICAgICAgICAgICAgPHBhdGhcbiAgICAgICAgICAgICAgICAgIGQ9XCJNMTIgMEM1LjQgMCAwIDUuNCAwIDEyczUuNCAxMiAxMiAxMiAxMi01LjQgMTItMTJTMTguNiAwIDEyIDB6bTcuMyAxOS4zYy0uOS45LTIuMSAxLjctMy4zIDIuMi0xLjMuNS0yLjYuOC00IC44cy0yLjctLjMtNC0uOGMtMS4yLS41LTIuMy0xLjMtMy4zLTIuMi0uOS0xLTEuNy0yLjEtMi4yLTMuMy0uNS0xLjMtLjgtMi42LS44LTRzLjMtMi43LjgtNEMzIDYuOCAzLjggNS43IDQuNyA0LjcgNS43IDMuOCA2LjggMyA4IDIuNWMxLjMtLjUgMi42LS44IDQtLjhzMi43LjMgNCAuOGMxLjIuNSAyLjMgMS4zIDMuMyAyLjIuOSAxIDEuNyAyLjEgMi4yIDMuMy41IDEuMy44IDIuNi44IDRzLS4zIDIuNy0uOCA0Yy0uNSAxLjItMS4zIDIuMy0yLjIgMy4zem0tNy40LTMuN3MtLjEgMCAwIDBjLS41IDAtLjktLjUtLjgtLjkuMS0xLjIgMS0yLjEgMS45LTMuMSAxLjUtMS41IDEuNS0yIDEuNi0yLjUgMC0uNi0uMi0xLjItLjYtMS42LS41LS41LTEuMi0uOC0xLjktLjgtMS40IDAtMi41IDEuMS0yLjUgMi41IDAgLjUtLjQuOC0uOC44LS41IDAtLjgtLjQtLjgtLjgtLjItMS4yLjItMi4yIDEtM1MxMC45IDUgMTIgNWMxLjIgMCAyLjMuNSAzLjEgMS4zLjguOCAxLjEgMS44IDEuMSAyLjktLjEgMS4xLS40IDEuOS0yLjEgMy42LS44LjgtMS40IDEuNS0xLjQgMiAwIC40LS40LjgtLjguOHpNMTAuOCAxOGMwIC40LjIuNy41LjkuMy4yLjcuMiAxIDAgLjMtLjIuNS0uNS41LS45IDAtLjYtLjUtMS0xLTFzLTEgLjUtMSAxelwiXG4gICAgICAgICAgICAgICAgICBjbGFzcz1cInN0MFwiPjwvcGF0aD5cbiAgICAgICAgICAgICAgPC9zdmc+XG4gICAgICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICAgIDwvdGlueS1wb3BvdmVyPlxuICAgICAgPC90aW55LWZvcm0taXRlbT5cbiAgICAgIDx0aW55LWZvcm0taXRlbT5cbiAgICAgICAgPHRpbnktYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwiaGFuZGxlU3VibWl0KClcIj4g5rOo5YaMIDwvdGlueS1idXR0b24+XG4gICAgICAgIDx0aW55LWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cInJlbW92ZVBhc3NcIj4g5riF6Zmk5a+G56CB5qCh6aqMIDwvdGlueS1idXR0b24+XG4gICAgICA8L3RpbnktZm9ybS1pdGVtPlxuICAgIDwvdGlueS1mb3JtPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cImpzeFwiPlxuaW1wb3J0IHsgRm9ybSwgRm9ybUl0ZW0sIElucHV0LCBCdXR0b24sIFBvcG92ZXIsTW9kYWwgfSBmcm9tICdAb3BlbnRpbnkvdnVlJ1xuXG5leHBvcnQgZGVmYXVsdCB7XG4gIGNvbXBvbmVudHM6IHtcbiAgICBUaW55Rm9ybTogRm9ybSxcbiAgICBUaW55Rm9ybUl0ZW06IEZvcm1JdGVtLFxuICAgIFRpbnlJbnB1dDogSW5wdXQsXG4gICAgVGlueVBvcG92ZXI6IFBvcG92ZXIsVGlueUJ1dHRvbjogQnV0dG9uXG4gIH0sXG4gIGRhdGEoKSB7XG4gICAgICBsZXQgdmFsaWRhdGVQYXNzID0gKHJ1bGUsIHZhbHVlLCBjYWxsYmFjaykgPT4ge1xuICAgICAgICBpZiAoIS9eKD89LipbYS16XSkoPz0uKltBLVpdKSg/PS4qXFxkKVthLXpBLVpcXGRdezgsfSQvLnRlc3QodmFsdWUpKSB7XG4gICAgICAgICAgY2FsbGJhY2sobmV3IEVycm9yKCfmnIDlsJHlhavkuKrlrZfnrKbvvIzoh7PlsJHljIXlkKvkuIDkuKrlpKflhpnlrZfmr43vvIzkuIDkuKrlsI/lhpnlrZfmr43lkozkuIDkuKrmlbDlrZcnKSlcbiAgICAgICAgfSBlbHNlIHtcbiAgICAgICAgICBpZiAodGhpcy5jcmVhdGVEYXRhLnBhc3N3b3JkICE9PSAnJykge1xuICAgICAgICAgICAgdGhpcy4kcmVmcy5ydWxlRm9ybVJlZi52YWxpZGF0ZUZpZWxkKCdwYXNzd29yZCcpXG4gICAgICAgICAgfVxuICAgICAgICAgIGNhbGxiYWNrKClcbiAgICAgICAgfVxuICAgICAgfVxuXG4gICAgcmV0dXJuIHtcbiAgICAgIGNyZWF0ZURhdGE6IHtcbiAgICAgICAgdXNlcm5hbWU6ICcnLFxuICAgICAgICBwYXNzd29yZDogJydcbiAgICAgIH0sXG4gICAgICBpc3ZhbGlkYXRlOiB0cnVlLFxuICAgICAgcnVsZXM6IHtcbiAgICAgICAgdXNlcm5hbWU6IFtcbiAgICAgICAgICB7IHJlcXVpcmVkOiB0cnVlLCBtZXNzYWdlOiAn5b+F5aGrJywgdHJpZ2dlcjogJ2JsdXInIH0sXG4gICAgICAgICAgeyBtaW46IDIsIG1heDogMTEsIG1lc3NhZ2U6ICfplb/luqblv4XpobvkuI3lsI/kuo4yJywgdHJpZ2dlcjogWydjaGFuZ2UnLCAnYmx1ciddIH1cbiAgICAgICAgXSxcbiAgICAgICAgcGFzc3dvcmQ6IFtcbiAgICAgICAgICB7IHJlcXVpcmVkOiB0cnVlLCBtZXNzYWdlOiAn5b+F5aGrJywgdHJpZ2dlcjogJ2JsdXInIH0sXG4gICAgICAgICAgeyB2YWxpZGF0b3I6IHZhbGlkYXRlUGFzcywgdHJpZ2dlcjogJ2JsdXInIH1cbiAgICAgICAgXVxuICAgICAgfVxuICAgIH1cbiAgfSxcbiAgbWV0aG9kczoge1xuICAgIFxuICAgIGhhbmRsZVN1Ym1pdCgpIHtcbiAgICAgIHRoaXMuJHJlZnMucnVsZUZvcm1SZWYudmFsaWRhdGUoKHZhbGlkKSA9PiB7XG4gICAgICAgIGlmICh2YWxpZCkge1xuICAgICAgICAgIE1vZGFsLmFsZXJ0KCfmoKHpqozpgJrov4fvvIzlvIDlp4vms6jlhozvvIEnKVxuICAgICAgICB9IGVsc2Uge1xuICAgICAgICAgIE1vZGFsLm1lc3NhZ2UoeyBtZXNzYWdlOiAn5qCh6aqM5LiN6YCa6L+H77yB77yBJywgc3RhdHVzOiAnd2FybmluZycgfSlcbiAgICAgICAgICByZXR1cm4gZmFsc2VcbiAgICAgICAgfVxuICAgICAgfSlcbiAgICB9LFxuICAgIHJlbW92ZVBhc3MoKSB7XG4gICAgICB0aGlzLmlzdmFsaWRhdGUgPSBmYWxzZSAvLyDpgJrov4fphY3nva52YWxpZGF0ZS1vbi1ydWxlLWNoYW5nZeWxnuaApyzorr7nva7mmK/lkKblnKhydWxlc+WxnuaAp+aUueWPmOWQjueri+WNs+inpuWPkeS4gOasoemqjOivgVxuICAgICAgdGhpcy5ydWxlcyA9IHtcbiAgICAgICAgdXNlcm5hbWU6IFtcbiAgICAgICAgICB7IHJlcXVpcmVkOiB0cnVlLCBtZXNzYWdlOiAn5b+F5aGrJywgdHJpZ2dlcjogJ2JsdXInIH0sXG4gICAgICAgICAgeyBtaW46IDIsIG1heDogMTEsIG1lc3NhZ2U6ICfplb/luqblv4XpobvkuI3lsI/kuo4yJywgdHJpZ2dlcjogJ2NoYW5nZScgfVxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICB9XG59XG48L3NjcmlwdD5cblxuPHN0eWxlIHNjb3BlZD5cbi5kZW1vLWZvcm0ge1xuICB3aWR0aDogMzgwcHg7XG59XG48L3N0eWxlPlxuIiwiIjoie1wiaW1wb3J0c1wiOntcIkBvcGVudGlueS92dWVcIjpcImh0dHBzOi8vdW5wa2cuY29tL0BvcGVudGlueS92dWVAMy4xMC4wL3J1bnRpbWUvdGlueS12dWUubWpzXCIsXCJAb3BlbnRpbnkvdnVlLWljb25cIjpcImh0dHBzOi8vdW5wa2cuY29tL0BvcGVudGlueS92dWVAMy4xMC4wL3J1bnRpbWUvdGlueS12dWUtaWNvbi5tanNcIixcIkBvcGVudGlueS92dWUtbG9jYWxlXCI6XCJodHRwczovL3VucGtnLmNvbS9Ab3BlbnRpbnkvdnVlQDMuMTAuMC9ydW50aW1lL3RpbnktdnVlLWxvY2FsZS5tanNcIixcIkBvcGVudGlueS92dWUtY29tbW9uXCI6XCJodHRwczovL3VucGtnLmNvbS9Ab3BlbnRpbnkvdnVlQDMuMTAuMC9ydW50aW1lL3RpbnktdnVlLWNvbW1vbi5tanNcIixcInNvcnRhYmxlanNcIjpcImh0dHBzOi8vdW5wa2cuY29tL3NvcnRhYmxlanNAMS4xNS4wL21vZHVsYXIvc29ydGFibGUuZXNtLmpzXCJ9fSIsIl9vIjp7fX0=

### Step to reproduce

如果在表单中放了popover，表单验证出错时，提示会出现两次

### What is expected

![image](https://github.com/opentiny/tiny-vue/assets/8731711/5169cae3-9bb1-4497-84d5-aa4b94d537f3)

**Comment by gimmyhehe** [comment]
感谢您对TinyVue的支持~  
But,复现demo链接不正确，打开是个demo界面是下图所示。
![image](https://github.com/opentiny/tiny-vue/assets/26026184/2554c00a-9dcc-414f-a9e2-d491d301c17c)
截图中出现的两个校验提示。form-item下如果有多个子元素就会出现截图中所示问题，可以用div标签包一下，使得form-item下只有一个子元素再尝试一下~

**Comment by gimmyhehe** [comment]
@duanleping 若上述方法不能解决问题，麻烦再提供一下正确的复现demo链接~

**Comment by duanleping** [comment]
@gimmyhehe 感谢您的回复，用div标签包一下，使得form-item下只有一个子元素的话，问题可以解决。那个链接复制到浏览器的地址栏，是正确的复现demo链接。谢谢！

**Comment by gimmyhehe** [comment]
@duanleping 重新试了一下，点击跳转链接不正确~  复制链接后粘贴demo正确~
