### ISSUE TITLE
🐛 [Bug]: Checkbox button group, after exceeding the maximum width, there is no line wrapping

### ISSUE THREAD

**Issue by windhc** [opentiny/tiny-vue#460]
### Version

3.10.0

### Vue Version

3.3.4

### Link to minimal reproduction

![image](https://github.com/opentiny/tiny-vue/assets/13448833/31e58a3e-775b-4fc9-8e5d-709e2baf6872)

### Step to reproduce

如图所示

**Comment by gimmyhehe** [comment]
请问现在官网还存在这个问题嘛~  我查看最新的官网，目前换行是正常的。
https://opentiny.design/tiny-vue/zh-CN/os-theme/components/button-group
![image](https://github.com/opentiny/tiny-vue/assets/26026184/361369af-3fcf-46e7-b30b-5c01c3f3c579)

**Comment by gimmyhehe** [comment]
@windhc 看起来你的截图和我们官网示例不太一样，可以发个复现链接么~

**Comment by windhc** [comment]
@gimmyhehe 
https://opentiny.design/tiny-vue/zh-CN/os-theme/components/checkbox#checkbox-button-multiple

**Comment by gimmyhehe** [comment]
@windhc 感谢反馈。问题已收录，修复后将下一版本发布~
