### ISSUE TITLE
✨ [Feature]: There is no confirmation API for table personalization. I hope to add an API for clicking confirmation.

### ISSUE THREAD

**Issue by lhdpfc** [opentiny/tiny-vue#461]
### What problem does this feature solve

表格个性化设置没有确认api，希望可以增加点击确认时的api
![image](https://github.com/opentiny/tiny-vue/assets/79300561/d6728ef4-3bcd-40a6-9dda-4e9b0739d60c)

![企业微信截图_16938935733103](https://github.com/opentiny/tiny-vue/assets/79300561/c3e5a619-4e81-4550-989a-b879a6147b17)

### What does the proposed API look like

希望可以增加点击确认时的api把个性化参数传出来。

**Comment by zzcr** [comment]
取消、确认、重置按钮都有时间可以监听，这个迭代我们会安排丰富下官网的demo示例
 <tiny-grid-toolbar
        id="custom-sort-columns"
        :resizable="{ storage: true }"
        :setting="{ storage: 'local', sortable: Sortable }"
        @save-setting="saveSetting"
        @cancel-setting="cancelSetting"
        @reset-setting="resetSetting"
      ></tiny-grid-toolbar>
