### ISSUE TITLE
✨ [Feature]: ColorPicker support basic color and history color

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-vue#490]
### What problem does this feature solve

在富文本编辑器等场景中使用 ColorPicker，用户可能希望能选择几个常见的特定颜色，并且希望多次选择的颜色色值是一样的。如果只能从颜色面板里选择颜色，可能很难选到两个一样的颜色，因此希望提供一些常见的固定颜色给用户选择。

大致效果如下：

<img width="252" alt="image" src="https://github.com/opentiny/tiny-vue/assets/9566362/aab2a2d7-1ee5-4c47-9a3b-0d91e8675fe9">

<img width="176" alt="image" src="https://github.com/opentiny/tiny-vue/assets/9566362/02e0f8f1-d56c-4d25-92c7-f2a1e8e1dc2d">

<img width="299" alt="image" src="https://github.com/opentiny/tiny-vue/assets/9566362/4a3f674d-36cc-492e-8a0b-27ac106fb06d">

### What does the proposed API look like

最好是能抽取成单独的组件，用户可以自行定义和拼接，比如只要基本色或者只要高级色，或者两个都要。

**Comment by GaoNeng-wWw** [comment]
work in progress

**Comment by zzcr** [comment]
新版本已支持
