### ISSUE TITLE
✨ [Feature]: For the change event of the select component, can you consider using the object corresponding to the selected item as the second parameter

### ISSUE THREAD

**Issue by Swarz** [opentiny/tiny-vue#494]
### What problem does this feature solve

需要获取选中值的其他属性时
    不需要设置为对象属性，或者不需要遍历option

### What does the proposed API look like

change： 
Function(arg,arg2)

arg2是选中项对应的对象或者选中项对应的对象组成的数组

**Comment by shenjunjian** [comment]
select的选项传入， 有2种方式：
1： 通过标签： <  tiny-option v-for="item in options" :key="item.value" :label="item.label" :value="item.value"> </tiny-option>
2： 通过属性： <  tiny-select v-model="value" :options="options"> </tiny-select>

**分析：**
1、通过标签时， select 组件其实只能**取到label, value 这么一个键值**对， 取不到 用户业务数据的其它属性的。   因为用户是把他的数据对象， Pick了2个属性，传进来了的。  这种情况， select 拿不到完整的 **option 对象**,  最多拼一个对象返回。

2、通过属性时， 可以取到完整的 业务数据的对象。  

**结论**：
无论标签还是属性的情况， 用户的业务数据一般会有一个业务数组， 用户自行遍历这个数组也不会增加多少复杂度。
组件不做变更了。

**另外**： 当下拉树， 下拉表格的场景时， change事件会有第2个参数的，就是用户的业务对象。
