### ISSUE TITLE
🐛 [Bug]: When executing build:ui button, an error occurs and packaging fails.

### ISSUE THREAD

**Issue by pe-3** [opentiny/tiny-vue#498]
### Version

3.7.12

### Vue Version

2 2.7 3

### Link to minimal reproduction

https://github.com/opentiny/tiny-vue

### Step to reproduce

执行命令 pnpm build:ui button

报错如下：
Error [RollupError]: "./pc.vue" is imported as an external by "../../packages/vue/src/button/src/index.ts", but is already an existing non-external module id.

### What is expected

检查一下 internals/cli/src/commands/build/build-ui.ts 中的 external 配置

### What is actually happening

执行报错

**Comment by GaoNeng-wWw** [comment]
可以贴一下报错日志吗？

**Comment by kagol** [comment]
我刚看了下单组件构建是OK的
![image](https://github.com/opentiny/tiny-vue/assets/9566362/fced282a-dca1-4f4a-9c6e-eb178a29360d)
