### ISSUE TITLE
🐛 [Bug]: The form form cannot be used in vue2

### ISSUE THREAD

**Issue by pandasstart** [opentiny/tiny-vue#502]
### Version

 @opentiny/vue@2.10.0

### Vue Version

vue@2.7.14

### Link to minimal reproduction

https://opentiny.design/tiny-vue/zh-CN/os-theme/components/form

### Step to reproduce

我已经安装过了vue与opentiny。
我使用https://opentiny.design/tiny-vue/zh-CN/os-theme/components/alert，里面的alert组件，可以成功使用。
但是我使用https://opentiny.design/tiny-vue/zh-CN/os-theme/components/form，里面的form组件，就不能使用。

### What is expected

直接复制粘贴，即可使用，而无需做更多的修改。或者，请老师提供下其他的方案，能帮我解决一下

**Comment by gimmyhehe** [comment]
@pandasstart 目前tiny-vue对2.7版本支持还在完善当中，建议先使用vue2.6版本，或者直接升级到vue3~

**Comment by pandasstart** [comment]
> @pandasstart目前tiny-vue对2.7版本支持还完善，建议先使用vue2.6版本，或者直接升级到vue3~
thinks

**Comment by pandasstart** [comment]
> > Bot detected the issue body's language is not English, translate it automatically.
> 
> @pandasstart At present, tiny-vue’s support for version 2.7 is still being improved. It is recommended to use vue2.6 version first, or directly upgrade to vue3~

thinks

**Comment by zzcr** [comment]
2.11.0版本已支持vue2.7可以测试一下
