### ISSUE TITLE
🐛 [Bug]: When the Modal mobile is turned off, there will be a blue imprint

### ISSUE THREAD

**Issue by XivLaw** [opentiny/tiny-vue#505]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://opentiny.design/tiny-vue/zh-CN/os-theme/components/modal

### Step to reproduce

当页面处于移动端模式时，打开模态窗后，点击确定关闭时，页面上会留下一个浅蓝色的印子。
![GIF 2023-9-23 20-27-41](https://github.com/opentiny/tiny-vue/assets/19726921/1079ca07-17c9-4b16-ab3e-e32eff7ed95d)

**Comment by Huangyilin19** [comment]
问题已解决.
