### ISSUE TITLE
✨ [Feature]: It is recommended that the FileUpload file upload component of Open Tiny vue, as shown in the Upload upload component in TDesign, supports the monitoring and uploading of paste events, and improves upload efficiency and user experience through the paste upload method.

### ISSUE THREAD

**Issue by LinLiang66** [opentiny/tiny-vue#509]
### What problem does this feature solve

需求背景：
1、不支持粘贴上传的情况下，客户屏幕截图后需要保存到本地后才能通过组件上传
2、客户收到文件后在不知道文件位置的情况下，明明可以直接复制粘贴上传，但还是需要客户找到文件位置才能进行上传，
要解决的问题；
1、提升用户体验，一键粘贴上传，简单、高效。体验好
2、无需跟传统上传方式一样先保存文件到本地后在进行上传

### What does the proposed API look like

如TDesign 中的Upload 上传组件所示，支持粘贴事件的监听和上传，通过粘贴上传方法 提升上传效率和用户使用体验
[TDesign粘贴上传演示视频地址：](https://github.com/opentiny/tiny-vue/assets/93206426/6bed0720-0dbb-4e3f-962b-9927d51acffd)
TDesign粘贴上传演示图片地址：
![image](https://github.com/opentiny/tiny-vue/assets/93206426/8540f024-f3b5-44bd-8755-b7e95f7a4fd7)

**Comment by kagol** [comment]
Finished by @chenxi-20 on #593
