### ISSUE TITLE
🐛 [Bug]: There is no prompt to open the tab in IDEA after installing tinyvue

### ISSUE THREAD

**Issue by qindongliang** [opentiny/tiny-vue#516]
### Version

latest

### Vue Version

3.3.4

### Link to minimal reproduction

```
import App from './App.vue'
import { createApp } from 'vue'
import './style.css'
import TinyVue from '@opentiny/vue'


console.log(TinyVue)
const app = createApp(App)
app.use(TinyVue)
app.mount('#app')

```
<img width="547" alt="image" src="https://github.com/opentiny/tiny-vue/assets/7587994/16eba012-fe6a-45d8-85c8-e3eec390b692">

### Step to reproduce

```
import App from './App.vue'
import { createApp } from 'vue'
import './style.css'
import TinyVue from '@opentiny/vue'


console.log(TinyVue)
const app = createApp(App)
app.use(TinyVue)
app.mount('#app')

```
<img width="547" alt="image" src="https://github.com/opentiny/tiny-vue/assets/7587994/16eba012-fe6a-45d8-85c8-e3eec390b692">

### What is expected

有提示的 suggest

### What is actually happening

```
import App from './App.vue'
import { createApp } from 'vue'
import './style.css'
import TinyVue from '@opentiny/vue'


console.log(TinyVue)
const app = createApp(App)
app.use(TinyVue)
app.mount('#app')

```
<img width="547" alt="image" src="https://github.com/opentiny/tiny-vue/assets/7587994/16eba012-fe6a-45d8-85c8-e3eec390b692">

### Any additional comments (optional)

2022.1的 idea

**Comment by kagol** [comment]
@qindongliang 全局引入的方式确实没有智能提示，我们来看下这个问题，你可以试试按需引入。

```
<script setup lang="ts">
import { Button as TinyButton } from '@opentiny/vue'
</script>

<template>
  <tiny-button type="primary">测试按钮</tiny-button>
</template>
```

**Comment by qindongliang** [comment]
@kagol ok，按需引入可以的
