### ISSUE TITLE
✨ [Feature]: Form component printing function and QR code related function

### ISSUE THREAD

**Issue by liguohuanb** [opentiny/tiny-vue#517]
### What problem does this feature solve

希望增加表格组件打印功能（打印机打印和打印成PDF），包括复合表格组件打印，打印是管理系统的刚需；
增加二维码生成以及扫码功能，希望识别速度要快

### What does the proposed API look like

可以设置打印的列（可见列以及所有的行）

**Comment by zzcr** [comment]
您好，感谢你的意见，我们内部评估下~~

**Comment by zzcr** [comment]
二维码组件已有：https://opentiny.design/tiny-vue/zh-CN/os-theme/components/qr-code
打印PDF功能组件没有规划支持，感觉是业务相关功能哈
