### ISSUE TITLE
🐛 [Bug]: The button's autofocus function doesn't seem to work

### ISSUE THREAD

**Issue by hiasky** [opentiny/tiny-vue#523]
### Version

latest

### Vue Version

Vue3

### Link to minimal reproduction

What does the autofocus feature of the button mean? It doesn't seem to show the effect.
https://opentiny.design/tiny-vue/zh-CN/os-theme/components/button#autofocus

### Step to reproduce

https://github.com/opentiny/tiny-vue/assets/103343025/a4aef1ac-4ee8-4c3e-9957-b6c4834cd757

**Comment by kagol** [comment]
@Binks123 After setting autofocus, the button will automatically be in focus, and you can press Enter directly to start the click event of the button. And the button in the focus state will show a blue border and a blue font color.
