### ISSUE TITLE
🐛 [Bug]: This offical example of notify doesn't work for me.

### ISSUE THREAD

**Issue by cleverpig** [opentiny/tiny-vue#534]
### Version

3.8.3

### Vue Version

3.3.4

### Link to minimal reproduction

this offical example of notify: https://opentiny.design/tiny-vue/zh-CN/os-theme/components/notify
It doesn't work for me.

### Step to reproduce

<template>
  <div class="content">
    <button @click="handleClick" :reset-time="0">弹出提示框</button>
  </div>
</template>

<script lang="ts">
import { Notify, Button } from '@opentiny/vue'

export default {
  name: 'Tiny',
  components: {
    Button
  },
  methods: {
    handleClick() {
      Notify({
        type: 'info',
        title: '通知消息的标题'
      })
    }
  }
}
</script>

### What is actually happening

![image](https://github.com/opentiny/tiny-vue/assets/580435/d4fe8de9-7d38-40bb-8a94-7f53e33ae70e)

**Comment by GaoNeng-wWw** [comment]
```typescript
// vite.config.js

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [vue()],
  define: {
    'process.env': { ...process.env }
  }
})
```
