### ISSUE TITLE
🐛 [Bug]: The tiny-dropdown component visible-arrow configuration is invalid

### ISSUE THREAD

**Issue by falcon-jin** [opentiny/tiny-vue#549]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://opentiny.design/tiny-vue/playground?cmpId=dropdown&fileName=visible-arrow.vue&apiMode=Options

### Step to reproduce

visible-arrow配置无效
![image](https://github.com/opentiny/tiny-vue/assets/48880836/4d76d802-9f5a-4172-85f8-aaaea7e1f996)

### What is expected

visible-arrow配置有效

**Comment by gweesin** [comment]
It's looks wonderful now, I think real problem on your computer is that the JS resource loading failure, Can you provide more info?

**Comment by chenguang1994** [comment]
visible-arrow是配置在dropdown的不是menu的，内部使用的变量也不对，用的showIcon，我一会提交一个pr

**Comment by gweesin** [comment]
> visible-arrow是配置在dropdown的不是menu的，内部使用的变量也不对，用的showIcon，我一会提交一个pr

Showing arrow is the behavior of `tiny-dropdown`. So what problem will be caused if visible-arrow property exist in `tiny-dropdown-menu` whether `tiny-dropdown`?

The code will cause **Breaking Change**

**Comment by kagol** [comment]
@falcon-jin 这应该不是一个问题，请参考：
https://github.com/opentiny/tiny-vue/pull/553#issuecomment-1751634635
