### ISSUE TITLE
✨ [Feature]: Support Non-Unix-based system when development

### ISSUE THREAD

**Issue by gweesin** [opentiny/tiny-vue#552]
### What problem does this feature solve

I find some unix commands using in scripts when I contribute to tiny-vue. That behaviour will cause error if you use other OS like Windows.
For example, the `cp` command using frequently in scripts of `package.json`.

### What does the proposed API look like

We could use [shx](https://www.npmjs.com/package/shx) to support cross platform.
We just add the library and transfer `cp` command to `shx cp` command.

- [x] I'm glad to resolve this problem

**Comment by zzcr** [comment]
你好，我们都是windows去开发tinyvue，如果可以的话可以使用bash命令行去操作一些命令
