### ISSUE TITLE
🐛 [Bug]: The ColorPicker color selection panel is a bit low-level

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-vue#556]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

颜色选择面板的层级有点低，很容易被其他元素遮挡住，导致样式问题。

建议：
1. 层级稍微设置大一些（比如：z-index: 10），确保大部分场景（至少组件demo场景中）颜色选择面板不被遮挡
2. 如果有小部分场景还是会存在遮挡，可以提供相应的api，供用户自行配置层级

以下是其中的两个场景

![image](https://github.com/opentiny/tiny-vue/assets/9566362/f49feb6b-dd9a-4dc0-80c9-5956187724dd)

![image](https://github.com/opentiny/tiny-vue/assets/9566362/19f1db11-ed8e-40f3-be30-d57baa8b076a)

### Step to reproduce

以上

**Comment by kagol** [comment]
@GaoNeng-wWw 刚看了下，好像是 z-index 那个主题变量名字没有对应上

**Comment by GaoNeng-wWw** [comment]
好的，我修复一下
