### ISSUE TITLE
🐛 [Bug]: Click margin-top zoom will collapse treemenu

### ISSUE THREAD

**Issue by gweesin** [opentiny/tiny-vue#559]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

click this zoom

![image](https://github.com/opentiny/tiny-vue/assets/42909374/166ca13d-d8a3-4792-a144-0f6c196d4c9a)

### Step to reproduce

the same as **Link to minimal reproduction**

### What is expected

the top zoom of menu item also need be a hot zoom.

**Comment by kagol** [comment]
@gweesin 你看得好细心~👍

**Comment by kagol** [comment]
Fixed by @chenguang1994 on #568
