### ISSUE TITLE
🐛 [Bug]: Import opentiny error when sub-module define `type: module`

### ISSUE THREAD

**Issue by gweesin** [opentiny/tiny-vue#569]
### Version

2.10.0

### Vue Version

2.6.14

### Link to minimal reproduction

https://github.com/gweesin/test-tiny-vue-in-vue2

you also can open it online by stackblitz:

https://stackblitz.com/github/gweesin/test-tiny-vue-in-vue2

### Step to reproduce

1. `pnpm add -S @opentiny/vue@2`
2. import a component and use it

```js
import { TimeLine } from "@opentiny/vue";

export default {
  render(h) {
    return h(TimeLine);
  },
};
```

### What is expected

compile without error

### What is actually happening

![image](https://github.com/opentiny/tiny-vue/assets/42909374/0208f182-768e-4888-8db5-dd040a36602c)

The problem is that sub-module (or alias component) defined `type: module`, so when import files, it must include suffix of files, but not.

> The sub-module example
> ![image](https://github.com/opentiny/tiny-vue/assets/42909374/43bd3244-45f9-41a8-8fa2-b4348fc35552)

> The import statement
> ![image](https://github.com/opentiny/tiny-vue/assets/42909374/e023d1e2-6a12-4597-9519-478fa5a831d8)

actual:

```js
import { isDate } from "@opentiny/vue-renderless/common/deps/date-util";
```

expect: 

```js
import { isDate } from "@opentiny/vue-renderless/common/deps/date-util.js";
```

**Comment by gweesin** [comment]
We could incorporate a webpack rule to address this issue:

```
rules: [
  // ...
  {
      test: /\.m?js/,
      resolve: {
          fullySpecified: false
      }
  }
  // ...
]
```

> [fullySpecified](https://webpack.js.org/configuration/module/#resolvefullyspecified)

**Comment by gweesin** [comment]
从脚手架层面处理可能不是很好的方案，[esbuild 不支持生成带文件后缀的 import 语句](https://github.com/evanw/esbuild/issues/622)，需要加插件处理或者不使用 `type: "module"` 属性

**Comment by gweesin** [comment]
目前看一些著名的开源项目主要采用的是后者的方案，加 esbuild 插件的话边界情况较多，不好处理

**Comment by khuntoriia** [comment]
```
module: {
      rules: [
        {
          test: /\.m?js/,
          resolve: {
              fullySpecified: false
          }
        }
      ],
    },
```
