### ISSUE TITLE
✨ [Feature]: The pagination table serial number can be linked to the current page number

### ISSUE THREAD

**Issue by falcon-jin** [opentiny/tiny-vue#571]
### What problem does this feature solve

![image](https://github.com/opentiny/tiny-vue/assets/48880836/6646f1f3-2fc7-4091-8316-f1357e141905)
目前第一页 第二页 序号都是一样的

### What does the proposed API look like

加入每页10条数据 第一页序号从1到10 切换到第二页 序号从11开始  因为grid有pager属性 这个应该容易做到

**Comment by wkif** [comment]
没有很明白具体需要什么效果

**Comment by falcon-jin** [comment]
> 没有很明白具体需要什么效果

第一页序号从1到10 第二页序号应该从11-20 而不是还是1-10

**Comment by zzcr** [comment]
https://opentiny.design/tiny-vue/zh-CN/os-theme/components/grid-pager#pager-inner-pager 可以看下这个例子
