### ISSUE TITLE
✨ [Feature]: Support Nuxt3

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-vue#577]
### What problem does this feature solve

需要开发一个 Nuxt 模块，支持在 Nuxt 中使用 TinyVue 组件库。

### What does the proposed API look like

可以参考：https://nuxt.com/modules/element-plus

**Comment by zzcr** [comment]
您好，感谢你的意见，我们内部评估下~~

**Comment by zzcr** [comment]
OpenTiny 开源之夏已安排支持nuxt3相关议题哈
