### ISSUE TITLE
When will the new version be released?

### ISSUE THREAD

**Issue by sdhzth** [opentiny/tiny-vue#588]
### What problem does this feature solve

每次新版发布有具体的时间表吗？

### What does the proposed API look like

例如每个月 2个月等等，隔壁TDesign新版发布挺快的，谢谢。

**Comment by wkif** [comment]
据说预计月底的版本会发布RichTextEditor ColorPicker Divider CalendarView四个组件

**Comment by kagol** [comment]
@sdhzth v3.11.0 新版本已发布，可查看 Release Notes: https://github.com/opentiny/tiny-vue/releases/tag/v3.11.0

**Comment by kagol** [comment]
@sdhzth 一般一个月发一次大版本，补丁版本的发布会更频繁
