### ISSUE TITLE
✨ [Feature]: Tree-menu search box placeholder supports customization

### ISSUE THREAD

**Issue by falcon-jin** [opentiny/tiny-vue#589]
### What problem does this feature solve

![image](https://github.com/opentiny/tiny-vue/assets/48880836/ed7c1b52-c2d2-499c-8c99-085a1af60689)

### What does the proposed API look like

希望tree-menu 搜索框placeholder支持自定义

**Comment by Huangyilin19** [comment]
好的，我们内部先评审下解决方案。
