### ISSUE TITLE
✨ [Feature]: Can I beautify the document interface

### ISSUE THREAD

**Issue by fanbingbing16** [opentiny/tiny-vue#594]
### What problem does this feature solve

![image](https://github.com/opentiny/tiny-vue/assets/84823288/7e24cd64-618a-4edf-b2c8-454a2c392caf)
个人认为文档界面有点不太美观

### What does the proposed API look like

1.滚动条还是默认的如果改成
![image](https://github.com/opentiny/tiny-vue/assets/84823288/0827fe91-d257-42f0-98ef-54545afabdcf)
个人认为会好看很多
2.这边的框太小，有的文字都被挡住了

**Comment by zzcr** [comment]
我们官网的文档，如果本地开发启动的是 pnpm site命令~~
