### ISSUE TITLE
🐛 [Bug]: There is a bug in the loading example of the document

### ISSUE THREAD

**Issue by zxlfly** [opentiny/tiny-vue#595]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://opentiny.design/tiny-vue/zh-CN/os-theme/components/loading

### Step to reproduce

https://opentiny.design/tiny-vue/zh-CN/os-theme/components/loading
文档点击第一个demo基本用法
![image](https://github.com/opentiny/tiny-vue/assets/26324442/c5ed285f-7975-466b-ab28-6b509eb2cdc0)

### What is expected

实际效果应该作用域当前示例

**Comment by kagol** [comment]
Fixed by @chenguang1994 on #597
