### ISSUE TITLE
✨ [Feature]: Drawer drawer adds transition animation

### ISSUE THREAD

**Issue by zxlfly** [opentiny/tiny-vue#596]
### What problem does this feature solve

展示隐藏的过程中没用动画过度，显得很生硬，用户体验感不好
遮罩层是很快就消失了，抽屉部分慢一点，不知道是不是加了过度没生效

### What does the proposed API look like

增加默认的过渡效果

**Comment by zzcr** [comment]
3.11.0版本已修复这个问题
