### ISSUE TITLE
🐛 [Bug]: Table built-in paging component total parameter is invalid

### ISSUE THREAD

**Issue by merry9899** [opentiny/tiny-vue#604]
### Version

3.10.1

### Vue Version

3.2.45

### Link to minimal reproduction

![mmexport1697717440003](https://github.com/opentiny/tiny-vue/assets/107098795/56ce5c39-e1d4-4810-b489-ec212f9c3daa)
:data数据源模式，内置或注入分页组件模式，我想手动输入分页数据总条数，发现total输入后无效，是bug，还是需要在别的地方输入，谢谢指教

### Step to reproduce

![mmexport1697717440003](https://github.com/opentiny/tiny-vue/assets/107098795/56ce5c39-e1d4-4810-b489-ec212f9c3daa)
:data数据源模式，内置或注入分页组件模式，我想手动输入分页数据总条数，发现total输入后无效，是bug，还是需要在别的地方输入，谢谢指教

**Comment by zzcr** [comment]
表格的分页一般是配合fetchData使用的https://opentiny.design/tiny-vue/zh-CN/os-theme/components/grid-data-source#tiny-first-menu-request-service
