### ISSUE TITLE
✨ [Feature]: Is it possible to add multi-tab components?

### ISSUE THREAD

**Issue by ice-piont** [opentiny/tiny-vue#609]
### What problem does this feature solve

使用TinyPro构建管理系统，用户在使用管理系统时候，操作表单数据时，往往需要查看相关联的业务数据，查看或者核对后，再返回当前页面填入和编辑数据，没有多页签，管理系统非常难使用，尤其涉及财务数据，数据是不能错的，用户只能记录到纸上，把需要的数据一一准备好，然后再打开要操作的页面进行处理。一般管理类系统要求必须支持多页签，没有多页签没法使用。

### What does the proposed API look like

1、每点击一个菜单，也多页签位置多一个对应页面；
2、弹出对话框应该在页面内，切换多页签不影响对话框，切换回来时，页签内对话框所填写的内容保持原样。
3、页面内所有的状态在多页签切换时保持原样，选择的查询条件、翻页、选中的记录等，在页签切换回来时，均保持原样。

**Comment by wkif** [comment]
或许你说的是这个 https://opentiny.design/tiny-vue/zh-CN/os-theme/components/tabs

**Comment by kagol** [comment]
@ice-piont 你应该是希望 TinyPro 提供多页签能力，可以到 tiny-cli 项目提交一个 issue～
https://github.com/opentiny/tiny-cli
感谢你的大力支持

**Comment by kagol** [comment]
> 或许你说的是这个 https://opentiny.design/tiny-vue/zh-CN/os-theme/components/tabs
@wkif 
ice-piont 应该是希望在 TinyPro 后台管理模板中增加多页签模式
