### ISSUE TITLE
🐛 [Bug]: [dialoagSelect] no description of "change" event in API-events

### ISSUE THREAD

**Issue by KevinAndrewDong** [opentiny/tiny-vue#612]
### Version

3.10.1

### Vue Version

3.2.45

### Link to minimal reproduction

https://opentiny.design/tiny-vue/zh-CN/os-theme/components/dialog-select#API

### Step to reproduce

1. open the link https://opentiny.design/tiny-vue/zh-CN/os-theme/components/dialog-select#API
2. check the "change" event given by Demo ( @change="onDialogSelectChange") , and the events in API

### What is expected

description of "change" event in dialoagSelect-API-events

**Comment by MomoPoppy** [comment]
好的，此处会进行文档优化Okay,
we're going to optimize the document here.

**Comment by MomoPoppy** [comment]
已补充文档。
The document has been supplemented.
