### ISSUE TITLE
🐛 [Bug]: Error running npm i

### ISSUE THREAD

**Issue by GaoNeng-wWw** [opentiny/tiny-vue#65]
### Version

-

### Vue Version

-

### Link to minimal reproduction

https://github.com/GaoNeng-wWw/tiny-vue.git

### Step to reproduce

1. git clone https://github.com/GaoNeng-wWw/tiny-vue.git
2. npm i 
3. 复现错误

### What is expected

正常安装且不出错

### What is actually happening

控制台发生了报错，具体报错参考[报错日志](https://gist.github.com/GaoNeng-wWw/abaf197a600f289779780aae8f4263fc)

### Any additional comments (optional)

Node: v18.7.0
npm: v8.15.0

**Comment by kagol** [comment]
@GaoNeng-wWw 报错日志里有以下提示：
```
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```

请加上`--force`参数再试试：`npm i --force`，我后面更新下贡献指南。

另外，本地启动项目之前，需要将以下四个仓库全部clone下来，放到同一个目录层级中：
- [tiny-vue](https://github.com/opentiny/tiny-vue)
- [tiny-vue-renderless](https://github.com/opentiny/tiny-vue-renderless)
- [tiny-vue-theme](https://github.com/opentiny/tiny-vue-theme)
- [tiny-vue-theme-mobile](https://github.com/opentiny/tiny-vue-theme-mobile)

**Comment by GaoNeng-wWw** [comment]
可以正常启动了，感谢~
