### ISSUE TITLE
✨ [Feature]: Table toolbar buttons support custom colors

### ISSUE THREAD

**Issue by falcon-jin** [opentiny/tiny-vue#661]
### What problem does this feature solve

![image](https://github.com/opentiny/tiny-vue/assets/48880836/58b8b484-dfbd-4384-9e0d-57feb527156c)
目前不支持
![image](https://github.com/opentiny/tiny-vue/assets/48880836/f891e8d8-217e-419b-8b7b-ca48b852ed85)

### What does the proposed API look like

表格工具栏按钮支持自定义颜色 内置几个颜色

**Comment by zzcr** [comment]
可以使用工具栏插槽哈
