### ISSUE TITLE
✨ [Feature]: Icon library wants to support iconfont

### ISSUE THREAD

**Issue by dyh333** [opentiny/tiny-vue#668]
### What problem does this feature solve

图标库目前只支持svg格式

### What does the proposed API look like

希望支持iconfont图标的导入和用法

**Comment by shenjunjian** [comment]
阿里的iconfont是一个很伟大的网站，里面提供了大量的svg, png以及素材原图。
至于项目如何引用它们的图标， 请参考他们官网的介绍或者 搜索  “SVG转字体” 的相关文章，自行配置。

tinyvue是一个专注Vue2/3的组件库，它内置了一些图标组件，是不依赖iconfont 网站的。
