### ISSUE TITLE
🐛 [Bug]: tree in tinytheme is different

### ISSUE THREAD

**Issue by STofone** [opentiny/tiny-vue#678]
### Version

latset

### Vue Version

latset

### Link to minimal reproduction

https://tinyuidesign.cloudbu.huawei.com/tiny-vue/zh-CN/os-theme/components/tree#highlight-current

### Step to reproduce

.

### What is expected

tree in tinytheme is different
tinytheme select all the node but tinyvue select part of it
the border-radius seems not working in tinyvue
![image](https://github.com/opentiny/tiny-vue/assets/37892335/3307baa6-bb77-4b39-9e66-8011ef6a3335)
![image](https://github.com/opentiny/tiny-vue/assets/37892335/1585f356-b396-432b-80a5-45df10e85806)

**Comment by Huangyilin19** [comment]
确实是个问题，我们内部研究下解决方案。

**Comment by shenjunjian** [comment]
1、样式带来的用户体验差异， 并不影响组件的功能与使用。
2、hover时高亮一整行，还是只高亮块到底哪个好， 就体验上来说各有好坏。
3、element ui是高亮一整行， 但华为云规范是明确只高亮块的。

该问题待讨论，建议保留不变
