### ISSUE TITLE
🐛 [Bug]: The animation direction of left/top/bottom of the drawer component is wrong

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-vue#689]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

参考链接：https://opentiny.design/tiny-vue/zh-CN/os-theme/components/drawer#placement

![image](https://github.com/opentiny/tiny-vue/assets/9566362/957742c5-0d1f-4f05-87b2-ce89632d1aac)

### Step to reproduce

点击以下 demo 中的 left、top、bottom按钮，弹出动画的方向不对。
可参考ElementPlus效果：https://element-plus.gitee.io/zh-CN/component/drawer.html#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95

https://opentiny.design/tiny-vue/zh-CN/os-theme/components/drawer#placement

**Comment by AcWrong02** [comment]
Let me try to fix it!
