### ISSUE TITLE
🐛 [Bug]: In the Slider component input box mode, when the step is set to 0.5, the input box does not support decimal point input.

### ISSUE THREAD

**Issue by AcWrong02** [opentiny/tiny-vue#699]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

```
<template>
    <tiny-slider
      v-model="value"
      @change="change"
      :disabled="isDisabled"
      :show-input="true"
      :step="0.5"
    />
</template>

<script setup lang="ts">
import { ref } from "vue";
import { Slider as TinySlider } from "@opentiny/vue";

const value = ref(0);
const isDisabled = ref(false);

const change = val => {
  console.log(val);
  if (val > 50) {
    isDisabled.value = true;
  }
};
</script>
```

### Step to reproduce

按照上面的代码直接调试即可

### What is expected

希望在输入框模式下可以支持小数点输入

### What is actually happening

输入框模式下无法输入小数点

### Any additional comments (optional)

null

**Comment by fanbingbing16** [comment]
![image](https://github.com/opentiny/tiny-vue/assets/84823288/c049d65c-748d-4826-8f60-2c310e21f9df)
文档有说step必须是大于0的正整数

**Comment by AcWrong02** [comment]
> ![image](https://user-images.githubusercontent.com/84823288/278957161-c049d65c-748d-4826-8f60-2c310e21f9df.png) 文档有说step必须是大于0的正整数

那应该还是要支持小数比较好点吧^v^
