### ISSUE TITLE
🐛 [Bug]: popover v-model cannot work expected

### ISSUE THREAD

**Issue by gweesin** [opentiny/tiny-vue#704]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://opentiny.design/vue-playground?mode=pc&theme=default#3.11|eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgbGFuZz1cInRzeFwiPlxuLy8g5byV5YWlIEBvcGVudGlueS92dWUg57uE5Lu2XG5pbXBvcnQgeyBCdXR0b24sIExpbmsgfSBmcm9tICdAb3BlbnRpbnkvdnVlJ1xuXG5leHBvcnQgZGVmYXVsdCB7XG4gIGNvbXBvbmVudHM6IHtcbiAgICBUaW55QnV0dG9uOiBCdXR0b24sXG4gICAgVGlueUxpbms6IExpbmtcbiAgfSxcbiAgZGF0YSgpIHtcbiAgICByZXR1cm4ge1xuICAgICAgbXNnOiAnaGVsbG8gd29ybGQhJ1xuICAgIH1cbiAgfVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPFRpbnlCdXR0b24+56Gu5a6aPC9UaW55QnV0dG9uPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGRpdiBjbGFzcz1cInRpbnl2dWVcIj5cbiAgICA8ZGl2IGNsYXNzPVwidGlueXZ1ZS1wYWdlXCI+XG4gICAgICB0aW55dnVlXG4gICAgICA8dGlueS1saW5rIHR5cGU9XCJzdWNjZXNzXCIgaHJlZj0naHR0cHM6Ly9naXRodWIuY29tL29wZW50aW55L3RpbnktdnVlJz5cbiAgICAgICAgdGlueXZ1ZVxuICAgICAgPC90aW55LWxpbms+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlIGxhbmc9XCJsZXNzXCIgc2NvcGVkPlxuICBoMXtcbiAgICBjb2xvcjojNWU3Y2UwO1xuICB9XG4gIC50aW55dnVle1xuICAgIGZvbnQtc2l6ZTogMTh4cDtcbiAgICAmLXBhZ2V7XG4gICAgICBjb2xvcjojNWU3Y2UwO1xuICAgIH1cbiAgfVxuPC9zdHlsZT5cbiIsInNyYy8iOiJ7XCJpbXBvcnRzXCI6e1wiQG9wZW50aW55L3Z1ZVwiOlwiaHR0cHM6Ly91bnBrZy5jb20vQG9wZW50aW55L3Z1ZUAzLjExL3J1bnRpbWUvdGlueS12dWUubWpzXCIsXCJAb3BlbnRpbnkvdnVlLWljb25cIjpcImh0dHBzOi8vdW5wa2cuY29tL0BvcGVudGlueS92dWVAMy4xMS9ydW50aW1lL3RpbnktdnVlLWljb24ubWpzXCIsXCJAb3BlbnRpbnkvdnVlLWxvY2FsZVwiOlwiaHR0cHM6Ly91bnBrZy5jb20vQG9wZW50aW55L3Z1ZUAzLjExL3J1bnRpbWUvdGlueS12dWUtbG9jYWxlLm1qc1wiLFwiQG9wZW50aW55L3Z1ZS1jb21tb25cIjpcImh0dHBzOi8vdW5wa2cuY29tL0BvcGVudGlueS92dWVAMy4xMS9ydW50aW1lL3RpbnktdnVlLWNvbW1vbi5tanNcIixcInNvcnRhYmxlanNcIjpcImh0dHBzOi8vdW5wa2cuY29tL3NvcnRhYmxlanNAMS4xNS4wL21vZHVsYXIvc29ydGFibGUuZXNtLmpzXCJ9fSIsInRzY29uZmlnLmpzb24iOiJ7XHJcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xyXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXHJcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcclxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcclxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXHJcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxyXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxyXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlXHJcbiAgfSxcclxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XHJcbiAgICBcInRhcmdldFwiOiAzLjNcclxuICB9XHJcbn1cclxuIiwic3JjL2Jhc2ljLXVzYWdlLnZ1ZSI6Ijx0ZW1wbGF0ZT5cblx0PE1zcEJ1dHRvblNlbGVjdCA6ZGF0YT1cImRhdGFcIj5cbiAgICDkuIvmi4nmjInpkq5cbiAgPC9Nc3BCdXR0b25TZWxlY3Q+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJqc3hcIj5cbmltcG9ydCB7IFBvcG92ZXIsIEJ1dHRvbiB9IGZyb20gJ0BvcGVudGlueS92dWUnXG5pbXBvcnQgTXNwQnV0dG9uU2VsZWN0IGZyb20gJy4vQ29tcC52dWUnXG5cbmV4cG9ydCBkZWZhdWx0IHtcbiAgY29tcG9uZW50czoge1xuICAgIFRpbnlQb3BvdmVyOiBQb3BvdmVyLFxuICAgIFRpbnlCdXR0b246IEJ1dHRvbixcbiAgICBNc3BCdXR0b25TZWxlY3RcbiAgfSxcbiAgZGF0YSgpIHtcbiAgICByZXR1cm4ge1xuICAgICAgZGF0YTogW1xuICAgICAgICB7IGlkOiAxLCB0ZXh0OiAn5pu05aSa5oyJ6ZKuMScgfSxcbiAgICAgICAgeyBpZDogMiwgdGV4dDogJ+abtOWkmuaMiemSrjInIH0sXG4gICAgICAgIHsgaWQ6IDMsIHRleHQ6ICfmm7TlpJrmjInpkq4zJyB9LFxuICAgICAgXVxuICAgIH1cbiAgfVxufVxuPC9zY3JpcHQ+XG4iLCJzcmMvQ29tcC52dWUiOiI8dGVtcGxhdGU+XG4gICAgPFRpbnlCdXR0b25Hcm91cCBjbGFzcz1cIm1zcF9idXR0b25fc2VsZWN0XCI+XG4gICAgICAgIDxUaW55QnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgOnJlc2V0VGltZT1cIjBcIj5cbiAgICAgICAgICAgIDxzbG90Pjwvc2xvdD5cbiAgICAgICAgPC9UaW55QnV0dG9uPlxuXG4gICAgICAgIDxUaW55UG9wb3ZlclxuICAgICAgICAgICAgdi1tb2RlbD1cInBvcHBlclZpc2libGVcIlxuICAgICAgICAgICAgOnZpc2libGVBcnJvdz1cImZhbHNlXCJcbiAgICAgICAgICAgIHBsYWNlbWVudD1cImJvdHRvbS1lbmRcIlxuICAgICAgICAgICAgOndpZHRoPVwicG9wb3ZlcldpZHRoXCJcbiAgICAgICAgICAgIHBvcHBlckNsYXNzPVwibXNwX2J1dHRvbl9zZWxlY3RfX3BvcHBlclwiXG4gICAgICAgID5cbiAgICAgICAgICAgIDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuICAgICAgICAgICAgICAgIDxUaW55QnV0dG9uIDppY29uPVwiZHJvcGRvd25JY29uXCIgdHlwZT1cInByaW1hcnlcIiA6cmVzZXRUaW1lPVwiMFwiPjwvVGlueUJ1dHRvbj5cbiAgICAgICAgICAgIDwvdGVtcGxhdGU+XG5cbiAgICAgICAgICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD5cbiAgICAgICAgICAgICAgICA8c2xvdCBuYW1lPVwiZHJvcGRvd25cIj5cbiAgICAgICAgICAgICAgICAgICAgPGRpdlxuICAgICAgICAgICAgICAgICAgICAgICAgY2xhc3M9XCJtc3BfYnV0dG9uX3NlbGVjdF9fcG9wcGVyX19pdGVtXCJcbiAgICAgICAgICAgICAgICAgICAgICAgIHYtZm9yPVwiZHJvcGRvd25JdGVtIGluIGRhdGFcIlxuICAgICAgICAgICAgICAgICAgICAgICAgOmtleT1cImRyb3Bkb3duSXRlbS5pZFwiXG4gICAgICAgICAgICAgICAgICAgICAgICBAY2xpY2s9XCJfY2xpY2tEcm9wZG93bkl0ZW0oZHJvcGRvd25JdGVtLmlkKVwiXG4gICAgICAgICAgICAgICAgICAgID5cbiAgICAgICAgICAgICAgICAgICAgICAgIHt7IGRyb3Bkb3duSXRlbS50ZXh0IH19XG4gICAgICAgICAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgICAgICAgIDwvc2xvdD5cbiAgICAgICAgICAgIDwvdGVtcGxhdGU+XG4gICAgICAgIDwvVGlueVBvcG92ZXI+XG4gICAgPC9UaW55QnV0dG9uR3JvdXA+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0PlxuaW1wb3J0IHsgQnV0dG9uLCBCdXR0b25Hcm91cCwgUG9wb3ZlciB9IGZyb20gJ0BvcGVudGlueS92dWUnO1xuaW1wb3J0IHsgSWNvbkRlbHRhRG93biB9IGZyb20gJ0BvcGVudGlueS92dWUtaWNvbic7XG5cbmV4cG9ydCBkZWZhdWx0IHtcbiAgICBuYW1lOiAnTXNwQnV0dG9uU2VsZWN0JyxcbiAgICBwcm9wczoge1xuICAgICAgICBkYXRhOiB7XG4gICAgICAgICAgICB0eXBlOiBBcnJheSxcbiAgICAgICAgICAgIGRlZmF1bHQ6ICgpID0+IFtdXG4gICAgICAgIH1cbiAgICB9LFxuICAgIGNvbXBvbmVudHM6IHtcbiAgICAgICAgVGlueUJ1dHRvbjogQnV0dG9uLFxuICAgICAgICBUaW55QnV0dG9uR3JvdXA6IEJ1dHRvbkdyb3VwLFxuICAgICAgICBUaW55UG9wb3ZlcjogUG9wb3ZlclxuICAgIH0sXG4gICAgZGF0YSgpIHtcbiAgICAgICAgcmV0dXJuIHtcbiAgICAgICAgICAgIHBvcHBlclZpc2libGU6IGZhbHNlLFxuICAgICAgICAgICAgZHJvcGRvd25JY29uOiBJY29uRGVsdGFEb3duKCksXG5cbiAgICAgICAgICAgIC8qKiBAdHlwZSB7UmVzaXplT2JzZXJ2ZXJ9ICovXG4gICAgICAgICAgICByZXNpemVPYnNlcnZlcjogbnVsbCxcblxuICAgICAgICAgICAgcG9wb3ZlcldpZHRoOiAwXG4gICAgICAgIH07XG4gICAgfSxcbiAgICBtb3VudGVkKCkge1xuICAgICAgICBsZXQgZWwgPSB0aGlzLiRlbDtcbiAgICAgICAgdGhpcy5wb3BvdmVyV2lkdGggPSBlbC5vZmZzZXRXaWR0aDtcblxuICAgICAgICB0aGlzLnJlc2l6ZU9ic2VydmVyID0gbmV3IFJlc2l6ZU9ic2VydmVyKCgpID0+IHtcbiAgICAgICAgICAgIHRoaXMucG9wb3ZlcldpZHRoID0gZWwub2Zmc2V0V2lkdGg7XG4gICAgICAgIH0pO1xuICAgIH0sXG4gICAgbWV0aG9kczoge1xuICAgICAgICBfY2xpY2tEcm9wZG93bkl0ZW0oaWQpIHtcbiAgICAgICAgICAgIC8vIEZJWE1FOiBleHBlY3QgdGhpcyBiZWhhdmlvciB3aWxsIGNsb3NlIHBvcG92ZXJcbiAgICAgICAgICAgIHRoaXMucG9wcGVyVmlzaWJsZSA9IGZhbHNlO1xuICAgICAgICAgICAgdGhpcy4kZW1pdCgnY2hhbmdlJywgaWQpO1xuICAgICAgICB9XG4gICAgfSxcbiAgICBiZWZvcmVEZXN0cm95KCkge1xuICAgICAgICB0aGlzLnJlc2l6ZU9ic2VydmVyLmRpc2Nvbm5lY3QoKTtcbiAgICB9XG59O1xuPC9zY3JpcHQ+XG5cbjxzdHlsZSBsYW5nPVwic2Nzc1wiPlxuLm1zcF9idXR0b25fc2VsZWN0X19wb3BwZXIudGlueS1wb3BvdmVyLnRpbnktcG9wcGVyIHtcbiAgICAtLXRpLXBvcG92ZXItcGxhY2VtZW50LW1hcmdpbi12ZXJ0aWNhbDogMDtcbiAgICAtLXRpLXBvcG92ZXItcGFkZGluZy12ZXJ0aWNhbDogMDtcbiAgICAtLXRpLXBvcG92ZXItcGFkZGluZy1ob3Jpem9udGFsOiAwO1xufVxuXG4ubXNwX2J1dHRvbl9zZWxlY3RfX3BvcHBlcl9faXRlbSB7XG4gICAgY3Vyc29yOiBwb2ludGVyO1xuICAgIHBhZGRpbmc6IDhweDtcblxuICAgICY6aG92ZXIge1xuICAgICAgICBjb2xvcjogI2ZmZjtcbiAgICAgICAgYmFja2dyb3VuZC1jb2xvcjogIzc2OTNmNTtcbiAgICB9XG59XG48L3N0eWxlPlxuIiwiIjoie1wiaW1wb3J0c1wiOntcIkBvcGVudGlueS92dWVcIjpcImh0dHBzOi8vdW5wa2cuY29tL0BvcGVudGlueS92dWVAMy4xMS9ydW50aW1lL3RpbnktdnVlLm1qc1wiLFwiQG9wZW50aW55L3Z1ZS1pY29uXCI6XCJodHRwczovL3VucGtnLmNvbS9Ab3BlbnRpbnkvdnVlQDMuMTEvcnVudGltZS90aW55LXZ1ZS1pY29uLm1qc1wiLFwiQG9wZW50aW55L3Z1ZS1sb2NhbGVcIjpcImh0dHBzOi8vdW5wa2cuY29tL0BvcGVudGlueS92dWVAMy4xMS9ydW50aW1lL3RpbnktdnVlLWxvY2FsZS5tanNcIixcIkBvcGVudGlueS92dWUtY29tbW9uXCI6XCJodHRwczovL3VucGtnLmNvbS9Ab3BlbnRpbnkvdnVlQDMuMTEvcnVudGltZS90aW55LXZ1ZS1jb21tb24ubWpzXCIsXCJzb3J0YWJsZWpzXCI6XCJodHRwczovL3VucGtnLmNvbS9zb3J0YWJsZWpzQDEuMTUuMC9tb2R1bGFyL3NvcnRhYmxlLmVzbS5qc1wifX0iLCJfbyI6e319

### Step to reproduce

1. open minimal reproduction
2. click dropdown icon **▾**
3. click li item in popover content
4. see minimal reproduction `Comp.vue` line 73 to get more details

### What is expected

expect click li item can close popover

### What is actually happening

click li item and set `popperVisible = false` as v-model value, not work

**Comment by kagol** [comment]
@gweesin Thank you for your feedback. This may be a problem. We will analyze it.

From the effect of the minimum reproducible demo you send, you can choose to use the dropdown component, and the dropdown component also supports turning on the tooltip prompt function in the options.

Refer to the following link: https://opentiny.design/tiny-vue/zh-CN/os-theme/components/dropdown#tip

**Comment by shenjunjian** [comment]
请参考 Popover的最新官网上的 “触发方式” 的示例。

**原因：**  
“通过trigger 属性设定弹出框的4种触发方式， 默认值为 click 。
当触发方式为 manual时，通过设置v-model 属性，动态控制显示和隐藏弹出框。”

你设置v-model, 那么必须指定manual。 
你的示例中，不指定manual, 那么触发方式就是click。   v-model="popperVisible" 就不能控制它了。

**解决方法：**
   添加 trigger='manual',  为tinyButton 图标添加  @click='popperVisible=true' 即可！

**Comment by shenjunjian** [comment]
最后，组件库已经有 Dropdown  组件了，完全是你想实现的东西、

**Comment by gweesin** [comment]
So, the real problem is that if you use the dropdown slot, you cannot close the dropdown unless you click outside.
