### ISSUE TITLE
🐛 [Bug]: ToolTip theme function, when type is error, should the displayed background be red?

### ISSUE THREAD

**Issue by AcWrong02** [opentiny/tiny-vue#714]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

read official documents ：https://opentiny.design/tiny-vue/zh-CN/os-theme/components/tooltip
![image](https://github.com/opentiny/tiny-vue/assets/147061401/1c8e42e6-909e-4bd5-af55-43798f60e6d5)

### Step to reproduce

null

### What is expected

error背景颜色我认为应该是红色？

### What is actually happening

error背景颜色是黑色

**Comment by shenjunjian** [comment]
谢谢你的建议，已经修复了颜色。
