### ISSUE TITLE
🐛 [Bug]: Collapse The collapsed panel can only be expanded when clicking on the icon or text.

### ISSUE THREAD

**Issue by AcWrong02** [opentiny/tiny-vue#717]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

look at the offical document：https://opentiny.design/tiny-vue/zh-CN/os-theme/components/collapse
When I click on the red box area, there is no response.
![image](https://github.com/opentiny/tiny-vue/assets/147061401/ca8b70f9-19a3-4d1a-ad0c-4eaaacdd45a1)

### Step to reproduce

null

### What is expected

When I click on the red box area, there should be a response.

### What is actually happening

When I click on the red box area, there is no response.

**Comment by zzcr** [comment]
您好，感谢你的意见，我们内部评估下~~
