### ISSUE TITLE
🐛 [Bug]: ActionMenu components have a lot of warning messages

### ISSUE THREAD

**Issue by falcon-jin** [opentiny/tiny-vue#723]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

![image](https://github.com/opentiny/tiny-vue/assets/48880836/e6efa632-c137-4b6b-a431-b9ee28205338)
官方示例https://opentiny.design/vue-playground?cmpId=action-menu&fileName=slot-item.vue&apiMode=Options&mode=pc&theme=default

### Step to reproduce

去除警告

**Comment by falcon-jin** [comment]
目前是自己使用解决 
provide('dropdownMenuVm', undefined);

**Comment by MomoPoppy** [comment]
后续会优化示例或代码逻辑去除警告
The example or code logic will be optimized to remove warnings.

**Comment by MomoPoppy** [comment]
此问题已修改。控制台已经没有警告，演练场更新最新的组件包后就不会报错了。
This issue has been fixed. No warning is displayed on the console. After the latest component package is updated, no error is reported.
