### ISSUE TITLE
✨ [Feature]: Supports the global display of the loading progress bar of page loading, asynchronous request, and file upload

### ISSUE THREAD

**Issue by qianmoQ** [opentiny/tiny-vue#724]
### What problem does this feature solve

The loading progress bar of page loading, asynchronous request, and file upload is displayed globally.

### What does the proposed API look like

please see https://www.iviewui.com/view-ui-plus/component/navigation/loading-bar

**Comment by zzcr** [comment]
您好，感谢你的意见，我们内部评估下~~

**Comment by zzcr** [comment]
你好，我们有提供全局弹窗和loading组件，您提的需求感觉有点偏业务了
