### ISSUE TITLE
🐛 [Bug]: [Grid-right-click menu-cell menu] The right-click menu cannot be moved to the secondary menu

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-vue#725]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

复现demo地址：https://opentiny.design/tiny-vue/zh-CN/os-theme/components/grid-context-menu#grid_Example-shortcutMenu-cell-menu

### Step to reproduce

- 表格中右键弹出菜单
- 鼠标移到一级菜单中，没法再移入二级菜单

**Comment by zzcr** [comment]
您好，感谢你的意见，我们内部评估下~~

**Comment by zzcr** [comment]
已修复此问题，等待3.12.0版本发布
