### ISSUE TITLE
🐛 [Bug]: TinyCLI packaging failed

### ISSUE THREAD

**Issue by Zhang-qiuxian** [opentiny/tiny-vue#726]
### Version

@opentiny/vue@3.11.1

### Vue Version

latest

### Link to minimal reproduction

2023-11-03 10:00:21 [tiny-toolkit-pro]: 项目打包中... 

> gin-web@1.0.0 build
> vite build --config ./config/vite.config.prod.ts

vite v2.9.16 building for production...
transforming (5448) node_modules/@opentiny/vue-river/node_modules/zrender/lib/contain/windingLine.jsUse of eval is strongly discouraged, as it poses security risks and may cause issues with minification
✓ 5452 modules transformed.
rendering chunks (43)...
<--- Last few GCs --->

[79739:0x6a07520]    52948 ms: Mark-sweep (reduce) 2038.5 (2082.5) -> 2038.4 (2082.8) MB, 834.6 / 0.0 ms  (average mu = 0.222, current mu = 0.228) allocation failure; GC in old space requested

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb7b3e0 node::Abort() [node]
 2: 0xa8c8aa  [node]
 3: 0xd69100 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xd694a7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xf46ba5  [node]
 6: 0xf5908d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 7: 0xf3378e v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 8: 0xf34b57 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 9: 0xf15d2a v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
10: 0x12dae9d v8::internal::Runtime_AllocateInOldGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
11: 0x1707b79  [node]
Aborted (core dumped)
2023-11-03 10:01:14 [tiny-toolkit-pro]: build失败 

### Step to reproduce

刚拉取下来之后执行build就报错

**Comment by zzcr** [comment]
看样子是内存溢出了，可以加大点打包内存，或者使用@opentiny/vue-vite-import按需打包插件：https://opentiny.design/tiny-vue/zh-CN/os-theme/docs/import-components
