### ISSUE TITLE
🐛 [Bug]: Grid component setTreeExpansion(rows, false) method, set true and false have different performance. The same data is set to true to expand within one second, and to set false takes more than 30 seconds to close

### ISSUE THREAD

**Issue by David-TechNomad** [opentiny/tiny-vue#737]
### Version

3.11.0

### Vue Version

3.2.44

### Link to minimal reproduction

Grid 组件 setTreeExpansion(rows, false)这个方法，set true和false的性能不一样，同样的数据设置true在一秒以内展开，设置false需要30多秒收起[捂脸]

### Step to reproduce

Grid 组件 setTreeExpansion(rows, false)这个方法，set true和false的性能不一样，同样的数据设置true在一秒以内展开，设置false需要30多秒收起[捂脸]

**Comment by David-TechNomad** [comment]
https://opentiny.design/vue-playground?mode=pc&theme=default#3.11|eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgbGFuZz1cInRzeFwiPlxyXG4vLyDlvJXlhaUgQG9wZW50aW55L3Z1ZSDnu4Tku7ZcclxuaW1wb3J0IHsgQnV0dG9uLCBMaW5rIH0gZnJvbSAnQG9wZW50aW55L3Z1ZSdcclxuXHJcbmV4cG9ydCBkZWZhdWx0IHtcclxuICBjb21wb25lbnRzOiB7XHJcbiAgICBUaW55QnV0dG9uOiBCdXR0b24sXHJcbiAgICBUaW55TGluazogTGlua1xyXG4gIH0sXHJcbiAgZGF0YSgpIHtcclxuICAgIHJldHVybiB7XHJcbiAgICAgIG1zZzogJ2hlbGxvIHdvcmxkISdcclxuICAgIH1cclxuICB9XHJcbn1cclxuPC9zY3JpcHQ+XHJcblxyXG48dGVtcGxhdGU+XHJcbiAgPFRpbnlCdXR0b24+56Gu5a6aPC9UaW55QnV0dG9uPlxyXG4gIDxoMT57eyBtc2cgfX08L2gxPlxyXG4gIDxkaXYgY2xhc3M9XCJ0aW55dnVlXCI+XHJcbiAgICA8ZGl2IGNsYXNzPVwidGlueXZ1ZS1wYWdlXCI+XHJcbiAgICAgIHRpbnl2dWVcclxuICAgICAgPHRpbnktbGluayB0eXBlPVwic3VjY2Vzc1wiIGhyZWY9J2h0dHBzOi8vZ2l0aHViLmNvbS9vcGVudGlueS90aW55LXZ1ZSc+XHJcbiAgICAgICAgdGlueXZ1ZVxyXG4gICAgICA8L3RpbnktbGluaz5cclxuICAgIDwvZGl2PlxyXG4gIDwvZGl2PlxyXG48L3RlbXBsYXRlPlxyXG5cclxuPHN0eWxlIGxhbmc9XCJsZXNzXCIgc2NvcGVkPlxyXG4gIGgxe1xyXG4gICAgY29sb3I6IzVlN2NlMDtcclxuICB9XHJcbiAgLnRpbnl2dWV7XHJcbiAgICBmb250LXNpemU6IDE4eHA7XHJcbiAgICAmLXBhZ2V7XHJcbiAgICAgIGNvbG9yOiM1ZTdjZTA7XHJcbiAgICB9XHJcbiAgfVxyXG48L3N0eWxlPlxyXG4iLCIiOiJ7XCJpbXBvcnRzXCI6e1wiQG9wZW50aW55L3Z1ZVwiOlwiaHR0cHM6Ly91bnBrZy5jb20vQG9wZW50aW55L3Z1ZUAzLjExL3J1bnRpbWUvdGlueS12dWUubWpzXCIsXCJAb3BlbnRpbnkvdnVlLWljb25cIjpcImh0dHBzOi8vdW5wa2cuY29tL0BvcGVudGlueS92dWVAMy4xMS9ydW50aW1lL3RpbnktdnVlLWljb24ubWpzXCIsXCJAb3BlbnRpbnkvdnVlLWxvY2FsZVwiOlwiaHR0cHM6Ly91bnBrZy5jb20vQG9wZW50aW55L3Z1ZUAzLjExL3J1bnRpbWUvdGlueS12dWUtbG9jYWxlLm1qc1wiLFwiQG9wZW50aW55L3Z1ZS1jb21tb25cIjpcImh0dHBzOi8vdW5wa2cuY29tL0BvcGVudGlueS92dWVAMy4xMS9ydW50aW1lL3RpbnktdnVlLWNvbW1vbi5tanNcIixcInNvcnRhYmxlanNcIjpcImh0dHBzOi8vdW5wa2cuY29tL3NvcnRhYmxlanNAMS4xNS4wL21vZHVsYXIvc29ydGFibGUuZXNtLmpzXCJ9fSIsInRzY29uZmlnLmpzb24iOiJ7XHJcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xyXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXHJcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcclxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcclxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXHJcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxyXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxyXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlXHJcbiAgfSxcclxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XHJcbiAgICBcInRhcmdldFwiOiAzLjNcclxuICB9XHJcbn1cclxuIiwibWV0aG9kcy9zZXQtdHJlZS1leHBhbnNpb24udnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDx0aW55LWJ1dHRvbiBAY2xpY2s9XCJjbGlja1wiPuWxleW8gOaMh+WumuWxgjwvdGlueS1idXR0b24+XG4gICAgPHRpbnktYnV0dG9uIEBjbGljaz1cImNsaWNrMlwiPuaUtui1t+aMh+WumuWxgjwvdGlueS1idXR0b24+XG4gICAgPHRpbnktZ3JpZFxuICAgICAgOmRhdGE9XCJ0YWJsZURhdGFcIlxuICAgICAgcmVmPVwidHJlZVJlZlwiXG4gICAgICA6dHJlZS1jb25maWc9XCJ7IGNoaWxkcmVuOiAnY2hpbGRyZW4nIH1cIlxuICAgICAgOmVkaXQtY29uZmlnPVwieyB0cmlnZ2VyOiAnY2xpY2snLCBtb2RlOiAnY2VsbCcsIHNob3dTdGF0dXM6IHRydWUgfVwiXG4gICAgICA6c2VsZWN0LWNvbmZpZz1cInsgbGFiZWxGaWVsZDogJ2luZGV4JyB9XCJcbiAgICAgIDpkcm9wLWNvbmZpZz1cIntcbiAgICAgICAgcGx1Z2luOiBTb3J0YWJsZSxcbiAgICAgICAgcm93OiB0cnVlLFxuICAgICAgICBjb2x1bW46IHRydWUsXG4gICAgICAgIC8vIHJlZnJlc2g6IHRydWUsXG4gICAgICB9XCJcbiAgICAgIGhlaWdodD1cIjUwMFwiXG4gICAgPlxuICAgICAgPHRlbXBsYXRlICN0b29sYmFyPlxuICAgICAgICA8dGlueS1ncmlkLXRvb2xiYXIgY2xhc3M9XCJjdXN0b21pemVkQm94XCI+XG4gICAgICAgICAgPHRlbXBsYXRlICNidXR0b25zPlxuICAgICAgICAgICAgPHRpbnktYnV0dG9uIEBjbGljaz1cImluc2VydEV2ZW50XCI+IOaWsOWiniA8L3RpbnktYnV0dG9uPlxuICAgICAgICAgICAgPHRpbnktYnV0dG9uIEBjbGljaz1cInJlbW92ZUV2ZW50XCI+IOenu+mZpOmAieS4rSA8L3RpbnktYnV0dG9uPlxuICAgICAgICAgICAgPHRpbnktYnV0dG9uIEBjbGljaz1cImdldFJlbW92ZUV2ZW50XCI+IOiOt+WPluWIoOmZpCA8L3RpbnktYnV0dG9uPlxuICAgICAgICAgICAgPHRpbnktYnV0dG9uIEBjbGljaz1cImdldFVwZGF0ZUV2ZW50XCI+IOiOt+WPluS/ruaUuSA8L3RpbnktYnV0dG9uPlxuICAgICAgICAgICAgPHRpbnktYnV0dG9uIEBjbGljaz1cImNsZWFyVHJlZUV4cGFuZFwiPiDmuIXnqbrlsZXlvIDnirbmgIEgPC90aW55LWJ1dHRvbj5cbiAgICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICA8L3RpbnktZ3JpZC10b29sYmFyPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIDx0aW55LWdyaWQtY29sdW1uIHR5cGU9XCJzZWxlY3Rpb25cIiB3aWR0aD1cIjEwMFwiIHRyZWUtbm9kZT48L3RpbnktZ3JpZC1jb2x1bW4+XG4gICAgICA8dGlueS1ncmlkLWNvbHVtbiB0eXBlPVwiaW5kZXhcIiB3aWR0aD1cIjgwXCI+PC90aW55LWdyaWQtY29sdW1uPlxuICAgICAgPHRpbnktZ3JpZC1jb2x1bW4gZmllbGQ9XCJuYW1lXCIgdGl0bGU9XCLlhazlj7jlkI3np7BcIj48L3RpbnktZ3JpZC1jb2x1bW4+XG4gICAgICA8dGlueS1ncmlkLWNvbHVtbiBmaWVsZD1cImFyZWFcIiB0aXRsZT1cIuWMuuWfn1wiIDplZGl0b3I9XCJ7IGNvbXBvbmVudDogJ2lucHV0JywgYXV0b3NlbGVjdDogdHJ1ZSB9XCI+PC90aW55LWdyaWQtY29sdW1uPlxuICAgICAgPHRpbnktZ3JpZC1jb2x1bW5cbiAgICAgICAgZmllbGQ9XCJlbXBsb3llZXNcIlxuICAgICAgICB0aXRsZT1cIuWRmOW3peaVsFwiXG4gICAgICAgIDplZGl0b3I9XCJ7IGNvbXBvbmVudDogJ2lucHV0JywgYXV0b3NlbGVjdDogdHJ1ZSB9XCJcbiAgICAgID48L3RpbnktZ3JpZC1jb2x1bW4+XG4gICAgPC90aW55LWdyaWQ+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cCBsYW5nPVwianN4XCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG4gIFxuaW1wb3J0IHtcbiAgR3JpZCBhcyBUaW55R3JpZCxcbiAgR3JpZENvbHVtbiBhcyBUaW55R3JpZENvbHVtbixcbiAgQnV0dG9uIGFzIFRpbnlCdXR0b24sXG4gIEdyaWRUb29sYmFyIGFzIFRpbnlHcmlkVG9vbGJhcixcbiAgTW9kYWwsXG59IGZyb20gJ0BvcGVudGlueS92dWUnXG5pbXBvcnQgU29ydGFibGUgZnJvbSAnc29ydGFibGVqcydcbiAgY29uc3QgdmFsdWUgPSByZWYoJycpXG5mdW5jdGlvbiBjYW5SZW1vdmUobm9kZSwgbm9kZXMpIHtcbiAgbGV0IGZsYWcgPSBmYWxzZVxuXG4gIGZvciAobGV0IGkgPSAwOyBpIDwgbm9kZXMubGVuZ3RoOyBpKyspIHtcbiAgICBmbGFnID0gbm9kZXNbaV0gPT09IG5vZGUgfHwgKG5vZGVzW2ldLmlkICYmIG5vZGUuaWQgJiYgbm9kZXNbaV0uaWQgPT09IG5vZGUuaWQpXG4gICAgaWYgKGZsYWcpIGJyZWFrXG4gIH1cblxuICByZXR1cm4gZmxhZ1xufVxuXG5mdW5jdGlvbiBwdXNoSWZOb3ROdWxsKGFycmF5LCBpdGVtKSB7XG4gIGlmIChpdGVtICE9PSBudWxsKSBhcnJheS5wdXNoKGl0ZW0pXG59XG5cbmZ1bmN0aW9uIGNvcHlDYW5ub3RSZW1vdmUobm9kZSwgbm9kZXMpIHtcbiAgbGV0IGNvcHlOb2RlXG5cbiAgaWYgKGNhblJlbW92ZShub2RlLCBub2RlcykpIHtcbiAgICBjb3B5Tm9kZSA9IG51bGxcbiAgfSBlbHNlIHtcbiAgICBpZiAoQXJyYXkuaXNBcnJheShub2RlLmNoaWxkcmVuKSkge1xuICAgICAgbGV0IGNoaWxkcmVuID0gW11cblxuICAgICAgZm9yIChsZXQgaSA9IDA7IGkgPCBub2RlLmNoaWxkcmVuLmxlbmd0aDsgaSsrKSB7XG4gICAgICAgIHB1c2hJZk5vdE51bGwoY2hpbGRyZW4sIGNvcHlDYW5ub3RSZW1vdmUobm9kZS5jaGlsZHJlbltpXSwgbm9kZXMpKVxuICAgICAgfVxuICAgICAgY29weU5vZGUgPSBPYmplY3QuYXNzaWduKE9iamVjdC5hc3NpZ24oe30sIG5vZGUpLCB7XG4gICAgICAgIGlkOiBub2RlLmlkIHx8IHVuZGVmaW5lZCxcbiAgICAgICAgY2hpbGRyZW5cbiAgICAgIH0pXG4gICAgfSBlbHNlIHtcbiAgICAgIGNvcHlOb2RlID0gT2JqZWN0LmFzc2lnbihPYmplY3QuYXNzaWduKHt9LCBub2RlKSwge1xuICAgICAgICBpZDogbm9kZS5pZCB8fCB1bmRlZmluZWQsXG4gICAgICAgIGNoaWxkcmVuOiB1bmRlZmluZWRcbiAgICAgIH0pXG4gICAgfVxuICB9XG5cbiAgcmV0dXJuIGNvcHlOb2RlXG59XG5cbmZ1bmN0aW9uIGNvcHkobm9kZXMxLCBub2RlczIpIHtcbiAgbGV0IHJlcyA9IFtdXG5cbiAgZm9yIChsZXQgaSA9IDA7IGkgPCBub2RlczEubGVuZ3RoOyBpKyspIHtcbiAgICBwdXNoSWZOb3ROdWxsKHJlcywgY29weUNhbm5vdFJlbW92ZShub2RlczFbaV0sIG5vZGVzMikpXG4gIH1cblxuICByZXR1cm4gcmVzXG59XG5cbmNvbnN0IHRhYmxlRGF0YSA9IHJlZihbXG4gXG5dKVxuZm9yKGxldCBpPTA7aTwyMDAwO2krKyl7XG4gIHRhYmxlRGF0YS52YWx1ZS5wdXNoKHtcbiAgICBpZDogJzcnLFxuICAgIHBpZDogJzAnLFxuICAgIG5hbWU6ICflurflurfniankuJpZWOWFrOWPuCcsXG4gICAgYXJlYTogJ+WNjuWNl+WMuicsXG4gICAgZW1wbG95ZWVzOiAnNDAwJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICBpZDogJzgnLFxuICAgICAgICBwaWQ6ICc3JyxcbiAgICAgICAgbmFtZTogJ+a3seWcs+W4guemj+W+t+Wunee9kee7nOaKgOacr1lY5YWs5Y+4JyxcbiAgICAgICAgYXJlYTogJ+WNjuWNl+WMuicsXG4gICAgICAgIGVtcGxveWVlczogJzU0MCcsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgaWQ6ICcyMycsXG4gICAgICAgICAgICBwaWQ6ICcxMCcsXG4gICAgICAgICAgICBuYW1lOiAnSUvmnInpmZDotKPku7vogqHku71ZWOWFrOWPuCcsXG4gICAgICAgICAgICBhcmVhOiAn5Y2O5Y2X5Yy6JyxcbiAgICAgICAgICAgIGVtcGxveWVlczogJzQ1NScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgaWQ6ICcyMycsXG4gICAgICAgICAgICBwaWQ6ICcxMCcsXG4gICAgICAgICAgICBuYW1lOiAnSUvmnInpmZDotKPku7vogqHku71ZWOWFrOWPuCcsXG4gICAgICAgICAgICBhcmVhOiAn5Y2O5Y2X5Yy6JyxcbiAgICAgICAgICAgIGVtcGxveWVlczogJzQ1NScsXG4gICAgICAgICAgfVxuICAgICAgICBdLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGlkOiAnMjMnLFxuICAgICAgICAgICAgcGlkOiAnMTAnLFxuICAgICAgICAgICAgbmFtZTogJ0lL5pyJ6ZmQ6LSj5Lu76IKh5Lu9WVjlhazlj7gnLFxuICAgICAgICAgICAgYXJlYTogJ+WNjuWNl+WMuicsXG4gICAgICAgICAgICBlbXBsb3llZXM6ICc0NTUnLFxuICAgICAgICAgIH1cbiAgICAgICAgXVxuICAgICAgICAgIH1cbiAgICAgICAgXVxuICAgICAgfSxcbiAgICBdXG4gIH0pXG59XG5jb25zdCByZW1vdmVMaXN0ID0gcmVmKFtdKVxuY29uc3QgdHJlZVJlZiA9IHJlZigpXG5cbmZ1bmN0aW9uIGluc2VydEV2ZW50KCkge1xuICBsZXQgdHJlZSA9IHRyZWVSZWYudmFsdWVcbiAgY29uc3Qgcm93ID0ge1xuICAgIG5hbWU6ICfmlrDmlbDmja4nLFxuICAgIGlzTmV3OiB0cnVlLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIG5hbWU6ICfmlrDmlbDmja4tY2hpbGQnXG4gICAgICB9XG4gICAgXVxuICB9XG4gIHRyZWUuY3JlYXRlUm93KHJvdykudGhlbigobmV3Um93KSA9PiB7XG4gICAgLy8g5o+S5YWl5Yiw56ys5LiA6KGMXG4gICAgdGFibGVEYXRhLnZhbHVlID0gW25ld1JvdywgLi4udGFibGVEYXRhLnZhbHVlXVxuICAgIGxldCBhY3RpdmVSb3cgPSB0YWJsZURhdGEudmFsdWVbMF1cbiAgICB0cmVlLnJlZnJlc2hEYXRhKCkudGhlbigoKSA9PiB0cmVlLnNldEFjdGl2ZVJvdyhhY3RpdmVSb3cpKVxuICB9KVxufVxuXG5mdW5jdGlvbiByZW1vdmVFdmVudCgpIHtcbiAgY29uc3QgaXNTYW1lT2JqZWN0ID0gKG9iajEsIG9iajIpID0+IEpTT04uc3RyaW5naWZ5KG9iajEpID09PSBKU09OLnN0cmluZ2lmeShvYmoyKVxuICBsZXQgdHJlZSA9IHRyZWVSZWYudmFsdWVcbiAgbGV0IHJlbW92ZVJlY29yZHMgPSB0cmVlLmdldFNlbGVjdFJlY29yZHMoKVxuXG4gIHRhYmxlRGF0YS52YWx1ZSA9IGNvcHkodGFibGVEYXRhLnZhbHVlLCByZW1vdmVSZWNvcmRzKVxuXG4gIGZvciAobGV0IGkgPSAwOyBpIDwgdGFibGVEYXRhLnZhbHVlLmxlbmd0aDsgaSsrKSB7XG4gICAgZm9yIChsZXQgaiA9IDA7IGogPCByZW1vdmVSZWNvcmRzLmxlbmd0aDsgaisrKSB7XG4gICAgICBpZiAoaXNTYW1lT2JqZWN0KHRhYmxlRGF0YS52YWx1ZVtpXSwgcmVtb3ZlUmVjb3Jkc1tqXSkpIHtcbiAgICAgICAgdGFibGVEYXRhLnZhbHVlLnNwbGljZShpLCAxKVxuICAgICAgfVxuICAgIH1cbiAgfVxuICByZW1vdmVMaXN0LnZhbHVlID0gcmVtb3ZlUmVjb3Jkcy5tYXAoKGl0ZW0pID0+ICh7IC4uLml0ZW0gfSkpXG59XG5cbmZ1bmN0aW9uIGdldFJlbW92ZUV2ZW50KCkge1xuICBsZXQgcmVtb3ZlUmVjb3JkcyA9IHJlbW92ZUxpc3QudmFsdWVcblxuICBNb2RhbC5hbGVydChyZW1vdmVSZWNvcmRzLmxlbmd0aClcbn1cblxuZnVuY3Rpb24gZ2V0VXBkYXRlRXZlbnQoKSB7XG4gIGxldCB1cGRhdGVSZWNvcmRzID0gdHJlZVJlZi52YWx1ZS5nZXRVcGRhdGVSZWNvcmRzKClcblxuICBNb2RhbC5hbGVydCh1cGRhdGVSZWNvcmRzLmxlbmd0aClcbn1cblxuZnVuY3Rpb24gY2xlYXJUcmVlRXhwYW5kKCkge1xuICB0cmVlUmVmLnZhbHVlLmNsZWFyVHJlZUV4cGFuZCgpXG59XG4gIGZ1bmN0aW9uIGZsYXR0ZW5UcmVlQnlMZXZlbChsZXZlbCkge1xuICAgIGNvbnN0IHQgPSBEYXRlLm5vdygpO1xuICAgIGNvbnN0IHJlc3VsdCA9IFtdO1xuXG4gICAgY29uc3QgdHJhdmVyc2UgPSAobm9kZSwgY3VycmVudExldmVsKSA9PiB7XG4gICAgICBjb25zdCBleHBhbnNpb24gPSBjdXJyZW50TGV2ZWwgPCBsZXZlbDtcbiAgICAgIGlmIChleHBhbnNpb24gJiYgIW5vZGUuZXhwYW5zaW9uKSB7XG4gICAgICAgIG5vZGUuZXhwYW5zaW9uID0gdHJ1ZVxuICAgICAgICByZXN1bHQucHVzaChub2RlKTtcbiAgICAgIH1cblxuICAgICAgaWYgKGV4cGFuc2lvbiAmJiBub2RlLmNoaWxkcmVuICYmIG5vZGUuY2hpbGRyZW4ubGVuZ3RoID4gMCkge1xuICAgICAgICBmb3IgKGxldCBjaGlsZCBvZiBub2RlLmNoaWxkcmVuKSB7XG4gICAgICAgICAgdHJhdmVyc2UoY2hpbGQsIGN1cnJlbnRMZXZlbCArIDEpO1xuICAgICAgICB9XG4gICAgICB9XG4gICAgfTtcblxuICAgIGZvciAobGV0IG5vZGUgb2YgdGFibGVEYXRhLnZhbHVlKSB7XG4gICAgICB0cmF2ZXJzZShub2RlLCAwKTtcbiAgICB9XG4gICAgY29uc29sZS5sb2coXCJ4eHh4MVwiLCBEYXRlLm5vdygpIC0gdCk7XG4gICAgcmV0dXJuIHJlc3VsdDtcbiAgfVxuICAvKipcbiAgICog5bGV5byA5pWw5o2uXG4gICAqIEBwYXJhbSBsZXZlbCDlsZXlvIAg5bGC57qnXG4gICAqL1xuICBmdW5jdGlvbiBleHBhbnNpb25UcmVlQnlMZXZlbChsZXZlbCkge1xuICAgIGNvbnN0IHQgPSBEYXRlLm5vdygpO1xuICAgIGNvbnN0IGRhdGEgPSB0aGlzLmZsYXR0ZW5UcmVlQnlMZXZlbChsZXZlbClcbiAgICBjb25zb2xlLmxvZygnMTExMScsIGRhdGEpO1xuXG4gICAgdGhpcy50aGVOR3JpZFJlZi5zZXRUcmVlRXhwYW5zaW9uKGRhdGEsIHRydWUpO1xuICAgIGNvbnNvbGUubG9nKFwieHh4eDExXCIsIERhdGUubm93KCkgLSB0KTtcbiAgfVxuICAvKipcbiAgICog5pS26LW35pWw5o2uXG4gICAqIEBwYXJhbSBsZXZlbCDmlLbotbcg5bGC57qnXG4gICAqL1xuICBmdW5jdGlvbiByZXRyYWN0VHJlZUJ5TGV2ZWwobGV2ZWwsIGxldmVsMikge1xuICAgIGNvbnN0IHQgPSBEYXRlLm5vdygpO1xuICAgIGNvbnN0IGRhdGEgPSB0aGlzLmZsYXR0ZW5UcmVlQnlMZXZlbDIobGV2ZWwsIGxldmVsMilcbiAgICBjb25zb2xlLmxvZygnMjIyMjInLCBkYXRhKTtcblxuICAgIHRoaXMudGhlTkdyaWRSZWYuc2V0VHJlZUV4cGFuc2lvbihkYXRhLCBmYWxzZSk7XG4gICAgY29uc29sZS5sb2coXCJ4eHh4MjJcIiwgRGF0ZS5ub3coKSAtIHQpO1xuICB9XG4gIC8qKlxuICAgKiDojrflj5bmlLbotbfmlbDmja5cbiAgICogQHBhcmFtIGxldmVsIOiOt+WPluaUtui1t+aVsOaNruWxgue6p1xuICAgKiBAcGFyYW0gbGV2ZWwyIOW3sue7j+WxleW8gOWxgue6p1xuICAgKi9cbiAgZnVuY3Rpb24gZmxhdHRlblRyZWVCeUxldmVsMihsZXZlbCwgbGV2ZWwyKSB7XG4gICAgY29uc3QgdCA9IERhdGUubm93KCk7XG4gICAgY29uc3QgcmVzdWx0ID0gW107XG5cbiAgICBjb25zdCB0cmF2ZXJzZSA9IChub2RlLCBjdXJyZW50TGV2ZWwpID0+IHtcbiAgICAgIGlmIChjdXJyZW50TGV2ZWwgPj0gbGV2ZWwgJiYgY3VycmVudExldmVsIDwgbGV2ZWwyKSB7XG4gICAgICAgIG5vZGUuZXhwYW5zaW9uID0gZmFsc2U7XG4gICAgICAgIHJlc3VsdC5wdXNoKG5vZGUpO1xuICAgICAgfVxuXG4gICAgICBpZiAoY3VycmVudExldmVsIDwgbGV2ZWwyICYmIG5vZGUuY2hpbGRyZW4gJiYgbm9kZS5jaGlsZHJlbi5sZW5ndGggPiAwKSB7XG4gICAgICAgIGZvciAobGV0IGNoaWxkIG9mIG5vZGUuY2hpbGRyZW4pIHtcbiAgICAgICAgICB0cmF2ZXJzZShjaGlsZCwgY3VycmVudExldmVsICsgMSk7XG4gICAgICAgIH1cbiAgICAgIH1cbiAgICB9O1xuXG4gICAgZm9yIChsZXQgbm9kZSBvZiB0YWJsZURhdGEudmFsdWUpIHtcbiAgICAgIHRyYXZlcnNlKG5vZGUsIDApO1xuICAgIH1cbiAgICBjb25zb2xlLmxvZyhcInh4eHgyXCIsIERhdGUubm93KCkgLSB0KTtcbiAgICByZXR1cm4gcmVzdWx0O1xuICB9XG4gIGZ1bmN0aW9uIGNsaWNrKCkge1xuICB0cmVlUmVmLnZhbHVlLnNldFRyZWVFeHBhbnNpb24oZmxhdHRlblRyZWVCeUxldmVsKDMpLCB0cnVlKVxufVxuICBmdW5jdGlvbiBjbGljazIoKSB7XG4gIHRyZWVSZWYudmFsdWUuc2V0VHJlZUV4cGFuc2lvbihmbGF0dGVuVHJlZUJ5TGV2ZWwyKDEsIDMpLCBmYWxzZSlcbn1cbjwvc2NyaXB0PlxuIiwiX28iOnt9fQ==
![image](https://github.com/opentiny/tiny-vue/assets/23149356/7a999bb4-e180-4d8b-82b1-e3fc3c7e9bde)

**Comment by zzcr** [comment]
感谢您的反馈，我们安排定位一下

**Comment by zzcr** [comment]
已修复此问题：https://github.com/opentiny/tiny-vue/pull/906
