### ISSUE TITLE
🐛 [Bug]: grid component, numeric input component. After modification, the previous numbers will be restored and the edited status will still be displayed. The original data should be of type number. The edited data will be printed in string type.

### ISSUE THREAD

**Issue by David-TechNomad** [opentiny/tiny-vue#764]
### Version

3.11.0

### Vue Version

3.2.44

### Link to minimal reproduction

https://opentiny.design/vue-playground?mode=pc&theme=default#3.11|eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgbGFuZz1cInRzeFwiPlxyXG4vLyDlvJXlhaUgQG9wZW50aW55L3Z1ZSDnu4Tku7ZcclxuaW1wb3J0IHsgQnV0dG9uLCBMaW5rIH0gZnJvbSAnQG9wZW50aW55L3Z1ZSdcclxuXHJcbmV4cG9ydCBkZWZhdWx0IHtcclxuICBjb21wb25lbnRzOiB7XHJcbiAgICBUaW55QnV0dG9uOiBCdXR0b24sXHJcbiAgICBUaW55TGluazogTGlua1xyXG4gIH0sXHJcbiAgZGF0YSgpIHtcclxuICAgIHJldHVybiB7XHJcbiAgICAgIG1zZzogJ2hlbGxvIHdvcmxkISdcclxuICAgIH1cclxuICB9XHJcbn1cclxuPC9zY3JpcHQ+XHJcblxyXG48dGVtcGxhdGU+XHJcbiAgPFRpbnlCdXR0b24+56Gu5a6aPC9UaW55QnV0dG9uPlxyXG4gIDxoMT57eyBtc2cgfX08L2gxPlxyXG4gIDxkaXYgY2xhc3M9XCJ0aW55dnVlXCI+XHJcbiAgICA8ZGl2IGNsYXNzPVwidGlueXZ1ZS1wYWdlXCI+XHJcbiAgICAgIHRpbnl2dWVcclxuICAgICAgPHRpbnktbGluayB0eXBlPVwic3VjY2Vzc1wiIGhyZWY9J2h0dHBzOi8vZ2l0aHViLmNvbS9vcGVudGlueS90aW55LXZ1ZSc+XHJcbiAgICAgICAgdGlueXZ1ZVxyXG4gICAgICA8L3RpbnktbGluaz5cclxuICAgIDwvZGl2PlxyXG4gIDwvZGl2PlxyXG48L3RlbXBsYXRlPlxyXG5cclxuPHN0eWxlIGxhbmc9XCJsZXNzXCIgc2NvcGVkPlxyXG4gIGgxe1xyXG4gICAgY29sb3I6IzVlN2NlMDtcclxuICB9XHJcbiAgLnRpbnl2dWV7XHJcbiAgICBmb250LXNpemU6IDE4eHA7XHJcbiAgICAmLXBhZ2V7XHJcbiAgICAgIGNvbG9yOiM1ZTdjZTA7XHJcbiAgICB9XHJcbiAgfVxyXG48L3N0eWxlPlxyXG4iLCIiOiJ7XCJpbXBvcnRzXCI6e1wiQG9wZW50aW55L3Z1ZVwiOlwiaHR0cHM6Ly91bnBrZy5jb20vQG9wZW50aW55L3Z1ZUAzLjExL3J1bnRpbWUvdGlueS12dWUubWpzXCIsXCJAb3BlbnRpbnkvdnVlLWljb25cIjpcImh0dHBzOi8vdW5wa2cuY29tL0BvcGVudGlueS92dWVAMy4xMS9ydW50aW1lL3RpbnktdnVlLWljb24ubWpzXCIsXCJAb3BlbnRpbnkvdnVlLWxvY2FsZVwiOlwiaHR0cHM6Ly91bnBrZy5jb20vQG9wZW50aW55L3Z1ZUAzLjExL3J1bnRpbWUvdGlueS12dWUtbG9jYWxlLm1qc1wiLFwiQG9wZW50aW55L3Z1ZS1jb21tb25cIjpcImh0dHBzOi8vdW5wa2cuY29tL0BvcGVudGlueS92dWVAMy4xMS9ydW50aW1lL3RpbnktdnVlLWNvbW1vbi5tanNcIixcInNvcnRhYmxlanNcIjpcImh0dHBzOi8vdW5wa2cuY29tL3NvcnRhYmxlanNAMS4xNS4wL21vZHVsYXIvc29ydGFibGUuZXNtLmpzXCJ9fSIsInRzY29uZmlnLmpzb24iOiJ7XHJcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xyXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXHJcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcclxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcclxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXHJcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxyXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxyXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlXHJcbiAgfSxcclxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XHJcbiAgICBcInRhcmdldFwiOiAzLjNcclxuICB9XHJcbn1cclxuIiwidGlueS1maXJzdC1tZW51L2N1c3RvbS1lZGl0aW5nLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPHRpbnktZ3JpZFxuICAgIDpkYXRhPVwidGFibGVEYXRhXCJcbiAgICBzZXEtc2VyaWFsXG4gICAgOmVkaXQtY29uZmlnPVwie1xuICAgICAgdHJpZ2dlcjogJ2NsaWNrJyxcbiAgICAgIG1vZGU6ICdjZWxsJyxcbiAgICAgIHNob3dTdGF0dXM6IHRydWUsXG4gICAgICBhY3RpdmVNZXRob2RcbiAgICB9XCJcbiAgPlxuICAgIDx0aW55LWdyaWQtY29sdW1uIHR5cGU9XCJpbmRleFwiIHdpZHRoPVwiNjBcIj48L3RpbnktZ3JpZC1jb2x1bW4+XG4gICAgPHRpbnktZ3JpZC1jb2x1bW4gZmllbGQ9XCJuYW1lXCIgdGl0bGU9XCLlkI3np7BcIiA6ZWRpdG9yPVwieyBjb21wb25lbnQ6ICdpbnB1dCcsIGF1dG9zZWxlY3Q6IHRydWUgfVwiPjwvdGlueS1ncmlkLWNvbHVtbj5cbiAgICA8dGlueS1ncmlkLWNvbHVtbiBmaWVsZD1cImFyZWFcIiB0aXRsZT1cIuWMuuWfn1wiIDplZGl0b3I9XCJ7IGNvbXBvbmVudDogJ3NlbGVjdCcsIG9wdGlvbnMgfVwiPjwvdGlueS1ncmlkLWNvbHVtbj5cbiAgICA8dGlueS1ncmlkLWNvbHVtblxuICAgICAgZmllbGQ9XCJjcmVhdGVkRGF0ZVwiXG4gICAgICB0aXRsZT1cIuWIm+W7uuaXtumXtFwiXG4gICAgICA6ZWRpdG9yPVwie1xuICAgICAgICBjb21wb25lbnQ6ICdpbnB1dCcsXG4gICAgICAgIGF0dHJzOiB7IHR5cGU6ICdkYXRlJyB9LFxuICAgICAgICBhdXRvc2VsZWN0OiB0cnVlXG4gICAgICB9XCJcbiAgICA+PC90aW55LWdyaWQtY29sdW1uPlxuICAgIDx0aW55LWdyaWQtY29sdW1uXG4gICAgICBmaWVsZD1cImVtcGxveWVlc1wiXG4gICAgICB0aXRsZT1cIuS6uuaVsFwiXG4gICAgICA6ZWRpdG9yPVwie1xuICAgICAgICBjb21wb25lbnQ6ICdpbnB1dCcsXG4gICAgICAgIGF0dHJzOiB7IHR5cGU6ICdudW1iZXInIH0sXG4gICAgICAgIGF1dG9zZWxlY3Q6IHRydWVcbiAgICAgIH1cIlxuICAgID48L3RpbnktZ3JpZC1jb2x1bW4+XG4gICAgPHRpbnktZ3JpZC1jb2x1bW5cbiAgICAgIGZpZWxkPVwiaW50cm9kdWN0aW9uXCJcbiAgICAgIHRpdGxlPVwi5YWs5Y+4566A5LuLXCJcbiAgICAgIDplZGl0b3I9XCJ7IGNvbXBvbmVudDogJ2lucHV0JywgYXV0b3NlbGVjdDogdHJ1ZSB9XCJcbiAgICAgIHNob3ctb3ZlcmZsb3c9XCJlbGxpcHNpc1wiXG4gICAgPjwvdGlueS1ncmlkLWNvbHVtbj5cbiAgPC90aW55LWdyaWQ+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJqc3hcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEdyaWQgYXMgVGlueUdyaWQsIEdyaWRDb2x1bW4gYXMgVGlueUdyaWRDb2x1bW4gfSBmcm9tICdAb3BlbnRpbnkvdnVlJ1xuXG5jb25zdCBvcHRpb25zID0gcmVmKFtcbiAgeyBsYWJlbDogJ+WNjuWMl+WMuicsIHZhbHVlOiAn5Y2O5YyX5Yy6JyB9LFxuICB7IGxhYmVsOiAn5Y2O5Lic5Yy6JywgdmFsdWU6ICfljY7kuJzljLonIH0sXG4gIHsgbGFiZWw6ICfljY7ljZfljLonLCB2YWx1ZTogJ+WNjuWNl+WMuicgfVxuXSlcbmNvbnN0IHRhYmxlRGF0YSA9IHJlZihbXG4gIHtcbiAgICBpZDogJzEnLFxuICAgIG5hbWU6ICdHRkTnp5HmioBZWOWFrOWPuCcsXG4gICAgYXJlYTogJ+WNjuS4nOWMuicsXG4gICAgYWRkcmVzczogJ+emj+W3nicsXG4gICAgaW50cm9kdWN0aW9uOiAn5YWs5Y+45oqA5pyv5ZKM56CU5Y+R5a6e5Yqb6ZuE5Y6a77yM5piv5Zu95a62ODYz6aG555uu55qE5Y+C5LiO6ICF77yM5bm26KKr5pS/5bqc6K6k5a6a5Li64oCc6auY5paw5oqA5pyv5LyB5Lia4oCd44CCJyxcbiAgICBlbXBsb3llZXM6IDMwMCxcbiAgICBjcmVhdGVkRGF0ZTogJzIwMTYtMDctMDggMTI6MzY6MjInXG4gIH0sXG4gIHtcbiAgICBpZDogJzInLFxuICAgIG5hbWU6ICdXV1dX56eR5oqAWVjlhazlj7gnLFxuICAgIGFyZWE6ICfljY7ljZfljLonLFxuICAgIGFkZHJlc3M6ICfmt7HlnLPnpo/nlLDljLonLFxuICAgIGludHJvZHVjdGlvbjogJ+WFrOWPuOaKgOacr+WSjOeglOWPkeWunuWKm+mbhOWOmu+8jOaYr+WbveWutjg2M+mhueebrueahOWPguS4juiAhe+8jOW5tuiiq+aUv+W6nOiupOWumuS4uuKAnOmrmOaWsOaKgOacr+S8geS4muKAneOAgicsXG4gICAgZW1wbG95ZWVzOiAxMzAwLFxuICAgIGNyZWF0ZWREYXRlOiAnMjAxNC0wMi0xNCAxNDoxNDoxNCdcbiAgfSxcbiAge1xuICAgIGlkOiAnMycsXG4gICAgbmFtZTogJ1JGVuaciemZkOi0o+S7u+WFrOWPuCcsXG4gICAgYXJlYTogJ+WNjuWNl+WMuicsXG4gICAgYWRkcmVzczogJ+S4reWxseW4gicsXG4gICAgaW50cm9kdWN0aW9uOiAn5YWs5Y+45oqA5pyv5ZKM56CU5Y+R5a6e5Yqb6ZuE5Y6a77yM5piv5Zu95a62ODYz6aG555uu55qE5Y+C5LiO6ICF77yM5bm26KKr5pS/5bqc6K6k5a6a5Li64oCc6auY5paw5oqA5pyv5LyB5Lia4oCd44CCJyxcbiAgICBlbXBsb3llZXM6IDM2MCxcbiAgICBjcmVhdGVkRGF0ZTogJzIwMTMtMDEtMTMgMTM6MTM6MTMnXG4gIH0sXG4gIHtcbiAgICBpZDogJzQnLFxuICAgIG5hbWU6ICdUR0JZWOWFrOWPuCcsXG4gICAgYXJlYTogJ+WNjuWMl+WMuicsXG4gICAgYWRkcmVzczogJ+aiheW3nicsXG4gICAgaW50cm9kdWN0aW9uOiAn5YWs5Y+45oqA5pyv5ZKM56CU5Y+R5a6e5Yqb6ZuE5Y6a77yM5piv5Zu95a62ODYz6aG555uu55qE5Y+C5LiO6ICF77yM5bm26KKr5pS/5bqc6K6k5a6a5Li64oCc6auY5paw5oqA5pyv5LyB5Lia4oCd44CCJyxcbiAgICBlbXBsb3llZXM6IDgxMCxcbiAgICBjcmVhdGVkRGF0ZTogJzIwMTItMTItMTIgMTI6MTI6MTInXG4gIH0sXG4gIHtcbiAgICBpZDogJzUnLFxuICAgIG5hbWU6ICdZSE7np5HmioBZWOWFrOWPuCcsXG4gICAgYXJlYTogJ+WNjuWNl+WMuicsXG4gICAgYWRkcmVzczogJ+mftuWFsycsXG4gICAgaW50cm9kdWN0aW9uOiAn5YWs5Y+45oqA5pyv5ZKM56CU5Y+R5a6e5Yqb6ZuE5Y6a77yM5piv5Zu95a62ODYz6aG555uu55qE5Y+C5LiO6ICF77yM5bm26KKr5pS/5bqc6K6k5a6a5Li64oCc6auY5paw5oqA5pyv5LyB5Lia4oCd44CCJyxcbiAgICBlbXBsb3llZXM6IDMwMCxcbiAgICBjcmVhdGVkRGF0ZTogJzIwMTYtMDctMDggMTI6MzY6MjInXG4gIH0sXG4gIHtcbiAgICBpZDogJzYnLFxuICAgIG5hbWU6ICflurflurfniankuJpZWOWFrOWPuCcsXG4gICAgYXJlYTogJ+WNjuWMl+WMuicsXG4gICAgYWRkcmVzczogJ+W5v+W3nuWkqeays+WMuicsXG4gICAgaW50cm9kdWN0aW9uOiAn5YWs5Y+45oqA5pyv5ZKM56CU5Y+R5a6e5Yqb6ZuE5Y6a77yM5piv5Zu95a62ODYz6aG555uu55qE5Y+C5LiO6ICF77yM5bm26KKr5pS/5bqc6K6k5a6a5Li64oCc6auY5paw5oqA5pyv5LyB5Lia4oCd44CCJyxcbiAgICBlbXBsb3llZXM6IDgwMCxcbiAgICBjcmVhdGVkRGF0ZTogJzIwMTEtMTEtMTEgMTE6MTE6MTEnXG4gIH1cbl0pXG5cbi8vIOiHquWumuS5iee8lui+ke+8jOWmgu+8muS4jeWFgeiuuOe8lui+kSBhcmVhID0g5Y2O5Lic5Yy6IOeahOWNleWFg+agvFxuZnVuY3Rpb24gYWN0aXZlTWV0aG9kKHsgcm93IH0pIHtcbiAgcmV0dXJuIHJvdy5hcmVhICE9PSAn5Y2O5Lic5Yy6J1xufVxuPC9zY3JpcHQ+XG4iLCJfbyI6e319
![image](https://github.com/opentiny/tiny-vue/assets/23149356/b13ce9bd-512c-4188-9e69-d0faef22e313)

### Step to reproduce

grid 组件，数字输入 组件，修改之后还原之前的数字，还是显示编辑过的状态，应该是原始数据是number类型，打印编辑完的数据，给的是string类型的

**Comment by zzcr** [comment]
已提mr修复此问题
