### ISSUE TITLE
Ts type introduction error and packaging error

### ISSUE THREAD

**Issue by clearPeople13** [opentiny/tiny-vue#773]
表单验证需要ts类型
import {IFormInstance} from "@opentiny/vue-renderless/types/form.type";
我找到类型
![image](https://github.com/opentiny/tiny-vue/assets/119475063/02cd4117-c477-403a-8d23-6b14a5145ff9)
![image](https://github.com/opentiny/tiny-vue/assets/119475063/4edb8018-747c-4753-900e-d93bea4268de)

使用的vite，表单可以正常验证，但是不能打包，这么解决，还有其他的组件的ts类型在哪找？
"@opentiny/vue": "^3.11.1",用的这个版本

**Comment by zzcr** [comment]
好的，我们来排查下~~

**Comment by gimmyhehe** [comment]
@clearPeople13 尝试一下加个.mjs后缀尝试一下？
import { IFormInstance } from "@opentiny/vue-renderless/types/form.type.mjs";
我这边本地验证上述方式是可以的，没有后缀的写法报错原因，后续会进一步排查原因

**Comment by gimmyhehe** [comment]
@clearPeople13 组件类型声明文件，都在@opentiny/vue-renderless包下的types目录。 另外，声明文件在3.12.0版本将对构建产物进行修改，将声明文件后缀改为.d.ts。  import { IFormInstance } from "@opentiny/vue-renderless/types/form.type"; 这种写法在下一班中将能正常运行~
