### ISSUE TITLE
✨ [Feature]: Animation effect improvement of controls such as Numeric,Select

### ISSUE THREAD

**Issue by harvenzhang** [opentiny/tiny-vue#794]
### What problem does this feature solve

目前鼠标放在图标上，点击图标都没有动画过渡效果，希望能增加。

### What does the proposed API look like

无

**Comment by zzcr** [comment]
你好，请问下，是一直没有动画效果呢，还是之前版本有但是现在没有了

**Comment by harvenzhang** [comment]
一直没有。比如鼠标放在arrow上，arrow是不是可以做个颜色变化。现在的很死板，无任何效果。

**Comment by shenjunjian** [comment]
现在  select 图标会有动画翻转， 下拉面板的展开有动画。（去年提issue时，当时组件可能丢失了下拉动画了） 
Numeric 点击没有任何反应，@harvenzhang  可能期望 +- 号能变大抖动一下。

@harvenzhang 的意思是很多组件都缺少动画， 组件的动画效果，我们需要找设计师讨论之后再添加。
