### ISSUE TITLE
🐛 [Bug]: Wrong cell value when exiting editing when pressing ESC key.

### ISSUE THREAD

**Issue by harvenzhang** [opentiny/tiny-vue#797]
### Version

3.11.1

### Vue Version

4.5

### Link to minimal reproduction

None

### Step to reproduce

当按下ESC键时，退出编辑器，此时单元格的值变成了编辑器的值，应该恢复编辑前的值

**Comment by zzcr** [comment]
这里只是退出编辑状态，如果需要还原值表格有重置数据方法
