### ISSUE TITLE
🐛 [Bug]: [tree] tree component node content will be misaligned if it exceeds the screen range.

### ISSUE THREAD

**Issue by qinlaodemanong** [opentiny/tiny-vue#831]
### Version

3.11.2

### Vue Version

3.2.31

### Link to minimal reproduction

![image](https://github.com/opentiny/tiny-vue/assets/82434064/eadf9fe4-5775-4c9a-8a37-408c183b848d)

### Step to reproduce

https://opentiny.design/vue-playground?cmpId=tree&fileName=node-events.vue&apiMode=Composition&mode=pc&theme=default
1、修改节点显示内容长度
2、拉伸区域

**Comment by zzcr** [comment]
您好，感谢你的意见，我们内部评估下~~

**Comment by GaoNeng-wWw** [comment]
I will solve this problem
