### ISSUE TITLE
🐛 [Bug]: [cascader] Cascader component multi-select does not echo the selected name after configuring emitPath:false

### ISSUE THREAD

**Issue by falcon-jin** [opentiny/tiny-vue#843]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

![32b80c679f158a39cf0f872fa40cb87](https://github.com/opentiny/tiny-vue/assets/48880836/ec38450e-19db-4c6f-b28e-ad3013ac2167)
cascader组件多选 配置 emitPath:false之后不回显选中的名称
:props="{ checkStrictly: true, multiple: true, emitPath:false }" 
问题代码
![image](https://github.com/opentiny/tiny-vue/assets/48880836/56d090ef-d9ac-49d5-8b9c-a38b34e2540e)

### Step to reproduce

添加属性 :props="{ checkStrictly: true, multiple: true, emitPath:false }"

**Comment by zzcr** [comment]
您好，感谢你的意见，我们内部评估下~~
