### ISSUE TITLE
 [Bug]: [form] If size="small" is placed directly in the tiny-form form, there will be an error of two pixels between the input box and the button.

### ISSUE THREAD

**Issue by YuPeng6688** [opentiny/tiny-vue#849]
<img width="318" alt="WechatIMG658" src="https://github.com/opentiny/tiny-vue/assets/150329130/c320f69f-0c90-452d-8c45-9e779b79547c">
<img width="436" alt="Snipaste_2023-11-17_12-40-13" src="https://github.com/opentiny/tiny-vue/assets/150329130/ec004c84-f403-4cc6-b0fe-05ded61f89c9">

**Comment by gimmyhehe** [comment]
问题已收录，修改后将在下一版本发布~
