### ISSUE TITLE
[official website] demo mixed with multiple Timeline components in Steps components

### ISSUE THREAD

**Issue by kagol** [opentiny/tiny-vue#85]
以下两个 demo 应该是 Timeline 组件的 demo，却用在了 Steps 组件中，建议移到 Steps 组件的 demo 中。

- [普通步骤条](https://opentiny.design/tiny-vue/zh-CN/os-theme/components/steps#normal-steps)
- [时间线步骤条](https://opentiny.design/tiny-vue/zh-CN/os-theme/components/steps#timeline-steps)

<img width="1357" alt="image" src="https://user-images.githubusercontent.com/9566362/227750633-000ba3c1-a278-43c9-94d9-3a01902dc13f.png">

**Comment by qinwencheng** [comment]
似乎不需要移动，而是应该直接删除。这里乱入的普通步骤条和时间步骤条都提到把type改为xxx，然而实际上无论是timeline组件还是step组件，都没有type属性
