### ISSUE TITLE
Rich text does not recognize the custom passed string label style

### ISSUE THREAD

**Issue by YuPeng6688** [opentiny/tiny-vue#850]
<img width="1510" alt="Snipaste_2023-11-17_12-34-33" src="https://github.com/opentiny/tiny-vue/assets/150329130/e47eef33-dfbf-48bb-8ff6-ac6792f16b82">

**Comment by GaoNeng-wWw** [comment]
cc @Caesar-ch

**Comment by Huauauaa** [comment]
@liaopt wrap the text with a span, and write styles into span. It seems to be Tiptap’s stuff.

**Comment by shenjunjian** [comment]
先使用第一个示例，生成一段富文本生成的value值， 这个html代码段才有效。 
把这个value 传递给content时， 可以正常回显！

![image](https://github.com/opentiny/tiny-vue/assets/6848520/a819357a-7145-4c3d-a802-b0807514617d)

**Comment by shenjunjian** [comment]
通过上图，说明并不是不支持html的传入， 是否能识别取决于html是否有效。 
html什么情况下有效，这块还研究的不深。
