### ISSUE TITLE
🐛 [Bug]: After opening dialog, when the mouse presses the left button, moving out of the dialog,dialog will be hidden, which is equivalent to dialog hiding after the mouse is pressed outside the dialog.

### ISSUE THREAD

**Issue by harvenzhang** [opentiny/tiny-vue#865]
### Version

3.11.1

### Vue Version

4.5

### Link to minimal reproduction

当用户在录入 时，用鼠标全选textbox时，不小心超出了dialog外面 ，dialog就关闭了

### Step to reproduce

N

**Comment by zzcr** [comment]
您好，感谢你的意见，我们内部评估下~~

**Comment by James-9696** [comment]
此问题已修复，可见官网最新版本dialog的demo示例
