### ISSUE TITLE
✨ [Feature]: [grid] I hope to add the API to get the status of adding, deleting and changing a row.

### ISSUE THREAD

**Issue by harvenzhang** [opentiny/tiny-vue#867]
### What problem does this feature solve

用户可以根据不同状态设置不同的css

### What does the proposed API look like

None

**Comment by zzcr** [comment]
感谢反馈，我们会尽快看下这个问题

**Comment by kagol** [comment]
@harvenzhang 可否描述详细一下这个需求，比如希望给什么组件增加功能，最好补充一些截图辅助表格，感谢你的大力支持！

**Comment by harvenzhang** [comment]
就是给表格组件添加一个获取行状态的方法，比如：
方法名：getRowStatus(rowIndex) ， 返回：updated, removed, inserted, nochanged  这四种结果。
用户可根据行的这四种状态，做进一步处理。

**Comment by zzcr** [comment]
你好，表格的状态可以在数据中体现，并使用自定义渲染器，显示不同的状态：https://opentiny.design/tiny-vue/zh-CN/os-theme/components/grid-renderer#renderer-custom-renderer
