### ISSUE TITLE
🐛 [Bug]: Each cell in the csv content exported by the table has more \t tabs.

### ISSUE THREAD

**Issue by ShengAndShu** [opentiny/tiny-vue#881]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://tinyuidesign.cloudbu.huawei.com/tiny-vue/zh-CN/os-theme/components/grid-import-export

### Step to reproduce

1. 点击'导出数据'按钮；
2. 打开导出的csv文件；
3. 查看任意一个有数据的单元格，发现单元格内文本多了\t制表符

### What is expected

单元格文本不含\t制表符

### What is actually happening

单元格文本含有意料之外的\t制表符

**Comment by zzcr** [comment]
感谢反馈，我们会尽快看下这个问题

**Comment by zzcr** [comment]
this.$refs.theGrid.exportCsv({
        filename: 'table.csv',
        original: true,
        isHeader: false,
        useTabs:false,
        data: this.tableData
      })
配置下useTabs为false就可以取消制表符
