### ISSUE TITLE
🐛 [Bug]: [grid] Write toggleRowSelection in the cell-click event, and when you switch rows, the select-change event becomes invalid, even if you click the check box.

### ISSUE THREAD

**Issue by harvenzhang** [opentiny/tiny-vue#890]
### Version

3.11.1

### Vue Version

4.5

### Link to minimal reproduction

None

### Step to reproduce

None

**Comment by zzcr** [comment]
您好，感谢你的意见，我们内部评估下~~

**Comment by zzcr** [comment]
https://opentiny.design/tiny-vue/zh-CN/os-theme/components/grid-operation-column#methods-set-selection
setSelection 方法不会触发 select-change 事件，只有点击才会触发。官网上已有说明哈，只有点击才会触发
