### ISSUE TITLE
[grid] Table Gird component drag element style adjustment

### ISSUE THREAD

**Issue by wfppfw** [opentiny/tiny-vue#891]
想问一下，这个拖拽的样式调整，我看demo可以控制拖拽元素移动背景为红色,demo代码中没有体现，拖拽是由sortablejs实现的，sortablejs上配置forceFallback: true可以修改原生拖拽样式，请问一下这部分是Sortable对象插件这样配置了吗，能给出一下这个demo比较全的代码吗控制的拖拽样式代码吗，求求啦

![Snip20231121_38](https://github.com/opentiny/tiny-vue/assets/37470149/2b012ad2-9d5a-48cd-b009-5cf07af1d088)

![Snip20231122_1](https://github.com/opentiny/tiny-vue/assets/37470149/b02b2a73-9964-4784-bd54-bb3612d69c8c)

**Comment by zzcr** [comment]
这个样式控制是通过三行样式去控制的
.sortable-chosen {
  background: #ceeea9 !important;
}
.sortable-drag {
  background: red !important;
}
.row__drag-disable {
  background: #f1f1f1 !important;
}

**Comment by wfppfw** [comment]
谢谢！！！！




在2023年11月22日 ***@***.***> 写道：

这个样式控制是通过三行样式去控制的
.sortable-chosen {
background: #ceeea9 !important;
}
.sortable-drag {
background: red !important;
}
.row__drag-disable {
background: #f1f1f1 !important;
}
