### ISSUE TITLE
✨ [Feature]: [grid] I hope I can add the following two methods: getRowByIndex and toggleRowSelectionByIndex

### ISSUE THREAD

**Issue by harvenzhang** [opentiny/tiny-vue#902]
### What problem does this feature solve

getRowByIndex:  通过index获取到行
toggleRowSelectionByIndex :  通过index选择行
目前，只支持getRowById 和toggleRowSelection ，参数都是row, 希望可以通过index获取或选择行  

### What does the proposed API look like

getRowByIndex(rowIndex)
toggleRowSelectionByIndex(rowIndex)

**Comment by zzcr** [comment]
getData(rowIndex) 可以通过索引获取某一行的数据，获取到数据然后再调用toggleRowSelection 就可以啦~~~
