### ISSUE TITLE
✨ [Feature]: [grid] Hope to increase the number of events completed by loading table data

### ISSUE THREAD

**Issue by harvenzhang** [opentiny/tiny-vue#910]
### What problem does this feature solve

希望可以增加表格数据加载完成的事件，当表格数据加载完成时，执行一些操作。

### What does the proposed API look like

当表格数据加载完成时，执行一些操作。

**Comment by zzcr** [comment]
你好，我是这么理解的：如果是静态数据绑定的形式，表格加载数据的形式是跟着vue的生命周期走的，如果是fetchData的形式那就是在resolve数据后
