### ISSUE TITLE
🐛 [Bug]: [slider] Slider component vertical mode, drag to the anchor will jump

### ISSUE THREAD

**Issue by yoyo201626** [opentiny/tiny-vue#915]
### Version

opentiny/vue@3.11.0

### Vue Version

3

### Link to minimal reproduction

https://opentiny.design/tiny-vue/zh-CN/os-theme/components/slider

### Step to reproduce

1. 滚动到下面
![图片](https://github.com/opentiny/tiny-vue/assets/104079404/66f86835-fc24-4875-bdc6-8cadefc47391)

2. 点击锚点
![图片](https://github.com/opentiny/tiny-vue/assets/104079404/d38c0f36-4d6a-4e80-820e-40c5300be802)

**Comment by Huauauaa** [comment]
It seems that the component  didn’t calculate the position after scroll

```ts
// renderless/src/slider/index.ts
// bindMouseDown()
+ api.bindResize()
const currentValue  = api.calculateValue(event)
```

**Comment by yoyo201626** [comment]
> It seems that the component didn’t calculate the position after scroll
> 
> ```ts
> // renderless/src/slider/index.ts
> // bindMouseDown()
> + api.bindResize()
> const currentValue  = api.calculateValue(event)
> ```
@Huauauaa 
I think more critical is this code in `packages\renderless\src\slider\index.ts#calculateValue `:
```ts
  (event) => {
    let currentValue = 0

    if (state.sliderSize == 0) {
      const handleEl = vm.$refs.slider
      state.sliderSize = handleEl['client' + (props.vertical ? 'Height' : 'Width')]
      state.sliderOffset = handleEl.getBoundingClientRect()
    }

    const offset = state.sliderOffset as DOMRect

    if (event.type === 'touchmove' || event.type === 'touchstart' || event.type === 'touchend') {
      if (props.vertical) {
        currentValue = props.max - ((event.touches[0].pageY - offset.top) / state.sliderSize) * state.rangeDiff
      } else {
        currentValue = props.min + ((event.touches[0].pageX - offset.left) / state.sliderSize) * state.rangeDiff
      }
    } else {
      if (props.vertical) {
        currentValue = props.max - ((event.pageY - offset.top) / state.sliderSize) * state.rangeDiff
      } else {
        currentValue = props.min + ((event.pageX - offset.left) / state.sliderSize) * state.rangeDiff
      }
    }
    return currentValue
  }
```
`event.pageY` is the Y coordinate relative to **the entire document**, but `offset.top` which get from `Element.getBoundingClientRect()` is relative to **the Viewport**

**Comment by yoyo201626** [comment]
**应该选择使用相对 Viewport 的定位来计算**

因为当前没有好办法来准确获取某个Element的相对于document的定位。

这对于鼠标事件`event`来说，只要把`event.pageY`改成`event.clientY`就可以。

但是对于当前锚点元素`handleEl`来说，为了减少回流，我们不能太频繁地使用`Element.getBoundingClientRect()`来获取相对于ViewPort的定位。这是需要解决的。

**Comment by yoyo201626** [comment]
1
