### ISSUE TITLE
🐛 [Bug]: [numeric] The Numeric counter component increases the value incorrectly when clicked with the notebook mouse touchpad.

### ISSUE THREAD

**Issue by AcWrong02** [opentiny/tiny-vue#919]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://opentiny.design/tiny-vue/zh-CN/os-theme/components/numeric#basic-usage

### Step to reproduce

不用鼠标点击，而是使用笔记本鼠标触摸板点击，会发现点击一次增加的数字不是1

### What is expected

使用笔记本鼠标触摸板点击，点击一次增加的数字是1

### What is actually happening

使用笔记本鼠标触摸板点击，会发现点击一次增加的数字不是1

**Comment by zzcr** [comment]
https://github.com/opentiny/tiny-vue/pull/951 已修复此问题
