### ISSUE TITLE
✨ [Feature]: I hope I can experience the theme configuration system without logging in.

### ISSUE THREAD

**Issue by dufu1991** [opentiny/tiny-vue#925]
### What problem does this feature solve

我只是想简单体验一下主题配置系统，但是竟然需要登录，我能理解的是配置好的主题配置是以账号保存且可以分享出去，但是我只是简单体验一下配置，竟然使用登录拒之门外。

### What does the proposed API look like

建议可以体验时取消这个限制。

**Comment by kagol** [comment]
@dufu1991 这个建议很好，我们已经反馈给主题配置系统的开发同事了，感谢你的建议～ 
下次主题配置系统的issue可以提到 tiny-cli 项目：https://github.com/opentiny/tiny-cli
此问题已提交给 tiny-cli 项目：https://github.com/opentiny/tiny-cli/issues/122
感谢你的大力支持
