### ISSUE TITLE
🐛 [Bug]: Add grid components to dialog and edit them. Clicking on the blank space of dialog will not trigger edit-closed.

### ISSUE THREAD

**Issue by horadrim1015** [opentiny/tiny-vue#953]
### Version

3.10.1

### Vue Version

3.2.31

### Link to minimal reproduction

代码请见附件
[code.txt](https://github.com/opentiny/tiny-vue/files/13495765/code.txt)

### Step to reproduce

点击单元格编辑完成后，点击dialog的空白处，不会触发edit-closed
![企业微信截图_17012282965531](https://github.com/opentiny/tiny-vue/assets/65272873/d6a635d1-af57-4123-be3e-ad030d093267)

**Comment by zzcr** [comment]
可以看下这个示例：https://opentiny.design/tiny-vue/zh-CN/os-theme/components/grid-faq#faq-gridInDialogBox
