### ISSUE TITLE
🐛 [Bug]: If the table component sets the freeze column, it will obscure the outer border of the table.

### ISSUE THREAD

**Issue by thestar077** [opentiny/tiny-vue#957]
### Version

3.10.0

### Vue Version

3.2.47

### Link to minimal reproduction

表格组件如果设置了冻结列，会把表格的外边框给遮挡

现象：
![image](https://github.com/opentiny/tiny-vue/assets/16183489/62976d5a-7732-45c3-b243-fd2dc3a9ecf9)

预期：
![image](https://github.com/opentiny/tiny-vue/assets/16183489/7c0b18fd-8f18-4e8e-81b0-954693370181)

### Step to reproduce

表格组件如果设置了冻结列，会把表格的外边框给遮挡

现象：
![image](https://github.com/opentiny/tiny-vue/assets/16183489/62976d5a-7732-45c3-b243-fd2dc3a9ecf9)

预期：
![image](https://github.com/opentiny/tiny-vue/assets/16183489/7c0b18fd-8f18-4e8e-81b0-954693370181)

**Comment by zzcr** [comment]
已修复此问题，3.12.0版本发布
