### ISSUE TITLE
🐛 [Bug]: [numeric] The min property of the Numeric component, when modelValue < min, displays the initial value of modelValue.  Max attribute is the same.

### ISSUE THREAD

**Issue by AcWrong02** [opentiny/tiny-vue#963]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://opentiny.design/vue-playground?mode=pc&theme=default#3.11|eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgbGFuZz1cInRzeFwiPlxyXG4vLyDlvJXlhaUgQG9wZW50aW55L3Z1ZSDnu4Tku7ZcclxuaW1wb3J0IHsgQnV0dG9uLCBMaW5rIH0gZnJvbSAnQG9wZW50aW55L3Z1ZSdcclxuXHJcbmV4cG9ydCBkZWZhdWx0IHtcclxuICBjb21wb25lbnRzOiB7XHJcbiAgICBUaW55QnV0dG9uOiBCdXR0b24sXHJcbiAgICBUaW55TGluazogTGlua1xyXG4gIH0sXHJcbiAgZGF0YSgpIHtcclxuICAgIHJldHVybiB7XHJcbiAgICAgIG1zZzogJ2hlbGxvIHdvcmxkISdcclxuICAgIH1cclxuICB9XHJcbn1cclxuPC9zY3JpcHQ+XHJcblxyXG48dGVtcGxhdGU+XHJcbiAgPFRpbnlCdXR0b24+56Gu5a6aPC9UaW55QnV0dG9uPlxyXG4gIDxoMT57eyBtc2cgfX08L2gxPlxyXG4gIDxkaXYgY2xhc3M9XCJ0aW55dnVlXCI+XHJcbiAgICA8ZGl2IGNsYXNzPVwidGlueXZ1ZS1wYWdlXCI+XHJcbiAgICAgIHRpbnl2dWVcclxuICAgICAgPHRpbnktbGluayB0eXBlPVwic3VjY2Vzc1wiIGhyZWY9J2h0dHBzOi8vZ2l0aHViLmNvbS9vcGVudGlueS90aW55LXZ1ZSc+XHJcbiAgICAgICAgdGlueXZ1ZVxyXG4gICAgICA8L3RpbnktbGluaz5cclxuICAgIDwvZGl2PlxyXG4gIDwvZGl2PlxyXG48L3RlbXBsYXRlPlxyXG5cclxuPHN0eWxlIGxhbmc9XCJsZXNzXCIgc2NvcGVkPlxyXG4gIGgxe1xyXG4gICAgY29sb3I6IzVlN2NlMDtcclxuICB9XHJcbiAgLnRpbnl2dWV7XHJcbiAgICBmb250LXNpemU6IDE4eHA7XHJcbiAgICAmLXBhZ2V7XHJcbiAgICAgIGNvbG9yOiM1ZTdjZTA7XHJcbiAgICB9XHJcbiAgfVxyXG48L3N0eWxlPlxyXG4iLCIiOiJ7XCJpbXBvcnRzXCI6e1wiQG9wZW50aW55L3Z1ZVwiOlwiaHR0cHM6Ly91bnBrZy5jb20vQG9wZW50aW55L3Z1ZUAzLjExL3J1bnRpbWUvdGlueS12dWUubWpzXCIsXCJAb3BlbnRpbnkvdnVlLWljb25cIjpcImh0dHBzOi8vdW5wa2cuY29tL0BvcGVudGlueS92dWVAMy4xMS9ydW50aW1lL3RpbnktdnVlLWljb24ubWpzXCIsXCJAb3BlbnRpbnkvdnVlLWxvY2FsZVwiOlwiaHR0cHM6Ly91bnBrZy5jb20vQG9wZW50aW55L3Z1ZUAzLjExL3J1bnRpbWUvdGlueS12dWUtbG9jYWxlLm1qc1wiLFwiQG9wZW50aW55L3Z1ZS1jb21tb25cIjpcImh0dHBzOi8vdW5wa2cuY29tL0BvcGVudGlueS92dWVAMy4xMS9ydW50aW1lL3RpbnktdnVlLWNvbW1vbi5tanNcIixcInNvcnRhYmxlanNcIjpcImh0dHBzOi8vdW5wa2cuY29tL3NvcnRhYmxlanNAMS4xNS4wL21vZHVsYXIvc29ydGFibGUuZXNtLmpzXCJ9fSIsInRzY29uZmlnLmpzb24iOiJ7XHJcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xyXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXHJcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcclxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcclxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXHJcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxyXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxyXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlXHJcbiAgfSxcclxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XHJcbiAgICBcInRhcmdldFwiOiAzLjNcclxuICB9XHJcbn1cclxuIiwiYmFzaWMtdXNhZ2UudnVlIjoiPHRlbXBsYXRlPlxuICA8dGlueS1udW1lcmljIHYtbW9kZWw9XCJudW0xXCIgOm1pbj1cIjNcIj48L3RpbnktbnVtZXJpYz5cbiAgPHRpbnktbnVtZXJpYyB2LW1vZGVsPVwibnVtMlwiIDptYXg9XCI1XCI+PC90aW55LW51bWVyaWM+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJqc3hcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IE51bWVyaWMgYXMgVGlueU51bWVyaWMgfSBmcm9tICdAb3BlbnRpbnkvdnVlJ1xuXG5jb25zdCBudW0xID0gcmVmKDEpXG5jb25zdCBudW0yID0gcmVmKDYpXG48L3NjcmlwdD5cbiIsIl9vIjp7fX0=

### Step to reproduce

打开playground

### What is expected

在初始的时候，如果modelValue<min，那显示的值应该是min
在初始的时候，如果modelValue>max，那显示的值应该是max

### What is actually happening

在初始的时候，如果modelValue<min，显示的值变成了modelValue，这是不对的
在初始的时候，如果modelValue>max，显示的值是modelValue，这是不对的

**Comment by wkif** [comment]
我来试着修复一下

**Comment by James-9696** [comment]
此问题已修复了，可见官网最值与数值循环的demo
