### ISSUE TITLE
🐛 [Bug]: [numeric] The step-strictly function of the Numeric component is incorrect

### ISSUE THREAD

**Issue by AcWrong02** [opentiny/tiny-vue#964]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://opentiny.design/vue-playground?mode=pc&theme=default#3.11|eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgbGFuZz1cInRzeFwiPlxuLy8g5byV5YWlIEBvcGVudGlueS92dWUg57uE5Lu2XG5pbXBvcnQgeyBCdXR0b24sIExpbmsgfSBmcm9tICdAb3BlbnRpbnkvdnVlJ1xuXG5leHBvcnQgZGVmYXVsdCB7XG4gIGNvbXBvbmVudHM6IHtcbiAgICBUaW55QnV0dG9uOiBCdXR0b24sXG4gICAgVGlueUxpbms6IExpbmtcbiAgfSxcbiAgZGF0YSgpIHtcbiAgICByZXR1cm4ge1xuICAgICAgbXNnOiAnaGVsbG8gd29ybGQhJ1xuICAgIH1cbiAgfVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPFRpbnlCdXR0b24+56Gu5a6aPC9UaW55QnV0dG9uPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGRpdiBjbGFzcz1cInRpbnl2dWVcIj5cbiAgICA8ZGl2IGNsYXNzPVwidGlueXZ1ZS1wYWdlXCI+XG4gICAgICB0aW55dnVlXG4gICAgICA8dGlueS1saW5rIHR5cGU9XCJzdWNjZXNzXCIgaHJlZj0naHR0cHM6Ly9naXRodWIuY29tL29wZW50aW55L3RpbnktdnVlJz5cbiAgICAgICAgdGlueXZ1ZVxuICAgICAgPC90aW55LWxpbms+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlIGxhbmc9XCJsZXNzXCIgc2NvcGVkPlxuICBoMXtcbiAgICBjb2xvcjojNWU3Y2UwO1xuICB9XG4gIC50aW55dnVle1xuICAgIGZvbnQtc2l6ZTogMTh4cDtcbiAgICAmLXBhZ2V7XG4gICAgICBjb2xvcjojNWU3Y2UwO1xuICAgIH1cbiAgfVxuPC9zdHlsZT5cbiIsIiI6IntcImltcG9ydHNcIjp7XCJAb3BlbnRpbnkvdnVlXCI6XCJodHRwczovL3VucGtnLmNvbS9Ab3BlbnRpbnkvdnVlQDMuMTEvcnVudGltZS90aW55LXZ1ZS5tanNcIixcIkBvcGVudGlueS92dWUtaWNvblwiOlwiaHR0cHM6Ly91bnBrZy5jb20vQG9wZW50aW55L3Z1ZUAzLjExL3J1bnRpbWUvdGlueS12dWUtaWNvbi5tanNcIixcIkBvcGVudGlueS92dWUtbG9jYWxlXCI6XCJodHRwczovL3VucGtnLmNvbS9Ab3BlbnRpbnkvdnVlQDMuMTEvcnVudGltZS90aW55LXZ1ZS1sb2NhbGUubWpzXCIsXCJAb3BlbnRpbnkvdnVlLWNvbW1vblwiOlwiaHR0cHM6Ly91bnBrZy5jb20vQG9wZW50aW55L3Z1ZUAzLjExL3J1bnRpbWUvdGlueS12dWUtY29tbW9uLm1qc1wiLFwic29ydGFibGVqc1wiOlwiaHR0cHM6Ly91bnBrZy5jb20vc29ydGFibGVqc0AxLjE1LjAvbW9kdWxhci9zb3J0YWJsZS5lc20uanNcIn19IiwidHNjb25maWcuanNvbiI6IntcclxuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XHJcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcclxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxyXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxyXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcclxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXHJcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXHJcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWVcclxuICB9LFxyXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcclxuICAgIFwidGFyZ2V0XCI6IDMuM1xyXG4gIH1cclxufVxyXG4iLCJhbGxvdy1lbXB0eS52dWUiOiI8dGVtcGxhdGU+XG4gIDx0aW55LW51bWVyaWNcbiAgICB2LW1vZGVsPVwic3RlcE51bVwiXG4gICAgOnN0ZXA9XCJzdGVwXCJcbiAgICBzdGVwLXN0cmljdGx5XG4gID48L3RpbnktbnVtZXJpYz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cImpzeFwiPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgTnVtZXJpYyBhcyBUaW55TnVtZXJpYywgTW9kYWwgfSBmcm9tICdAb3BlbnRpbnkvdnVlJ1xuXG5jb25zdCBzdGVwID0gcmVmKDIpXG5jb25zdCBzdGVwTnVtID0gcmVmKDIpXG48L3NjcmlwdD5cbiIsIl9vIjp7fX0=

### Step to reproduce

打开playground

### What is expected

在step-strictly模式下，且step等于2的时候，输入框应该只能输入为2的倍数的数，或者是自动化格式到为2的倍数

### What is actually happening

在step-strictly模式下，且step等于2的时候，我可以输入任何值的数

**Comment by Huangyilin19** [comment]
问题已收到,我们尽快出方案解决.

**Comment by James-9696** [comment]
此问题 已通过#1284解决，当设置step为5时，用户输入的值为6，那么输入框将会自动取值为5。当用户输入的值为9，那么输入框将会自动取值为10。后续发布的3.20版本，也可以这么设置:step={ value: 5, mode: 'strictly' } 等同于 step-strictly
