### ISSUE TITLE
✨ [Feature]: Vue component document scroll block

### ISSUE THREAD

**Issue by jiangchangzhi** [opentiny/tiny-vue#97]
### What problem does this feature solve

在鼠标进入演示的时候建议把浏览器 默认滚动事件给禁用掉

### What does the proposed API look like

0

**Comment by kagol** [comment]
@jiangchangzhi 能描述清楚一些吗？没有理解什么意思

**Comment by zzcr** [comment]
新官网预览演示已变成vue的repl技术
